### ISSUE TITLE
关于画面居中问题

### ISSUE THREAD

**Issue by zhiwo** [pili-engineering/PLDroidPlayer#100]
设置的match_parent, 但是画面不居中，这个有没有办法设置

**Comment by Jhuster** [comment]
demo 也是 match_parent，画面是居中的，你说的不居中指的是什么，有哪些跟 demo 不一样的配置 ？可以贴一张图出来看看。

**Comment by zhiwo** [comment]
是视频画面偏左，不是在屏幕中间

**Comment by Jhuster** [comment]
@zhiwo demo 没有这个问题，请仔细检查你的布局。

**Comment by zhiwo** [comment]
嗯嗯谢谢是我布局问题
