### ISSUE TITLE
getDuration()总是返回-1是什么原因

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#101]
我没有用MediaController，想自己在Activity中得到视频的总时间和当前时间，但是getDurarion()总是返回-1，请问是都有哪些因素造成的。

**Comment by Jhuster** [comment]
@lzx1 可能码流中的时间戳或者时长信息不对，码流地址发出来看看。

**Comment by lzx1** [comment]
就是一普通的视频，在Demo上运行时没有问题的http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by Jhuster** [comment]
@lzx1 码流是正常的，demo 也是正常的，仔细对比你的代码和 demo 的区别吧。
