### ISSUE TITLE
PLVideoTextureView切换地址的时候 会有上个视频的最后一贞的的残留，时间不长

### ISSUE THREAD

**Issue by gf5353** [pili-engineering/PLDroidPlayer#103]
怎么在切换地址的时候把PLVideoTextureView绘制内容清空（最好是透明），目前我的做法是切换前修改Alpha，在OnInfoListener 得到第一帧画面成功渲染的时候再修改Alpha，有没有更好的方案

**Comment by Jhuster** [comment]
@gf5353 可以试试在`PLVideoTextureView `上面覆盖一层全黑色背景的 View，在切换地址的时候显示出来，切换完毕后再隐藏掉。
