### ISSUE TITLE
seekTo 有时进度出错

### ISSUE THREAD

**Issue by bear45** [pili-engineering/PLDroidPlayer#106]
拖动控制栏调用seektTo()跳转到指定进度时，有时会出现视频播放进度不正确。比如拖动到 20秒，准备后，自己又跳到16秒。

**Comment by Jhuster** [comment]
@bear45 一般播放器的 seektTo 都会寻找附近的关键帧，这种情况可能是正好在20秒处不是关键帧，而最近的关键帧在16秒处。

**Comment by sunxu3074** [comment]
@Jhuster 你好，请问是不是缓存好的了才能seekTo？ 还有问一下PLVideoView能嵌入一个activity么？就能播放也能滚动看其他的内容，我试了下但是被背景挡住了。

**Comment by Jhuster** [comment]
@sunxu3074  对于回放文件，任何时候都可以 seekTo。 View 里面怎么可能嵌入 activity 呢？肯定是把其他内容 overlay 在 View 上

**Comment by sunxu3074** [comment]
```
// 这句是不能seekTo的 videoPath是rtmp://开头的 存在我们本地服务器上的一个视频文件
mMediaController = new MediaController(this, false, isLiveStreaming(mVideoPath));

// 改成了这句后 能够seek 但是当seekTo到视频尾端的时候会直接回调onCompletion()方法，这是为什么呢
 mMediaController = new MediaController(this, false, false);
```

我说的意思怎么把view弄成不是match_parent的，我设置了高度，但是背景还是灰色的。

**Comment by Jhuster** [comment]
seekTo 到视频“尾端”的时候，如果定位到尾端的关键帧就是最后一帧或者很快就播放完了最后几帧，当然会调用 onCompletion() 。

你设置了高度，View 就是你设置的高度，VideoView 以外的背景就是你的 parent view 的背景，你改 parent view 的颜色不要是灰色就行了。

**Comment by sunxu3074** [comment]
不只是seekTo到尾端的时候会调用onCompletion();连续seek几次就会调用这个方法。而调用了 mMediaController.setInstantSeeking(true)之后除了seek到尾端不会出现之前的问题了。请问这是什么问题呢？

**Comment by nixionglin** [comment]
@Jhuster 关键帧是谁定义的呢，是服务器返回流里的定义吗？
