### ISSUE TITLE
当暂停的时候调用stopPlayback闪退

### ISSUE THREAD

**Issue by mzyisbest** [pili-engineering/PLDroidPlayer#1069]
当我进入播放界面  然后等视频开始播放  点击暂停按钮 当视频处于暂停状态的时候  按返回键  调用stopPlayback（） 释放视频资源的时候   闪退   以下是错误日志

01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: GetMethodID received NULL jclass
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]     in call to GetMethodID
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]     from int com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeSetView(long, java.lang.Object)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x75791fd0 self=0xf45b6500
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=18194 nice=-4 cgrp=top_visible sched=0/0 handle=0xf732db38
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 2701284040 639042040 4184 ) utm=246 stm=24 core=3 HZ=100
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xff2e8000-0xff2ea000 stackSize=8MB
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeSetView(Native method)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.qiniu.qplayer.mediaEngine.MediaPlayer.a(MediaPlayer.java:282)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.qiniu.qplayer.mediaEngine.MediaPlayer.a(MediaPlayer.java:293)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.pili.pldroid.player.PLMediaPlayer.setDisplay(PLMediaPlayer.java:139)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.pili.pldroid.player.widget.a.d(PLBaseVideoView.java:281)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.pili.pldroid.player.widget.a.u(PLBaseVideoView.java:45)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.pili.pldroid.player.widget.a$3.a(PLBaseVideoView.java:1260)
01-08 18:06:36.900 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureDestroyed(PLVideoTextureView.java:364)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.TextureView.destroySurface(TextureView.java:239)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.TextureView.onDetachedFromWindowInternal(TextureView.java:229)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.View.dispatchDetachedFromWindow(View.java:14684)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3069)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3069)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3069)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   ... repeated 4 times
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4622)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.ViewGroup.removeViewAt(ViewGroup.java:4571)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.views.view.ReactViewGroup.removeViewAt(ReactViewGroup.java:447)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.views.view.ReactViewManager.removeViewAt(ReactViewManager.java:287)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.views.view.ReactViewManager.removeViewAt(ReactViewManager.java:36)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:378)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   - locked <0x0012d04c> (a com.facebook.react.uimanager.NativeViewHierarchyManager)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:988)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   - locked <0x0a420895> (a com.facebook.react.modules.core.ReactChoreographer)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.Choreographer.doCallbacks(Choreographer.java:698)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.Choreographer.doFrame(Choreographer.java:630)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Handler.handleCallback(Handler.java:743)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Handler.dispatchMessage(Handler.java:95)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:150)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.main(ActivityThread.java:5659)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Method.invoke!(Native method)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/java_vm_ext.cc:410] 
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/runtime.cc:368] Runtime aborting...
01-08 18:06:36.901 18194-18194/com.anjie.sixty A/art: art/runtime/runtime.cc:368] 
01-08 18:06:36.911 957-983/? E/HsmCoreServiceImpl: onTransact in code is: 102

**Comment by mzyisbest** [comment]
是因为调用销毁的时候开的新线程导致的 已经修复

**Comment by jamninetyfive** [comment]
请问这是你自己封装的react-native版本么~
