### ISSUE TITLE
退出界面的卡顿UI线程，出现ANR提示。

### ISSUE THREAD

**Issue by Neacy** [pili-engineering/PLDroidPlayer#107]
进入界面开始加载视频中，在视频还没加载成功的时候就退出界面造成UI线程卡顿直接弹出ANR提示了。
而如果视频加载成功再退出来就不会存在这个问题。

**Comment by Jhuster** [comment]
@Neacy 你好，麻烦提供一下详细的测试信息，比如：手机型号、网络环境、播放的 URL 地址，另外，给你发了一封邮件，麻烦帮忙抓取一下详细的 log 回复给我们，非常感谢。

**Comment by Neacy** [comment]
@Jhuster 你可能没明白我说的我详细跟你描述一下。
点击进入视频播放界面
mVedioView.setVideoPath(livePath)传入视频地址
这时候VedioView就开始加载这个视频，**还没等VedioView加载成功的时候退出视频播放界面**
mVedioView.stopPlayback()调用这个回收视频资源

这时候就回到了之前的视频列表   滑动ListView就会没反应需要等下面这个log打印出来后才能正常滑动，而这个时候就出现了ANR提示。

E/IJKMEDIA: http://apps.mushu.cn/jc_2665_m_big_hd.mp4: Immediate exit requested

后台log就只看到这么一句，没有别的。
Nexus 5X  Android6.0.1  Wifi环境    http://apps.mushu.cn/jc_2665_m_big_hd.mp4

麻烦你看下。

视频播放界面
![image](https://cloud.githubusercontent.com/assets/3108178/15347535/fdc86454-1cf4-11e6-9a7b-597109bf5a19.png)
视频列表
![image](https://cloud.githubusercontent.com/assets/3108178/15347549/1e8d481c-1cf5-11e6-914b-b2785a3d2de8.png)

**Comment by Jhuster** [comment]
@Neacy 我理解你的意思，在加载没完成的时候直接退出，我这边用 demo 无法复现这个问题。出现这种情况可能跟你的本地环境有一定关系，邮件给你了一份有更加详细 debug log 的 apk，可以抓一下 log 给我们分析一下，谢谢。

**Comment by Neacy** [comment]
我运行了下你发的demo  当你点击播放的时候进入视频播放界面 退出来再次点击播放存在需要一段时间后才能再次进入视频播放界面，所以我怀疑是不是回收资源的时候导致主线程卡住了。
我选择的Activity是VedioViewActivity。

后台打印的log我回你邮件了  你查看下。

**Comment by xiangchalong** [comment]
我也出现类似问题，就是当缓冲的时候(出现701，但是702还没有出现前)如果推出界面，再次点击进入，就会出现ANR。
