### ISSUE TITLE
总时长问题

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#108]
能不能不用项目提供的MediaController而在Activity中直接得到视频的总时长，我在Activity中调用getDuration()方法返回的总是-1，在demo中也是这样

**Comment by Jhuster** [comment]
@lzx1 可以不用 `MediaController `，mVideoView.getDuration() 我测试过了，没有问题的。

注意，只有回放、文件才能得到有效的时长，直播流是没有时长的。

你可以把你的流地址发出来看看。
