### ISSUE TITLE
视频播放过程中，点击暂停按钮，过几秒在点击播放按钮，视频不是从暂停的地方开始播放的，而且下面的进度条也会往前跑，麻烦解决下啊，谢谢了，2.1.5,2.1.6，和最新的2.1.7试了都有这个问题

### ISSUE THREAD

**Issue by BeBroken** [pili-engineering/PLDroidPlayer#1088]
点击暂停播放后，再次点击播放按钮，播放的位置发生了变化，实际上调用pause方法，视频还是在播的

**Comment by BeBroken** [comment]
链接：https://pan.baidu.com/s/1FAWzTGWZEMLiu-0SyK9ggg 
提取码：wcfn 
由于视频链接需要内网访问，现附上现象视频链接

**Comment by BeBroken** [comment]
问题已经确认OK了，是我使用不当导致，需要选择点播模式，谢谢你们的解答，谢谢。服务很棒！

**Comment by dutay** [comment]
我也遇到了同样的问题，能否具体解答一下是哪里使用不当啊
