### ISSUE TITLE
关于直播情况下，画面延迟的问题

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#109]
我使用的是PLVideoTextureView。
第一点：推流的服务器不存在延迟
第二点：网络流畅
第三点：同一个推流地址，ios端的播放最多延迟两秒，所以说明服务器推流是没有延迟的问题

问题： 服务器推流过来，手机端用PLVideoTextureView播放，当出现缓冲view的时候，画面会停在那里进行等待继续播放，当可以播放的时候，视频是继续往下顺序播放的，看清楚，是继续往下播放，而不是快速播放到当前的画面，比如我在03秒的时候卡住了，这个时候PLVideoTextureView显示了缓冲的view，等到13秒的时候才继续播放，这个时候，PLVideoTextureView播放的画面是04秒的画面，也就是继续慢慢往下播放，然后就出现了问题，严重延迟，起码10秒以上（不固定，有时候更久），然后我尝试在延迟比较严重的情况下（延迟时间超过10秒以上），我停止了播放，再重新打开播放，（注：我这个操作过程非常快，最多两秒的时间。）这个时候看到的画面，是最新的画面，也就是不延迟了，而如果只要是出现缓冲的情况下，就会重复出现以上的问题。

请问：不知道是不是PLVideoTextureView做了缓冲的策略，有没有办法让PLVideoTextureView永远是播放到最新的画面？

**Comment by Jhuster** [comment]
@tz-xiaomage 目前的确有这个问题，我们会在下一个版本中改进。

**Comment by tz-xiaomage** [comment]
@Jhuster 感谢你的回答，不知道下个版本大概是什么时候？ 还有不知道现在的版本有没有大概可以处理以上问题的方法？或者我在当缓冲出现的时候，计算出现的时间，然后调用视频的停止，然后立马调用播放操作？

**Comment by Jhuster** [comment]
@tz-xiaomage 可以考虑在延时比较大的时候，做重新播放或者｀seekTo｀操作。

**Comment by tz-xiaomage** [comment]
@Jhuster 请教一下，不知道这个延迟计算，我应该在哪个位置计算呢？ seekTo是有long参数的，而我rtmp流是没有总时长的，我应该设置多少

**Comment by Jhuster** [comment]
@tz-xiaomage 直播是不存在 “时长” 的概念的，只有文件和回放才会有时长。另外，目前版本你应该无法做这个延迟的计算，定期 seekTo(0) 试试，或者重连。

**Comment by tz-xiaomage** [comment]
@Jhuster seekTo（0）试了，会直接停在那里缓冲，不会播放，只能重连了
![image](https://cloud.githubusercontent.com/assets/12270504/15446516/1b7ac862-1f56-11e6-93d9-fd077f21840e.png)

**Comment by tz-xiaomage** [comment]
@Jhuster 还有我总感觉它是不是播放开始前预缓存了一小段，就算我重连，也会稍微卡在那里约4秒左右才播放，这个时候播放的画面，虽然不会延迟超过10秒以上了，可是还是延迟

**Comment by Jhuster** [comment]
@tz-xiaomage 没有预缓存，你跑 `demo` 播放的时候很快就出现画面了即可验证。重连的卡是因为 `stopPlayback` 退出的时候需要一定的时间销毁资源。目前的情况来看，不建议你自己来做延时的优化，下一版在 2 周内会发布，会包含有延时的优化。

**Comment by tz-xiaomage** [comment]
@Jhuster 感谢回答，期待中
