### ISSUE TITLE
目前播放器支持哪些格式？

### ISSUE THREAD

**Issue by huihui4045** [pili-engineering/PLDroidPlayer#1093]
目前播放器支持哪些格式？，支持avi格式吗

**Comment by panyingdaoz** [comment]
本地mp4

**Comment by HugoLipeng** [comment]
支持多种域名解析。HTTP-DNS, UDP-DNS, SYS-DNS.
支持RTMP和HTTP+FLV直播方式。
点播支持多种格式(MP4、FLV、MP3、M3U8、AAC)。
支持视频解码（H264，H265，MPEG4）。
支持音频解码（AAC，MP3，SPEEX）。
