### ISSUE TITLE
Support arm64 and x86

### ISSUE THREAD

**Issue by wubj** [pili-engineering/PLDroidPlayer#11]
thanks for your project,
Is it possible support arm64 and x86 device?

**Comment by jpxiong** [comment]
It will support arm64 & x86 future, but no plan at present. Thanks.

**Comment by jpxiong** [comment]
The newest version had supported the arm64. F.Y.I.

**Comment by wubj** [comment]
Great!!

**Comment by jpxiong** [comment]
v1.1.3 had been provided x86.
