### ISSUE TITLE
使用PLVideoView设置了宽高却无效的问题

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#110]
这个问题，不知道算不算问题
使用PLVideoView，给它设置了宽高，实际上是不起作用的，比如我推的是1280_720的流，然后我想要让播放画面小一点，给PLVideoView设置了240_180宽高大小，然后实际播放的时候，画面是超出了240_180的大小，然后我尝试给它设置点击事件，发现只有在240_180区域内点击才有效果，超出的那些是没有点击效果的，可是界面上却显示了出来（无论是哪种预览模式16:9、4:3等等都是会超出，百分百）

它还有一个问题是，如果我的界面上有两个PLVideoView，它们是层叠的，240_180的在上，全屏的在下，但是实际播放的时候，小的会被遮挡在后面，我用了vivo、oppo、华为、乐视，都有这个问题，唯独只有一部三星4.1系统没问题，我尝试将它们的层叠位置转换一下，全屏的在上，240_180的在下，发现除了三星4.1被遮挡了，其他的手机都会反而把240*180的显示在上面

**Comment by Jhuster** [comment]
@tz-xiaomage 由于 `PLVideoView ` 会按照视频尺寸进行缩放，所以如果希望限定窗口大小的话，建议在 `PLVideoView ` 外面套一层 `FrameLayout` 来限定窗口大小，例如：

```
    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="800px"
        android:layout_height="800px"
        android:layout_margin="10dp" >

        <com.pili.pldroid.player.widget.PLVideoView
            android:id="@+id/VideoView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </FrameLayout>
```

**Comment by Jhuster** [comment]
@tz-xiaomage 宽高的设置是起了作用的，由于 `PLVideoView` 会根据你配置的缩放类型对视频进行缩放，所以你看到的效果与设置的宽高有区别，如果希望播放的画面正好填满你配置的宽高，可以使用如下配置：

```
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);
```

**Comment by Jhuster** [comment]
@tz-xiaomage 第二个问题是常见的多个 `SurfaceView` 层叠的问题，如果希望某一个 `PLVideoView` 在上面显示，可以调用：

```
mVideoView.getSurfaceView(). setZOrderOnTop(true);
```

**Comment by Jhuster** [comment]
@tz-xiaomage 假设你设置的 width 和 height 都是 500px，而视频尺寸是 1280 x 720，那么，为了保持视频不被拉伸，`PLVideoView` 会保持比例对 View 的宽高进行变换，如果希望变换后的 View 宽高不超过 View 的 width 和 height，可以选择使用 `ASPECT_RATIO_FIT_PARENT` 这种模式。

注：如果用 `ASPECT_RATIO_PAVED_PARENT` 模式的话，为了保持比例，的确会超出预设的 width 和 height

**Comment by ViTess** [comment]
@Jhuster 往后是否可以加上不按比例而是贴合布局尺寸拉伸的功能？

**Comment by Jhuster** [comment]
@ViTess 不按比例缩放显示的效果会很奇怪，如果需要这种效果，目前你可以考虑使用 `PLMediaPlayer` 类自己来实现 `VideoView`

**Comment by tz-xiaomage** [comment]
@Jhuster 
@tz-xiaomage 第二个问题是常见的多个 SurfaceView 层叠的问题，如果希望某一个 PLVideoView 在上面显示，可以调用：

mVideoView.getSurfaceView(). setZOrderOnTop(true);

如果设置了这个ZOrderOnTop,那视图会位于最顶层，遮挡住其他任何view，连弹窗也会被遮挡，这样的体验不友好，是否有办法让小窗口永远显示在大窗口的顶部，但是却不会位于Window顶部呢？
如果两个都设置setZOrderMediaOverlay的话，那一样会出现小窗口被遮挡问题，如果大窗口不设置，那大窗口就显示不出来了
