### ISSUE TITLE
demo无法正常使用

### ISSUE THREAD

**Issue by fangkyi03** [pili-engineering/PLDroidPlayer#1106]
使用官方demo版本
play版本2.1.7
使用中提供的rtmp://live.hkstv.hk.lxdns.com/live/hks 无法播放
手动输入http://www.w3school.com.cn/i/movie.ogg
提示failed to open player

android模拟器 跟小米8真机都测试过 无法播放
![image](https://user-images.githubusercontent.com/30390014/56796477-30118f00-6845-11e9-8e51-5a2cc6b13df8.png)
![image](https://user-images.githubusercontent.com/30390014/56796487-343dac80-6845-11e9-95ba-a61c9f279ca8.png)
进去以后一直维持这个页面 然后过几秒以后就直接挂掉了

**Comment by ReikyZ** [comment]
demo 默认的 hks 地址已经失效；ogg 格式目前不支持
以下是我们支持的格式
 支持RTMP和HTTP+FLV直播方式。
 点播支持多种格式(MP4、FLV、MP3、M3U8、AAC)。
 支持视频解码（H264，H265，MPEG4）。
 支持音频解码（AAC，MP3，SPEEX）。

**Comment by fangkyi03** [comment]
已经不使用七牛云播放器了

**Comment by guoshilun** [comment]
> 已经不使用七牛云播放器了

现在使用的那家播放器，我也想换了，现在2.1.9版本起播时间太慢了，
