### ISSUE TITLE
都支持什么格式啊，为什么RMVB播放不了啊

### ISSUE THREAD

**Issue by LuffyBySunny** [pili-engineering/PLDroidPlayer#1108]

**Comment by ReikyZ** [comment]
支持多种域名解析。HTTP-DNS, UDP-DNS, SYS-DNS.
 支持RTMP和HTTP+FLV直播方式。
 点播支持多种格式(MP4、FLV、MP3、M3U8、AAC)。
 支持视频解码（H264，H265，MPEG4）。
 支持音频解码（AAC，MP3，SPEEX）。

RMVB 不支持的。
