### ISSUE TITLE
判断是否是直播

### ISSUE THREAD

**Issue by chenwulue** [pili-engineering/PLDroidPlayer#111]
`private boolean isLiveStreaming(String url) {
        if (url.startsWith("rtmp://")
                || (url.startsWith("http://") && url.endsWith(".m3u8"))
                || (url.startsWith("http://") && url.endsWith(".flv"))) {
            return true;
        }
        return false;
    }`
这个是判断是否直播流的方法吗？ 第二第三个不能确定是直播吧

**Comment by Jhuster** [comment]
@chenwulue 这段代码是简单的演示代码，在真正的应用中，是需要开发者自行判断的，比如访问你们的应用服务器，判断某个流是否为直播。
