### ISSUE TITLE
在调用pause后，调用到nativePause时发生anr

### ISSUE THREAD

**Issue by hewjinxu** [pili-engineering/PLDroidPlayer#1115]
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7481e878 self=0xf0dc8000
  | sysTid=23491 nice=-10 cgrp=default sched=0/0 handle=0xf4df1494
  | state=S schedstat=( 11978347288 4254609244 29448 ) utm=942 stm=255 core=7 HZ=100
  | stack=0xff1c3000-0xff1c5000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/23491/stack)
  native: #00 pc 00061854  /system/lib/libc.so (nanosleep+12)
  native: #01 pc 0003eb5b  /system/lib/libc.so (usleep+54)
  native: #02 pc 000445ed  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/lib/arm/libQPlayer.so (???)
  native: #03 pc 00078489  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/lib/arm/libQPlayer.so (???)
  native: #04 pc 0007b173  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/lib/arm/libQPlayer.so (???)
  native: #05 pc 0007cfc3  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/lib/arm/libQPlayer.so (???)
  native: #06 pc 00411879  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
  native: #07 pc 0040d375  /system/lib/libart.so (art_quick_invoke_stub_internal+68)
  native: #08 pc 003e6c99  /system/lib/libart.so (art_quick_invoke_stub+224)
  native: #09 pc 000a1015  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+136)
  native: #10 pc 001e5b81  /system/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+236)
  native: #11 pc 001e066f  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+814)
  native: #12 pc 003e2781  /system/lib/libart.so (MterpInvokeDirect+196)
  native: #13 pc 00400214  /system/lib/libart.so (ExecuteMterpImpl+14484)
  native: #14 pc 00315bc4  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.qiniu.qplayer.mediaEngine.MediaPlayer.d+150)
  native: #15 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #16 pc 001c94d1  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
  native: #17 pc 001e0657  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
  native: #18 pc 003e18f3  /system/lib/libart.so (MterpInvokeVirtual+442)
  native: #19 pc 00400114  /system/lib/libart.so (ExecuteMterpImpl+14228)
  native: #20 pc 003147f4  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.pili.pldroid.player.PLMediaPlayer.pause+12)
  native: #21 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #22 pc 001c94d1  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
  native: #23 pc 001e0657  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
  native: #24 pc 003e18f3  /system/lib/libart.so (MterpInvokeVirtual+442)
  native: #25 pc 00400114  /system/lib/libart.so (ExecuteMterpImpl+14228)
  native: #26 pc 003154cc  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.pili.pldroid.player.widget.a.pause+32)
  native: #27 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #28 pc 001c94d1  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
  native: #29 pc 001e0657  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
  native: #30 pc 003e1e0f  /system/lib/libart.so (MterpInvokeSuper+1098)
  native: #31 pc 00400194  /system/lib/libart.so (ExecuteMterpImpl+14356)
  native: #32 pc 00314ccc  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.pili.pldroid.player.widget.PLVideoTextureView.pause)
  native: #33 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #34 pc 001c94d1  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
  native: #35 pc 001e0657  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
  native: #36 pc 003e18f3  /system/lib/libart.so (MterpInvokeVirtual+442)
  native: #37 pc 00400114  /system/lib/libart.so (ExecuteMterpImpl+14228)
  native: #38 pc 0030f00c  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.blackshark.discovery.view.widget.PLVideoPlayer.pause+30)
  native: #39 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #40 pc 001c94d1  /system/lib/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+152)
  native: #41 pc 001e0657  /system/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+790)
  native: #42 pc 003e18f3  /system/lib/libart.so (MterpInvokeVirtual+442)
  native: #43 pc 00400114  /system/lib/libart.so (ExecuteMterpImpl+14228)
  native: #44 pc 0030d0cc  /data/app/com.blackshark.discovery-iDCfgk_EhgEpYqpoL3EI0g==/oat/arm/base.vdex (com.blackshark.discovery.view.activity.MomentVideoDetailActivity.onPause+8)
  native: #45 pc 001c4deb  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3880578129+378)
  native: #46 pc 001c9417  /system/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+82)
  native: #47 pc 003d53d9  /system/lib/libart.so (artQuickToInterpreterBridge+880)
  native: #48 pc 004118ff  /system/lib/libart.so (art_quick_to_interpreter_bridge+30)
  at com.qiniu.qplayer.mediaEngine.MediaPlayer.nativePause(Native method)
  at com.qiniu.qplayer.mediaEngine.MediaPlayer.d(MediaPlayer.java:437)
  at com.pili.pldroid.player.PLMediaPlayer.pause(PLMediaPlayer.java:261)
  at com.pili.pldroid.player.widget.a.pause(PLBaseVideoView.java:766)
  at com.pili.pldroid.player.widget.PLVideoTextureView.pause(PLVideoTextureView.java:21)
  at com.blackshark.discovery.view.widget.PLVideoPlayer.pause(PLVideoPlayer.kt:159)
  at com.blackshark.discovery.view.activity.MomentVideoDetailActivity.onPause(MomentVideoDetailActivity.kt:156)
  at android.app.Activity.performPause(Activity.java:7373)
  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
  at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4072)
  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4037)
  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3989)
  at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6758)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by hewjinxu** [comment]
在activity pause时（如退出到后台），对player进行pause，报了anr，以上是anr部分相关的traces，如需要更详细的请回复。考虑可能跟系统都AudioTracker有关（本播放器在我的APP上报了很多AudioTracker问题），但因为没有so中的详细实施细节，不知如何debug。

**Comment by w4901** [comment]
发现了跟你一样的bug，找到原因了吗？

**Comment by hewjinxu** [comment]
更换播放器

**Comment by hewjinxu** [comment]
> 发现了跟你一样的bug，找到原因了吗？

更换播放器

**Comment by logeable** [comment]
please fix this

**Comment by hewjinxu** [comment]
更换gsyvideoplayer
