### ISSUE TITLE
视频暂停问题

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#112]
调用pause()方法暂停之后，再次调用start()方法视频会从头开始播放，而不是在暂停位置播放时什么原因？

**Comment by Jhuster** [comment]
@lzx1 你应该指的是用的`PLVideoView`，home 键退到后台再进来的情况吧 ？ 

https://github.com/pili-engineering/PLDroidPlayer/issues/105

**Comment by lzx1** [comment]
不是，是点击暂停按钮，然后再点击开始按钮。点击暂停按钮的时候我调用的是pause()方法，点击开始按钮调用的是start()方法。

**Comment by Jhuster** [comment]
@lzx1 刚刚在 demo 上验证了，并没有你说的这个问题。
