### ISSUE TITLE
公网rtsp都不能播放

### ISSUE THREAD

**Issue by tzraeq** [pili-engineering/PLDroidPlayer#1126]
就这个地址，我就不明白了，直接用你们的Demo改个地址，都不能播放，直接卡死。rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov

**Comment by ReikyZ** [comment]
支持RTMP和HTTP+FLV直播方式。
 点播支持多种格式(MP4、FLV、MP3、M3U8、AAC)。
 支持视频解码（H264，H265，MPEG4）。
 支持音频解码（AAC，MP3，SPEEX）。

--------------------
以上是我们支持的协议与编码
