### ISSUE TITLE
如何一直显示进度条，就是始终在播放器正下方

### ISSUE THREAD

**Issue by Jame1989** [pili-engineering/PLDroidPlayer#113]
播放器不是全屏的，如何一直显示进度条，就是始终在播放器正下方？

**Comment by Jhuster** [comment]
@Jame1989 进度条的源代码就在 `demo` 里，把 `sDefaultTimeout` 设置为 0 ，即可一直显示。

**Comment by Jame1989** [comment]
这个是的，但是我要的效果是一直显示在播放器下方，要改动的还挺多的，之前是基于Popuwindow做的；还有个问题：循环播放接口没有吗？

**Comment by Jhuster** [comment]
@Jame1989 `PLMediaPlayer ` 提供了 `setLooping` 接口，`PLVideoView` 后面版本会加上。
