### ISSUE TITLE
窗口播放转换全屏

### ISSUE THREAD

**Issue by zilingyao** [pili-engineering/PLDroidPlayer#114]
你好 现在视频布局固定在顶部 下方是一个listview 想在视频窗口加一个全屏切换图标  点击实现横向全屏 请问怎么实现？有没有具体的参数方法可用

**Comment by Jhuster** [comment]
@zilingyao 播放器只负责提供视频播放功能，你所说的这个需求并不是播放器可以帮你完成的，具体实现请参考网上的相关资料。

**Comment by zilingyao** [comment]
你好 谢谢你上个问题的解答 现在有个问题 就是用一个手机推流到我们自己的服务器 然后另一个手机播放的时候出现声音画面不同步的情况 声音快于画面传过来 而且有杂音乱音 请问这是什么情况造成的呢？

**Comment by Jhuster** [comment]
我不清楚你们的推流细节，目前 `PLDroidPlayer` 是没有音视频同步问题，建议你们需要先用 VLC 等第三方播放器看看你们的推流效果。

**Comment by Jame1989** [comment]
具体全屏怎么实现啊，我全屏时，同个Activity 把PLvideoview设置为contentview，但是视频却从头开始播放了，为什么啊？

**Comment by Jhuster** [comment]
`PLVideoView` 在 Activity 销毁的时候，会释放资源，建议不要让 Activity 销毁。
