### ISSUE TITLE
网络异常，恢复网络后如何从断开的位置继续播放

### ISSUE THREAD

**Issue by chenwulue** [pili-engineering/PLDroidPlayer#116]
网络断开
播到01：22提示网络出错
网络恢复
执行resume无效。。。
看demo说
  The PLMediaPlayer has moved to the Error state, if you want to retry, must reset first !
             try {
                 mMediaPlayer.reset();
                 mMediaPlayer.setDisplay(mSurfaceView.getHolder());
                 mMediaPlayer.setDataSource(mVideoPath);
                 mMediaPlayer.prepareAsync();
             } catch (IOException e) {
                 e.printStackTrace();
             }
但是这样就直接从头开发播放了，请问要怎么从停止的位置播放呢？自己记录position，用seekTo实现？

**Comment by Jhuster** [comment]
@chenwulue 嗯，是的。
