### ISSUE TITLE
硬解播放器总是会黑一下然后再开始播放

### ISSUE THREAD

**Issue by gf5353** [pili-engineering/PLDroidPlayer#117]

**Comment by Jhuster** [comment]
@gf5353 刚刚我用 demo 使用硬解播放，没有出现黑一下的问题，确认一下你的流是否有问题。另外，画面没出来前本来就是黑屏状态，“黑一下” 的意思是？

**Comment by gf5353** [comment]
@Jhuster 直接是demo上的 PLMediaPlayerActivity 硬解没有没有这个现象，PLVideoViewActivity 和PLVideoTextureActivity 的硬解 和软解对比，loading状态消失后都会黑一阵子，软解不会，起播速度软解比硬解快

**Comment by Jhuster** [comment]
@gf5353 嗯，明白你的意思了，`PLXXXView` 的 `loading` 是判断 `MEDIA_INFO_VIDEO_RENDERING_START` 或者 `MEDIA_INFO_AUDIO_RENDERING_START` 出现后就隐藏了，硬解部分机型可能渲染画面较慢，建议仿照 “ PLMediaPlayerActivity” 自己来做 `PLXXXView` 的 `loading` 动画，只判断 `MEDIA_INFO_VIDEO_RENDERING_START` 出现再隐藏。

**Comment by gf5353** [comment]
@Jhuster ok明白了
