### ISSUE TITLE
请问支持speex解码吗

### ISSUE THREAD

**Issue by oemers** [pili-engineering/PLDroidPlayer#119]
播放音频，我用项目试了，一直I/O error，想问是否支持 speex 的解码方式？

**Comment by Jhuster** [comment]
@oemers 不支持 speex 的解码。

**Comment by oemers** [comment]
如果 要支持，我该怎么做，（我是新手）

**Comment by Jhuster** [comment]
@oemers 建议直接使用 `ijkplayer` 项目，重新编译 `ffmpeg` 源码，添加对 `speex` 的支持。

**Comment by Jhuster** [comment]
@oemers 可以尝试重新编译我们的底层库：https://github.com/pili-engineering/ijkplayer，配置编译选项，添加对 speex 的支持，然后替换掉 `libpldroidplayer.so`

**Comment by wenjue** [comment]
@Jhuster  您好，编译了你们的底层库后生成了几个.so文件，请问一下你们是如何合并成一个libpldroidplayer.so文件的或者需要在哪里配置一下，望解答一下，谢谢！

**Comment by Jhuster** [comment]
@wenjue 编译完成后应该会生成 libpldroidplayer.so 的，决定生成该文件的配置文件是：`pili-ijkplayer/ijkmedia/ijkplayer/Android.mk` 里面的 `LOCAL_MODULE ` 的定义。

**Comment by wenjue** [comment]
@Jhuster 感谢解答，现在可以了，应该是之前切换分支影响的，谢谢

**Comment by wenjue** [comment]
@Jhuster  您好，我编译你们的底层库的时候遇到一些错误，具体错误如下：
[armeabi] SharedLibrary  : libpldroidplayer.so
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1362: error: undefined reference to 'avfilter_inout_alloc'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1363: error: undefined reference to 'avfilter_inout_alloc'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1379: error: undefined reference to 'avfilter_graph_parse_ptr'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1390: error: undefined reference to 'avfilter_graph_config'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1392: error: undefined reference to 'avfilter_inout_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1393: error: undefined reference to 'avfilter_inout_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1382: error: undefined reference to 'avfilter_link'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1517: error: undefined reference to 'avfilter_graph_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1518: error: undefined reference to 'avfilter_graph_alloc'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1537: error: undefined reference to 'avfilter_get_by_name'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1536: error: undefined reference to 'avfilter_graph_create_filter'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1544: error: undefined reference to 'avfilter_get_by_name'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1543: error: undefined reference to 'avfilter_graph_create_filter'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1589: error: undefined reference to 'avfilter_graph_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1428: error: undefined reference to 'avfilter_get_by_name'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1427: error: undefined reference to 'avfilter_graph_create_filter'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1434: error: undefined reference to 'avfilter_get_by_name'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1433: error: undefined reference to 'avfilter_graph_create_filter'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1464: error: undefined reference to 'avfilter_link'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1490: error: undefined reference to 'avfilter_link'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1479: error: undefined reference to 'avfilter_link'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:3142: error: undefined reference to 'avfilter_register_all'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1655: error: undefined reference to 'av_buffersrc_add_frame'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1658: error: undefined reference to 'av_buffersink_get_frame_flags'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1683: error: undefined reference to 'avfilter_graph_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1712: error: undefined reference to 'avfilter_graph_alloc'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1756: error: undefined reference to 'avfilter_graph_free'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1757: error: undefined reference to 'avfilter_graph_alloc'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1774: error: undefined reference to 'av_buffersrc_add_frame'
/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/jni/ijkmedia/ijkplayer/ff_ffplay.c:1781: error: undefined reference to 'av_buffersink_get_frame_flags'
collect2: error: ld returned 1 exit status
make: *** [/home/satan/android/code/pili-ijkplayer/android/ijkplayer/ijkplayer-armv5/src/main/obj/local/armeabi/libpldroidplayer.so] Error 1

请问是我哪里操作步骤错误了吗

**Comment by Jhuster** [comment]
@wenjue 是否有执行：

```
./init-android.sh

cd android/contrib
./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all
```

**Comment by wenjue** [comment]
有，我是按照README步骤来编译的，我编译bilibili的可以，你们的就报那个错误

**Comment by uglyer** [comment]
@wenjue 我也是遇到这个问题，同样有执行，不知道应该如何解决。

**Comment by wenjue** [comment]
@uglyer 我也没有解决，后来我直接用bilibili的了

**Comment by uglyer** [comment]
@wenjue 谢谢，用B站的播放直播流延迟如何？

**Comment by wenjue** [comment]
@uglyer 延迟的影响是多方面的，我用rtmp协议播的话延迟大概2-3s

**Comment by uglyer** [comment]
@wenjue 我现在有一个蛋疼的需求，播放局域网的rtsp源，同时播放4路，要求延迟在1s内。

**Comment by uglyer** [comment]
@wenjue 同时，还有旋转视频流90度。

**Comment by wenjue** [comment]
@uglyer 我对流媒体这块也是刚接触，还在学习中，这个帮不到你，抱歉

**Comment by uglyer** [comment]
@wenjue 没事，非常感谢。

@Jhuster 能否帮忙看一下这个是什么问题导致，或者能不能编译个支持rtsp协议的so，还用着你们家的直播服务呀。

**Comment by uglyer** [comment]
@wenjue 没事，非常感谢。

@Jhuster 能否帮忙看一下这个是什么问题导致，或者能不能编译个支持rtsp协议的so，还用着你们家的直播服务呀。

**Comment by uglyer** [comment]
@wenjue 我发现用module.sh 链接lite是能编译，用module-default.sh就不行，但是需要添加rtsp支持，不知道怎么做了。

**Comment by wenjue** [comment]
@uglyer  [how to play RTSP urls on ios IJKPlayer?](https://github.com/Bilibili/ijkplayer/issues/1108)

**Comment by uglyer** [comment]
@wenjue 现在没有修改任何文件，直接编译 然后替换so文件后再解码第一帧之后遇到这样……

No implementation found for long tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(int, long) (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer__1getPropertyLong__IJ)
at tv.danmaku.ijk.media.player.IjkMediaPlayer._getPropertyLong(Native Method)
                                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.getPktTotalSize(IjkMediaPlayer.java:716)

**Comment by pcyan** [comment]
@uglyer 我也遇到了`No implementation found`的错误，你解决了吗

**Comment by Jhuster** [comment]
最新的 1.4.1 版本已经支持 speex 解码了

**Comment by pcyan** [comment]
@Jhuster 支持speex解码的话，默认是不用speex的对吗，wiki也没看到要怎么使用speex进行解码
