### ISSUE TITLE
missing picture in access unit with size 4428

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#120]
![image](https://cloud.githubusercontent.com/assets/12270504/15533152/e2b1edce-2295-11e6-9393-d8d10e247b28.png)
xiaomi mi 3c 6.0.1推的流在PLVideoTextureView播放器上会出现如下错误，然后画面是一直不出来的

**Comment by Jhuster** [comment]
@tz-xiaomage 使用 VLC 或者 FFPlay 是否可以播放你推的流，你推的流是什么格式，什么编码配置。

**Comment by tz-xiaomage** [comment]
@Jhuster 推的流是rtmp的， 我用的别的手机推的流是可以播放的，硬编码视频H.264

**Comment by Jhuster** [comment]
@tz-xiaomage 看样子像推流端有问题，使用其他的播放器播放一下你的流，然后检测一下在 xiaomi mi 3c 6.0.1 推流的 log，看看有什么异常。
