### ISSUE TITLE
播放rtmp出现 Server error: NetStream.Play.StreamNotFound

### ISSUE THREAD

**Issue by scdqs** [pili-engineering/PLDroidPlayer#126]
SDK的是最新的1.2.2版本
播放默认地址的流没问题
但是播放我自己搭建的Red5提供的直播流就无法播放（用PLAudioPlayerActivity能播放出声音）
![image](https://cloud.githubusercontent.com/assets/5986625/15632211/33e30a28-25bd-11e6-9079-5eec403e4faf.png)

**Comment by Jhuster** [comment]
@scdqs 服务器的搭建可能有问题，建议先使用 VLC 或者 ffplay 播放你的流试一试。

**Comment by fool019** [comment]
我的也是报这个错误，但是我的直播流是没问题的，网页、ios端都能播放，就是安卓的播放不了。
播放器能播放demo里的视频，但是播放我的视频流就报这个错误，是什么问题能？

**Comment by Jhuster** [comment]
@fool019 @scdqs 这种错误一般是由于服务器做了权限处理，可以考虑联合服务器的开发一起调试一下为什么返回：“Operation not permitted”

**Comment by fool019** [comment]
刚刚解决了
// Some optimization with buffering mechanism when be set to 1
mAVOptions.setInteger(AVOptions.KEY_LIVE_STREAMING, 1);  //这里把1改成0就可以了
