### ISSUE TITLE
使用PLMediaPlayer实例如何进行高级配置？

### ISSUE THREAD

**Issue by fangyong** [pili-engineering/PLDroidPlayer#127]
PLMediaPlayer mMediaPlayer = new PLMediaPlayer();
我看文档里面写的是通过VideoView去设置的，比如我想设置硬件解码我该如何调用方法？

**Comment by Jhuster** [comment]
@fangyong `PLMediaPlayer` 构造函数支持 `public PLMediaPlayer(AVOptions options)`，`AVOptions` 的用法与 `PLVideoView` 一样，`demo` 里 `PLMediaPlayerActivity` 已经给出了示例的。

**Comment by fangyong** [comment]
谢谢，我是直接看文档就去写了，没看sample，再次感谢你的耐心回答！！
