### ISSUE TITLE
卡机无响应,

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#128]
受网络影响或者播放错误影响 会导致无响应 ,特别是在切换视频过程中,问题持续这么多天了，真心有点失望。。这效率。

**Comment by Jhuster** [comment]
@qssq 能否描述一下详细情况，使用 demo 在真机上调试是否也有问题？网络是 移动网络 还是 WiFi，能否发一下 ANR 的 log 信息。
