### ISSUE TITLE
error android studio import demo

### ISSUE THREAD

**Issue by msdos2** [pili-engineering/PLDroidPlayer#13]
Information:Gradle tasks [:app:assembleDebug]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava
:app:preDexDebug UP-TO-DATE
:app:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/pili/pldroid/player/IMediaController$MediaPlayerControl;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_51\bin\java.exe'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 3.45 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by jpxiong** [comment]
You should remove the old version jar file from your project, and only reserve the newest one.

**Comment by msdos2** [comment]
I could file you indicate that the project would be removed
Thank you

**Comment by jpxiong** [comment]
? I can't understand well.

**Comment by msdos2** [comment]
I file I have to remove the project studio android

**Comment by jpxiong** [comment]
So is that ok now ?

**Comment by msdos2** [comment]
![captura de pantalla 10](https://cloud.githubusercontent.com/assets/7550249/9305206/aa9e3dcc-44ef-11e5-9ab3-e07e1ff0af2e.png)

**Comment by jpxiong** [comment]
Where is your /libs folder ?

**Comment by msdos2** [comment]
![captura de pantalla 12](https://cloud.githubusercontent.com/assets/7550249/9305269/604df162-44f0-11e5-9144-aba8dac40c15.png)

**Comment by jpxiong** [comment]
As the pre comment:
>You should remove the old version jar file from your project, and only reserve the newest one.

You should delete the `pldroid-player-1.0.0.jar` from your Android Studio.

**Comment by msdos2** [comment]
Thanks already solved
