### ISSUE TITLE
播放网络视频（不是直播），断网再恢复没有任何反应

### ISSUE THREAD

**Issue by Jame1989** [pili-engineering/PLDroidPlayer#130]
如题：
1.播放时，拔wifi的网线，这时候，当播放到缓冲处就一直转圈圈，即使恢复网络也这样；
2.播放时，拔wifi的网线，在播放到达缓冲处前恢复网络，这时候现象是播放到缓冲处重头播放了。
 请问这2个问题如何解决？非常急

**Comment by Jhuster** [comment]
@Jame1989 确实有这个现象，网络断开－－恢复后，在播放完缓冲的数据后，会触发 `onCompletion`，目前可以通过 `getDuration()` 和 `getCurrentPosition()` 来判断是否播放完毕，如果没有播放完毕，则重连后调用 `seekTo()` 恢复到上次播放的位置继续播放。

**Comment by Jame1989** [comment]
我测试过，没有触发onError也没触发onCompletion,播放到缓冲处日志：
05-31 16:18:43.401    3354-3354/com.fztech.qupeiyintv I/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Info: MEDIA_INFO_VIDEO_RENDERING_START
05-31 16:18:43.401    3354-3354/com.fztech.qupeiyintv D/PLMediaPlayer﹕ first video rendered: 975 ms
05-31 16:19:25.021    3354-4874/com.fztech.qupeiyintv D/IJKMEDIA﹕ FFP_MSG_BUFFERING_START:

**Comment by Jame1989** [comment]
@Jhuster 
我测试过，没有触发onError也没触发onCompletion,播放到缓冲处日志：
05-31 16:18:43.401 3354-3354/com.fztech.qupeiyintv I/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Info: MEDIA_INFO_VIDEO_RENDERING_START
05-31 16:18:43.401 3354-3354/com.fztech.qupeiyintv D/PLMediaPlayer﹕ first video rendered: 975 ms
05-31 16:19:25.021 3354-4874/com.fztech.qupeiyintv D/IJKMEDIA﹕ FFP_MSG_BUFFERING_START:

**Comment by Jhuster** [comment]
@Jame1989 我在 `demo` 里测试过，会触发 `onCompletion` , 你是否调用了 `setOnCompletionListener`

**Comment by Jame1989** [comment]
@Jhuster 调用了啊，是把wifi的外网拔掉，相当于假网，当缓冲播放完之后，就一直转圈圈。最后一句日志：FFP_MSG_BUFFERING_START:

**Comment by Jame1989** [comment]
@看文档上说的是直播会触发onError，如果onError返回true，则不会触发onCompletion；如果如果onError返回false，则会触发onCompletion； 但是我测试不论onError还是onCompletion都不触发

**Comment by Jhuster** [comment]
@Jame1989 假网的情况下确实有这个问题，谢谢反馈，目前版本你可以考虑加一个 `FFP_MSG_BUFFERING_START ` 超时，超时后重新连接。

**Comment by Jame1989** [comment]
@Jhuster 怎么加超时啊，他只是在onInfo里回调了一次。。。我怎么判断超时啊

**Comment by Jhuster** [comment]
@Jame1989 收到 `FFP_MSG_BUFFERING_START ` 后，如果超过一定时间没有收到`MEDIA_INFO_BUFFERING_END`，则判定为超时。

**Comment by Jame1989** [comment]
@Jhuster  好的 谢谢。希望后面能完善一些异常的回调。O(∩_∩)O
