### ISSUE TITLE
一个页面中有两个PLVideoTextureView，同时播放会有画面卡顿的情况

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#131]
两个PLVideoTextureView是叠合在一起的，PLVideoTextureView--A是320_320，B是640_480
320_320的在640_480的上面

**Comment by Jhuster** [comment]
@tz-xiaomage 两路解码播放的话，手机性能不够，难免出现卡顿。都使用的是软解还是硬解？

**Comment by tz-xiaomage** [comment]
都是使用硬解

**Comment by Jhuster** [comment]
@tz-xiaomage 嗯，跟你的手机型号/性能、网络带宽、播放视频的分辨率/码率/帧率都有一定关系。
