### ISSUE TITLE
PLVideoViewActivity 为什么不能快进

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#132]
demo 里面的PLVideoViewActivity 为什么不能快进，下面那条不能拉动，VideoViewActivity里面可以，需要怎么设置吗。

**Comment by Jhuster** [comment]
@talentsxh 进度条是否能拖动，取决于 `MediaController` 的构造函数的第三个参数，如果播放的是文件和回放视频，则可以设置为true，如果是在线直播，应该为false，逻辑上直播应该不支持拖动。

**Comment by talentsxh** [comment]
感谢大神对初学者的回答，还有个问题是这支持哪些格式的网站上的视频，我已经测试过，MP4，flv，m3u8，以及最初的rtmp，swf的格式好像有点问题。想问一下是否支持avi， .wma, .rmvb。因为这几种也很常用。

**Comment by Jhuster** [comment]
@talentsxh 这是另一个问题，建议新开 issue，我们默认没有支持所有格式，这样会导致 so 太大，你可以重新编译我们的底层源码，添加更多格式的支持，https://github.com/pili-engineering/ijkplayer，具体支持的格式的配置文件在该项目的 `module.sh` 脚本中。编译成功后，替换本工程的 `libpldroidplayer.so` 即可。

**Comment by talentsxh** [comment]
改了之后发现还是不能拖动，而且网速不好情况下，在缓冲也没有提示，下面的时间还会继续的走。

**Comment by Jhuster** [comment]
@talentsxh 1. 播放本地文件试试拖动  2. 播放的是直播还是回放，地址发出来看看

**Comment by talentsxh** [comment]
本地和网络的都一样无法拖动，如果是网络的地址，网速不好，下面的时间还是继续走，但是画面不动，缓冲的进度条也不见了。无法像VideoView一样。网络地址http://img1.peiyinxiu.com/2014121211339c64b7fb09742e2c.mp4

**Comment by Jhuster** [comment]
`MediaController` 的构造函数的第三个参数应该设置为 false，刚刚我用 demo 试过了，可以拖动。

**Comment by talentsxh** [comment]
能否发一份你的demo给我775767274@qq.com，感谢。

**Comment by Jhuster** [comment]
@talentsxh 这个 github repo 不就是 demo 源码么 ？git clone 或者 download 下来就可以跑了。

**Comment by talentsxh** [comment]
感谢，表示已经解决了。

**Comment by 1214658495** [comment]
大神，求助一下。我碰到和上面差不多的问题，播上面的地址是没有问题，但我的播放地址是“rtsp://192.168.42.1/tmp/SD0/TEST.MP4”，这个是流媒体本地视频。拖动进度条视频就卡在那，没法快进，求大神帮忙分析一下。（没有变更demo的任何代码）
