### ISSUE TITLE
audioManager的泄露问题导致activity常驻内存

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#133]
我反复测试了一下 ，发现 所持有的PLVideovwiew  原来是在内存中没有销毁 ，可能是这个原因,但是我后面 在onDestory强制把mediacontrol里面的质控了，确实没有了，但是还是存在audioMnager泄露 ，看直播 就会有泄露希望赶快修复下，我这苹果都上线啦，安卓这个泄露问题比较严重 呀。不能上线感觉。

**Comment by Jhuster** [comment]
@qssq 确实有`AudioManager`导致的泄漏问题，下一版修复，下周发布新版。

**Comment by Jhuster** [comment]
@qssq 我使用 `leakcanary` 测试 `demo` 并没有任何内存泄漏，请问你是如何测试内存泄漏的 ？有什么截图吗？

**Comment by qssq** [comment]
什么叫泄露就是actity销毁了还持有引用你只需要反复点击播放然后关闭播放界面就行了 直接把播放地址写好方便更快测试停留在非播放界面 不久后就有结果了也就是mainactivity

**Comment by qssq** [comment]
会感觉有点卡 内存占用高
