### ISSUE TITLE
播放器没声音

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#134]
手机在同个页面进行先 推流 然后 播放rtmp流，发现播放rtmp流是没有声音的。
请问是不是因为推流那一块占用了音频，所以播放不出声音？
能不能让两边共享音频？

**Comment by Jhuster** [comment]
@tz-xiaomage 推流只是采集音频，播放器只是播放声音，不冲突，你先确认一下单独播放这个 rtmp 流是否有声音，或者用第三方播放器播放一下这个 rtmp 流。

**Comment by tz-xiaomage** [comment]
我页面中只是推流的话，是有声音的，但是只要在播放的过程中进行推流，这个流就没声音，好像音频被播放器也占用了一样

**Comment by kyserCool** [comment]
我也发现这个问题，好像推流的那个采集不到音频，被占用了一样

**Comment by kyserCool** [comment]
@Jhuster 请教一下，不知道音频的采集是否能怎么设置可以让播放的跟录制的都同时进行？

**Comment by Jhuster** [comment]
@tz-xiaomage @kyserCool 播放器肯定没有占用音频采集，我刚刚用我们的推流sdk和播放器sdk在一个页面中验证过，是可以同时采集和播放的，你们使用的推流sdk是什么？版本是多少？

**Comment by tz-xiaomage** [comment]
@Jhuster 我使用的是[yasea](https://github.com/begeekmyfriend/yasea)
