### ISSUE TITLE
播放m3u8直播，出现404 not found resourcce错误

### ISSUE THREAD

**Issue by zc9** [pili-engineering/PLDroidPlayer#136]

**Comment by Jhuster** [comment]
@zc9 请确认视频流是否存在。

**Comment by zc9** [comment]
@Jhuster 视频流存在，用vlc可以播放

**Comment by Jhuster** [comment]
@zc9 视频流地址发出来看看

**Comment by zc9** [comment]
http://mobile.api.hunantv.com/channel/getDetail?appVersion=4.6.4&channelId=1011&device=iPhone&mac=1364eb814e83677e5ccd3769f445d64d63e79948&osType=ios&osVersion=9.000000&seqId=0f985d386555fe901f51e37e75c23a2f&ticket=X340YOCVRSJERASZAB61&type=live

**Comment by zc9** [comment]
我是从这个接口拿的

**Comment by zc9** [comment]
@Jhuster 我用vlc测试是可以的

**Comment by Jhuster** [comment]
@zc9 直接给出一个播放的 URL 吧

**Comment by zc9** [comment]
@Jhuster http://vl.dopool.com/video4/index_128k.m3u8?date=20160605165208&uid=&rnd=2016060516520845269&client=imgo&key=a705353d59942eaf14ef3cd3a46637de&cip=192.168.1.220&cck=5c4cbd5de2eef72792b15ef59ae74869

**Comment by Jhuster** [comment]
@zc9 我这边用 `VLC` 和 `Safari` 播放，要么出错，要么出现第一帧画面后就无法继续播放，用 `ffplay` 播放，显示的是：“HTTP error 500 Internal Server Error”，请检查一下服务器程序。

**Comment by zc9** [comment]
@Jhuster 我用vlc sdk 做测试可以播放啊，我同事在chrome装了个m3u8插件也是可以播放的

**Comment by zc9** [comment]
@Jhuster 意思是服务器程序有问题？那奇怪为什么拿vlc sdk测试的时候可以播放啊

**Comment by Jhuster** [comment]
@zc9 下面是使用 `ffplay` 播放打印的 `log`，一个标准的流，应该在各种通用型播放器都能正常播放出来：

```
ffplay -v debug "http://vl.dopool.com/video4/index_128k.m3u8?date=20160605165208&uid=&rnd=2016060516520845269&client=imgo&key=a705353d59942eaf14ef3cd3a46637de&cip=192.168.1.220&cck=5c4cbd5de2eef72792b15ef59ae74869"

ffplay version 3.0.1 Copyright (c) 2003-2016 the FFmpeg developers
  built with Apple LLVM version 7.3.0 (clang-703.0.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libmp3lame --enable-libxvid --enable-librtmp --enable-ffplay --enable-libspeex --enable-libfdk-aac --enable-openssl --enable-libopus --enable-nonfree --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[http @ 0x7fa4a2516200] Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[http @ 0x7fa4a2516200] request: GET /video4/index_128k.m3u8?date=20160605165208&uid=&rnd=2016060516520845269&client=imgo&key=a705353d59942eaf14ef3cd3a46637de&cip=192.168.1.220&cck=5c4cbd5de2eef72792b15ef59ae74869 HTTP/1.1
User-Agent: Lavf/57.25.100
Accept: */*
Range: bytes=0-
Connection: close
Host: vl.dopool.com
Icy-MetaData: 1


[http @ 0x7fa4a2516200] HTTP error 404 Not FoundB sq=    0B f=0/0   
http://vl.dopool.com/video4/index_128k.m3u8?date=20160605165208&uid=&rnd=2016060516520845269&client=imgo&key=a705353d59942eaf14ef3cd3a46637de&cip=192.168.1.220&cck=5c4cbd5de2eef72792b15ef59ae74869: Server returned 404 Not Found
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
```

**Comment by zc9** [comment]
@Jhuster 意思是这个流不是标准的流，有什么办法解决吗？

**Comment by Jhuster** [comment]
@zc9 并不是流的问题，log 里显示服务器返回 `HTTP error 404 Not Found` ，建议你用 `ffplay` 播放，同时跟服务器的同事联调一下，看看为什么访问这个流的时候，会返回 `HTTP error 404 Not Found`

**Comment by zc9** [comment]
@Jhuster 我们现在拿的是别人的测试地址，自己的服务器还没搭建好

**Comment by zc9** [comment]
@Jhuster 我刚才拿了其它地址测试，播放一段时间画面卡死，声音还有。重新进入又可以了

**Comment by Jhuster** [comment]
@zc9 你们的流我用 vlc 播放偶尔也能出来，播放一会就卡死，服务器的支持可能不够好。`demo` 播放其他第三方的 HLS 流都没有问题的。

**Comment by zc9** [comment]
@Jhuster 可以加下你的QQ吗

**Comment by Jhuster** [comment]
@zc9 就在 issue 上讨论吧，解决的问题可以让更多的人搜索到，你的这个问题非常建议你跟你们使用的服务器端的人沟通一下。

**Comment by zc9** [comment]
@Jhuster 我在网上找的一个hls地址，播放一段时间画面停止了？

**Comment by zc9** [comment]
@Jhuster PLVideoView类横屏的时候怎么旋转画面

**Comment by Jhuster** [comment]
@zc9 如果想旋转画面，请使用 `PLVideoTextureView` ,  `PLVideoView` 不支持旋转。

**Comment by zc9** [comment]
@Jhuster 用PLVideoView全屏模式下画面没办法跟着翻转？

**Comment by Jhuster** [comment]
@zc9 没办法，`PLVideoView` 不支持旋转。

**Comment by zc9** [comment]
@Jhuster http://vl.dopool.com/video7/index_128k.m3u8?date=20160612124910&uid=&rnd=2016061212491031611&client=imgo&key=c3ab0d64ebcb52b05a348c21aa0fa740&cip=192.168.1.220&cck=b4dbe4bbcffa8106b7f314078aba0dd7 这个直播地址用安卓原生的video可以播放，为什么用这个就出现404 resource not found

**Comment by longbai** [comment]
@zc9 刚才用ffplay也不能播，看了下，m3u8 里面的ts 文件返回404 了

**Comment by zc9** [comment]
@longbai 为什么用安卓原生的video都可以播放，这个很奇怪
