### ISSUE TITLE
支持MKV和RMVB等视频的播放么?

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#137]

**Comment by Jhuster** [comment]
@yanxiandroid 不支持。我们默认没有支持所有格式，这样会导致 so 太大，你可以重新编译我们的底层源码，添加更多格式的支持，[ijkplayer](https://github.com/pili-engineering/ijkplayer)，具体支持的格式的配置文件在该项目的 `module.sh` 脚本中。编译成功后，替换本工程的 `libpldroidplayer.so` 即可。

**Comment by yanxiandroid** [comment]
@Jhuster 您好,我只是一个做Android应用软件的开发者,我已经用上了您的框架到项目中了,没编译过底层源码,可以提供相关的方法和资料吗?

**Comment by Jhuster** [comment]
@yanxiandroid 编译方法请参考该项目的 ReadMe.md 文档。

**Comment by yanxiandroid** [comment]
@Jhuster 我说的是so包的编译方法,,.顺便问一下.播放本地视频完毕之后怎么才能播放下一个本地视频,在onCompletion里面监听设置路径貌似不行?
