### ISSUE TITLE
关于跟cardboard的结合

### ISSUE THREAD

**Issue by chenwulue** [pili-engineering/PLDroidPlayer#138]
其实这个问题我都不清楚是要在这里问还是去cardboard那里问，是这样的，当我的项目中同时引用了Cardboard跟你的sdk，在某些机型（目前测试出来的是小米note高配版）上，会导致找不到cardboardview，在没有用到你的东西的时候都会（只用到cardboardview），然后把你sdk里的jni里面的东西全部删掉了就没问题。。。

**Comment by jans1086** [comment]
你好，请问你们是用cardboard SDK结合这个来做VR直播吗？希望可以交流一下

**Comment by chenwulue** [comment]
@jans1086 好啊，我QQ 853565866

**Comment by longbai** [comment]
@chenwulue 有没有完整的log？
