### ISSUE TITLE
http播放：出现404 not found resourcce错误

### ISSUE THREAD

**Issue by zhiwo** [pili-engineering/PLDroidPlayer#139]
http://dl.fyfile.com:81/vod1/丹尼-席克-定意爱孩子/1心与心的连结VS-外在的掌控-实用QA.mp4

用浏览器可以打开

**Comment by Jhuster** [comment]
@zhiwo ffplay 和 VLC 都无法打开这个流。

**Comment by longbai** [comment]
这个地址 浏览器也打不开 http://dl.fyfile.com:81/vod1/丹尼-席克-定意爱孩子/1心与心的连结VS-外在的掌控-实用QA.mp4 
能打开的是这个 http://dl.fyfile.com/vod1/丹尼-席克-定意爱孩子/1心与心的连结VS-外在的掌控-实用QA.mp4，404 一般都是资源找不到，服务器端的问题。

**Comment by zhiwo** [comment]
@longbai 牛啊，我们服务端都不知道哪儿的问题，感谢感谢，我还以为视频问题呢
