### ISSUE TITLE
rtmp is supported?

### ISSUE THREAD

**Issue by msdos2** [pili-engineering/PLDroidPlayer#14]
08-17 15:09:48.580   30581-4191/com.pili.android.playerdemo W/IJKMEDIA﹕ remove 'timeout' option for rtmp.
08-17 15:09:48.580   30581-4191/com.pili.android.playerdemo W/IJKMEDIA﹕ Detected librtmp style URL parameters, these aren't supported by the libavformat internal RTMP handler currently enabled. See the documentation for the correct way to pass parameters.
08-17 15:09:48.650  30581-30581/com.pili.android.playerdemo I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1803e8eb time:80199841
08-17 15:09:48.670  30581-30581/com.pili.android.playerdemo V/ActivityThread﹕ updateVisibility : ActivityRecord{c6cf643 token=android.os.BinderProxy@253103fc {com.pili.android.playerdemo/com.pili.pldroid.playerdemo.MainActivity}} show : false
08-17 15:09:48.700  30581-30581/com.pili.android.playerdemo W/IInputConnectionWrapper﹕ getTextBeforeCursor on inactive InputConnection
08-17 15:09:48.700  30581-30581/com.pili.android.playerdemo W/IInputConnectionWrapper﹕ getExtractedText on inactive InputConnection
08-17 15:09:48.870  30581-30581/com.pili.android.playerdemo W/IInputConnectionWrapper﹕ showStatusIcon on inactive InputConnection
08-17 15:09:48.940   30581-4191/com.pili.android.playerdemo E/IJKMEDIA﹕ rtmp://31.220.0.155/privatestream/ playpath=launo1?keys=g5tlrvVt3J87f6Rb9u5bGw&keyt=1438923315 swfUrl=http://privatestream.tv/js/jwplayer.flash.swf live=1 pageUrl=http://privatestream.tv/player?streamname=launo1&width=800&height=600: I/O error
08-17 15:09:48.940   30581-4188/com.pili.android.playerdemo D/IJKMEDIA﹕ FFP_MSG_ERROR: -5
08-17 15:09:48.940  30581-30581/com.pili.android.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Error (-10000,-5)
08-17 15:09:48.940  30581-30581/com.pili.android.playerdemo D/VideoView﹕ Error: -10000,-5
08-17 15:09:48.940  30581-30581/com.pili.android.playerdemo D/VideoPlayerActivity﹕ onError what=-10000, extra=-5

**Comment by jpxiong** [comment]
PLDroidPlayer support `RTMP`/`HLS`/`mainstream media format`(like `mp4`, etc.). You can find the feature support list in README.

The error is the I/O error. You should check the link whether valid.

**Comment by msdos2** [comment]
this link if it works. you can add the lib librtmp in case prodría pay for it took a long time trying to get to operate the librtmp .thanks 
link: 
rtmp://31.220.0.155/privatestream/ playpath=launo1?keys=g5tlrvVt3J87f6Rb9u5bGw&keyt=1438923315 swfUrl=http://privatestream.tv/js/jwplayer.flash.swf live=1 pageUrl=http://privatestream.tv/player?streamname=launo1&width=800&height=600

**Comment by jpxiong** [comment]
Sorry. I can't understand what you said. If you are a Chinese, please say Chinese instead of English.

**Comment by msdos2** [comment]
you can add support RTMP , this link works. if necessary he could pay for it. I am not able to compile libtrmp

**Comment by alcastelo** [comment]
Hi there.
I know rtmp is working, since i make test and the streams are showing.
msdos 2 Are you spanish?

**Comment by jpxiong** [comment]
@msdos2  RTMP and hls are supported. PLDroidPlayer is based on ffplay. You do not need do anything else, just run the demo. I found the log you posted, it's I/O error. Can you test the link by ffplay ?

**Comment by jpxiong** [comment]
@msdos2 You just need input the link without the AVFormat properties. I noticed that your link includes the `live=1`. By now, the newest version is v1.1.2. I suggest you use the newest version to do the test.

**Comment by msdos2** [comment]
![captura de pantalla 15](https://cloud.githubusercontent.com/assets/7550249/9357308/839c75ac-4686-11e5-82fb-2ed37d1386fb.png)
teste 1.1.2

**Comment by alcastelo** [comment]
@msdos2  as @jpxiong says, try to test the link with ffplay.

Intenta reproducir la url con el reproductor ffplay para PC, si funciona ahi, deberia funcionar en este.  Los parametros de AVFormat tendras que eliminarlos (puede que solo con el rtmp:xxx.xxx.xxx.xxx/xxxx/id sea suficiente). Casi seguro que tu problema es saber como pasar los parametros (por ejemplo el keys y el keyt)  al reproductor, ya que los streams rtmp funcionan . 

Sorry about the spanish chat, i hope this help @msdos2.

**Comment by msdos2** [comment]
gracias probare lo que  mas ha dicho.   yo creo le falta compilar la librtmp  el rtmdump  https://github.com/yixia/librtmp para funcione con parametros token ect.

**Comment by msdos2** [comment]
AVOptions options = new AVOptions();
        //options.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 3 * 1000); // the unit of timeout is ms
        ///options.setInteger(AVOptions.KEY_MEDIACODEC, 1); // 1 -> enable, 0 -> disable
       // options.setString(AVOptions.KEY_FFLAGS, AVOptions.VALUE_FFLAGS_NOBUFFER); // "nobuffer"
        //options.setInteger(AVOptions.KEY_BUFFER_TIME, 1000); // the unit of buffer time is ms
        mVideoView.setVideoURI(Uri.parse("rtmp://31.220.0.139"));
        options.setString("rtmp_app","/pull");
        options.setString("rtmp_playpath","hollywood562?keys=0Zi36_JZh1oV0d7O7EuwGA&keyt=1440252641");
        options.setString("rtmp_pageurl","http://leton.tv/player.php?streampage=hollywood562&width=600&height=450");
        options.setString("rtmp_swfurl", "http://files.leton.tv/jwplayer.flash.swf");
        mVideoView.setAVOptions(options);

**Comment by jpxiong** [comment]
No. AVOptions only support `KEY_GET_AV_FRAME_TIMEOUT `, `KEY_MEDIACODEC `,`KEY_FFLAGS `,`KEY_BUFFER_TIME ` at present. Next time we will support more options.

**Comment by jpxiong** [comment]
I compile a temp jar file [here](http://7xigry.com1.z0.glb.clouddn.com/pldroid-player-1.1.2.jar), supporting to add each option into player. Download the jar and test it like this:

```
        AVOptions options = new AVOptions();
//        options.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 3 * 1000); // the unit of timeout is ms
//        options.setInteger(AVOptions.KEY_MEDIACODEC, 1); // 1 -> enable, 0 -> disable
        options.setString(AVOptions.KEY_FFLAGS, AVOptions.VALUE_FFLAGS_NOBUFFER); // "nobuffer"
//        options.setInteger(AVOptions.KEY_BUFFER_TIME, 1000); // the unit of buffer time is ms

        options.setString("rtmp_app","/pull");
        options.setString("rtmp_playpath","hollywood562?keys=0Zi36_JZh1oV0d7O7EuwGA&keyt=1440252641");
        options.setString("rtmp_pageurl","http://leton.tv/player.php?streampage=hollywood562&width=600&height=450");
        options.setString("rtmp_swfurl", "http://files.leton.tv/jwplayer.flash.swf");

        mVideoView.setAVOptions(options);
        mVideoView.setOnTouchListener(this);

        mVideoView.setVideoPath("rtmp://31.220.0.139");
```

I tried, but i got I/O error. Maybe the connection is closed.

Hope its helpful for you.

**Comment by msdos2** [comment]
it works now . I modified these parameters. now comes another problem some links must be added the token parameter. but it does not work .

       AVOptions options = new AVOptions();
//        options.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 3 * 1000); // the unit of timeout is ms
//        options.setInteger(AVOptions.KEY_MEDIACODEC, 1); // 1 -> enable, 0 -> disable
        options.setString(AVOptions.KEY_FFLAGS, AVOptions.VALUE_FFLAGS_NOBUFFER); // "nobuffer"
//        options.setInteger(AVOptions.KEY_BUFFER_TIME, 1000); // the unit of buffer time is ms
        options.setString("rtmp_app","pull");
        options.setString("rtmp_playpath","hollywood562?keys=w_AJH2zvYTNmtqkj11IdwQ&keyt=1440341458");
        options.setString("rtmp_pageurl","http://leton.tv/player.php?streampage=hollywood562&width=600&height=450");
        options.setString("rtmp_swfurl", "http://files.leton.tv/jwplayer.flash.swf");
        mVideoView.setAVOptions(options);
     mVideoView.setVideoPath("rtmp://93.174.95.87");
This link contains token but not working.
        options.setString("rtmp_app","iguide");
        options.setString("rtmp_playpath","0bf02qe6msgtu4s");
        options.setString("rtmp_pageurl","http://www.iguide.to/view/1/HBO");
        options.setString("rtmp_swfurl", "http://www.iguide.to/player/secure_player_iguide_token.swf");
        options.setString("rtmp_token", "#ed%h0#w18623jsda6523lDGD");
        options.setString("rtmp_live", "1");
               mVideoView.setAVOptions(options);
     mVideoView.setVideoPath("rtmp://safe.iguide.to");
this link is the original:
rtmp://safe.iguide.to/iguide playpath=0bf02qe6msgtu4s swfUrl=http://www.iguide.to/player/secure_player_iguide_token.swf live=1 pageUrl=http://www.iguide.to/view/1/HBO token=#ed%h0#w18623jsda6523lDGD


thanks very much for your help.

**Comment by jpxiong** [comment]
Is it OK on ffplay ? What's the error information ?

**Comment by jpxiong** [comment]
Close as no feedback any more!
