### ISSUE TITLE
播放网络视频，home退出，重新进入又重新开始。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#142]
播放网络视频，home退出，重新进入又重新开始。有哪些属性可以设置吗。

**Comment by Jhuster** [comment]
@talentsxh 这周会发布新版，避免这个问题。

**Comment by talentsxh** [comment]
希望可以加一个可以调节亮度和声音的seekbar，那样的话就完美多了。

**Comment by Jhuster** [comment]
@talentsxh 调节亮度、声音、进度条等等 UI 控件，并不是播放器的核心，不同的人也有不同的 UI 定制化需求，因此建议使用者自己来实现。

**Comment by Jhuster** [comment]
@talentsxh 请更新到 1.2.3 版，解决了本 issue 提出的问题。
