### ISSUE TITLE
此sdk需要授权吗？

### ISSUE THREAD

**Issue by SmallStoneDD** [pili-engineering/PLDroidPlayer#144]
在项目中集成了这个sdk，请问项目上线的时候需要授权或者收费吗？

**Comment by Jhuster** [comment]
@SmallStoneDD 不需要

**Comment by SmallStoneDD** [comment]
@Jhuster 好的  谢谢！

**Comment by yuhuayi** [comment]
那封装的jar包代码可以放出来不？另外打的so文件是在ijkplayer代码编译的，还是做了改动编译的？
