### ISSUE TITLE
PLVideoTextureView崩溃问题

### ISSUE THREAD

**Issue by liangshan98** [pili-engineering/PLDroidPlayer#148]
使用代码的方式添加PLVideoTextureView，结果出现了如下的崩溃： 

stack:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
    at android.view.ViewGroup.measureChild(ViewGroup.java:5511)
    at com.pili.pldroid.player.widget.PLVideoTextureView.onMeasure(PLVideoTextureView.java:111)
    at android.view.View.measure(View.java:17573)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)

在oncreate中使用如下代码：
   FrameLayout frameLayout             = new FrameLayout(context);  
//        FrameLayout.LayoutParams params     = new FrameLayout.LayoutParams(videoWidth, videoHeight);
        FrameLayout.LayoutParams params     = new FrameLayout.LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT);
        params.gravity                      = Gravity.CENTER;
        mVideoView                          = new PLVideoTextureView(context);
        mVideoView.getLayoutParams();
        mVideoView.setDisplayAspectRatio(PLVideoTextureView.ASPECT_RATIO_PAVED_PARENT);        // TODO: 是否需要适配其他方案

```
    frameLayout.addView(mVideoView, params);   
```

**Comment by liangshan98** [comment]
同样的代码使用PLVideoView没问题

**Comment by Jhuster** [comment]
@liangshan98 嗯，经测试，动态创建 `PLVideoTextureView ` 确实有这个问题，谢谢反馈，会在下一版修复。
