### ISSUE TITLE
使用PLVideoView播放本地视频,如何在播放完毕后直接播放下一个视频,我在onCompletion设置新路径,还是无法播放?

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#149]

**Comment by Jhuster** [comment]
试试把 `AVOptions` 的 `AVOptions.KEY_START_ON_PREPARED` 设置为 1

**Comment by yanxiandroid** [comment]
嗯,完美解决了我的问题.看你回复的issue涉及到频繁切换集数的问题,已经使用线程操作了..感谢楼主

**Comment by chentao7v** [comment]
@yanxiandroid  为何我在线程中异步setVideoPath，app会挂掉

**Comment by chentao7v** [comment]
@yanxiandroid 即使在子线程中setVideoPath再切换回主线程播放，频繁切换视频还是很卡顿啊。你是怎么解决的啊

**Comment by Jhuster** [comment]
@chentao7v 切换过程卡顿，还是切换完毕后，正常播放过程中卡顿？

**Comment by chentao7v** [comment]
切换完成，setVideoPath之后。播放视频不存在卡顿
我是使用RecyclerView显示了许多视频的缩略图，点击Item之后切换视频，如果点击的速度足够快，videoview明显忙不过来，同时也会影响Item的选择操作

**Comment by Jhuster** [comment]
@chentao7v 播放器释放资源需要时间，后面的版本会考虑优化播放器的退出耗时。

**Comment by chentao7v** [comment]
@Jhuster  感谢大神，愿早日优化这个问题
