### ISSUE TITLE
播放网络视频，返回home，回来之后视频是黑的。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#151]
播放网络视频，返回home，回来之后不设置start，设置的是pause之后视频是黑的。可以解决吗。还有就是已经缓冲过的播放时会出现卡顿，上一版不会卡顿。

**Comment by Jhuster** [comment]
@talentsxh `PLVideView` 的 `SurfaceView` 在 `Activity` 进入后台后会被消耗，如果从后台返回的时候，你用 `pause` 禁止了新的视频画面渲染出来，自然是黑的。

**Comment by Jhuster** [comment]
@talentsxh 卡顿的描述不够详细，如何重现。
