### ISSUE TITLE
pldvideoview的点击事件在哪？

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#152]
我把mVideoView设置为全屏，然后点击的时候出来MediaController。我想问的是，我点击屏幕的时候那个ontouch事件在哪里。在哪里设置的点击事件。我想复写ontouch，但是只会拦截到ACTION_DOWN，其他的都不会拦截到。

**Comment by Jhuster** [comment]
@talentsxh sdk 内部并没有拦截 onTouchEvent，你在外部应该可以收到各种 Touch Event 的

**Comment by talentsxh** [comment]
如何设置让MediaController弹起。与不弹起。

**Comment by Jhuster** [comment]
@talentsxh `MediaController` 的源码就在 demo 里，show() 弹出，hide() 不弹起，你也可以自行修改里面的逻辑。
