### ISSUE TITLE
Jar包源码可以开放吗？有地方想修改

### ISSUE THREAD

**Issue by wyww1989** [pili-engineering/PLDroidPlayer#153]
你好，请问jar包源码可以开源吗？

**Comment by Jhuster** [comment]
@wyww1989 需要哪方面的修改？

**Comment by wyww1989** [comment]
@Jhuster  你好 需要类似ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0);
因为在调研视频分段播放，看到 [issues](https://github.com/Bilibili/ijkplayer/issues/211)  有人推荐这样的方法，但是PLVideoTextureView 这一块 setOption被打包封装进去了，所以不知道有没有什么方法可以做到。
