### ISSUE TITLE
直播过程出现画面卡死

### ISSUE THREAD

**Issue by SmallStoneDD** [pili-engineering/PLDroidPlayer#156]
使用PLVideoView播放直播视频的时候播放大概3分钟会卡死在画面不动 并打印以下Log
IJKMEDIA: av_read_frame error: fffffffb(�,�,�,�): unknown

**Comment by Jhuster** [comment]
@SmallStoneDD 播放地址发出来我们这边看看

**Comment by SmallStoneDD** [comment]
rtmp://pcpy.bjyunxi.com/oflaDemo/room1019 live=1 是我自己推的测试流 现在正在推

**Comment by Jhuster** [comment]
@SmallStoneDD 这边正在播放，目前还没有看到卡死，另外，av_read_frame error 后没有出现 onError 回调吗 ？ 你是用的 demo 测试的吗？

**Comment by Jhuster** [comment]
@SmallStoneDD 从这边看来，你那边网络不是很好，流非常卡。

**Comment by SmallStoneDD** [comment]
有时候不一定是3分钟  可能会时间长一些 但出现此错误后并没有回调onError  是使用Demo测试

**Comment by Jhuster** [comment]
@SmallStoneDD 刚刚检查了一下代码，出现 `av_read_frame error` 后，会立即发送 `onCompletion` 回调消息。我这边一直在用 demo 测试，还没有出现卡死。

**Comment by SmallStoneDD** [comment]
我在阅读文档时读到以下语句
播放过程中产生错误信息，则会回调该接口（onError），返回值决定了该错误是否已经被处理，如果返回 false，则代表没有被处理，下一步则会触发 onCompletion 消息。
所以我在此处返回了true  就没有设置onCompletion的回调 而是在onError这个地方做统一处理；
如果此错误会回调onComoetion的话那我做出相应的处理即可
 谢谢您

**Comment by Jhuster** [comment]
@SmallStoneDD 不客气，这里的消息通知或许应该发送 onError，谢谢反馈，后面的版本我再考虑优化一下。
