### ISSUE TITLE
怎么处理plvideoview没播放之前背景透明

### ISSUE THREAD

**Issue by zc9** [pili-engineering/PLDroidPlayer#159]
怎么处理plvideoview没播放之前背景透明

**Comment by Jhuster** [comment]
@zc9 不太明白这个需求的目的，有使用 Android 官方的 VideoView 实现过类似的功能吗？

**Comment by zc9** [comment]
@Jhuster 进入activity 播放器区域是透明的，直到开始播放画面后

**Comment by shishuo365** [comment]
@zc9 这个问题的原因是原生IJKPlayer内部 XXRenderView 默认背景被设置成了全透明（alpha=0），可以通过修改源码实现，祝你好运~

**Comment by lichen228** [comment]
@zc9 兼容性问题，Android6.0以上会出现这个现象，并且会存在如下情况：有在xml中设置android：backgroundcolor后，颜色会一直存在，通过代码修改颜色无效
