### ISSUE TITLE
Resources.getSystem().getIdentifier("media_controller", "layout", "android");

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#160]
这个布局在哪，我想重新定制，需要怎么做，文档里面没写。

**Comment by Jhuster** [comment]
@talentsxh 这个是Android系统源码内的资源，如果希望完全自定义 MediaController，可以参考：http://www.brightec.co.uk/ideas/custom-android-media-controller

**Comment by talentsxh** [comment]
竖屏状态下怎样设置MediaController在视频的下方。像横屏一下。
