### ISSUE TITLE
PLVideoTextureView解析的视频质量不如PLVideoView

### ISSUE THREAD

**Issue by chentao7v** [pili-engineering/PLDroidPlayer#162]
同一个视频，在PLVideoView中播放时质量要好过PLVideoTextureView。由于是滚动的列表，必须使用PLVideoTextureView

**Comment by Jhuster** [comment]
@chentao7v 两个 View 的底层代码是一样的，唯一的区别是一个窗口使用了 SurfaceView，一个窗口使用了 TextureView，解码器没有区别的。截个图看看效果？

**Comment by chentao7v** [comment]
![videoview](https://cloud.githubusercontent.com/assets/17487668/16139790/9b94f158-347d-11e6-9732-bf3bd660c706.png)

**Comment by chentao7v** [comment]
![textureview](https://cloud.githubusercontent.com/assets/17487668/16139864/59069cd2-347e-11e6-89c9-47af006238ce.png)

**Comment by chentao7v** [comment]
第一个是VideoView，第二个是TextureView。

**Comment by chentao7v** [comment]
@Jhuster 还有一个问题，就是播放本地的视频时缓冲时间也比较长。我这边测试1个3秒左右的视频缓冲时间大概在1秒左右。频繁通过后台线程切主线程setVideoPath切换视频时，卡顿效果更明显。

**Comment by Jhuster** [comment]
@chentao7v 我们使用 demo 测试本地文件，很快就打开了，你换一个视频文件试试。
