### ISSUE TITLE
竖屏状态下怎样设置MediaController在视频的下方。像横屏一下。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#163]
希望setAnchorView(View view)的参数还是ViewGroup，想你给的demo一样可以在添加framelayout，可以在视频的下方出现。

**Comment by talentsxh** [comment]
不然通过获取屏幕的大小和视频的大小来计算出popup位置，还是会出现一些问题。如每个手机不适配。

**Comment by Jhuster** [comment]
@talentsxh ViewGroup 是继承 View 类的，`setAnchorView(View view)` 可以传入 `ViewGroup` 的
