### ISSUE TITLE
视频软件硬件解码具体的优势劣势有哪些

### ISSUE THREAD

**Issue by lishen19920525** [pili-engineering/PLDroidPlayer#164]
// 1 -> hw codec enable, 0 -> disable [recommended]
options.setInteger(AVOptions.KEY_MEDIACODEC, 0);

设成软件播放的时候手机非常烫，但是代码中推荐的却是软件解码，是因为兼容性问题吗

**Comment by Jhuster** [comment]
@GlowGeniusesStudio 主要考虑的是兼容性问题，你可以考虑在已充分测试过的机型上设置为硬解。

**Comment by GlowGeniusesStudio** [comment]
软件解码可以保证所有手机都可以正常解码么。机型判断是根据cpu么。

**Comment by Jhuster** [comment]
@GlowGeniusesStudio 目前还没有发现软解的机型适配问题。 机型可以根据 Android 的 Build.MODEL 宏。

**Comment by GlowGeniusesStudio** [comment]
谢谢！
