### ISSUE TITLE
急问，请问如何将网络上看完的视频，做本地缓存。

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#165]
你好，大神·我现在有个需求就是，我们是做短视频播放，当用户完整的看完一个视频，我们本地需要做缓存，请问该如何实现呢·谢谢。急~

**Comment by 15189611** [comment]
哦谢谢您，请问您用了？能否加下Q:  151896911 我的。麻烦告知下您的，谢谢

**Comment by meunicorn** [comment]
你可以直接用他的框架，使用方法比较简单，但是有什么问题并不太清楚，或者你可以直接参考他的做法，使用proxy的方式来缓存到本地

发自我的 iPhone

在 2016年6月20日，下午6:57，15189611 <notifications@github.com<mailto:notifications@github.com>> 写道：


哦谢谢您，请问您用了？能否加下Q: 151896911 我的。麻烦告知下您的，谢谢

―
