### ISSUE TITLE
请问能不能计算播放器rtmp流延迟多长的情况？

### ISSUE THREAD

**Issue by tz-xiaomage** [pili-engineering/PLDroidPlayer#168]
请问能不能计算播放器rtmp流延迟多长的情况？

**Comment by Jhuster** [comment]
@tz-xiaomage 不支持。

**Comment by tz-xiaomage** [comment]
@Jhuster 那请问，在客户端计算rtmp流的延迟时长，这是可行的吗？

**Comment by Jhuster** [comment]
@tz-xiaomage 延时的计算，需要知道当前播放的这一帧数据的“绝对时间”，一般码流的时间戳是“相对时间”，所以无法实现。

**Comment by tz-xiaomage** [comment]
@Jhuster 这个相对时间跟绝对时间是什么区别呢？现在的播放器能不能获取到这个相对时间？

**Comment by Jhuster** [comment]
@tz-xiaomage 绝对时间是指类似 "2016-06-21 08:00:00" 这样的时间，相对时间第二帧相对于第一帧的时间差。不能。

**Comment by Jhuster** [comment]
@tz-xiaomage 嗯，可以的，目前没有对上层提供接口。

**Comment by tz-xiaomage** [comment]
@Jhuster 不知道能不能提供一下这个接口呢？通过时间来计算大概的延迟是不可行的，就通过缓冲区来计算大概延迟了多少，这个能解决一定的延迟吧？

**Comment by Jhuster** [comment]
@tz-xiaomage 缓冲区只能计算出累积的延时，端到端的准确延时不能靠这个计算。 后面的版本中会考虑提供一些播放统计信息的回调。

**Comment by tz-xiaomage** [comment]
@Jhuster 好的，感谢，希望这种信息能多点提供。最后问一个，一般互动直播这种要求低延迟的，是怎么弄的啊？

**Comment by Jhuster** [comment]
@tz-xiaomage 我们的 sdk 提供了 `AVOption` 类，`KEY_LIVE_STREAMING` 参数设置为 1，底层会做一些优化，即可减少延时。

**Comment by tz-xiaomage** [comment]
@Jhuster 我主要是在直播过程中有一些socket要发送，因为延迟的问题，想能不能拿到大概延迟的时间，然后延迟socket事件到达一定的同步

**Comment by fool019** [comment]
直播时，KEY_LIVE_STREAMING 参数已设置为 1，但是延迟问题还是很严重，十几分钟时间延迟就能达到10s以上。
现在有没有别的什么办法处理该问题？或者有没有类似刷新的功能，让它直接加载到最新的幁？

**Comment by Jhuster** [comment]
@fool019 目前 1.2.3 版本添加了对延时的优化，你可以试试效果。

**Comment by fool019** [comment]
我用的就是1.2.3的，不行的，有没有别的办法稍微处理一下？

**Comment by fool019** [comment]
而且用 PLVideoTextureView 时，KEY_LIVE_STREAMING 参数已设置为 1，会报未知错误。
用 PLMediaPlayer，KEY_LIVE_STREAMING 参数已设置为 1，有时可以有时不行。

**Comment by fool019** [comment]
而且用 PLVideoTextureView 时，KEY_LIVE_STREAMING 参数已设置为 1，会报未知错误。
用 PLMediaPlayer，KEY_LIVE_STREAMING 参数已设置为 1，有时可以有时不行。

会不会是在直播资源不是特别好，或者网络情况不是特别好的时候，出现以上状况？

**Comment by Jhuster** [comment]
@fool019 这边测过的，网络抖动带来的延时可以消除掉的。你使用 vlc 或者 ffplay 来播放一下，看看播放是否流畅 ？
