### ISSUE TITLE
关于使用 PLMediaPlayer 和SufaceView 切换全屏时再切回来视频报错停止~！急请

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#169]
hi,请问下关于使用 PLMediaPlayer 和SufaceView 切换全屏时再切回来小屏视频报错停止~！急~~~~谢谢

**Comment by Jhuster** [comment]
@15189611 你的代码逻辑具体是怎么写的

**Comment by 15189611** [comment]
我等下发给你看？


发自 网易邮箱大师
在2016年06月21日 23:56，卢俊 写道:

@15189611 你的代码逻辑具体是怎么写的

**Comment by 15189611** [comment]
我的代码逻辑是当点击全屏按钮时。将在显示的View删除，然后重新创建一个在去显示全屏，
