### ISSUE TITLE
播放m3u8画面老是出现卡死

### ISSUE THREAD

**Issue by zc9** [pili-engineering/PLDroidPlayer#170]
http://124.232.231.246:8088/000000001001/201600010001/index.m3u8?

**Comment by Jhuster** [comment]
@zc9 我这边播放没有出现卡，用的什么版本，是不是网络不太好。

**Comment by zc9** [comment]
@Jhuster 1.2.2版本 网速可以， 每次进去播放1分钟 就卡死了，重新进去又可以播放

**Comment by axuan2015** [comment]
播放m3u8卡顿
