### ISSUE TITLE
急急急！怎么获取视频的方向？

### ISSUE THREAD

**Issue by yewei02538** [pili-engineering/PLDroidPlayer#171]
我用手机拍的1280*720的视频  视频内容是竖着的 ，，可视播放起来是横着的？  怎么获得视频方向？

**Comment by Jhuster** [comment]
@yewei02538  "onInfo: 10001, 90", 收到这个消息后，使用 `PLVideoTextureView` 的 `setDisplayOrientation` 旋转显示的方向，后面会补充这个回调的接口和文档。
