### ISSUE TITLE
播放的第二进度条有时候不会动这是为何，不是会一直缓冲下去的吗直到缓冲完成?

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#175]
没有缓冲过的进度条状态也能播放？

**Comment by Jhuster** [comment]
@talentsxh 直播还是点播 ？ 直播是无法一直缓冲的，点播或者播放文件，是有缓冲的

**Comment by talentsxh** [comment]
不是直播，网络视频，mPlayer.getBufferPercentage()这个有时候一直拿到的都是0，有没有办法判断是否已经缓冲过的接口。

**Comment by Jhuster** [comment]
@talentsxh “判断是否已经缓冲过的接口” 请问是怎样的一种需求？ 另外，如何复现上面描述的问题 ？

**Comment by talentsxh** [comment]
视频长度6秒。发现setprogress() ，mPlayer.getBufferPercentage()得到的值为0，因此出现第二进度条不会走，然后视频却可以播放。
地址http://image19-c.yueus.com/os_yueyue/yueyue/20160617/12/11520320160617120353781.mp4

**Comment by talentsxh** [comment]
缓冲到一半，播完后，就感觉死掉了，controller也不会出来了。是不是可以设置的。

**Comment by Jhuster** [comment]
@talentsxh 我这边用 demo 可以播放到最后，并且播放完毕后，调用了：onCompletion

**Comment by talentsxh** [comment]
你试一下这个视频，第二缓冲条没有出现。
http://image19-c.yueus.com/os_yueyue/yueyue/20160617/12/11520320160617120353781.mp4

**Comment by Jhuster** [comment]
@talentsxh 由于视频时长比较短，网络比较好的情况下，很快就缓冲到文件尾，一旦缓冲到最后了，就不会再有缓冲进度的回调。
