### ISSUE TITLE
播放m3u8直播流一段时间画面就卡死了

### ISSUE THREAD

**Issue by zc9** [pili-engineering/PLDroidPlayer#176]
http://124.232.231.246:8088/000000001001/201600010001/index.m3u8?

**Comment by Jhuster** [comment]
@zc9 这个流是怎么产生的？ 时间戳可能有问题。`AVOptions.KEY_GET_AV_FRAME_TIMEOUT` 设置大一点试试，比如 30 * 1000

**Comment by zc9** [comment]
@Jhuster 设置了还是一样 播放一段时间就卡了

**Comment by Jhuster** [comment]
@zc9 这个流时间戳应该有问题，你播放其他的流看看。

**Comment by zc9** [comment]
@Jhuster 其它流也是一样的

**Comment by zc9** [comment]
我们这边有70个流播放都是一样

**Comment by zc9** [comment]
@Jhuster 苹果那边用原生的播放同样的流播放没问题

**Comment by Jhuster** [comment]
可能是因为苹果原生的播放器使用的音视频同步机制不一样，对于你们的这种流，我们后面有空再专门调试一下，我们的播放器测试大部分其他的 HLS 直播流，是兼容的。

**Comment by Jhuster** [comment]
@zc9 刚刚分析了一下，你们的这个码流很奇怪，跟常见 m3u8 的码流不一样，有 302 跳转和 m3u8 的嵌套，不知道你们的服务器切片为啥要这样设计，建议你跟服务器的小伙伴沟通一下，做成更加标准的HLS直播流。
