### ISSUE TITLE
请问关于sufaceView +PLMediaPlay SufaceView如何进行全屏切换，求帮忙

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#177]
请问sufaceView +PLMediaPlay SufaceView如何进行全屏切换，求帮忙 ，谢谢·本人实在弄不出来了，急求！谢谢各位

**Comment by Jhuster** [comment]
@15189611 为什么不考虑使用 PLVideoView 或者 PLVideoTextureView，我们直接提供此功能 ？ 如果你想完全自己来实现全屏代码，需要重写 SurfaceView 的 onMeasure 函数。

**Comment by 15189611** [comment]
我想过，就是PLVideoView能全屏切换？因为我的需求是每条listView的item是一张图片，然后点击播放按钮就播放，还有全屏按钮，能帮帮忙？

**Comment by 15189611** [comment]
我是继承VideoView的然后重写了onMeASURE 跟VIdeoView里面一样

**Comment by Jhuster** [comment]
PLVideView 提供了全屏切换的函数，具体可以参考 wiki 文档，它是一个 View，外层加一个 FrameLayout 在 View 上面浮动一个 Button 作为全屏按钮，很简单的，这些不属于播放器本身的问题，可以 Google 查询一下如何实现你需要的 UI 效果。

**Comment by 15189611** [comment]
我想问下PLVideoView就相当一个SufaceView是？

**Comment by 15189611** [comment]
我差不多将你gitgub文档看了好多遍。没找到全屏播放的啊，只有一个VideoView,

**Comment by Jhuster** [comment]
@15189611 https://github.com/pili-engineering/PLDroidPlayer/wiki/5-快速开始#using-PLXXXView

PLVideoView 和 PLVideTextureView 提供了各种画面预览模式，包括：原始尺寸、适应屏幕、全屏铺满、16:9、4:3 等，设置方法如下：

```
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_ORIGIN);
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_FIT_PARENT);
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_16_9);
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_4_3);
```

**Comment by 15189611** [comment]
还有想问下PLVideoView 必须放在FramentLayou里面？
我可不可以通过New的方式将他创建啊，谢谢

**Comment by 15189611** [comment]
请问能告诉下我？谢谢

**Comment by Jhuster** [comment]
@15189611 为什么你不能自己创建一个工程，new 一下试试呢？答案是可以的，不是必须放到 FramentLayout 里面

**Comment by 15189611** [comment]
好的，谢谢你
