### ISSUE TITLE
使用PlVideoVIew崩溃

### ISSUE THREAD

**Issue by tangxiangpi** [pili-engineering/PLDroidPlayer#179]
在华为HUAWEI GRA-TL00(HUAWEI)，金立GN9006(GiONEE)，htcHTC E9pw(htc)上重现。用的是硬解
#00 pc 0003bb84 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
#01 pc 00016655 /system/lib/libc.so (pthread_kill+52) [armeabi-v7a]
#02 pc 00017267 /system/lib/libc.so (raise+10) [armeabi-v7a]
#03 pc 00013ba5 /system/lib/libc.so (__libc_android_abort+36) [armeabi-v7a]
#04 pc 0001237c /system/lib/libc.so (abort+4) [armeabi-v7a]
#05 pc 00228183 /system/lib/libart.so (art::Runtime::Abort()+170) [armeabi-v7a]
#06 pc 000a74b9 /system/lib/libart.so (art::LogMessage::~LogMessage()+1360) [armeabi-v7a]
#07 pc 0015bc4d /system/lib/libart.so (art::IndirectReferenceTable::AbortIfNoCheckJNI()+72) [armeabi-v7a]
#08 pc 00238ed3 /system/lib/libart.so (art::Thread::DecodeJObject(_jobject*) const+726) [armeabi-v7a]
#09 pc 001b5827 /system/lib/libart.so (art::JNI::GetObjectArrayElement(_JNIEnv_, _jobjectArray_, int)+286) [armeabi-v7a]
#10 pc 00053d3f /data/app/com.voipclient-1/lib/arm/libpldroidplayer.so [armeabi-v7a]
#11 pc 000545d1 /data/app/com.voipclient-1/lib/arm/libpldroidplayer.so (SDL_AMediaCodec_getInputBuffer+4) [armeabi-v7a]
#12 pc 0004e4ab /data/app/com.voipclient-1/lib/arm/libpldroidplayer.so [armeabi-v7a]
#13 pc 0005224f /data/app/com.voipclient-1/lib/arm/libpldroidplayer.so [armeabi-v7a]
#14 pc 00015e43 /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a]
#15 pc 00013f03 /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

**Comment by Jhuster** [comment]
@tangxiangpi 请问是直接跑的 demo 吗？ 播放的地址是？

**Comment by tangxiangpi** [comment]
@Jhuster 集成到我们自己的应用了。用的rtmp直播地址

**Comment by Jhuster** [comment]
@tangxiangpi 硬解的兼容性不是很好，可以考虑软解试试。
