### ISSUE TITLE
pcm_s16le Codec

### ISSUE THREAD

**Issue by alcastelo** [pili-engineering/PLDroidPlayer#18]
Good day.
First of all, thank you for your project.
I would ask if you could add support for audio codec pcm_s16le.
I know the ffmpeg library supports it but is not compiled by default.
Thank you very much for your time and  help.

**Comment by jpxiong** [comment]
Sorry. We maybe not support the extra codec. But you can clone the [repo](https://github.com/jpxiong/ijkplayer) and compile it by yourself. If you have any compile problem, you can add an issue.

**Comment by alcastelo** [comment]
Thank you so much!!
I will try it

**Comment by jpxiong** [comment]
Good luck!
