### ISSUE TITLE
有办法判断超时吗，断网一直在转圈。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#180]
缓冲到一半，然后一半播完后，就一直转圈，看日志，只有FFP_MSG_BUFFERING_START:，没有FFP_MSG_BUFFERING_END:，有上面办法，停止转圈，并提示吗？

**Comment by Jhuster** [comment]
@talentsxh 嗯，确实有这个问题，特别是出现“假网”的情况下，下一版会修复。

**Comment by talentsxh** [comment]
哪现在有办法解决吗，转多少秒后自动消失并提示。是在onInfo里面写线程吗。

**Comment by Jhuster** [comment]
@talentsxh 你可以考虑在应用层做超时，在 `FFP_MSG_BUFFERING_START ` 的时候纪录当前时间，超过 10s 没有收到 `FFP_MSG_BUFFERING_END ` 消息则判定超时。

**Comment by talentsxh** [comment]
这个升级到1.3.0版本就可以解决了吧。看了你写的那个超时的错误应该是判断这个的吧

**Comment by talentsxh** [comment]
视频在缓冲的时候，想做点事，缓冲完就不做了，有的判断吗。是在info里面吗？

**Comment by Jhuster** [comment]
@talentsxh 是的，新增的 `ERROR_CODE_READ_FRAME_TIMEOUT` 可以解决这个问题

**Comment by Jhuster** [comment]
@talentsxh 缓存的开始和结束都是有 `onInfo` 的回调的。
