### ISSUE TITLE
播放很多视频流会出现 -1414092869错误码，请问这个是什么错误？？？

### ISSUE THREAD

**Issue by lizheng98** [pili-engineering/PLDroidPlayer#182]
06-27 19:26:53.022 13125-18361/com.efeizao.feizao I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [18361]
06-27 19:26:53.022 13125-18362/com.efeizao.feizao E/IJKMEDIA: http://rtmppull.efeizao.com/live/room_20384/chat.flv: Immediate exit requested
06-27 19:26:53.022 13125-18362/com.efeizao.feizao E/pldroid-player-native: failed to open input !
06-27 19:26:53.022 13125-18362/com.efeizao.feizao I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [18362]
06-27 19:26:53.032 13125-18360/com.efeizao.feizao D/IJKMEDIA: FFP_MSG_ERROR: -1414092869
06-27 19:26:53.032 13125-13125/com.efeizao.feizao E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1414092869)

**Comment by Jhuster** [comment]
@lizheng98 我这边可以正常打开，出现错误的时候，可以用 ffplay 播放试试，加上 -v debug 看看具体报错信息。
