### ISSUE TITLE
 关于PLMediaPlay +SufaceView播放 本地的.mp4文件，有声音画面不显示的问题，急求啊~

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#188]
大神，PLMediaPlay +SufaceView播放 本地的sd卡下的.mp4文件，有声音画面不显示的问题.
然后我用系统的MediaPlay+sufaceView可以播放并且显示，请帮忙看下这是什么原因，，急求啊~

**Comment by Jhuster** [comment]
@15189611 有详细的 log 信息没有 ？

**Comment by 15189611** [comment]
我这边暂时抓不到，请问该怎么抓你们的log

**Comment by Jhuster** [comment]
$ adb logcat -v threadtime > log.txt

**Comment by 15189611** [comment]
我抓了，请问怎么发给你log.txt

**Comment by Jhuster** [comment]
@15189611 把关键的错误信息贴出来。

**Comment by 15189611** [comment]
请稍等在上传


发自 网易邮箱大师
在2016年06月29日 17:48，卢俊 写道:

@15189611 有详细的 log 信息没有 ？

**Comment by 15189611** [comment]
能否发邮件给你，我抓了播放30秒的，不知道哪些是关键，谢谢


发自 网易邮箱大师
在2016年06月29日 17:48，卢俊 写道:

@15189611 有详细的 log 信息没有 ？

**Comment by 15189611** [comment]
[Uploading log.txt…]()

**Comment by 15189611** [comment]
http://pan.baidu.com/s/1kVhff6Z  大神这是链接

**Comment by Jhuster** [comment]
@15189611 你是用的硬解吗？用软解试试，另外，mp4文件也上传一下吧

**Comment by 15189611** [comment]
好


发自 网易邮箱大师
在2016年06月29日 18:20，卢俊 写道:

@15189611 你是用的硬解吗？用软解试试，另外，mp4文件也上传一下吧

**Comment by 15189611** [comment]
http://pan.baidu.com/s/1eR2DJJs  这是.mp4的文件，谢谢

**Comment by 15189611** [comment]
软解。硬解都不行啊·

**Comment by Jhuster** [comment]
@15189611 添加一条语句即可播放：`mAVOptions.setInteger("probesize", 50000);`

**Comment by 15189611** [comment]
好，请稍等，我试下

**Comment by 15189611** [comment]
好像还是不行，加了你这句话。谢谢

**Comment by 15189611** [comment]
有声音没画面~~

**Comment by 15189611** [comment]
求大神帮助啊·，项目下周要上线了·。。

**Comment by Jhuster** [comment]
@15189611 不支持这种格式的视频编码：mpeg4 (Simple Profile) (mp4v / 0x7634706D)，所以播放不出来。

**Comment by 15189611** [comment]
有没有办法想呢· mp4v  不支持？

**Comment by Jhuster** [comment]
@15189611 建议暂时使用系统的 VideoView 或者 MediaPlayer

**Comment by 15189611** [comment]
我这边录制的时候 看看能不能改录制的视频格式，请问你这边支持mp4哪些格式，谢谢

**Comment by Jhuster** [comment]
@15189611 H.264 是支持的。

**Comment by 15189611** [comment]
、好，请稍等，我这边试试看

**Comment by 15189611** [comment]
好的·，谢谢你，我这边改成H.264 有画面了····

**Comment by 15189611** [comment]
还有个问题想请问下，就是你新发布的1.3.0Jar PLMediaPlay是不是更加稳定点呢·，谢谢

**Comment by Jhuster** [comment]
@15189611 是的，修复了许多问题。

**Comment by 15189611** [comment]
好的额。谢谢你·

**Comment by 15189611** [comment]
大神还请教个问题，就是PlMediaPlay  调用onPause有时候不是马上能暂停声音·，请问这是什么原因呢·。
因为我在listView滚动时候要马上暂停，谢谢

**Comment by Jhuster** [comment]
@15189611 我用 demo 测试了，pause 后可以很快暂停的，“马上” 不知道指的是什么概念，另外，如果实在不行，试试先调用 `setVolume` 静音。

**Comment by 15189611** [comment]
我这个有时没暂停，至少播放30秒后，才能停住，不知道是不是不同步“”？

**Comment by Jhuster** [comment]
@15189611 应该不会出现这种情况，是用 demo 测试吗？ 这边对几个 Activity 都反复试过，没有出现这种情况。另外，不同的问题建议开不同的 issue
