### ISSUE TITLE
 change the video aspect 

### ISSUE THREAD

**Issue by msdos2** [pili-engineering/PLDroidPlayer#19]
hello as I can change the video aspect
![img_29082015_184053](https://cloud.githubusercontent.com/assets/7550249/9563351/68f037f4-4e81-11e5-98e3-f6f3c3163430.png)
. thanks

**Comment by jpxiong** [comment]
The `VideoView` is a `SurfaceView` as Android's. Avoiding the stretch , VideoView will always set fixed size which from source video. That means, the VideoView's size always be same as the source video.

**Comment by jpxiong** [comment]
No feedback. So close the issue.
