### ISSUE TITLE
有时调用onPause声音不能及时暂停~

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#191]
不是在demo中测试的·，而是在我应用中·一般都是在Activity onPause中调用暂停的~

**Comment by Jhuster** [comment]
@15189611 本 sdk 支持退到后台播放音频的特性，如果不希望在后台播放音频，可以在 Activity 的 onPause 中调用 `mVideoView.pause()`，或者 `mVideoView.stopPlayback()`，另外，建议参考`demo`程序。

**Comment by 15189611** [comment]
我用的是PlMediaPlay，+SufaceView,没有用mVieoView,请问能取消后台播放？

**Comment by Jhuster** [comment]
@15189611 `PLMediaPlayer` 也有的，在 Activity 的 `onPause` 中调用 `PLMediaPlayer.pause()`，或者 `PLMediaPlayer.stopPlayback()` , 文档在这，你可以多看看文档：https://github.com/pili-engineering/PLDroidPlayer/wiki

**Comment by 15189611** [comment]
PLMediaPlayer.stopPlayback() 这个函数没有啊·  我调不到啊·，在代码中试了啊~谢谢
