### ISSUE TITLE
当播放器在播放直播的时候。此时按home键切换到后台，过一会再点击应用播放。播放的效果出现直播一段时间就自动卡顿跳过4s的播放内容了

### ISSUE THREAD

**Issue by cdd163** [pili-engineering/PLDroidPlayer#193]
您好，我在1.2.3版本的播放中，发现当播放器在播放直播的时候。此时按home键切换到后台，过一会再点击应用播放。播放的效果出现直播一段时间就自动卡顿跳过4s的播放内容了，再直播一会。一会又卡顿跳4s的接着就往下播了。一直循环往复。（卡顿的效果不明显，就是视频画面状态静止的状态，就是无故老突然快进4s的直播内容了，此时网络状态良好）。切换到后台过会再直播播放。这个现象基本上是必现的现象了

**Comment by Jhuster** [comment]
@cdd163 嗯，1.3.0 版已修复。

**Comment by cdd163** [comment]
额。好的。谢谢
