### ISSUE TITLE
直播选用高清（rtmp）接收端播放没声音

### ISSUE THREAD

**Issue by zekoushenhao** [pili-engineering/PLDroidPlayer#194]
直播选用高清（rtmp）接收端播放没声音
选用低分辨率的就有声音  但是画面就比较模糊了

**Comment by Jhuster** [comment]
@zekoushenhao 测试流地址发出来测测看。

**Comment by zekoushenhao** [comment]
rtmp://2809.liveplay.myqcloud.com/live/2809_b12f571439eb11e6a2cba4dcbef5e35a

**Comment by Jhuster** [comment]
@zekoushenhao 很奇怪，为啥我刚刚有时候播放有声音有时候又没有，现在一直有声音，你们在那边有调整服务器程序吗，没有声音的时候，从底层的log来看，像是没有 read 到 audio frame

**Comment by zekoushenhao** [comment]
调整过录制的分辨率   我这边有声音的几率较小
