### ISSUE TITLE
MediaPlayerControl.getBufferPercentage() 返回值不能到100%

### ISSUE THREAD

**Issue by JamesKarl** [pili-engineering/PLDroidPlayer#195]
播放一个很短的视频，肯定缓冲完毕，但是getBufferPercentage返回不能到100%.

视频格式flv

**Comment by Jhuster** [comment]
@JamesKarl 嗯，确实有这个问题，最后一段数据缓冲结束后就没有再回调导致的，后面的版本会考虑修复。

**Comment by JamesKarl** [comment]
感谢支持 @Jhuster
