### ISSUE TITLE
播放直播流过1分钟不到自动退出显示Read frame timeout 或者Play Completed

### ISSUE THREAD

**Issue by yangjian92** [pili-engineering/PLDroidPlayer#196]
请问下这是什么情况？我在ijkplayer测试没这种情况。

**Comment by Jhuster** [comment]
`Read Timeout` 是由于超时读不到数据引发的，一般是网络不好引发的，可以考虑把超时时间设置得大一点：`mAVOptions.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 30 * 1000);`

**Comment by yangjian92** [comment]
ok。好的。O(∩_∩)O谢谢
