### ISSUE TITLE
关于rtmp全屏播放

### ISSUE THREAD

**Issue by roymondroymond** [pili-engineering/PLDroidPlayer#199]
1. PLDroidPalyerDemo 中，采用PLVideoTexttureActivity，用例子自带的rtmp可以全屏。但改成自己的rtmp， 高度全屏，但宽度只有一半。我用的视频流是640*480，20帧。帮忙解答一下原因。

2.不采用PLVideoTextureVidew和PLVideoView，参考例子中的PLMediaPlayerActivity,还是640*480的rtmp流，在onVideoSizeChanged写死FrameLayout.LayoutParams layout = new FrameLayout.LayoutParams(720, 1280); 高度有效果，宽度无效，请帮忙看一下，该怎么设置？我的目的，是全屏播放。

**Comment by Jhuster** [comment]
你把流地址发出来看看，用 demo 播放试试，全屏的关键配置是 View 设置为 match_parent, 另外，setDisplayAspectRatio(PLVideoTextureView.ASPECT_RATIO_PAVED_PARENT);

**Comment by roymondroymond** [comment]
rtmp://publish.3tee.com.cn/ucloud/r1922， 直接跑在你们的demo中，选择PLVideoTextureVidew， 全屏后，宽度不对

**Comment by Jhuster** [comment]
这个流没有在推了，确定流的尺寸没有问题吗？把显示的截图发出来看一下。
