### ISSUE TITLE
Requesting armeabi .so files

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidPlayer#20]
We are using PLDroidPlayer along with PLDroidCameraStreaming. For the same reason as mentioned in PLDroidCameraStreaming, could you please also provide armeabi .so files for PLDroidPlayer.

**Comment by jpxiong** [comment]
You can clone the code [here](https://github.com/jpxiong/ijkplayer) and compile it yourself.

**Comment by jpxiong** [comment]
V1.1.3 had provided armeabi, armeabi-v7a, arm64-v8a, x86.
