### ISSUE TITLE
这个是什么错误

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#202]
Error (-10000,-1094995529)
Error happened, what = -10000, extra = -1094995529

这个是视频地址：
http://image19-c.yueus.com/os_yueyue/yueyue/20160624/17/35699320160624170427572.mp4

**Comment by Jhuster** [comment]
@talentsxh 貌似你开了两个 issue 问同一个问题，这个视频源可能缺失一些信息。

**Comment by colorchenvip** [comment]
07-13 15:55:36.240 3581-4408/com.weizhu I/IJKMEDIA: SDL_RunThread: [4408] ff_msg_loop
07-13 15:55:36.241 3581-4409/com.weizhu I/IJKMEDIA: SDL_RunThread: [4409] ff_vout
07-13 15:55:36.241 3581-4410/com.weizhu I/IJKMEDIA: SDL_RunThread: [4410] ff_read
07-13 15:55:36.586 3581-4410/com.weizhu E/IJKMEDIA: http://7xs9fl.media1.z0.glb.clouddn.com/video/dc668b81fc18d77139ddd85d63c03623.mp4^3d50c62388ba536d354cff938c179a88.jpg: Server returned 404 Not Found
07-13 15:55:36.586 3581-4410/com.weizhu E/pldroid-player-native: failed to open input : 344 ms !
07-13 15:55:36.586 3581-4410/com.weizhu I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [4410]
07-13 15:55:36.587 3581-3581/com.weizhu E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-875574520)
07-13 15:55:36.587 3581-3581/com.weizhu E/PLMediaPlayer: Error happened, what = -10000, extra = -875574520
07-13 15:55:36.587 3581-3581/com.weizhu E/MediaPlayerActivity: Error happened, errorCode = -875574520

视频地址：http://7xs9fl.media1.z0.glb.clouddn.com/video/dc668b81fc18d77139ddd85d63c03623.mp4
貌似和#202 问题一样  视频没有问题 在别的地方可以放 是什么问题？麻烦看一下
