### ISSUE TITLE
快进、快退引起无法播放问题

### ISSUE THREAD

**Issue by Neacy** [pili-engineering/PLDroidPlayer#203]
使用mVedioView.seekTo(progress)实现快进快退然后就出现这个问题，视频就无法继续播放了。

07-07 16:40:14.561 23463-23463/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2002)
07-07 16:40:14.563 23463-23463/? E/PLMediaPlayer: Error happened, what = -10000, extra = -2002

这种是什么原因造成的？

**Comment by Jhuster** [comment]
@Neacy 你怎么做的快进快退 ？ 不建议用 seekTo 来快进快退，这并不是正确的姿势。

**Comment by Neacy** [comment]
我是界面采用SeekBar供用户操作播放进度来实现快进快退的。
如果不用seekTo的话，采用什么方式呢？
@Jhuster

**Comment by Jhuster** [comment]
@Neacy 目前我们还没有提供快进快退的功能，你说的是“拖动”还是“快进快退” ？

**Comment by Neacy** [comment]
@Jhuster 我这是拖动操作。

**Comment by Jhuster** [comment]
@Neacy 嗯，是频繁反复拖动吗？ 我再仔细测测。

**Comment by Neacy** [comment]
不是频繁的操作。

**Comment by Jhuster** [comment]
@Neacy 嗯，能提供一些更详细的信息吗，比如播放的文件、码流地址？操作的方式，是否其他的流也出现类似问题

**Comment by Neacy** [comment]
@Jhuster 
是使用你们公司的直播服务生产的直播回放视频。地址如下：
http://pili-media.meilihuli.com/recordings/z1.meili.product_219/app_product_219.mp4

操作方式：等视频缓存完成后，就直接拖动进度条到一定程度然后视频就缓冲失败报上面的错误。
是否跟网络有关系？

**Comment by hike2008** [comment]
未来会提供快进快退的Api么

**Comment by Neacy** [comment]
@hike2008 我是采用seekTo实现让视频跳转到某一个时刻，来实现快进快退的。

**Comment by hike2008** [comment]
不是不建议用seekTo么

**Comment by yanxiandroid** [comment]
@Jhuster 我现在的项目是TV项目,用的是您的这个框架,快进,快退暂时用的是seekTo，请问如果只有key事件，这快进，快退怎么做？

**Comment by Jhuster** [comment]
@yanxiandroid 目前播放器版本不支持快进快退。

**Comment by yanxiandroid** [comment]
@Jhuster 希望下版本能支持快进快退,感谢
