### ISSUE TITLE
PLDroidPlayer支持多窗口同时播放视频吗

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#205]
PLDroidPlayer支持多窗口同时播放视频吗

**Comment by Jhuster** [comment]
@jaychou2012 支持。

**Comment by jaychou2012** [comment]
嗯，实现了。但是直播时候视频播放时不是很流畅。如何解决

**Comment by jaychou2012** [comment]
这个必须要在七牛申请什么？我看jar包里有用到七牛的

**Comment by Jhuster** [comment]
@jaychou2012 不需要申请使用。

**Comment by jaychou2012** [comment]
可不可以把你的那个jar包源码给我下？

**Comment by jaychou2012** [comment]
需要开启硬件加速吗

**Comment by Jhuster** [comment]
@jaychou2012 你可以试试，设置 `AVOptions.KEY_MEDIACODEC` 为 1

**Comment by jaychou2012** [comment]
如何让播放时候画面铺满屏幕？不截取

**Comment by jaychou2012** [comment]
还有PLVideoView和PLVideoTextTureView哪个更好？哪个更不耗费资源

**Comment by Jhuster** [comment]
@jaychou2012 如果视频的分辨率跟屏幕的分辨率不成比例的情况下，从理论上做不到完全铺满全屏又无任何剪裁。

**Comment by Jhuster** [comment]
@jaychou2012 播放视频的资源消耗的关键点并在这两个 View，当然，你也再可以 Google 一下 SurfaceView 与 TextureView 的区别。

**Comment by jaychou2012** [comment]
那PLVideoView和PLVideoTextTureView哪个更好

**Comment by Jhuster** [comment]
`PLVideoTextTureView` 能提供更多的功能，如旋转、缩放等，而可能比 `PLVideoView `消耗内存要多一点，具体细节的对比，你可以 Google 一下 SurfaceView 与 TextureView 的区别。
