### ISSUE TITLE
推流端断开推流后，观众端不走onError的回调（1.3.0版本）

### ISSUE THREAD

**Issue by MarnoDev** [pili-engineering/PLDroidPlayer#207]
推流端断开推流后，观众端不走onError的回调（1.3.0版本），之前的1.2.3都可以

**Comment by Jhuster** [comment]
@MarnonDev 有 `onError` 回调，是 `ERROR_CODE_READ_FRAME_TIMEOUT` 或者 `ERROR_CODE_IO_ERROR`.
