### ISSUE TITLE
支持截屏吗？

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#209]
有没有办法解决从软件出去回来后没有自动播放，出现黑屏的情况。如果这些可以的话那就快完美了。

**Comment by Jhuster** [comment]
@talentsxh 目前可以考虑用一张默认的静态图代替，或者试试 `PLVideoTextureView` 的 `getTextureView().getBitmap()` 接口。

**Comment by talentsxh** [comment]
现在有没有重新播放的接口。上面那个方法使用截图可行。不过之前是用PLVideoView，现在改了，应该不会相差很大吧。再次多谢了。

**Comment by Jhuster** [comment]
@talentsxh 重新播放就是重新调用 `setVideoPath`。与 `PLVideoView ` 的差别的话主要在 `SurfaceView` 和 `TextureView` 的差别。

**Comment by talentsxh** [comment]
因为我的项目是使用android3.0版本的，而TextureView 是4.0之后的，不想升到4.0的话，请问要导入什么包，mVideoView.getTextureView()报错没办法。

**Comment by Jhuster** [comment]
@talentsxh 没办法，`TextureView` 只能 4.0 后使用。
