### ISSUE TITLE
关于缓冲

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#211]
我想拿到第一帧视频的图像后，显示第一帧图像，在info里面处理，立刻停止缓冲，暂停视频。有办法？主要是想立刻停止缓冲。

**Comment by talentsxh** [comment]
第一帧视频是多久，我seekto多少。

**Comment by Jhuster** [comment]
@talentsxh 视频种类那么多，第一帧的位置都不一样，seekTo 没用的。这个需求一般是从服务器那边拿到截帧在播放开始前显示出来。
