### ISSUE TITLE
动态加载的PLVideoTextureView无法添加BufferingIndicator

### ISSUE THREAD

**Issue by onlike** [pili-engineering/PLDroidPlayer#212]
动态new出来的PLVideoTextureView添加BufferingIndicator无反应

**Comment by Jhuster** [comment]
@onlike 可以暂时考虑在外部自己做 BufferingIndicator，检测 `onInfo` 的状态来 显示 和 隐藏。

**Comment by onlike** [comment]
好的

**Comment by onlike** [comment]
onInfo里面监听不到开始缓冲与停止缓冲的回调  @Jhuster 
07-22 11:17:45.261 14821-14821/com.jsonhu.people_news I/videoplay: OnInfoListener call back10001
07-22 11:17:45.340 14821-14821/com.jsonhu.people_news I/videoplay: OnInfoListener call back10002
07-22 11:17:45.341 14821-14821/com.jsonhu.people_news I/videoplay: OnInfoListener call back3

**Comment by onlike** [comment]
onInfo监听内不回调开始缓冲与停止缓冲的方法 @Jhuster 
07-22 11:17:45.261 14821-14821/com.*.**I/videoplay: OnInfoListener call back10001
07-22 11:17:45.340 14821-14821/com.*.**I/videoplay: OnInfoListener call back10002
07-22 11:17:45.341 14821-14821/com.*.**I/videoplay: OnInfoListener call back3
