### ISSUE TITLE
视频格式问题

### ISSUE THREAD

**Issue by StormBlue** [pili-engineering/PLDroidPlayer#213]
在使用中遇到几种格式播放有些问题，请教一下。
1.播放mkv时报错，无法播放；
2.播放mpg格式时，有的视频一直显示在缓存，有的视频只有声音没有画面；

想请教一下，是什么问题导致，可以解决方案

**Comment by Jhuster** [comment]
@StormBlue 不支持 rmvb、mkv 等视频格式，有声音没画面可能是因为该视频编码格式不支持。确保支持的封装格式是 mp4，RTMP，HLS 码流，音视频编码格式是 H.264 和 AAC。

**Comment by StormBlue** [comment]
谢谢~
