### ISSUE TITLE
PLVideoView vs PLVideoTextureView

### ISSUE THREAD

**Issue by kazemihabib** [pili-engineering/PLDroidPlayer#214]
when should I use PLVideoView and when to use PLVvideoTextureView ?

**Comment by Jhuster** [comment]
@kazemihabib `PLVideoView ` uses `SurfaceView` and `PLVideoTextureView ` uses `TextureView`. You can google the difference between  `SurfaceView` and `TextureView`.

**Comment by kazemihabib** [comment]
thanks
