### ISSUE TITLE
Android6.0以上出现播放器区域透明的现象

### ISSUE THREAD

**Issue by lichen228** [pili-engineering/PLDroidPlayer#216]
Android6.0以上版本的手机，在onPrepared之前，播放器区域会透明，直接看到手机桌面的应用图标。loading结束，开始播放后画面正常。
同时伴随以下情况：在xml中对播放器设置android:backgroundcolor后，通过代码动态修改其他颜色无效。
以上现象不会出现在Android5.0以上的手机
Same Issue：[https://github.com/pili-engineering/PLDroidPlayer/issues/159](url)

**Comment by Jhuster** [comment]
@lichen228 我们在几款 Android 6.0 机型上跑 demo 没有出现透明问题，请问是否修改了背景才出现的问题。

**Comment by lichen228** [comment]
@Jhuster 我做了些测试，目前观察到的现象是：直接将播放器嵌在Activity的layout文件里是正常的，但是将播放器封入自定义View，再在Activity的layout文件中引用view，就会出现透明现象。整个过程中均未对播放器的背景做任何操作。
除首次加载外，pause()之后再start()，也能观察到透明的现象

**Comment by Jhuster** [comment]
@lichen228 嗯，谢谢反馈，后面我们会调试并尝试修复一下这个场景下的问题。

**Comment by lichen228** [comment]
提供一种临时的解决方案，可以规避透明的阶段，方便遇到同样问题的朋友们：
（1）设置PLVideoVIew的android:alpha=“0”，同时设置外层layout背景色为black
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/rl_video_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black">

    <com.pili.pldroid.player.widget.PLVideoView
        android:id="@+id/live_video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:alpha="0"/>
</RelativeLayout>
（2）在onPrepared阶段还原播放器透明度,此时画面已经渲染完毕
    @Override
    public void onPrepared(PLMediaPlayer plMediaPlayer) {
        progressbar.setVisibility(View.GONE);
        mVideoView.setAlpha(1);
    }

至于为什么android:alpha起作用，而android:visibility就无效
这个问题可能是跟ijkplayer.so渲染完成前的alpha设置有关，根本上解决只能靠作者修改libpldroidplayer.so了
@Jhuster

**Comment by Jhuster** [comment]
@lichen228 嗯，谢谢。

**Comment by ZoroLu** [comment]
我也出现这个问题，修改了 style 主题背景透明，取消背景透明就不会出现这个问题。在背景透明情况下，我外层套了其他 view ,以及在同级 view  下（嵌套在 FrameLayout），把其他 下层的 view 设置背景也无效，在其上层有效。尝试了上面 @lichen228 的方法，发现顶部有一小块距离还是透明，我本身这个页面是可以右滑返回的，在优化返回过程它会把那部分透明的变成设置的黑色，但是松手恢复页面后又出现部分透明。 @Jhuster
