### ISSUE TITLE
please support x86 .so file

### ISSUE THREAD

**Issue by jboeyin** [pili-engineering/PLDroidPlayer#22]
Hi, as title mentioned, can you share with the x86 .so file?

**Comment by jpxiong** [comment]
You can clone the code here and compile it yourself.

**Comment by jboeyin** [comment]
I had tried your solution, I just compiled the project you provided, but I failed to get the .so files and jar file, especially I got the error message while I input the following commands with terminal window: 
./gradlew jarRelease
./gradlew cleanFFmpeg buildJniLibs
unfortunately, it shows no specified task.

**Comment by jpxiong** [comment]
```
$ cd android/contrib
android/contrib $ sh compile-ffmpeg.sh x86
android/contrib $ cd ../
android $ sh compile-ijk.sh x86
```

**Comment by jpxiong** [comment]
V1.1.3 have been provided the X86 SO.
