### ISSUE TITLE
自己用SurfaceView黑屏

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#224]
自己用SurfaceView黑屏，怎么回事？有声音。

可否把PLVideoView源码给一下

**Comment by Jhuster** [comment]
@jaychou2012 自己的 SurfaceView 应该使用 PLMediaPlayer，可能你的流的视频格式播放器不一定支持，把错误打印发出来看看。

**Comment by zhuhean** [comment]
碰到了同样的问题。
应该是先给surfaceView设callback：surfaceView.getHolder().addCallback(surfaceCallback);
然后再在surfaceCallback里面的surfaceCreated方法里去prepare()
