### ISSUE TITLE
在Handler里获取当前播放时间时候提示Read frame timeout !

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#225]
在Handler里获取当前播放时间时候提示Read frame timeout !

这是什么错误

**Comment by Jhuster** [comment]
@jaychou2012 确定是 `getCurrentPosition` 导致的吗？这个函数只是获取一个变量值而已。 `Read frame timeout !` 是网络不好读不到数据才会报错。
