### ISSUE TITLE
Vivo手机无法正常播放视频

### ISSUE THREAD

**Issue by 81813780** [pili-engineering/PLDroidPlayer#227]
**问题描述：** 同个视频URL，经测试，小米和Moto的可以正常播放，**但是Vivo的手机播放不了。**

**Vivo手机日志如下图：**
![我是图](http://o8wshxdfk.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160726170957.png)

**非常感谢pili-engineering提供的开源库**

**Comment by yjy951753** [comment]
跪求开发人员，早点适配vivo手机

**Comment by Jhuster** [comment]
应该是这个流本身的问题，可以换个播放地址试试
