### ISSUE TITLE
视频是黑的只有声音。

### ISSUE THREAD

**Issue by talentsxh** [pili-engineering/PLDroidPlayer#228]
有些视频是黑的只有声音，这是什么原因导致的。链接
http://downmp413.ffxia.com/mp413/%E5%8F%B6%E8%B4%9D%E6%96%87-%E5%90%93%E6%AD%BB%E5%AE%9D%E5%AE%9D%E4%BA%86[68mtv.com].mp4
错误
E/IJKMEDIA(7707): Option http-detect-range-support not found.

**Comment by Jhuster** [comment]
@talentsxh 此视频是 mp4v 格式编码的，不支持这个格式。

**Comment by paulwang2012** [comment]
请问一下作者，如果出现黑屏有声音情况，是否有抛出异常事件；
这样的话，我能捕获，及时更换其他视频源？

**Comment by Jhuster** [comment]
@paulwang2012 嗯，谢谢建议，后面的版本会考虑抛出异常或者返回错误状态。
