### ISSUE TITLE
视频播放的问题

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#229]
1.3.0版本播放带IP地址的URL的视频时候,偶尔会出现连接超时的情况，有时候又是出现未知错误，我现在用的是局域网测试的。。请问这种问题怎么处理的？

**Comment by Jhuster** [comment]
@yanxiandroid 有出现错误的 log 吗 ？

**Comment by yanxiandroid** [comment]
@Jhuster 08-01 13:05:13.475 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfed3c1d: partial file
08-01 13:05:13.475 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:13.787 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfed3dae: partial file
08-01 13:05:13.787 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:14.097 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfed3efe: partial file
08-01 13:05:14.097 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:14.409 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfed6393: partial file
08-01 13:05:14.409 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:14.719 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfed64e6: partial file
08-01 13:05:14.719 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:15.029 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfed6676: partial file
08-01 13:05:15.029 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:15.340 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfed86a7: partial file
08-01 13:05:15.340 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:15.651 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfed87fc: partial file
08-01 13:05:15.651 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:15.962 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeda6c1: partial file
08-01 13:05:15.962 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:16.273 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeda837: partial file
08-01 13:05:16.273 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:16.586 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfeda9c9: partial file
08-01 13:05:16.586 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:16.897 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfedc6f3: partial file
08-01 13:05:16.897 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:17.207 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfedc836: partial file
08-01 13:05:17.207 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:17.518 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfedc9ab: partial file
08-01 13:05:17.518 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:17.828 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfede9d0: partial file
08-01 13:05:17.828 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:18.140 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfedeb44: partial file
08-01 13:05:18.140 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:18.452 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee0bc8: partial file
08-01 13:05:18.452 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:18.762 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee0d1b: partial file
08-01 13:05:18.762 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:19.103 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfee0e57: partial file
08-01 13:05:19.103 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:19.413 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee3240: partial file
08-01 13:05:19.414 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:19.724 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee3385: partial file
08-01 13:05:19.724 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:20.035 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfee34ef: partial file
08-01 13:05:20.035 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:20.345 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee5a40: partial file
08-01 13:05:20.345 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:20.655 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee5b8f: partial file
08-01 13:05:20.655 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:20.966 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfee5d0d: partial file
08-01 13:05:20.966 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:21.276 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfee83c5: partial file
08-01 13:05:21.276 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:21.586 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfee8559: partial file
08-01 13:05:21.586 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:21.897 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeeae05: partial file
08-01 13:05:21.897 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:22.209 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeeaf97: partial file
08-01 13:05:22.209 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:22.519 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfeeb0e7: partial file
08-01 13:05:22.519 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:22.829 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeed894: partial file
08-01 13:05:22.829 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:23.140 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeed9d4: partial file
08-01 13:05:23.140 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:23.450 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfeedb0e: partial file
08-01 13:05:23.450 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:23.760 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfeeffe6: partial file
08-01 13:05:23.761 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:24.071 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfef0135: partial file
08-01 13:05:24.071 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:24.381 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfef219f: partial file
08-01 13:05:24.381 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:24.692 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfef232f: partial file
08-01 13:05:24.692 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:25.004 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfef24b7: partial file
08-01 13:05:25.004 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:25.314 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfef440e: partial file
08-01 13:05:25.315 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:25.625 6480-5894/com.yht.iptv E/IJKMEDIA: stream 1, offset 0xfef4597: partial file
08-01 13:05:25.625 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:05:25.935 6480-5894/com.yht.iptv E/IJKMEDIA: stream 0, offset 0xfef4729: partial file
08-01 13:05:25.935 6480-5894/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-01 13:06:16.556 6480-5898/com.yht.iptv E/IJKMEDIA: AVC: nal size 9524
08-01 13:06:16.556 6480-5898/com.yht.iptv E/IJKMEDIA: AVC: nal size 9524
08-01 13:06:16.556 6480-5898/com.yht.iptv E/IJKMEDIA: no frame!
08-01 13:06:16.736 6480-5892/com.yht.iptv D/IJKMEDIA: FFP_MSG_ERROR: -110
08-01 13:06:16.736 6480-6480/com.yht.iptv E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-110)
08-01 13:06:18.171 6480-6480/com.yht.iptv D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
08-01 13:06:18.171 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
08-01 13:06:18.171 6480-6480/com.yht.iptv D/IJKMEDIA: ffpipeline_set_surface()
08-01 13:06:18.171 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
08-01 13:06:18.578 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_stop()
08-01 13:06:18.578 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_stop()=0
08-01 13:06:18.578 6480-6480/com.yht.iptv D/IJKMEDIA: IjkMediaPlayer_release
08-01 13:06:18.578 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
08-01 13:06:18.578 6480-6480/com.yht.iptv D/IJKMEDIA: ffpipeline_set_surface()
08-01 13:06:18.579 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
08-01 13:06:18.579 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_shutdown_l()
08-01 13:06:18.579 6480-5892/com.yht.iptv D/IJKMEDIA: message_loop exit
08-01 13:06:18.579 6480-5892/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5892]
08-01 13:06:18.581 6480-5901/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5901]
08-01 13:06:18.581 6480-5897/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5897]
08-01 13:06:18.582 6480-5893/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5893]
08-01 13:06:18.652 6480-5894/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5894]
08-01 13:06:18.816 6480-5896/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5896]
08-01 13:06:18.881 6480-6480/com.yht.iptv E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x612b2ea0)
08-01 13:06:18.884 6480-6480/com.yht.iptv E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x614ef798)
08-01 13:06:18.885 6480-6480/com.yht.iptv E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x5e75c700)
08-01 13:06:18.886 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_shutdown_l()=void
08-01 13:06:18.886 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_dec_ref(): ref=0
08-01 13:06:18.886 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_shutdown_l()
08-01 13:06:18.886 6480-6480/com.yht.iptv D/IJKMEDIA: ijkmp_shutdown_l()=void

**Comment by yanxiandroid** [comment]
@Jhuster 提示连接超时...

**Comment by Jhuster** [comment]
@yanxiandroid 初步判断应该是你们的服务器程序不是很稳定。

**Comment by yanxiandroid** [comment]
@Jhuster   
08-05 10:54:46.988 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9b9148e: partial file
08-05 10:54:47.006 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:47.184 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9b99168: partial file
08-05 10:54:47.184 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:47.628 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9b9c3db: partial file
08-05 10:54:47.628 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:47.941 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9b9e063: partial file
08-05 10:54:47.941 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:48.251 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9b9fce2: partial file
08-05 10:54:48.251 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:48.562 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9ba7715: partial file
08-05 10:54:48.562 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:48.872 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9baa9ba: partial file
08-05 10:54:48.872 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:49.182 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bac6a5: partial file
08-05 10:54:49.182 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:49.493 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bae34a: partial file
08-05 10:54:49.493 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:49.804 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6459: partial file
08-05 10:54:49.805 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:50.115 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb65c3: partial file
08-05 10:54:50.115 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:50.426 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb673d: partial file
08-05 10:54:50.426 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:50.736 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb689c: partial file
08-05 10:54:50.736 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:51.047 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6a03: partial file
08-05 10:54:51.047 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:51.354 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6b70: partial file
08-05 10:54:51.354 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:51.668 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6cd5: partial file
08-05 10:54:51.669 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:51.979 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6e36: partial file
08-05 10:54:51.979 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:52.289 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb6f9e: partial file
08-05 10:54:52.289 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:52.654 7590-28468/com.yht.iptv E/IJKMEDIA: stream 1, offset 0x9bb70ff: partial file
08-05 10:54:52.654 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:52.964 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bb7261: partial file
08-05 10:54:52.964 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:53.275 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bba639: partial file
08-05 10:54:53.275 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:53.585 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bbc49e: partial file
08-05 10:54:53.585 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:53.897 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bbe20a: partial file
08-05 10:54:53.897 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:54.207 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bc60ff: partial file
08-05 10:54:54.207 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:54.537 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bc96dd: partial file
08-05 10:54:54.537 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:54.847 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bcb527: partial file
08-05 10:54:54.847 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:55.158 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bcd45e: partial file
08-05 10:54:55.158 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:55.468 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bd525e: partial file
08-05 10:54:55.468 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:55.779 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bd885c: partial file
08-05 10:54:55.779 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:56.090 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bda6ee: partial file
08-05 10:54:56.090 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:54:56.400 7590-28468/com.yht.iptv E/IJKMEDIA: stream 0, offset 0x9bdc53e: partial file
08-05 10:54:56.400 7590-28468/com.yht.iptv E/IJKMEDIA: av_read_frame error: ffffff92(�,�,�,�): AVERROR(ETIMEDOUT)
08-05 10:55:16.808 7590-28468/com.yht.iptv E/IJKMEDIA: read frame timeout !
08-05 10:55:16.814 7590-28466/com.yht.iptv D/IJKMEDIA: FFP_MSG_ERROR: -2002
08-05 10:55:16.815 7590-28468/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28468]
08-05 10:55:16.815 7590-28467/com.yht.iptv I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [28467]
08-05 10:55:16.904 7590-7590/com.yht.iptv E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2002)

这是报的未知错误

**Comment by yanxiandroid** [comment]
@Jhuster 当在连接局域网的设备多了,播放就会偶尔出现超时和未知错误,,请问这是什么原因?
