### ISSUE TITLE
Can't play Audio format "nellymoser"

### ISSUE THREAD

**Issue by hardman** [pili-engineering/PLDroidPlayer#23]
I played a rtmp path, and the stream info as below. The picture is normal but no sound.
-----log begin-----
09-07 16:47:33.317: I/IJKMEDIA(14778): Input #0, flv, from 'rtmp://testRtmp.com//1012039365-1103-55ed4be455959':
09-07 16:47:33.317: I/IJKMEDIA(14778):   Duration: 
09-07 16:47:33.317: I/IJKMEDIA(14778): N/A
09-07 16:47:33.317: I/IJKMEDIA(14778): , start: 
09-07 16:47:33.317: I/IJKMEDIA(14778): 0.000000
09-07 16:47:33.317: I/IJKMEDIA(14778): , bitrate: 
09-07 16:47:33.317: I/IJKMEDIA(14778): N/A
09-07 16:47:33.322: I/IJKMEDIA(14778):     Stream #0:0
09-07 16:47:33.322: I/IJKMEDIA(14778): : Video: h264 (Main), yuv420p(tv), 320x240 [SAR 1:1 DAR 4:3]
09-07 16:47:33.322: I/IJKMEDIA(14778): , 
09-07 16:47:33.322: I/IJKMEDIA(14778): 15.17 fps, 
09-07 16:47:33.322: I/IJKMEDIA(14778): 15 tbr, 
09-07 16:47:33.322: I/IJKMEDIA(14778): 1k tbn, 
09-07 16:47:33.322: I/IJKMEDIA(14778): 30 tbc
09-07 16:47:33.322: I/IJKMEDIA(14778):     Stream #0:1
09-07 16:47:33.322: I/IJKMEDIA(14778): : Audio: nellymoser, 22050 Hz, mono
09-07 16:47:33.322: W/IJKMEDIA(14778): No codec could be found with id 86050
-----log end-----

**Comment by alcastelo** [comment]
Hi there.
A couple of days ago @jpxiong answer me a similar question in the issue #18 , maybe it can help you.
