### ISSUE TITLE
请问下acc格式的音频文件不支持吗？

### ISSUE THREAD

**Issue by yangjian92** [pili-engineering/PLDroidPlayer#230]

**Comment by Jhuster** [comment]
@yangjian92 支持 aac 的音频解码。音频文件格式是什么，能否提供一个下载链接？

**Comment by yangjian92** [comment]
http://7xn47o.com1.z0.glb.clouddn.com/bbs/audios/2016/0530/b0/b00e99d18150d68ca95e7c8a1f7d1362.aac
我这边测试并不能播放，原生mediaplayer可以正常播放
