### ISSUE TITLE
集成sdk崩溃

### ISSUE THREAD

**Issue by zdnuist** [pili-engineering/PLDroidPlayer#232]
A/libc: Fatal signal 11 (SIGSEGV) at 0x0069006f (code=1), thread 13226 (ff_msg_loop)

**Comment by Jhuster** [comment]
@zdnuist 信息太少了，如果操作的，什么机型，demo 跑起来也会崩溃吗

**Comment by zdnuist** [comment]
拉流失败后重连，重连几次后就出现崩溃，华为\酷派\三星\小米都会出现，demo出现的概率比较小，使用的是PLVideoView,可能是哪些原因导致的？

**Comment by Jhuster** [comment]
@zdnuist 重连逻辑不要写成了死循环，重连之前建议用 Android API 检测一下当前网络连接是否可用，另外，每次重连之前建议有个间隔，比如 sleep(1000)
