### ISSUE TITLE
怎么实现像Vitamio那样让视频按原始尺寸等比例放大直至宽或高顶满屏幕 ，可以不全屏流出一定区域空白，但是不能裁剪

### ISSUE THREAD

**Issue by githubbimingcong** [pili-engineering/PLDroidPlayer#233]

**Comment by Jhuster** [comment]
@githubbimingcong Wiki 文档里有写的，使用 `setDisplayAspectRatio` ，参数用 `ASPECT_RATIO_FIT_PARENT`

**Comment by githubbimingcong** [comment]
@Jhuster  我试过这个参数  ASPECT_RATIO_FIT_PARENT会铺满屏幕但是会把图像拉伸，比如本来一个瘦高的图像会变得胖矮

**Comment by Jhuster** [comment]
@githubbimingcong 不会的，我们的sdk不会拉伸图像，用 demo 试试吧，注意 xml 文件 `PLVideoView` 外层不要再套别的 resize view

**Comment by githubbimingcong** [comment]
@Jhuster 大神  我服    我之前的VideoView的高度设置的是wrapContent现在改成matchParent就好了  非常感谢你的回答

**Comment by More-Stronger** [comment]
PLVideoView 怎么让他控件大小改变后,不重新设置播放内容的大小呢.  就比如抖音,顶部出现内容后,将视频向下推就行了,而不是改变尺寸.
