### ISSUE TITLE
自定义MediaController后，进度条失效，不能拖动，当前时间走动异常。

### ISSUE THREAD

**Issue by sendtion** [pili-engineering/PLDroidPlayer#234]
本想自定义MediaController，却发现这样的问题。进度条不能拖动快进，当前时间走个两三下就停止不动，不断点击播放器，当前时间会正常走动，感觉需要刷新似的。还有点击视频，控制条不能隐藏了。
请问这个问题怎么解决？

**Comment by Jhuster** [comment]
@sendtion 建议仔细参考 demo 给出的 `MediaController` 示例代码。
