### ISSUE TITLE
视频循环播放卡顿

### ISSUE THREAD

**Issue by blackfoxsyt** [pili-engineering/PLDroidPlayer#236]
同一个本地短视频循环播放或者连播多个短视频，切换视频的中间会出现黑屏或者卡顿，请问有解决办法嘛。

**Comment by blackfoxsyt** [comment]
主要是会卡顿一下再播下一个。

**Comment by Jhuster** [comment]
@blackfoxsyt 播放器播放完一个视频后，需要释放资源，加载和解析下一个视频，需要时间。建议在两个视频之间，添加 Loading 动画。

**Comment by blackfoxsyt** [comment]
@Jhuster 产品设计要求不能添加loading动画，希望能做到两个视频见无缝跳转，目前市场上面有很多健身软件，类似火辣，keep这些都是本地视频循环播放和连播，中间没有过度动画也没有卡顿，希望你们的播放器能够在这方面进行优化。
