### ISSUE TITLE
怎嘛清除缓存啊？

### ISSUE THREAD

**Issue by qweawdqq** [pili-engineering/PLDroidPlayer#239]
我没有找到清除缓存的方法呢？

**Comment by Jhuster** [comment]
@qweawdqq 为什么需要这样的方法？消除累积延时吗？1.3.0 版本的 `AVOption` 提供了消除累积延时的参数配置。

**Comment by qweawdqq** [comment]
通过观看内存变化，我发现在观看视频的时候，内存一直是在增长的，我退出观看了，内存也不下降，我就合计是不是，内存缓存了，但不删除

**Comment by Jhuster** [comment]
@qweawdqq 我刚刚用 demo 测试了，并没有出现你描述的情况，播放视频过程中，内存在上下小范围浮动，退出后也能降到一定的范围内。

**Comment by qweawdqq** [comment]
哦，还有个事情，就是我用PLVideoView的时候，做了快进的时候，有些时候会出现 缓存进度条卡住，
打log，观察一下是，有时候快进完了，得到缓存的进度有暂停的情况，另外还想咨询一下，使用这个控件，能不能边下边播，支不支持 直播！？（另外：你的项目，为我解决了很多问题！表示感谢！你要是沈阳的我就请你吃饭了！呵呵）

**Comment by Jhuster** [comment]
@qweawdqq 不支持边下边播。支持 RTMP & HLS 协议的直播。
