### ISSUE TITLE
视频暂停后，切换界面再切换回来时黑屏

### ISSUE THREAD

**Issue by StormBlue** [pili-engineering/PLDroidPlayer#243]
视频正常播放，通过controller暂停了视频，这时切换到别的界面，新启动一个界面或者点击home键，当再切换回视频界面时，播放器是黑屏状态。请教一下，可以解决办法使其保持在暂停得画面。

**Comment by Jhuster** [comment]
@StormBlue 无法一直保持画面，因为退出去的时候 SurfaceView 被销毁了。建议回来后放一张图片，等播放器加载完毕继续播放的时候再移除掉。
