### ISSUE TITLE
Eclipse无法findview

### ISSUE THREAD

**Issue by sdvye** [pili-engineering/PLDroidPlayer#244]
我在eclipse尝试新建一个播放rtmp的demo，工程配置都是按照文档来的，但是在启动程序获取控件的步骤就出错了。
PLVideoView mVideoView = (PLVideoView) findViewById(R.id.PLVideoView);
获取出来mVideoView=null
控制台打印警告：
Grow heap (frag case) to 8.204MB for 1048592-byte allocation
Could not find method android.widget.FrameLayout.<init>, referenced from method com.pili.pldroid.player.widget.a.<init>
VFY: unable to resolve direct method 6020: Landroid/widget/FrameLayout;.<init> (Landroid/content/Context;Landroid/util/AttributeSet;II)V
往解答！谢谢！

**Comment by Jhuster** [comment]
@sdvye `Activity` 的 `onCreate() ` 函数里 `setContentView` 所对应的 `xml` 文件发出来看看。

**Comment by sdvye** [comment]
@Jhuster 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <LinearLayout
        android:id="@+id/ll"
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:orientation="horizontal">

        <Button
            android:id="@+id/button1"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_weight="1"
            android:gravity="center"
            android:onClick="clickBtn"
            android:text="Button1" />
        <Button
            android:id="@+id/button2"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_weight="1"
            android:gravity="center"
            android:onClick="clickBtn"
            android:text="Button2" />
        <Button
            android:id="@+id/button3"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_weight="1"
            android:gravity="center"
            android:onClick="clickBtn"
            android:text="Button3" />
        <Button
            android:id="@+id/button4"
            android:layout_width="fill_parent"
            android:layout_height="fill_parent"
            android:layout_weight="1"
            android:gravity="center"
            android:onClick="clickBtn"
            android:text="Button4" />
        
    </LinearLayout>

    <FrameLayout
        android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    android:layout_below="@+id/ll">
	<com.pili.pldroid.player.widget.PLVideoView
	    android:name="@+id/PLVideoView"
	    android:layout_width="match_parent"
	    android:layout_height="match_parent"
	    android:layout_gravity="center"/>
    </FrameLayout>


</RelativeLayout>

**Comment by Jhuster** [comment]
@sdvye 你给的布局不全，感觉应该是编译不过的，你把 demo 的 xml 和 Activity 拷贝过去试试吧。
