### ISSUE TITLE
在使用机顶盒软解播放1080p视频的时候出现非常卡顿的问题，但是在手机上貌似比较好，机顶盒使用的是支持4K视频播放的盒子，请问这是什么原因？

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#248]

**Comment by Jhuster** [comment]
@yanxiandroid 机顶盒的 cpu 性能可能不强，能解 4K 应该用的是硬件解码。

**Comment by yanxiandroid** [comment]
@Jhuster 确实如您所说，我刚换用硬件解码很流畅，谢谢。

**Comment by yanxiandroid** [comment]
@Jhuster 换了硬解码之后,1080P确实可以流畅播放,但是有一个很致命的问题就是:退出播放的时候貌似会由于视频资源没有释放完毕出现卡死的情况,有时候需要等待几秒钟,有时候提示ANR.请问这是什么原因?

**Comment by Jhuster** [comment]
@yanxiandroid 是否开启了DNS解析优化？`https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5`

**Comment by yanxiandroid** [comment]
@Jhuster 我暂时没有开启DNS解析优化..我现在试试.谢谢!

**Comment by yanxiandroid** [comment]
@Jhuster 我加了DNS解析优化还是会出现卡顿的情况.我现在主要是局域网的播放,DNS优化是不是没效果?我添加优化的方法就是在oncrete加了PLNetworkManager.getInstance().startDnsCacheService(this);在onDestroy()执行PLNetworkManager.getInstance().stopDnsCacheService(this);

**Comment by Jhuster** [comment]
@yanxiandroid 哦，局域网应用，dns 解析没啥效果。你是播放的文件，还是在局域网搭建了一台流媒体服务器？

**Comment by yanxiandroid** [comment]
@Jhuster 我就是在局域网播放文件,请问这怎么解决?

**Comment by Jhuster** [comment]
@yanxiandroid 如果是播放的文件，卡，基本上跟机顶盒的性能有关了，如果是某些 1080P High Profile H.264 编码的视频，不一定能及时完成 IO读取＋解码＋渲染。

**Comment by yanxiandroid** [comment]
@Jhuster 但是播放基本很流畅,就是退出的时候会卡顿.这块有没有什么办法解决呢?

**Comment by Jhuster** [comment]
@yanxiandroid 如果不是频繁快速退出又进来又退出这样的方式切换的话，可以考虑在子线程中调用 `stopPlayback()`
