### ISSUE TITLE
魅族M040/Flyme2.2(A8860)  Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 11011

### ISSUE THREAD

**Issue by taolong001** [pili-engineering/PLDroidPlayer#249]
08-11 17:34:44.730 11011-11011/com.hz.yuanlang.lang_share D/dalvikvm: Trying to load lib /data/data/com.hz.yuanlang.lang_share/lib/libpldroidplayer.so 0x4234cf20
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/dalvikvm: Added shared lib /data/data/com.hz.yuanlang.lang_share/lib/libpldroidplayer.so 0x4234cf20
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'java.nio.ByteBuffer' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'java.util.ArrayList' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.os.Build$VERSION' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.os.Build' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.media.AudioTrack' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share I/IJKMEDIA: API-Level: 16
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.media.MediaCodec' loaded
08-11 17:34:44.755 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 11
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.media.MediaFormat' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'android.os.Bundle' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'tv.danmaku.ijk.media.player.IjkMediaPlayer' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: JJKLoader: OK: 'tv.danmaku.ijk.media.player.misc.IMediaDataSource' loaded
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: IjkMediaPlayer_native_init
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: IjkMediaPlayer_native_setup
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share D/pldroid-player-native: pldroid_player native version = 1.2.0 
08-11 17:34:44.755 11011-11011/com.hz.yuanlang.lang_share I/IJKMEDIA: ffp: 0x59cb8b00
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ffpipeline_create_from_android()
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d200272)
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_set_inject_opaque()=void
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
08-11 17:34:44.760 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
08-11 17:34:44.760 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 12
08-11 17:34:44.760 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 13
08-11 17:34:44.760 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 14
08-11 17:34:44.760 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 15
08-11 17:34:44.765 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 16
08-11 17:34:44.765 11011-11019/com.hz.yuanlang.lang_share I/dalvikvm: Total arena pages for JIT: 17
08-11 17:34:44.790 11011-11016/com.hz.yuanlang.lang_share D/dalvikvm: GC_CONCURRENT freed 1083K, 8% free 15361K/16519K, paused 13ms+4ms, total 56ms
08-11 17:34:44.790 11011-11011/com.hz.yuanlang.lang_share D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 11ms
08-11 17:34:44.790 11011-11086/com.hz.yuanlang.lang_share D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 14ms
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: IjkMediaPlayer_native_setup
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share I/IJKMEDIA: av_version_info: ff2.8--ijk0.4.1.1--dev0.3.3--rc4
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/pldroid-player-native: pldroid_player native version = 1.2.0 
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share I/IJKMEDIA: ffp: 0x5a3e5b10
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ffpipeline_create_from_android()
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_set_inject_opaque(0x1d20027a)
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_set_inject_opaque()=void
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
08-11 17:34:44.845 11011-11011/com.hz.yuanlang.lang_share D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
08-11 17:34:44.885 11011-11106/com.hz.yuanlang.lang_share D/dalvikvm: GC_FOR_ALLOC freed 342K, 7% free 15773K/16839K, paused 32ms, total 32ms
08-11 17:34:44.900 11011-11011/com.hz.yuanlang.lang_share D/LangVideoView: onSurfaceTextureAvailable() called with: surfaceTexture = [android.graphics.SurfaceTexture@42852600], i = [800], i1 = [440]
08-11 17:34:44.905 11011-11011/com.hz.yuanlang.lang_share D/LangVideoView: onSurfaceTextureAvailable() called with: surfaceTexture = [android.graphics.SurfaceTexture@428230b8], i = [800], i1 = [440]
08-11 17:34:44.930 11011-11011/com.hz.yuanlang.lang_share A/libc: Fatal signal 11 (SIGSEGV) at 0x00000030 (code=1), thread 11011 (lang.lang_share)

**Comment by taolong001** [comment]
@Jhuster 在其他手机上使用都没有问题，在魅族M040/Flyme2.2(A8860) 上崩溃

**Comment by Jhuster** [comment]
@taolong001 使用软编试试。

**Comment by Jhuster** [comment]
@taolong001 使用软解试试。

**Comment by susussa** [comment]
我也遇到这个问题  实在锤子手机上Smartisan SM701
