### ISSUE TITLE
为什么播放直播视频时，前3秒有画面延迟情况？感觉像慢动作

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#250]
为什么播放直播视频时，前3秒有画面延迟情况？感觉像慢动作。如何解决

**Comment by Jhuster** [comment]
@jaychou2012 应该是在网络不稳定的情况中，播放器为了减少累积延时有追帧动作。如果不希望追帧，可以考虑关闭 `AVOptions.KEY_DELAY_OPTIMIZATION` 试试。

**Comment by jaychou2012** [comment]
网络环境很稳定。AVOptions.KEY_DELAY_OPTIMIZATION=0吗？我似乎试过

**Comment by jaychou2012** [comment]
无效。还是那样怎么办？

**Comment by Jhuster** [comment]
@jaychou2012 播放的流是 demo 里面的那个吗

**Comment by jaychou2012** [comment]
不是

**Comment by Jhuster** [comment]
@jaychou2012 播放地址可以发出来看看吗？其他播放器也是类似效果吗？

**Comment by jaychou2012** [comment]
如何主动触发onVideoSizeChange方法
