### ISSUE TITLE
这播放器有设置缓存的方法吗？我播放有点视频链接很卡播一两秒就卡住在缓存了

### ISSUE THREAD

**Issue by melody1993** [pili-engineering/PLDroidPlayer#251]

**Comment by Jhuster** [comment]
@melody1993 默认的缓存足够了，可能是网络不太好，视频链接发出来我们这边看看？

**Comment by melody1993** [comment]
http://video.weijuxing.cn/2080_video1470708525931，我在电脑浏览器上播还算流畅

**Comment by Jhuster** [comment]
@melody1993 这个流在电脑上用 ffplay 播放也是很卡很卡，应该不是网络原因，可能跟音视频时间戳同步有关，这个流是如何打包的，建议你们分析下它的时间戳。

**Comment by melody1993** [comment]
意思要改下这个链接的时间戳？

**Comment by melody1993** [comment]
为什么浏览器默认的播放器播放很流畅啊？

**Comment by Jhuster** [comment]
@melody1993 不是链接的时间戳，是要分析一下码流里面打包的“音频＋视频”的时间戳，ffplay 播放也很卡，不同的浏览器/播放器对码流播放采取的音视频同步机制是不一样的。
