### ISSUE TITLE
可以把PLTextureView和PLVideoView源码给我下吗？我需要获取里面的PLMediaPlayer

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#252]
可以把PLTextureView和PLVideoView源码给我下吗？我需要获取里面的PLMediaPlayer。在播放短视频时，拖动后，获取到的时时播放时长有问题。getCurrentPosition()

**Comment by Jhuster** [comment]
@jaychou2012 拖动不准一般是视频的关键帧间隔太大或者有缺失，`PLVideoView` 的 `getCurrentPosition()` 内部就是用的 `PLMediaPlayer` 的 `getCurrentPosition()`
