### ISSUE TITLE
播放的画面与声音不同步怎么回事？

### ISSUE THREAD

**Issue by jaychou2012** [pili-engineering/PLDroidPlayer#253]
播放的画面与声音不同步怎么回事？SurfaceView，声音正常，画面有延迟

**Comment by Jhuster** [comment]
@jaychou2012 播放链接发出来看看，使用 `ffplay` 等第三方播放器播放是否也会出现问题？

**Comment by jaychou2012** [comment]
对m3u8或者Mp4支持不好吗

**Comment by Jhuster** [comment]
@jaychou2012 对于 m3u8 和 mp4 都是没有任何问题的，充分测试过，一般出现音视频不同步的时候，大多数最后调试下来都是推流端（即码流本身）的音视频时间戳有些问题。

`ffplay` 播放你们的码流是否有问题呢？ 是否有打印和分析一下码流的时间戳信息 ？你们的码流是如何产生的 ？
