### ISSUE TITLE
MediaController的PopupWindow位置问题

### ISSUE THREAD

**Issue by danniu1314** [pili-engineering/PLDroidPlayer#254]
mWindow.showAtLocation(mAnchor, Gravity.BOTTOM,anchorRect.left, 0); mWindow.showAtLocation(mRoot, Gravity.BOTTOM,anchorRect.left, 0);
我用构造函数传入了我需要展示在什么控件上，将这前面的父控件换成我自己传过来的view，但是还是显示在屏幕底部。我目前是上半屏显示视频，下半屏是其他控件，我在半屏的时候想把PopupWindow显示在视频控件的下方位置，横屏旋转后也是在这个控件的下方位置。我该怎么改动？

**Comment by tanhx2008** [comment]
建议不用播放器自带的MediaController，可以自己实现播放控制，实现些自定义的功能也比较方便，另外实现起来也很容易。

**Comment by 1214658495** [comment]
@tanhx2008 新人，能请教一下这个MediaController如何自定义自己的布局啊？（能否有个代码学习一下）谢谢大神指导

**Comment by jingjkai** [comment]
> mWindow.showAtLocation(mAnchor, Gravity.BOTTOM,anchorRect.left, 0); mWindow.showAtLocation(mRoot, Gravity.BOTTOM,anchorRect.left, 0);
> 我用构造函数传入了我需要展示在什么控件上，将这前面的父控件换成我自己传过来的view，但是还是显示在屏幕底部。我目前是上半屏显示视频，下半屏是其他控件，我在半屏的时候想把PopupWindow显示在视频控件的下方位置，横屏旋转后也是在这个控件的下方位置。我该怎么改动？

您好，请问您的问题最终是如何解决的呢
