### ISSUE TITLE
提一个播放视频demo的bug

### ISSUE THREAD

**Issue by huazidev** [pili-engineering/PLDroidPlayer#256]
当播放网络视频或者本地视频，如果视频超过35分钟，如果进度条拖动到35 分钟之后会重新播放，目前demo会有这个问题。
经过demo 查看当滑动进度条的时候，MediaController类中获取新的位置newposition，这个newposition不应该用int，当时常超过35分钟以后int类型溢出，获取到负值，所以player就重新播放，希望能处理一下：

 public void onProgressChanged(SeekBar bar, int progress, boolean fromuser) {
            if (!fromuser)
                return;

```
        final int newposition = (int) (mDuration * progress) / 1000;
        String time = generateTime(newposition);
        if (mInstantSeeking) {
            mHandler.removeCallbacks(mLastSeekBarRunnable);
            mLastSeekBarRunnable = new Runnable() {
                @Override
                public void run() {
                    mPlayer.seekTo(newposition);
                }
            };
            mHandler.postDelayed(mLastSeekBarRunnable, SEEK_TO_POST_DELAY_MILLIS);
        }
        if (mCurrentTime != null)
            mCurrentTime.setText(time);
    }
```

**Comment by Jhuster** [comment]
@huazi0923 `MediaController` 的源码在 demo 里面，你可以自行修改，这个控件代码只是作为演示用的，可以自己实现一个满足定制化需求的 `MediaController`。

**Comment by huazi0923** [comment]
已经自己改了，请问支持第一帧截屏吗？在播放之前显示。

**Comment by Jhuster** [comment]
@huazi0923 播放前可以加载一个通用的图片，`PLVideoTextureView.getTextureView().getBitmap()` 试试。

**Comment by huazi0923** [comment]
那PLVideoView有这个功能吗？必须要换成PLVideoTextureView吗？

**Comment by Jhuster** [comment]
@huazi0923 `PLVideoView` 没有这个功能。

**Comment by huazi0923** [comment]
好的，谢谢
