### ISSUE TITLE
使用PLDroidPlayer,视频源是其他服务商,不是七牛云的可以?

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#259]
另外问一下,以后PLDroidPlayer是否会和七牛云深度合作,导致使用其他直播源无法使用PLDroidPlayer.

**Comment by Jhuster** [comment]
@Vander-liu 不会，标准协议的流会一直保持兼容。

**Comment by Vander-liu** [comment]
那我看了一下我们PLDroidPlayer的Wiki为什么前置条件是这样的,
1.已注册七牛帐号
2.通过官网申请并已开通直播权限
而且需要阅读者准备接入七牛云直播.
因为这样我才产生了疑问的

**Comment by Jhuster** [comment]
@Vander-liu 嗯，这里只是希望使用者采用我们公司的直播云服务，并不做强制要求。

**Comment by Vander-liu** [comment]
好的,谢谢您的回答.

**Comment by newstrong** [comment]
支持开源，七牛 直播业务一定能越做越好！
