### ISSUE TITLE
Immediate exit requested

### ISSUE THREAD

**Issue by xinyitiandi** [pili-engineering/PLDroidPlayer#262]

**Comment by Jhuster** [comment]
@xinyitiandi 信息太少。

**Comment by xinyitiandi** [comment]
09-08 10:16:12.750 1764-4714/yinhangbang.ekeguan.com.yinhangbang4 E/IJKMEDIA: http://videoqiniu.ekeguan.com//%E9%93%B6%E8%A1%8C%E5%AF%BC%E5%AD%A6%E8%AF%BE/480pl/%E4%BA%94%E5%A4%A7%E8%A1%8C%E9%9D%A2%E8%AF%95%E6%80%8E%E4%B9%88%E5%8A%9E.mp4: Immediate exit requested
09-08 10:16:14.160 1764-1764/yinhangbang.ekeguan.com.yinhangbang4 E/CrashReport: Bugly NDK Version:2.2.0
09-08 10:16:14.160 1764-1764/yinhangbang.ekeguan.com.yinhangbang4 E/CrashReport: Old handler addresss 0x40068a71
09-08 10:16:14.160 1764-1764/yinhangbang.ekeguan.com.yinhangbang4 E/CrashReport: HandleSignal start 6
09-08 10:16:14.190 1764-1764/yinhangbang.ekeguan.com.yinhangbang4 E/CrashReport: Native log has not been initiated.
09-08 10:16:15.160 1764-1770/yinhangbang.ekeguan.com.yinhangbang4 A/libc: Fatal signal 6 (SIGABRT) at 0x00000424 (code=0), thread 1770 (Signal Catcher)

**Comment by xinyitiandi** [comment]
就是，在退出播放界面时，只要调用release释放视频资源，就崩溃了，然后报了这个错！

**Comment by xinyitiandi** [comment]
查了一下网上，是这样说的：当我的平板切换到3G模式下的时候，调用
avformat_open_input失败，我查看返回的错误值（用av_strerror函数），提示immediate exit requested
3G网络比较慢一点，有可能是你avformat_open_input的时候设置了AVFormatContext的interrupt_callback，把里面的值设置大一点，应该就可以了

**Comment by xinyitiandi** [comment]
但是不知道怎么设置

**Comment by Jhuster** [comment]
@xinyitiandi 这个超时时间可以在 `AVOptions` 的 `KEY_PREPARE_TIMEOUT`  进行配置。
