### ISSUE TITLE
关于快进的问题

### ISSUE THREAD

**Issue by qweawdqq** [pili-engineering/PLDroidPlayer#263]
你好，我想问一下，为什吗我视频快进完了之后，视频的缓存条 有时候会动不了啊？得到的缓存百分比 一直就是那个数字！

**Comment by qweawdqq** [comment]
还有就是 有时候缓存加载的百分比到98%就卡住了，不动了  一直就是98

**Comment by Jhuster** [comment]
@qweawdqq 谢反馈，有时底层缓存到 100% 的时候没有回调消息上来，的确是个 bug，后面修复。
