### ISSUE TITLE
支持库这么小，是否支持硬解的格式和设备兼容性会差一点？

### ISSUE THREAD

**Issue by zllikey** [pili-engineering/PLDroidPlayer#264]
支持库这么小，是否支持硬解的格式和设备兼容性会差一点？

**Comment by Jhuster** [comment]
@zllikey 硬解用的是 MediaCodec，它是 Android 系统的 API，不需要额外的动态库支持，跟动态库大小无关的。

**Comment by zllikey** [comment]
问一下PLDROIDPLAYER是否基于https://github.com/pili-engineering/pili-ijkplayer的ijjplayer0.4.3.12版本进行二次封装？据我所知ijkplayer目前最新版本已经去到0.6.0，改进了很多东西

**Comment by Jhuster** [comment]
@zllikey 嗯，还没有同步到 0.6.0
