### ISSUE TITLE
关于带IP地址的局域网播放视频的缓存问题.

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#265]
使用options.setInteger(AVOptions.KEY_CACHE_BUFFER_DURATION, 2000);
options.setInteger(AVOptions.KEY_MAX_CACHE_BUFFER_DURATION, 4000);可以设置带IP地址播放的视频的缓存吗?如果支持,请问最大支持多长时间的缓存?

**Comment by Jhuster** [comment]
@yanxiandroid 所有功能都不区分播放地址的格式的。 这两个参数WiKi文档有介绍上限和下限。另外，注意，它们是用来做累积延时优化的，不是本地缓存，参考 WiKi 文档的说明。

**Comment by yanxiandroid** [comment]
@Jhuster WiKi上面只是说最大缓存默认的是4000ms,峰值谁多少呢?

**Comment by Jhuster** [comment]
@yanxiandroid 它是用来做累积延时优化的，你希望最大可容忍的累积延时是多少，你就设置为多少。
