### ISSUE TITLE
纯音频播放时，延迟要比同时播放音视频要高很多，什么原因？

### ISSUE THREAD

**Issue by hfutxqd** [pili-engineering/PLDroidPlayer#266]
我开始以为Buffer可能时固定的大小，要等到Buffer填满后才开始播放，音视频的流量大，所以延迟就低了，但是怎么调整AVOptions，好像都没有什么效果

**Comment by Jhuster** [comment]
@hfutxqd 纯音频播放暂时没有加上累计延时优化，后面的版本会加上。

**Comment by hfutxqd** [comment]
下个版本大概什么时候会出呢？
