### ISSUE TITLE
问一下 demo上播放MP4 格式的视频的问题（demo上的无论选择软解码 或是硬解码 几种测试的播放器都是 只有声音 没有图像 其他的播放器是可以的 ） 请问是不是哪里还有什么没有设置好？

### ISSUE THREAD

**Issue by colorchenvip** [pili-engineering/PLDroidPlayer#268]

**Comment by Jhuster** [comment]
@colorchenvip 是否有错误 log，另外 mp4 是 h.264 编码的吗 ？

**Comment by colorchenvip** [comment]
未见错误log提示  地址http://7xlo7u.media1.z0.glb.clouddn.com/1/discover/video/aa5d7cb1e2e1f1046d02e643f5c1fd6c.mp4?e=1471945753&token=2By9Dv_ga4ZwK5x4xSOPGAwMqXYxCgfZk8ESA0Tu:XNvuUlmkmx_EbjKLhk-Rxvq4QgU=  麻烦看一下

**Comment by tanhx2008** [comment]
08-23 17:27:00.474 I/IJKMEDIA(17025): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(1.000000,0.000000)
08-23 17:27:00.474 I/IJKMEDIA(17025): audio_session_id = 1422
08-23 17:27:00.474 I/IJKMEDIA(17025): AudioCodec: avcodec, aac
08-23 17:27:00.474 W/IJKMEDIA(17025): No codec could be found with id 13

**Comment by tanhx2008** [comment]
视频的编码格式不支持

**Comment by colorchenvip** [comment]
ok thanks

**Comment by 751811032** [comment]
意思就是不支持H265吗
