### ISSUE TITLE
请问支持rtsp的流嘛？

### ISSUE THREAD

**Issue by panacena** [pili-engineering/PLDroidPlayer#269]
请问支持rtsp的流嘛？

**Comment by Jhuster** [comment]
@panacena 为了减小 so 的体积，我们去掉了 RTSP 协议的支持，后面我们会考虑编译一个涵盖更多协议的 so 提供给有需要的人。

**Comment by newstrong** [comment]
请增加rtsp的支持，希望减少延迟

**Comment by Jhuster** [comment]
@newstrong 我们已经在 1.3.0 版本添加了累积延时的优化，需要在 `AVOptions`里打开开关。

**Comment by newstrong** [comment]
意思是1.3.0版本支持rtsp通道？




newstrong@yeah.net
 
发件人： 卢俊
发送时间： 2016-09-01 22:19
收件人： pili-engineering/PLDroidPlayer
抄送： Qiang Zhong; Mention
主题： Re: [pili-engineering/PLDroidPlayer] 请问支持rtsp的流嘛？ (#269)
@newstrong 我们已经在 1.3.0 版本添加了累积延时的优化，需要在 AVOptions里打开开关。

**Comment by Jhuster** [comment]
@newstrong 不支持。
