### ISSUE TITLE
视频点播如何重连

### ISSUE THREAD

**Issue by xiayuetao** [pili-engineering/PLDroidPlayer#270]
在视频点播时因为突然获取不到数据流了返回异常后如何进行重连？
使用的是PLVideoView，在捕获错误状态码后直接start好像并不起作用，一直卡在加载的状态

**Comment by Jhuster** [comment]
@xiayuetao 重连需要调用 `setDataSource`，建议实时记录当前的播放位置，重连成功后 `seek` 到当前位置。

**Comment by Jhuster** [comment]
重连需要调用 `setVideoPath`，建议实时记录当前的播放位置，重连成功后 `seek` 到当前位置。
