### ISSUE TITLE
请问 设置了屏幕旋转之后，自己写的底部进度布局如何根据屏幕自动旋转

### ISSUE THREAD

**Issue by Juni-Dai** [pili-engineering/PLDroidPlayer#271]

**Comment by Jhuster** [comment]
@Juni-Dai 可以 Google 一下 "Android RotateLayout"

**Comment by Juni-Dai** [comment]
没有直接让进度显示和播放这块的方向根据视频方向进行改变的方法吗？、

**Comment by Juni-Dai** [comment]
没有直接让进度显示和播放这块的方向根据视频方向进行改变的方法吗？、

**Comment by Juni-Dai** [comment]
没有直接让进度显示和播放这块的方向根据视频方向进行改变的方法吗？、

**Comment by Juni-Dai** [comment]
没有直接让进度显示和播放这块的方向根据视频方向进行改变的方法吗？、

**Comment by Juni-Dai** [comment]
没有直接让进度显示和播放这块的方向根据视频方向进行改变的方法吗？、

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster

**Comment by Juni-Dai** [comment]
mProgress = (ProgressBar) v.findViewById(MEDIACONTROLLER_PROGRESS_ID);
        if (mProgress != null) {
            if (mProgress instanceof SeekBar) {
                SeekBar seeker = (SeekBar) mProgress;
                seeker.setOnSeekBarChangeListener(mSeekListener);
                seeker.setThumbOffset(1);
            }
布局中使用ProgressBar是没办法进入instanceof这个条件的  请问是怎么做的呢？@Jhuster
