### ISSUE TITLE
ERROR_CODE_PREPARE_TIMEOUT  -2001

### ISSUE THREAD

**Issue by cdcdec** [pili-engineering/PLDroidPlayer#272]
直播视频时报这个(ERROR_CODE_PREPARE_TIMEOUT -2001)错误，是什么原因啊？

**Comment by Jhuster** [comment]
@chendongchu 连接服务器超时。

**Comment by chendongchu** [comment]
谢谢！问题找到了,是直播源的问题。又有个新的问题，播放视频时只有声音没有图像？

**Comment by Jhuster** [comment]
@chendongchu 视频是 H.264 编码的吗？

**Comment by chendongchu** [comment]
视频:MPEG-4 Visual,音频:AAC LC
