### ISSUE TITLE
无网络时重连，重连几次崩溃的问题

### ISSUE THREAD

**Issue by huazidev** [pili-engineering/PLDroidPlayer#273]
在无网络时，设置重连，重连几次后会崩溃，demo也有这个问题。
另一种情况是在播放过程中断网，播放完缓冲的视频暂停后，重连几次也会崩溃。如果我设置有网的情况下才重连，重连了也不会继续播放，好像播放器已经无效了，怎么也不会start。
播放的是存在七牛服务器上的视频。
链接：http://7fvkls.com1.z0.glb.clouddn.com/1431057981166_1.mp4
希望能看一下什么问题，多谢。

**Comment by Jhuster** [comment]
@huazi0923 请问你是如何做重连的，是调用 setVideoPath 吗 ？每次重连之前是否有判断网络连接性或者Sleep吗？

**Comment by huazi0923** [comment]
和demo里一样的，用的PLVideoTextureView
mVideoView.setVideoPath(mVideoPath);
mVideoView.start();

**Comment by Jhuster** [comment]
@huangdeheng 建议加一下判断和 sleep

**Comment by Jhuster** [comment]
@huazi0923 建议加一下判断和 sleep
