### ISSUE TITLE
pldroid_player jar 包里面的关于ijk player 的是必须要有的吗

### ISSUE THREAD

**Issue by yilylong** [pili-engineering/PLDroidPlayer#276]
jar 包里 tv.danmaku.ijk.media.player 下的内容必需要有吗 ？

**Comment by Jhuster** [comment]
@yilylong 什么意思，请问你的需求是什么

**Comment by yilylong** [comment]
是这样的 我在测试对比 IJKplayer 和 pldroidplayer 打包发现冲突 然后看到两个里面都有tv.danmaku.ijk.media.player  看到pldroidplayer  这个是居于IJKplayer  但是里面有独立的包 就想问问pldroidplayer  的jar 包里面必须有这个tv.danmaku.ijk.media.player里面的内容吗

**Comment by Jhuster** [comment]
@yilylong 嗯，是的，同一个工程不能同时引用 PLDroidPlayer 和 IJKPlayer

**Comment by yilylong** [comment]
ok thankyou

**Comment by hpyfei** [comment]
@Jhuster 一个工程，有无办法做到PLDroidPlayer 和 IJKPlayer共存呢？

**Comment by Jhuster** [comment]
无法共存
