### ISSUE TITLE
turn off the player, to clean up resources

### ISSUE THREAD

**Issue by nalovma** [pili-engineering/PLDroidPlayer#277]
I am using PLVideoView, after run the app I want go to other stream while the first one is running, I use
mVideoView.setVideoPath(mVideoPath);
mVideoView.start();
in the wiki it is written in that but after I chose the app crach in these points.
how the turn of the player and clean the resources before start new stream

**Comment by Jhuster** [comment]
@nalovma you should use `stopPlayback` to stop the player.

**Comment by nalovma** [comment]
When I use stopPlayback() the same problem

**Comment by Jhuster** [comment]
@nalovma Pls show me your code snippets, where and how you switch the stream.
