### ISSUE TITLE
视频播放报未知错误问题

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#278]
@Jhuster 我在播放局域网视频的时候,播放了一部分,然后暂停个10分钟左右再继续播放一会就会报未知错误。

**Comment by yanxiandroid** [comment]
@Jhuster 是不是播放器本身对OnError的判断存在的问题，当网络不稳定也会这样，或者网络断开一会，再连接上都可能出现OnError的回调。我希望在网络不好的情况下就类似于其他播放器一样一直加载就行，然后加载超时才退出，而不是直接就报了未知错误，给人很诧异的感觉。

**Comment by yanxiandroid** [comment]
@Jhuster 机顶盒是局域网播放文件,暂停3分钟左右,再播放一会就会出现未知错误，暂时的处理办法是在onError中重新设置解决，希望下版本能解决这个问题，用demo测试同样会出现次问题

**Comment by Jhuster** [comment]
@yanxiandroid 试过用 ffplay 或者其他播放器吗？

**Comment by yanxiandroid** [comment]
我现在没时间换其他播放器，比较忙，只是这里先mark下，等我有时间换了我再试试。暂时用这种方式解决的，只是觉得这算是个小bug所以提出来的。
