### ISSUE TITLE
rtmp流视频播放不了

### ISSUE THREAD

**Issue by atLearn** [pili-engineering/PLDroidPlayer#279]
在电脑上和和其他播放器可以正常，但是PLDroidPlayer提示Unknown Error，请问如何排查，谢谢

**Comment by Jhuster** [comment]
@atlearn 播放地址发出来看看

**Comment by atlearn** [comment]
刚刚调试发现我现在是想播放RTMP视频流，选的是直播就播放不了，选了点播可以播放，我播的是本地服务器的地址，目前还没有公网地址 rtmp://10.10.200.248/oflaDemo/streams，直播错误提示是：
09-02 15:59:37.240 657-963/? D/SSRMv2:CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 657  tag : ACTIVITY_RESUME_BOOSTER@8
09-02 15:59:38.130 21534-19537/com.pili.pldroid.playerdemo E/IJKMEDIA: Server error: NetStream.Play.StreamNotFound
09-02 15:59:38.130 21534-19537/com.pili.pldroid.playerdemo E/IJKMEDIA: rtmp://10.10.200.248/oflaDemo/streams: Operation not permitted
09-02 15:59:38.130 21534-19537/com.pili.pldroid.playerdemo E/pldroid-player-native: failed to open input : 1569 ms !
09-02 15:59:38.130 21534-19537/com.pili.pldroid.playerdemo D/pldroid-player-native: exit read thread !
09-02 15:59:38.130 21534-19535/com.pili.pldroid.playerdemo D/IJKMEDIA: FFP_MSG_ERROR: -1
09-02 15:59:38.130 21534-19537/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [19537]
09-02 15:59:38.140 21534-21534/com.pili.pldroid.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1)
09-02 15:59:38.140 21534-21534/com.pili.pldroid.playerdemo E/PLMediaPlayer: Error happened, what = -10000, extra = -1
09-02 15:59:38.140 21534-21534/com.pili.pldroid.playerdemo E/PLMediaPlayerActivity: Error happened, errorCode = -1
09-02 15:59:38.380 657-667/? D/dalvikvm: GC_FOR_ALLOC freed 1337K, 17% free 64644K/77504K, paused 190ms, total 190ms
09-02 15:59:38.400 657-666/? I/power: *** acquire_dvfs_lock : lockType : 1  freq : 1190400 
09-02 15:59:38.400 657-666/? D/SSRMv2:CustomFrequencyManagerService: acquireDVFSLockLocked : type : DVFS_MIN_LIMIT  frequency : 1190400  uid : 1000  pid : 657  pkgName : ACTIVITY_RESUME_BOOSTER@5

**Comment by Jhuster** [comment]
@atlearn `Server error: NetStream.Play.StreamNotFound`  用 ffplay 试试，很明显，流不存在。
