### ISSUE TITLE
视频暂停后调用哪个方法可以继续播放

### ISSUE THREAD

**Issue by vincentljdong** [pili-engineering/PLDroidPlayer#283]
还有就是调用哪个方法可以实现视频的快进和快退，麻烦告知，谢谢

**Comment by Jhuster** [comment]
@vincentljdong `start()` 即可继续播放。 不支持 快进、快退。

**Comment by vincentljdong** [comment]
你是说这个方法mVideoView.start()，但是没有用啊，谢谢

**Comment by vincentljdong** [comment]
@Jhuster

**Comment by Jhuster** [comment]
@vincentljdong 你是调用的 pause 暂停的吗？ 建议下载 demo 看看源码。

**Comment by vincentljdong** [comment]
@Jhuster 直接调用的onPause才能暂停，之后onResume或者start都不能继续播放

**Comment by vincentljdong** [comment]
@Jhuster 已经解决了，谢谢

**Comment by vincentljdong** [comment]
@Jhuster 对了，设置声音setVolume()里面的参数是设置一样还是左边不变右边变化值

**Comment by Jhuster** [comment]
@vincentljdong 设置一样。
