### ISSUE TITLE
请问直播和点播拉流有什么区别

### ISSUE THREAD

**Issue by atLearn** [pili-engineering/PLDroidPlayer#284]
手机推流上去之后，用PLDroidPlayer播放RTMP流，用直播播不了，点播可以播放，我的本地服务器是没有做缓存的。请问直播和点播拉流是有什么不一样，为什么一个可以播一个不能播。

**Comment by Jhuster** [comment]
@atlearn 使用 ffplay 是否能播放你的流地址？直播过程是否有报错信息
