### ISSUE TITLE
使用PLVideoTextureView 播放直播流，主线程阻塞

### ISSUE THREAD

**Issue by DB-boy** [pili-engineering/PLDroidPlayer#286]
使用PLVideoTextureView 播放直播流，在prepare 中，还为进行播放的时候，退出，会主线程阻塞，在onDestory中加了stopPlayback();，MediaController也将Handler取消了

**Comment by Jhuster** [comment]
@DB-boy 什么版本，是否添加了 DNS 解析优化 ？ `https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5`

**Comment by DB-boy** [comment]
@Jhuster pldroid-player-1.3.0 没有使用DNS优化，只是直接使用的拉流的地址，
        mVideoView.setVideoPath(rtmp);

**Comment by Jhuster** [comment]
@DB-boy 加上，不加的话很多手机底层的 dns 解析耗时很久会导致 ANR
