### ISSUE TITLE
PLVideoTextureView 怎么拿到每一帧的回调？

### ISSUE THREAD

**Issue by JoneWeng** [pili-engineering/PLDroidPlayer#287]
RT

**Comment by Jhuster** [comment]
@JoneWeng 如果你是为了做 “截屏”，可以考虑：`PLVideoTextureView.getTextureView().getBitmap()`

如果想拿到每一帧解码前或者解码后的数据，目前不支持。

**Comment by JoneWeng** [comment]
@Jhuster 谢谢。

我找到个解决方案

getTextureView().setSurfaceTextureListener()
listener::onSurfaceTextureUpdated 
textureView.getBitmap

**Comment by Jhuster** [comment]
@JoneWeng 赞！

**Comment by hnyer** [comment]
@JoneWeng   为什么我设置了 setSurfaceTextureListener 就一直在加载等待？  

   TextureView.SurfaceTextureListener aivinTextTureListner = new TextureView.SurfaceTextureListener() {
        @Override
        public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
        }

        @Override
        public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
        }

        @Override
        public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
            return false;
        }

        @Override
        public void onSurfaceTextureUpdated(SurfaceTexture surface) {
            Log.i("TAG" ,"onSurfaceTextureUpdated >>>>>") ;
        }
    } ;


        TextureView textureView =   mVideoView.getTextureView();
        if(textureView ==null){
            return;
        }else{
            //为什么添加上 监听，就一直在等待？？？ Buffering 提示框一直在旋转。
//            textureView.setSurfaceTextureListener(aivinTextTureListner);//aivinTextTureListner
        }

**Comment by JoneWeng** [comment]
@hnyer  要包装下原来的 listener

      TextureView.SurfaceTextureListener defaultSurfaceTextureListener = textureView.getSurfaceTextureListener();

        textureView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                defaultSurfaceTextureListener.onSurfaceTextureAvailable(surface, width, height);
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {
                defaultSurfaceTextureListener.onSurfaceTextureSizeChanged(surface, width, height);
            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                return defaultSurfaceTextureListener.onSurfaceTextureDestroyed(surface);
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {
                defaultSurfaceTextureListener.onSurfaceTextureUpdated(surface);
                // do something
            }
        });

**Comment by hnyer** [comment]
@JoneWeng   知道怎么直接获取每一帧的 yuv数据吗？   我先按照你的方法获得bitmap， 然后再将bitmap转为 yuv数据。 这种流程有点资源。   或者有没有更加高效的转换方法 ？ 谢谢 。

**Comment by JoneWeng** [comment]
@hnyer  我不知道

**Comment by hnyer** [comment]
@JoneWeng 好的 ，谢谢。  

ps ：各位大佬要是知道的 愿意告知我的  麻烦@我一下 。 
aivin666@qq.com
