### ISSUE TITLE
播放flv格式的视频, 读取到的总时长相差比较大

### ISSUE THREAD

**Issue by hike2008** [pili-engineering/PLDroidPlayer#289]
时间长的可能回相差一半就停止播放了

**Comment by Jhuster** [comment]
@hike2008 在线视频还是文件，地址给下

**Comment by hike2008** [comment]
http://playback.lvmengya.com/lvshang/ab4f22ba-f60c-46ac-ba2f-986d3421043a/2016/09/24/10.35.34.496.flv  比如这个
