### ISSUE TITLE
com.pili.pldroid.player.common.Util#isLiveStreaming

### ISSUE THREAD

**Issue by nguyenvancuongit** [pili-engineering/PLDroidPlayer#29]
I see that on com.pili.pldroid.player.common.Util#isLiveStreaming we have:

return url.startsWith("rtmp://") || url.endsWith(".m3u8");

i think endsWith(".m3u8") is not alway true. am i wrong?

should we change to "contain"?

**Comment by jpxiong** [comment]
I will open related API next version.

**Comment by jpxiong** [comment]
V1.1.4 had been fixed the issue.

**Comment by nguyenvancuongit** [comment]
@jpxiong thanks for working on a small issue
