### ISSUE TITLE
KEY_LIVE_STREAMING 直播流累积延迟

### ISSUE THREAD

**Issue by 751811032** [pili-engineering/PLDroidPlayer#290]
KEY_LIVE_STREAMING 直播流设置这个参数 =1的时候就播放不了。不设置就可以播放，但是有累积延迟(延时)。

**Comment by Jhuster** [comment]
@751811032 流地址发出来看看。

**Comment by 751811032** [comment]
rtmp://96.9.95.77/live/bbbtest

**Comment by Jhuster** [comment]
@751811032 播放不了，建议先用 ffplay 播放试试。

**Comment by 751811032** [comment]
但是不设置 KEY_LIVE_STREAMING(默认为0)的却可以播放。就是会有累积延迟。我拿ijk试试。我试了很多rtmp流都有这个问题。

**Comment by Jhuster** [comment]
@751811032 建议测试 `rtmp://live.hkstv.hk.lxdns.com/live/hks`，排除流本身的原因
