### ISSUE TITLE
局域网RTMP播放问题

### ISSUE THREAD

**Issue by lijunsxr123** [pili-engineering/PLDroidPlayer#294]
播放一个无线路由器搭建局域网，电脑OBS发RTMP直播流，用PLDroidPlayerDemo在Android手机上播放，播放器播放不了，报错log：
09-13 12:17:47.638 30792-30985/com.pili.pldroid.playerdemo E/IJKMEDIA: Server error: Play stream error
09-13 12:17:47.638 30792-30985/com.pili.pldroid.playerdemo E/IJKMEDIA: rtmp://192.168.31.200:1935/shortcut/OjnSsOMvb38gv/OjnSsOMvb38gv: Operation not permitted
09-13 12:17:47.638 30792-30985/com.pili.pldroid.playerdemo E/pldroid-player-native: failed to open input : 1247 ms !

**Comment by lijunsxr123** [comment]
播放流地址rtmp://192.168.31.200:1935/shortcut/OjnSsOMvb38gv/OjnSsOMvb38gv

**Comment by Jhuster** [comment]
@lijunsxr123 建议你先保证 Server 是正常的，用 ffplay 、VLC 或者在电脑上用 `http://www.cutv.com/demo/live_test.swf` 先播放一下，看看能否播放出来。

**Comment by lijunsxr123** [comment]
手机上其他播放器可以播放。用mxpalyer播放正常。

**Comment by lijunsxr123** [comment]
无线路由器配置局域网，不接入外网

**Comment by Jhuster** [comment]
@lijunsxr123 从 log 来看，是：“Server error: Play stream error” ，看看服务器日志
