### ISSUE TITLE
只适配armeabi会有问题吗？

### ISSUE THREAD

**Issue by BradleyWang** [pili-engineering/PLDroidPlayer#297]
准备使用，但是我们现在的工程有本地库且只提供了armeabi这一个abi，我只用armeabi这一个abi，其他的都兼容模式运行会有什么问题吗？

**Comment by Jhuster** [comment]
既然你们有本地库只有 armeabi ，那么你们只能选择只用 armeabi 了。至于兼容性和问题，建议 Google 下。
