### ISSUE TITLE
本地的 .mp4  文件 编解码器类型为 mpeg-4 Video ,是否 不支持播放

### ISSUE THREAD

**Issue by luketang3** [pili-engineering/PLDroidPlayer#298]
本地的 .mp4 文件,
用的解码方式是 软解码,
编解码 格式为h.264 能正常播放， 
mpeg-4 Video 就不能播放了，
没有抛出异常，请问 是不是不支持 mpeg-4 Video?

**Comment by Jhuster** [comment]
嗯，是的，不支持

**Comment by luketang3** [comment]
了解了，谢谢
