### ISSUE TITLE
PLVideoTextureView播放本地视频黑屏

### ISSUE THREAD

**Issue by caicai123** [pili-engineering/PLDroidPlayer#299]
PLVideoTextureView播放本地MP4， 结果是黑屏的     设置是跟demo一样的   我debug后发现onSurfaceCreated一只没有回调   不知道原因出在哪了   急救！！！

**Comment by caicai123** [comment]
已经找到原因了   关闭了硬件加速

**Comment by yuger** [comment]
我也碰到这个问题，找了大半天。

**Comment by Jhuster** [comment]
@yuger 本地视频是什么格式

**Comment by chinaminiren** [comment]
没有开启硬件加速 TextureView 的回调不会调用

**Comment by yuger** [comment]
@Jhuster MP4, android:hardwareAccelerated="true"才能用PLVideoTextureView，否则黑屏，不会报错。
