### ISSUE TITLE
有哪个方法可以获取视频的方向的吗

### ISSUE THREAD

**Issue by SWwei** [pili-engineering/PLDroidPlayer#300]

**Comment by Jhuster** [comment]
`OnInfoListener.MEDIA_INFO_VIDEO_ROTATION_CHANGED`

**Comment by 252830311** [comment]
请问这个要怎么使用呢

**Comment by qssq666123** [comment]
请问具体如何使用呢，比如我的播放器在全屏的时候当检测到竖屏的视频自动给他旋转，因为视频已经是竖立了，也就是非正常的视频。。。需要判宽高的那种
