### ISSUE TITLE
关于getBufferPercentage（）的问题

### ISSUE THREAD

**Issue by CzwAthou** [pili-engineering/PLDroidPlayer#301]
如果播放的是本地的视频，个人觉得这个方法返回的数值是不是应该为100呢？  而不是始终为0

**Comment by Jhuster** [comment]
@caicai123 本地视频的话， `AVOptions.KEY_LIVE_STREAMING` 设置的是 0 吧 ？

**Comment by caicai123** [comment]
@Jhuster 是的   播放本地视频   不是直播  所以设置的0

**Comment by Jhuster** [comment]
@caicai123 `getBufferPercentage()` 代表着已经读取和缓冲的字节占整个文件的字节百分比，本地文件如果不大的话，应该是很快就缓冲完毕，因此是 100

**Comment by caicai123** [comment]
@Jhuster 嗯  你说的是对的  但是实际是返回的结果始终为0

**Comment by Jhuster** [comment]
@caicai123 我刚刚专门又验证了一遍，`getBufferPercentage()` 不是 0 啊，一直在增加啊。你跑 demo，选择 PLVideoViewActivity 测试，选择 `点播`，你看看进度条是否在走，进度条就是根据 `getBufferPercentage()` 往前走，如果一直是 0 ，就不会走动

**Comment by caicai123** [comment]
![image](https://cloud.githubusercontent.com/assets/5925762/18734842/d12ca24c-80aa-11e6-89c1-c1d066b3c2fb.png) 我实在mediacontroller的setprogress内检测的  每次返回的数据都是0

**Comment by Jhuster** [comment]
@caicai123 确定 AVOptions.KEY_LIVE_STREAMING 设置的是 0 吗？我这边用 demo 测了 getBufferPercentage 不是 0，一直在增加
