### ISSUE TITLE
怎么获取原视频高度？

### ISSUE THREAD

**Issue by melody1993** [pili-engineering/PLDroidPlayer#302]

**Comment by Jhuster** [comment]
@melody1993 `OnVideoSizeChangedListener.onVideoSizeChanged(PLMediaPlayer mp, int width, int height)`

**Comment by melody1993** [comment]
通过什么调取的？不能通过PLVideoTextureView吧

**Comment by Jhuster** [comment]
@melody1993 `setOnVideoSizeChangedListener`
