### ISSUE TITLE
我们这边播放的时候有部分链接怎么都播放不了

### ISSUE THREAD

**Issue by horryw** [pili-engineering/PLDroidPlayer#303]
我们这边播放的时候有好些个链接怎么都播放不了，同样的设备同样的网络条件，用其他的App就可以播放（比如UC浏览器）

比如如下这个测试链接：
http://vshare.ys7.com:80/openlive/498570005_1_1.m3u8?ticket=eWNxK3dTc2VpS29mVkVnbXBuOEIzTmxJYy9oT0hFbzNMbW9ra0ljbS9xWT0kMSQyMDE3MDkxMzAwMDAwMCQxNDczNjA5NjAwMDAwJDE1MDUyMzIwMDAwMDAkMSQkJCQwZjc1MWM2N2ZhOTU0MzViOGMyOGIyY2Q1ZGJiYzZkOSQ=

**Comment by BradleyWang** [comment]
为了排除是我只引用armeabi所造成的兼容性原因，我又用demo来跑，也是同样的现象

**Comment by Jhuster** [comment]
@BradleyWang 你们的这个流有点不正常，用 `ffplay` 播放要等很久才出图像，建议仔细分析一下这个流，初步推测，前几个 ts 切片有问题。
