### ISSUE TITLE
PLMediaPlayerActivity我进入播放页面后，点击播放才开始播放，这个怎么设置？

### ISSUE THREAD

**Issue by danniu1314** [pili-engineering/PLDroidPlayer#306]
我将mMediaPlayer.prepareAsync()写到开始点击事件里面，这个时候未点击开始，进度条开始转，点了开始后，开始播放，点击停止会崩溃。我该如何设置这个进入后不自动播放，点击才开始播放

**Comment by danniu1314** [comment]
还有我先是半屏播放，然后全屏后，视频大小还是和之前半屏的时候尺寸一样大，上下边不能布满屏幕。这个该如何设置

**Comment by Jhuster** [comment]
@danniu1314 `PLMediaPlayer` 是需要你自己实现全屏播放的，demo 只是简单演示了基于 SurfaceView 的用法。`PLVideoTextureActivity` 进度条什么问题，进度条源码在 widget 目录，可以自行修改，或者自己实现一个进度条
