### ISSUE TITLE
关于视频快速关闭启动卡顿的问题的bug?

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#307]
我发现在用硬件解码播放本地视频的时候,刚开始播放很流畅快速退出再播放会出现卡顿的问题,,通过AS监听发现流畅播放的时候CPU占有率是5%.而卡顿之后CPU占用率高达60%甚至80%左右.这个时候就会卡顿,除非完全杀死应用,不然会一直卡顿下去,请问这个问题是怎么回事?我使用的是机顶盒,CPU性能不高.用的PLVideoView.

**Comment by Jhuster** [comment]
@yanxiandroid 多谢反馈，我们看看先。

**Comment by yanxiandroid** [comment]
@Jhuster 能尽快修复该bug吗?

**Comment by yanxiandroid** [comment]
@Jhuster 我升级到1.4版本了,该版本已经解决低性能机顶盒播放卡顿的问题了.感谢..
