### ISSUE TITLE
播放ip与域名效果不同的问题

### ISSUE THREAD

**Issue by 751811032** [pili-engineering/PLDroidPlayer#308]
同一个视频源，一条是原视频线路，一条是cdn的线路。原视频线路第一帧出现在两秒左右，cdn加速后的线路第一帧出现要十多秒。加了dns解析后大概五六秒。但是网页端的播放器都是两秒。这个会与播放器的设置有关吗。

**Comment by longbai** [comment]
能麻烦给下两条线路的域名，以及用户所在区域及运营商，以及解析到的IP，如果是使用七牛的服务 麻烦提下工单。

**Comment by 751811032** [comment]
rtmp://110.92.64.79/live        rtmp://gdvideo.fc.llnwd.net/live    前面那个是比较快的地址，后面那个是cdn加速后的地址(相对较慢的地址)。区域不确定，有浙江的，还有柬埔寨的，都试过，都是一样的。这个是否是域名与ip的关系。

**Comment by Jhuster** [comment]
@751811032 浏览器有域名缓存，清空浏览器的 cache 播放后面的地址试试速度。这个问题建议反馈给 CDN 提供商

**Comment by 751811032** [comment]
好的，谢谢
