### ISSUE TITLE
OnInfoListener能不能监听到从直播未开始到直播开始的状态变化？

### ISSUE THREAD

**Issue by 6Weiqi** [pili-engineering/PLDroidPlayer#309]

**Comment by Jhuster** [comment]
@6Weiqi 看 WiKi 文档，第一帧视频和第一帧音频渲染成功后，有回调。

**Comment by Jhuster** [comment]
@6Weiqi `App` 本身不应该如你描述那样去设计，列表中的项目应该是直播开始才能显示在列表中，然后点击进去播放，如果收到 onError 证明播放不成功，如果不做重连的话，就应该关闭播放器关闭页面。

**Comment by 6Weiqi** [comment]
@Jhuster 感谢，问题解决了
