### ISSUE TITLE
Rotate Video while playing in PLDroidPlayer

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidPlayer#31]
The videos captured using MediaRecorder have metadata Rotate=90 or 270. In the Android Video player the videos are properly oriented as per the metadata, but in PLDroidPlayer, they are not.

How can we rotate the video while playing in PLDroidPlayer?

**Comment by jpxiong** [comment]
Could you please provide the file ?

**Comment by gouravd** [comment]
mp4 file uploaded as png in #35
