### ISSUE TITLE
视频播放 很慢 很卡（dns的问题？）

### ISSUE THREAD

**Issue by zaxcler** [pili-engineering/PLDroidPlayer#310]
连我们公司的网的话，看视频很卡，用手机流量的话 还是很快的

**Comment by wenlian2035** [comment]
同样有遇到此问题

**Comment by axuan2015** [comment]
同样的问题

**Comment by Jhuster** [comment]
公司的网络，多人共享，不稳定导致卡顿，是很常见的现象

**Comment by qssq** [comment]
为什么 会阻塞ui?播放的时候 有很大概率阻塞ui.

**Comment by Jhuster** [comment]
@qssq 底层在线程中异步在读数据、解码和渲染，不会阻塞 UI，你看到播放界面没有变化，可能是网络原因导致视频卡住没有更新，但不影响 UI 点击

**Comment by qssq** [comment]
不知道，反正总是卡死了。奇怪了。以前的直播也是这样的，后面 的1.2.3是没问题了 。现在不知道是不是又有什么毛病了。 以前的卡死毛病是setvideopath是需要在子线程调用。

**Comment by qssq** [comment]
stopstack 不是主线程的吧 ，会导致无响应啊。我点击一个小窗口的关闭按钮就无响应了。

**Comment by Jhuster** [comment]
@qssq 一般是因为 DNS 解析卡死导致 ANR，建议开启 DNS 解析优化：`https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5`

**Comment by qssq** [comment]
plvideoview如何和 viewgroup容器分离呢？ 我现在开启了内存泄漏检测，plvideoview内存泄露。

**Comment by qssq** [comment]
可是理论上不应该anr呀，这问题是不是。

**Comment by qssq** [comment]
我在直播群里截图了，可以帮我看看嘛？

**Comment by qssq** [comment]
ao.tv I/art: Thread[7,tid=20874,WaitingInMainSignalCatcherLoop,Thread*=0x559041a200,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
10-08 16:48:43.652 20863-20874/com.buyao.tv I/art: Wrote stack traces to '/data/anr/traces.txt'
10-08 16:48:46.222 20863-20878/com.buyao.tv A/MobUncaughtExceptionHandler: tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize() timed out after 10 seconds
                                                                           java.util.concurrent.TimeoutException: tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize() timed out after 10 seconds
                                                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                               at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:870)
                                                                               at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                                               at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by Jhuster** [comment]
@qssq 先跑跑 demo 看看是否也是一样，另外，建议开启 DNS 解析优化：https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5

**Comment by qssq** [comment]
先跑demo这句话我听过 n遍了，之后还不是你们的问题，比如那个audiomanager的泄露，有些玩意没必要跑demo浪费时间了。

**Comment by qssq** [comment]
我还是换回去把， 最新的 卡顿阻塞ui太严重。还是 1.2.3好使

**Comment by qssq** [comment]
换回去还是这样。。。。。 只要一直在加载中 就会阻塞ui，内存泄露 ，  需求是这样的，详情页面的videoview和 mediacontrol 在关闭的时候 我从父view移除然后在列表界面的小视频窗口显示，结果没加载出来的时候 会导致 卡死问题严重。然后关闭 小视频窗口会调用videostopstack()结果要卡几秒。 但是如果视频是正常在播放就不会，您说的 设置dns 也不是权宜之计啊，我这是在线视频 不是直播，设置dns 顶多是网络快了，那么是用3g网络 或者本身是我们这边服务器有点卡呢？难道就应该让它无响应吗？

**Comment by qssq** [comment]
也许getparent().removeView() 然互在列表插入的方法行不通了，里面维护的还是之前的 context能动态创建吗？

**Comment by qssq** [comment]
动态创建又不阻碍播放进度。

**Comment by onlike** [comment]
@qssq 问下这个需求你做出来了吗 ？ 最后采用了什么方案？

**Comment by qssq** [comment]
@onlike  做出来了, 反射把 泄露的地方移除就行了。
