### ISSUE TITLE
请问1.2.3之后的pldroidplayer到底改了什么？

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#312]
我升级到目前的1.3.2视频播放不了了。 我替换了 jar和 jni文件 。

**Comment by qssq** [comment]
java.lang.SecurityException: Neither user 10696 nor current process has android.permission.WAKE_LOCK.
                                                                at android.os.Parcel.readException(Parcel.java:1546)
                                                                at android.os.Parcel.readException(Parcel.java:1499)
                                                                at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:348) 退出之后一个小窗口的 start()却能正常播放了，但是还抛出这个异常。

**Comment by qssq** [comment]
权限加了。 之前 是不需要调用start()方法的吧。

**Comment by qssq** [comment]
mVideoView.setVideoPath(url);//这个方法以前 还阻塞ui的，那么现在还阻塞ui吗？

**Comment by Jhuster** [comment]
@qssq 确定下面的权限加了 ？

```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

跑过 demo 没 ？手机什么系统版本 ？

**Comment by qssq** [comment]
额，sorry，我太相信百度了，百度说的不是这个权限 - - 。 那么 后面问的问题呢？setvideopath 已经不会再自动播放了吧需要再调用start()对吧，另外也 不需要开子线程 了吧？

**Comment by Jhuster** [comment]
@qssq 这个方法不会阻塞 UI

**Comment by Jhuster** [comment]
@qssq `https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.1`  options.setInteger(AVOptions.KEY_START_ON_PREPARED, 1);  决定是否自动播放

**Comment by qssq** [comment]
嗯好的，那我就不开子线程了，反正之前是阻塞ui的，后面你们说这个开在子线程 果然 就不卡了。

**Comment by qssq** [comment]
=  =

**Comment by qssq** [comment]
那多个参数的配置 呢options.setInteger(AVOptions.KEY_START_ON_PREPARED, 1);  KEY_MEDIACODEC 怎么个与法

**Comment by qssq** [comment]
懂了。

**Comment by qssq** [comment]
WAKE_LOCK 有了这个 东西，那我还需要手动管理锁屏 功能吗？之前我可是在activity的生命周期里面手动 管理的。   this.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

**Comment by qssq** [comment]
最新版本有这个权限了，俺么我还需要手动管理播放的时候屏幕常亮吗？

**Comment by Jhuster** [comment]
@qssq 需要。这个权限 SDK 用于后台播放，并不是管理屏幕亮灭。

**Comment by qssq** [comment]
设置了KEY_START_ON_PREPARED =1 并不能自动播放呀，而且 导致我原来的流程都走不通了 无响应。

**Comment by qssq** [comment]
我是详情调用setvideopath,然后在详情页面 并没有播放 ，然后关闭后 吧整个view发送到列表，在列表播放，这时才能播放。。

**Comment by qssq** [comment]
现在是还是不能自动播放，但是刚刚有没有出现无响应了，搞不懂 么子情况

**Comment by qssq** [comment]
嗯 ，好了，原来是 我设置了这个就不能再调用start()反而导致不播放了 - -

**Comment by qssq** [comment]
搞不懂了，感觉没有1.2.3好，我卸载了重新部署一遍 又不能自动播放了我 快崩溃了。 然后有 是无响应 之后又正常了， 难道是编译器出现了诡异问题。   我快疯了。怎么会这么不稳定啊。

**Comment by qssq** [comment]
可能是即时编译问题我重新 把play库的build文件夹删除了貌似没有毛病了。  不过
