### ISSUE TITLE
一个页面的videoview怎么在关闭后传递给另外一个页面 但是不会导致内存泄露？也很流畅的传递过去

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#314]
之前是直接把这个view传递给另外一个activity,但是activity所持有的上下文内存泄露了。        
尝试用下面方法
FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        videoContainer.addView(plVideoView, 0, layoutParams);
   又改怎么做呢？

另外 视频一直在加载的时候 调用stopstack()会卡顿

**Comment by qssq** [comment]
唉，没办法解决吗？我重新new了一个不行。

**Comment by qssq** [comment]
MediaController mediaController = event.getMediaController();
        PLVideoView plVideoView = new PLVideoView(getFragmentActivity());
        mediaController.setMediaPlayer(plVideoView);
        plVideoView.setMediaController(mediaController);
        plVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);
        AVOptions options = new AVOptions();
        //解码方式，codec＝1，硬解; codec=0, 软解
        options.setInteger(AVOptions.KEY_MEDIACODEC, 0); // 1 -> enable, 0 -> disable
        // 是否自动启动播放，如果设置为 1，则在调用 `prepareAsync` 或者 `setVideoPath` 之后自动启动播放，无需调用 `start()`
// 默认值是：1
        options.setInteger(AVOptions.KEY_START_ON_PREPARED, 1);
//        options.setInteger(AVOptions.KEY_START_ON_PREPARED, 1);
        plVideoView.setAVOptions(options);
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        videoContainer.addView(plVideoView, 0, layoutParams);
        plVideoView.setOnErrorListener(this);
        plVideoView.setOnSeekCompleteListener(this); 这样写并没有图像传输到新的plvideoview

**Comment by qssq** [comment]
唉。

**Comment by Jhuster** [comment]
@qssq 不建议你这样用，View 不应该在多个 Activity 之间传递

**Comment by qssq** [comment]
嗯 啊，但是怎么解决呢？我用new的方法 呢 则无法 实现  传递呀。 可需求就是这样的。这就尴尬了，如果像之前 是一个activity写的app这个问题 倒没什么。

**Comment by qssq** [comment]
new的方法 重新设置一遍 mediactronl难道连 setvideopath也要重新设置一遍吗？有没有办法 你们的mediatactrol继承的类可以实现 一种view绑定与解绑机制。解决这个麻烦的问题。

**Comment by qssq** [comment]
我想反射把context修改成当前的，可是 那个playview继承太多了，怎么个反射父类的父类的父类法？

**Comment by qssq** [comment]
onComplete()是 缓存完成吧。

**Comment by qssq** [comment]
大神在吗? plvideoview传递到另外一个activity有没有办法销毁原来持有的activity 呀。

**Comment by Jhuster** [comment]
这个问题可以 close 了，没有你这样的用法。View 不能传递，如果跳转 Activity 的时候希望保持播放状态，可以自己用 PLMediaPlayer 来做。

**Comment by qssq** [comment]
可是又这样的需求啊。   那么你说的这个有demo吗、

**Comment by Jhuster** [comment]
参考 demo 里面的 PLMediaPlayerActivity.java 文件，跳转的话，保持 `PLMediaPlayer` 对象不销毁，每个 Activity 都有一个 `SurfaceView` ，相当于跳转后在不同的 `SurfaceView` 上 “渲染” 图像。

**Comment by qssq** [comment]
好的，谢谢 我有空尝试下。

**Comment by qssq** [comment]
da但是这个demo的控制器怎么和 mediacontrol绑定额。 demo里面没有，这不，我都得重写啊？

**Comment by qssq** [comment]
成功反射 哈哈， 照样不内存泄露
