### ISSUE TITLE
之前使用的是1.2.2,现在想升级到1.3.2最新,关于So文件的问题.!~~~

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#318]
之前为了减小Apk的体积,采用动态加载的方式将So注入,但是现在想升级成最新版本,下载Demo时发现,So大小变化了这个问题.

那么问题来了:
如果是在旧渠道下载我们的Apk会兼容1.3.2的So文件么.

**Comment by Vander-liu** [comment]
@Jhuster 求助.

**Comment by Vander-liu** [comment]
还有另外问一下:compile 'com.qiniu.pili:pili-android-qos:0.8.+' 这个依赖是干嘛的.

**Comment by Jhuster** [comment]
建议每个版本的 jar 和 so 配套使用。

**Comment by Jhuster** [comment]
我们把一些 QOS 信息的抓取和处理逻辑封装在这个 `compile 'com.qiniu.pili:pili-android-qos:0.8.+'` 工程中了。
