### ISSUE TITLE
无域名的ip地址，连接失败

### ISSUE THREAD

**Issue by sdvye** [pili-engineering/PLDroidPlayer#320]
测试地址是自己布置的ip地址，没有域名指向，初始回调ERROR_CODE_IO_ERROR，IO异常，无法连接，但是h5和其他平台是可以正常拉流的。请问是不是需要设置什么还是本身就不支持无域名解析的ip地址？

**Comment by Jhuster** [comment]
@sdvye 支持 IP 地址的播放，你先在命令行下用 ffplay 播放你的流试试
