### ISSUE TITLE
自定义controller

### ISSUE THREAD

**Issue by laijunxi** [pili-engineering/PLDroidPlayer#321]
请问为什么我用的xml布局，加载出来只有上面的按钮显示，seekbar显示不出来。（v7包下的seekbar）

**Comment by Jhuster** [comment]
@laijunxi 由于是你自己写的 controller，需要你自己结合你写的 xml 文件以及 controller 的代码来分析了。

**Comment by laijunxi** [comment]
我直接用seekbar可以显示，用v7包下的seekbar不能显示
