### ISSUE TITLE
播放器报onError   errorcode = -104

### ISSUE THREAD

**Issue by fattylove** [pili-engineering/PLDroidPlayer#322]
dv:SM801
error_code:-104
error_msg:音频播放异常,错误代码->-104
error_time:2016-10-11 14:33:32
error_type:error
error_url:http://igetoss.cdn.igetget.com/aac/201610/05/64000_201610051657132603976953.m4a?OSSAccessKeyId=jNaxWIooBUXUVPJM&Expires=1478694006&Signature=a3XfzZvwEc33G4zm8tL7VeIzvK4%3D

dv:SM801
error_code:-104
error_msg:音频播放异常,错误代码->-104
error_time:2016-10-12 19:39:34
error_type:error
error_url:http://igetoss.cdn.igetget.com/aac/201609/30/64000_201609301819140998145790.m4a?OSSAccessKeyId=jNaxWIooBUXUVPJM&Expires=1478859609&Signature=uRDm296TASDPyBXwU1ty%2F%2BZMsGU%3D

error_code:-104
error_msg:音频播放异常,错误代码->-104
error_time:2016-10-10 20:50:01
error_type:error
error_url:http://igetoss.cdn.igetget.com/aac/201610/09/64000_201610091752348581575433.m4a?OSSAccessKeyId=jNaxWIooBUXUVPJM&Expires=1478694006&Signature=%2BokdVjCC7lghhoxv3%2F2LSBvd9NY%3D

error_code:-104
error_msg:音频播放异常,错误代码->-104
error_time:2016-10-11 00:17:24
error_type:error
error_url:http://igetoss.cdn.igetget.com/aac/201605/08/64000_201605081127556809844268.m4a?OSSAccessKeyId=jNaxWIooBUXUVPJM&Expires=1478690406&Signature=hxahWFJ8vcVg6dxOzUme06Jj34U%3D

error_code:-104
error_msg:音频播放异常,错误代码->-104
error_time:2016-10-10 20:50:01
error_type:error
error_url:http://igetoss.cdn.igetget.com/aac/201610/09/64000_201610091752348581575433.m4a?OSSAccessKeyId=jNaxWIooBUXUVPJM&Expires=1478694006&Signature=%2BokdVjCC7lghhoxv3%2F2LSBvd9NY%3D

**Comment by Jhuster** [comment]
@fattylove 开始播放就报错吗？ 能否先用 ffplay 播放验证下，是否有报错。

**Comment by fattylove** [comment]
我描述一下：
“得到APP”使用的PLMediaPlayer，使用的点播功能，播放的m4a格式的aac文件，存储在阿里云的oss上，做了cdn。之前播放过程中中断，反馈给七牛的技术人员，他们说是TCP断开的连接，我们让阿里云把TCP的连接超时修改成了60分钟，大部分用户反馈已经好了，但是最近又出现中断问题，后台打点日子报的错误如上（-104）错误，阿里云的同学用ffplay验证了，是没问题的。但是使用PLMediaPlayer依然存在概率性的中断。但是现在无法解决到底是何处的问题？

**Comment by Jhuster** [comment]
@fattylove -104 是一个典型的 socket error，错误描述是：“Connection reset by peer”，通常表示对端(服务器端) 程序没有关闭 socket 就直接退出了，从播放器的角度，没有办法去避免服务器端异常关闭 socket

**Comment by fattylove** [comment]
那如何减少 PLMediaPlayer的最大连接数呢？

**Comment by Jhuster** [comment]
@fattylove 这个连接服务器的数量完全取决于你们 App 同时播放的并发量，播放器SDK本身没有什么可做的，你只需注意在退出播放的时候，调用了 `stopPlayback()` 。
