### ISSUE TITLE
seekTo播放问题 

### ISSUE THREAD

**Issue by lizhifeng-sky** [pili-engineering/PLDroidPlayer#323]
我用PLMediaPlayer在播放 网络获取的hls时 seekTo能用吗？
 mMediaPlayer.setOnSeekCompleteListener(new PLMediaPlayer.OnSeekCompleteListener() {
                @Override
                public void onSeekComplete(PLMediaPlayer plMediaPlayer) {
//                    Toast.makeText(PLMediaPlayerActivity.this,"seekto完成",Toast.LENGTH_SHORT).show();
//                    plMediaPlayer.start();
                }
            });
会回调 但是会重新播放 我是不是哪里写错了？hls不能seekto吗？还是用其他的方式start？我对hls了解不多

**Comment by Jhuster** [comment]
你的 HLS 是直播流还是点播？只有文件和点播才支持 seek，需要配置 options.setInteger(AVOptions.KEY_LIVE_STREAMING, 0);

**Comment by lizhifeng-sky** [comment]
点播

**Comment by lizhifeng-sky** [comment]
mAVOptions.setInteger(AVOptions.KEY_PREPARE_TIMEOUT, 10 * 1000);
        mAVOptions.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 10 * 1000);
        // Some optimization with buffering mechanism when be set to 1
        mAVOptions.setInteger(AVOptions.KEY_LIVE_STREAMING, 0);

**Comment by Jhuster** [comment]
你用 demo 选择 `PLVideoViewActivity` 和 `点播`，输入一个 hls 文件地址，然后 `seek` 看看吧

**Comment by lizhifeng-sky** [comment]
我demo 用的是PLMediaPlayerActivity

**Comment by lizhifeng-sky** [comment]
但是demo中没测试  我先测试下试试

**Comment by lizhifeng-sky** [comment]
不行。。。seekTo虽然完成了回调 但是不会继续播放    会重新开始
PLVideoViewActivity 点播 软解

**Comment by Jhuster** [comment]
没有改 demo 代码吧？我们做过测试，你用 vlc 等播放器，先验证一下点播流本身是否正常。

**Comment by lizhifeng-sky** [comment]
http://ocgig6vo9.bkt.clouddn.com/48/3/1476264369403_dst  这是我的视频源 你看看跟视频源有没有关系 第一次用hls

**Comment by lizhifeng-sky** [comment]
demo没改  只是选择了点播模式

**Comment by lizhifeng-sky** [comment]
我改的是视频源链接

**Comment by lizhifeng-sky** [comment]
vlc我装不了 他说只支持armv7

**Comment by lizhifeng-sky** [comment]
在吗？我给你微信发了一个视频  你看看可好  PLDroidVideoView我没改过

**Comment by Jhuster** [comment]
@lizhifeng-sky 可能是你的点播文件的问题，网上找个别的视频试试。

**Comment by lizhifeng-sky** [comment]
这个视频原本是MP4在服务端进行了转码

**Comment by Jhuster** [comment]
@lizhifeng-sky 你借台手机装个 VLC 或者 VPlayer 试试吧，应该排查下流本身是否转码有问题。

**Comment by lizhifeng-sky** [comment]
好的  谢谢你

**Comment by lizhifeng-sky** [comment]
我测试了 vlc和vpalyer都可以播放  但是快进或者快退都是不行的 这是应该是转码问题吧？

**Comment by Jhuster** [comment]
@lizhifeng-sky 再拖动进度条试试

**Comment by lizhifeng-sky** [comment]
他们的快进快退就是进度条  我拖动进度条 就直接重新播放了

**Comment by Jhuster** [comment]
@lizhifeng-sky 嗯，可以断定了，就是码流本身的问题。

**Comment by lizhifeng-sky** [comment]
谢谢  纠结了好久
还有一个问题  如果我不停的重复进入播放界面会出现卡顿

**Comment by lizhifeng-sky** [comment]
这个码流你懂吗？
