### ISSUE TITLE
释放资源release放在子线程或许会更好吧？

### ISSUE THREAD

**Issue by lizhifeng-sky** [pili-engineering/PLDroidPlayer#325]
release 释放资源耗时比较长 容易造成界面卡顿 可以考虑放在子线程

**Comment by Jhuster** [comment]
@lizhifeng-sky 最新版已经对 release 做了优化

**Comment by lizhifeng-sky** [comment]
我用的是1.3.2

**Comment by Jhuster** [comment]
@lizhifeng-sky 1.3.2 耗时还是很久吗？什么型号的手机，是否有统计时间？

**Comment by lizhifeng-sky** [comment]
2s  小米5   6.0 系统  我是放在子线程处理的

**Comment by lizhifeng-sky** [comment]
返回前一个界面时还会卡顿一会

**Comment by Jhuster** [comment]
@lizhifeng-sky 需要加上 DNS 解析优化，https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5

**Comment by lizhifeng-sky** [comment]
好的  我看看

**Comment by lizhifeng-sky** [comment]
dns解析不支持hls吗？文档说1.3.0不支持  现在支持吗

**Comment by Jhuster** [comment]
@lizhifeng-sky 目前还不支持，按照文档把 dns 预解析服务打开即可，遇到 HLS 协议，SDK 内部会自动跳过预解析。

**Comment by hike2008** [comment]
加了dns解析, 首次能解析; 再次打开无法播放, 是什么设置错了么;

**Comment by Jhuster** [comment]
@hike2008 对比参考下 demo，另外，报错是什么 ？

**Comment by hike2008** [comment]
具体的我再定位测试一下, 有问题再开issue反馈吧

**Comment by lizhifeng-sky** [comment]
在吗？我能问你个问题吗？

**Comment by Jhuster** [comment]
@lizhifeng-sky 直接发出来吧

**Comment by lizhifeng-sky** [comment]
你在对m3u8解析时是怎么处理的？

**Comment by lizhifeng-sky** [comment]
我用原生的videoview播放
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.6.7)
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=319060,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=304x128
oceans_aes-audio=65000-video=236000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=461100,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=384x160
oceans_aes-audio=65000-video=370000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=674160,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=544x224
oceans_aes-audio=65000-video=571000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=999580,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=736x304
oceans_aes-audio=65000-video=878000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1489300,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=960x400
oceans_aes-audio=65000-video=1340000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2233420,CODECS="mp4a.40.2,avc1.66.31",RESOLUTION=1264x528
oceans_aes-audio=65000-video=2042000.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=68900,CODECS="mp4a.40.2"
oceans_aes-audio=65000.m3u8
这个是能播放

**Comment by lizhifeng-sky** [comment]
但是这种原生的播放器就不能播放了
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:13
#EXTINF:12.233333,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000000.ts
#EXTINF:8.333333,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000001.ts
#EXTINF:10.800000,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000002.ts
#EXTINF:12.733333,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000003.ts
#EXTINF:6.666667,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000004.ts
#EXTINF:11.200000,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000005.ts
#EXTINF:8.333333,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000006.ts
#EXTINF:0.666667,
/5pa40v0Xi7j-KrvdaFKy4NWEZDY=/Fo8CZKbP3DByhO_UVF2YgCkrEUWv/000007.ts
#EXT-X-ENDLIST

**Comment by lizhifeng-sky** [comment]
需要怎样的处理

**Comment by lizhifeng-sky** [comment]
有篇博客说第一个能播的 他还存在一个类似第二个m3u8文件

**Comment by lizhifeng-sky** [comment]
....
