### ISSUE TITLE
当引用过多so时，软解码播放视频CPU占用高

### ISSUE THREAD

**Issue by StormBlue** [pili-engineering/PLDroidPlayer#326]
因应用中其它功能使用了很多第三方sdk，引用了很多的so文件。
我在做完视频播放后发现CPU占用过高，后来我测试了下，如果只引用PLDroidPlayer自身的文件，在xiaomipad2上用软解码播放200mb的5分钟视频，CPU占用在35%左右；如果引入应用所使用的其它依赖so文件（25个左右，基本都是 捷通华声 的语音识别依赖），播放同样视频软解码CPU占用在80%左右。硬解码俩种情况基本都在10%以下。
利用traceview分析CPU方法占用，也没看出两种情形下有什么不同，想请教一下，这个是什么原因导致得，可有结局得方法。

**Comment by Jhuster** [comment]
@StormBlue 语音识别模块一般会在后台进行大量的耗 CPU 的计算工作，这个跟 PLDroidPlayer 无关。

**Comment by StormBlue** [comment]
是这样，后台没有启动任何操作，我是把so文件都直接拷贝到了PLDroidPlayerDemo项目的jniLibs文件中的。我随机找了一个so文件，拷贝了25个副本放到armeabi和armeabi-v7a中就会出现软解码CPU高占用的情况

**Comment by Jhuster** [comment]
@StormBlue 我觉得不会出现你描述的情况，随机拷贝到 jni 目录的 so 根本不会被 load，你再仔细测测和分析下吧。

**Comment by StormBlue** [comment]
最后测试发现，跟数量无关，有个so文件貌似不合法。我自己测试将任意一个文件后缀改为so，放入jnilibs中就会导致软解CPU占用过，原因还是不太清除。
