### ISSUE TITLE
MediaController能否不隐藏？

### ISSUE THREAD

**Issue by bunnyirsa** [pili-engineering/PLDroidPlayer#330]
在设置MediaController的时候，发现点击屏幕会自动隐藏，在外层无法取消该隐藏事件，请问有什么方法可以保持MediaController不隐藏？

**Comment by Jhuster** [comment]
@bunnyirsa 请自行修改 demo 里面的 MediaController 的源码，重点看 hide() 部分

**Comment by bunnyirsa** [comment]
我试过了，不行啊，hide（）全部都注释掉了都不行。。。

**Comment by Jhuster** [comment]
@bunnyirsa 确定把所有 hide, GONE 相关的都注释掉了？ debug 一下 MediaController 的源码吧

**Comment by bunnyirsa** [comment]
@Jhuster 我确定，hide、GONE相关源码全部都注释掉了，touch屏幕虽然不会消失，但是会闪烁一下，是不是动画原因？

**Comment by bunnyirsa** [comment]
是不是再jar包里面把这个隐藏的代码写死了？

**Comment by Jhuster** [comment]
@bunnyirsa 所以说，注释掉了还是有用的，SDK 会根据播放状态以及点击事件调用 `MediaController` 的 hide 方法。闪烁问题你再 debug 下吧，SDK 内部没有动画处理，都在`MediaController` 源码中 。
