### ISSUE TITLE
播放拖动进度条问题？

### ISSUE THREAD

**Issue by luolongchang** [pili-engineering/PLDroidPlayer#333]
使用了切片视频，我初始化播放器，跳到上次播放的进度的时候，为什么会从当前切片的首帧开始播放，而不是我当前所定位的位置点开始播放呢？例如：我的2分钟切片，拖到3:30时，会从2:01开始播放，而不是3:30开始播放？这个是什么问题？请求需要怎么解决？

**Comment by Jhuster** [comment]
@luolongchang 拖动的实现原理，就是查找最近的 I 帧，从现象来看，一般情况是 3:30 分不是 I 帧，而最近的 I 帧在 2:01，你可以分析下文件，把这附近的帧时间戳都打印出来看看。

**Comment by luolongchang** [comment]
你说的这个，不太明白啊！不论我是拖到某个位置，还是直接跳转到某个位置，这个播放器，播放的就会有切片处理的最大的间隔时间的一个误差，我也当了LOG，看了，确实是会回退！
