### ISSUE TITLE
dns缓存的问题

### ISSUE THREAD

**Issue by hike2008** [pili-engineering/PLDroidPlayer#334]
如果开启DNS缓存, 当播放路径中也包含domain时, 会同时替换两个domain, 导致播放出错:
即: rtmp://domain/domain/.....  这样的地址;

另外,  首屏秒开,  如何设置呢, wiki好像没找到相关的说明.

**Comment by Jhuster** [comment]
@hike2008 首屏秒开，只要 options 设置为 live_streaming 即可。 播放路径中含有 domain 的时候，log 发出来看看？

**Comment by hike2008** [comment]
uri的  path = xxxx.com/subpath;

完整的播放URL就是: rtmp://xxxx.com/xxxx.com/subpath

此时会解析成rtmp://ip/ip/subpath?domain=xxxx.com, 会替换所有的domian,

 应该是解析只替换首个domain, 解析成 rtmp://ip/path?domain=xxxx.com  即 rtmp://ip/domain/subpath?domain=xxxx.com才正确

**Comment by Jhuster** [comment]
@hike2008 嗯，这样的 URL 不太常见，的确是个问题，谢谢反馈，已记录。

**Comment by hike2008** [comment]
确实是这样, 不太常见, 但是由于存在这种情况, 亲的项目这部分代码也无法进行修改, 所以才来反馈 @Jhuster

**Comment by Jhuster** [comment]
@hike2008 嗯，多谢反馈，我们这边内部已经 fix 了，会在下个版本发布出来。
