### ISSUE TITLE
推出的视频流，观看的时候用这个能不能屏蔽掉画面只加载声音听声音，减少流量耗损。

### ISSUE THREAD

**Issue by danniu1314** [pili-engineering/PLDroidPlayer#335]
推流端推出来视频，这个播放器能将视频的画面和声音分开吗？有部分用户能看视频听声音，有些用户为了节省流量只听声音，不需要加载画面，如何去做呢？用的PLVideoTextureView

**Comment by Jhuster** [comment]
@danniu1314 这个需要推流的时候，音画分离，有一个播放 URL 专门只含音频流。
