### ISSUE TITLE
播放视频横竖屏问题

### ISSUE THREAD

**Issue by 252830311** [pili-engineering/PLDroidPlayer#339]
请问怎么获得视频播放的方向OnInfoListener.MEDIA_INFO_VIDEO_ROTATION_CHANGED,这个值一直不变

**Comment by 252830311** [comment]
请问OnInfoListener.MEDIA_INFO_VIDEO_ROTATION_CHANGED这个要怎么使用呢?

**Comment by tanhx2008** [comment]
private PLMediaPlayer.OnVideoSizeChangedListener mOnVideoSizeChangedListener = new PLMediaPlayer.OnVideoSizeChangedListener() {
        @Override
        public void onVideoSizeChanged(PLMediaPlayer plMediaPlayer, int width, int height) {
            Log.d(TAG, "onVideoSizeChanged: " + width + "," + height);
        }
    };

**Comment by tanhx2008** [comment]
用这个获取视频的宽和高
