### ISSUE TITLE
用nginx服务器时候，经常只有声音没有图像

### ISSUE THREAD

**Issue by zhangxyfs** [pili-engineering/PLDroidPlayer#34]
如题

**Comment by zhangxyfs** [comment]
使用1.1.3版本时候，大部分都是有声音没图像。改成1.1.2版本，问题解决..

**Comment by jpxiong** [comment]
可以提供一下有问题的链接吗？
请尝试将 `AVOptions.KEY_MEDIACODEC` 设置为 0，比如：
```
options.setInteger(AVOptions.KEY_MEDIACODEC, 0); // 1 -> enable, 0 -> disable
```

**Comment by gouravd** [comment]
I am having the same issue #27 

This happens even in 1.1.4 and even after AVOptions.KEY_MEDIA_CODEC, 0

**Comment by gouravd** [comment]
I have added additional information in issue #27
