### ISSUE TITLE
PLMediaPlayer.OnPreparedListener 结束了播放还是会黑屏一下才出画面

### ISSUE THREAD

**Issue by hike2008** [pili-engineering/PLDroidPlayer#340]
是否应该通过PLMediaPlayer.OnInfoListener来判断是否已经出现画面了

场景需求是:  播放器初始化阶段有预览图, 在可播放后将预览图隐藏, 以不显示黑色背景

**Comment by Jhuster** [comment]
@hike2008 是的，可以用 ·PLMediaPlayer.OnInfoListener· 来判断

**Comment by hike2008** [comment]
具体怎么判断比较准确呢 @Jhuster

**Comment by Jhuster** [comment]
@hike2008 PLMediaPlayer.OnInfoListener. MEDIA_INFO_VIDEO_RENDERING_START

**Comment by hike2008** [comment]
我试过, 用这个判断还是会黑一下

**Comment by hike2008** [comment]
但是会好一些, 有些不会, 我再从推流查查看吧
