### ISSUE TITLE
关于播放位置的问题

### ISSUE THREAD

**Issue by Ren-yibo** [pili-engineering/PLDroidPlayer#344]
在点播状态下，开始一个视频，然后把网络断开，这个时候有一部分缓存，可以继续比方视频，当缓存播放结束的时候getCurrentPosition获取的是“0”无法获取期望值，而且只有回调onError的EXTRA_CODE_CONNECTION_TIMEOUT值，求解，怎么获取Position的位置，以便监听网络连接的时候继续播放？

**Comment by Jhuster** [comment]
@Ren-yibo 在播放过程中，通过异步线程实时获取和保存。
