### ISSUE TITLE
prepareAsync()之后，有时候很久才会走OnPreparedListener的回调，有时候干脆就回调不了。导致播放不出来

### ISSUE THREAD

**Issue by Damonzh** [pili-engineering/PLDroidPlayer#347]
prepareAsync()之后，有时候很久才会走OnPreparedListener的回调，有时候干脆就回调不了。导致播放不出来

**Comment by Damonzh** [comment]
比如用这个资源播放：http://download.xmcdn.com/group5/M06/64/F3/wKgDtlRXXNqwWEKhAE2nR1Q7EBg253.aac

**Comment by Jhuster** [comment]
@Damonzh 我这边很快就播放出来了。可以考虑加上 DNS 解析优化，可以达到更快的首开：https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.5

**Comment by Damonzh** [comment]
好，我试试。不过我用原生MediaPlayer每次都能加载出来播放，用咱们这个库有一定的几率prepare之后就没反应了。

**Comment by Jhuster** [comment]
@Damonzh 嗯，可以看看没反应的时候，有什么报错的 log

**Comment by Damonzh** [comment]
@Jhuster 没有报任何错误

**Comment by Damonzh** [comment]
`11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_native_setup
11-02 11:11:32.135 D/pldroid-player-native(18939): pldroid_player native version = 1.1.0
11-02 11:11:32.135 D/IJKMEDIA(18939): ffpipeline_create_from_android()
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_inject_opaque(0x1da0055e)
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_inject_opaque()=void
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_android_set_mediacodec_select_callback()
11-02 11:11:32.135 D/IJKMEDIA(18939): ffpipeline_set_mediacodec_select_callback
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_android_set_mediacodec_select_callback()=void
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setOptionLong
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setDataSourceAndHeaders
11-02 11:11:32.135 V/IJKMEDIA(18939): setDataSource: path http://download.xmcdn.com/group5/M06/64/F3/wKgDtlRXXNqwWEKhAE2nR1Q7EBg253.aac
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_data_source(url="http://download.xmcdn.com/group5/M06/64/F3/wKgDtlRXXNqwWEKhAE2nR1Q7EBg253.aac")
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_data_source(url="http://download.xmcdn.com/group5/M06/64/F3/wKgDtlRXXNqwWEKhAE2nR1Q7EBg253.aac")=0
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_setVideoSurface
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_android_surface(surface=0x3330001d)
11-02 11:11:32.135 D/IJKMEDIA(18939): ffpipeline_set_surface()
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_set_android_surface(surface=0x3330001d)=void
11-02 11:11:32.135 D/IJKMEDIA(18939): IjkMediaPlayer_prepareAsync
11-02 11:11:32.135 D/IJKMEDIA(18939): ijkmp_prepare_async()
11-02 11:11:32.145 I/IJKMEDIA(18939): SDL_RunThread: [22844] ff_vout
11-02 11:11:32.145 D/IJKMEDIA(18939): ijkmp_prepare_async()=0
11-02 11:11:32.145 I/IJKMEDIA(18939): SDL_RunThread: [22845] ff_read
11-02 11:11:32.145 I/IJKMEDIA(18939): SDL_RunThread: [22843] ff_msg_loop
11-02 11:11:32.145 D/IJKMEDIA(18939): message_loop
11-02 11:11:32.145 D/IJKMEDIA(18939): FFP_MSG_FLUSH:
11-02 11:11:32.175 I/ActivityManager( 1159): Displayed com.pili.pldroid.playerdemo/.PLMediaPlayerActivity: +118ms
11-02 11:11:32.195 I/Timeline(18939): Timeline: Activity_idle id: android.os.BinderProxy@41e10390 time:205986508
11-02 11:11:32.505 I/Timeline( 1159): Timeline: Activity_windows_visible id: ActivityRecord{42d02940 u0 com.pili.pldroid.playerdemo/.PLMediaPlayerActivity t71} time:205986813`
又一次没播放成功，但是和上次的log不同

**Comment by Jhuster** [comment]
@Damonzh `open input: 201970 ms` 连接服务器打开这个流花了 20s 都没成功，有点不正常，一种可能是你的网络环境解析 DNS 太慢，另一种可能是服务器那边响应问题。 你先把 DNS 解析优化打开后再测试吧。

**Comment by Damonzh** [comment]
20后有个Immediate exit requested，这可以理解成连接超时取消了嘛？

**Comment by Damonzh** [comment]
@Jhuster 经过多次测试以及对比，感觉应该不是dns解析的问题，如果给定的音频时间比较长（目前是大于5分钟），就有一定的概率播放不出来音频。（小于5分钟没出现过问题）

**Comment by Jhuster** [comment]
@Damonzh 你的音频资源来自哪里？全部都是单纯的 aac 文件吗，还是 mp3 文件 ？不能播出来的是什么格式的文件？

**Comment by Jhuster** [comment]
@Damonzh `mAVOptions.setInteger("probesize", 500000);` 试试

**Comment by Damonzh** [comment]
@Jhuster 音频都是aac的。 `probesize` 控制的是什么呀？

**Comment by Jhuster** [comment]
@Damonzh `probesize`用来控制解析码流信息的力度，用 ffplay 播放你的流试试吧，看看是不是每次都能打开，从 log 看，有可能是服务端不稳定，open input 花了 20s 都连接不上服务器。

**Comment by Jhuster** [comment]
@Damonzh 你确定已经按照文档打开了 DNS 解析优化，然后依然没有效果吗？

**Comment by Damonzh** [comment]
@Jhuster 嗯 我在application里加入这句  `LNetworkManager.getInstance().startDnsCacheService(this, arrayOf("download.xmcdn.com"))`，然后也设置上这个 `avOptions.setInteger("probesize", 500000)` 仍然没啥效果
