### ISSUE TITLE
直播播放时闪退  Error (-10000,-2002)

### ISSUE THREAD

**Issue by mavsforlife** [pili-engineering/PLDroidPlayer#349]
直播流播放5-10分钟之后 闪退，toast提示 read frame timeout !
11-04 14:16:05.039 7210-15097/com.pili.pldroid.playerdemo E/IJKMEDIA: http://playv.upuday.com/ghlive/916535/playlist.m3u8: error while seeking
11-04 14:16:05.089 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f8515f290)
11-04 14:16:05.090 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f8515f300)
11-04 14:16:05.090 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f8515f370)
11-04 14:16:11.968 7210-17983/com.pili.pldroid.playerdemo E/IJKMEDIA: Option ijkinject-opaque not found.
11-04 14:23:01.373 7210-17983/com.pili.pldroid.playerdemo E/IJKMEDIA: read frame timeout !
11-04 14:23:01.381 7210-7210/com.pili.pldroid.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2002)
11-04 14:23:01.381 7210-7210/com.pili.pldroid.playerdemo E/PLMediaPlayer: Error happened, what = -10000, extra = -2002
11-04 14:23:01.914 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f626ab4c0)
11-04 14:23:01.914 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f626ab530)
11-04 14:23:01.915 7210-7210/com.pili.pldroid.playerdemo E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0x7f626ab5a0)

**Comment by Jhuster** [comment]
这个不是闪退，而是读数据超时了，检查下超时的时候直播流是否是稳定持续在推
