### ISSUE TITLE
Even if metadata rotate=90 the video is not rotated

### ISSUE THREAD

**Issue by gouravd** [pili-engineering/PLDroidPlayer#35]
Even if metadata rotate=90 the video is not rotated

**Comment by jpxiong** [comment]
Could you please provide the file ?

**Comment by gouravd** [comment]
Any file recorded from camera has this issue. But for your reference I am attaching the below file. SInce mp4 is not allowed to upload, I have renamed it to png, you must rename it to mp4 after downloading. 

This video is visible in portrait mode in Android Media VideoView, but not in PLDroidPlayer videoview

![vms_1447758775190](https://cloud.githubusercontent.com/assets/3840752/11210083/88620410-8d4b-11e5-94e5-d7df603b3b24.png)

**Comment by nisd93** [comment]
Is this issue resolved yet !!! I am facing same

**Comment by hike2008** [comment]
I am facing same
