### ISSUE TITLE
anr

### ISSUE THREAD

**Issue by rczhang13028** [pili-engineering/PLDroidPlayer#351]
在activity中的onDestroy回调中，调用PLVideoTextureView类的stopPlayback()方法，有时会出现anr问题
设备:小米2s
库版本:1.3.2

**Comment by Jhuster** [comment]
@rczhang13028 建议参考 Wiki 文档开启一下 DNS 解析优化，ANR 是因为某些手机，某些网络下，底层 dns 解析卡死，导致退出的时候等待线程退出超时而 ANR

**Comment by rczhang13028** [comment]
需要调用一下startDnsCacheService,启动 DNS 缓存管理服务?

**Comment by Jhuster** [comment]
@rczhang13028 是的

**Comment by rczhang13028** [comment]
好的，谢谢，
