### ISSUE TITLE
音频播放不出来问题？

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#353]
播放rtmp直播流的时候，同一个流有时候能播放出音频，有时候播放不出来，是什么原因？几率能达到百分之三四十。
也就是播放状态MEDIA_INFO_AUDIO_RENDERING_START = 2；出不来。

**Comment by Jhuster** [comment]
@lzx1 加一行配置试试：`mAVOptions.setInteger("probesize", 500000);`

**Comment by lzx1** [comment]
恩 加上之后好多了，现在是个别流几率很小的概率出现没有声音，是流的原因吗？

**Comment by Jhuster** [comment]
@lzx1 有什么报错信息？用别的播放器试试，比如 ffplay

**Comment by lzx1** [comment]
没有报错信息 就是MEDIA_INFO_AUDIO_RENDERING_START 状态回调不出来 。用ijkplayer播着没问题。

**Comment by Jhuster** [comment]
@lzx1 嗯，应该是音频编码格式不支持，为了减少 so 的体积，我们裁剪了支持的音视频编码格式。

**Comment by lzx1** [comment]
音频格式是NellyMoser，应该不只是音频格式的问题。我多次点开同一个主播间。也偶尔出现没有声音，几率还挺大的。希望能快点得到回复。谢谢。。

**Comment by Jhuster** [comment]
@lzx1 这个音频格式确实不支持的，肯定是播放不出来声音的。另外，`ffplay` 播放你的偶尔没声音的码流呢 ？每次都能播出来？

**Comment by lzx1** [comment]
是用这个播放器播加上mAVOptions.setInteger("probesize", 500000)这行代码后也有时候打开有声音，有时候没有声音，只是有声音的几率大一些，我没有用ffplay我用的是ijkplayer播放器，只要能播放出画面就能有声音。还有这个播放器支持的声音格式都有哪些？？

**Comment by Jhuster** [comment]
@lzx1 你确定所有的流都是 NellyMoser 的编码格式？同一个流有时候有声音有时候没声音？如果确定，那么把 probesize 继续加大试试。 我们支持的格式是由这个配置文件决定的：https://github.com/pili-engineering/pili-ijkplayer/blob/master/config/module-lite.sh

**Comment by lzx1** [comment]
不好意思，我们搞错了，移动端声音格式是AAC，pc端才是NellyMoser 格式，我们把流变成flv格式的话就没有问题了，声音一直有。非常感谢你耐心帮我解释。

**Comment by z2045217** [comment]
我这里也有这个问题。有的时候会出现没有声音的情况。我们是flv的。几率很小。但是也有啊。有一定几率会出现打开播放的时候只有画面没有声音情况。@Jhuster

**Comment by Jhuster** [comment]
@z2045217 上面提到的方法，你先试试，另外，是否同一个流有时候没有声音？

**Comment by z2045217** [comment]
@Jhuster 我也是按上面试了，对啊。就是同一个流。试了很多次。有很小的几率会出现。同一个流。有的时候没有声音。有的时候有。rtmp我们也试过。大概有些高清流。百分之五十的概率。出现没有声音。有的流却很少出现。

**Comment by Jhuster** [comment]
@z2045217 改 probesize 试过了是吧，那就用 ffplay 播放试试那些概率高的流吧，看看流本身以及时间戳会不会有问题。

**Comment by z2045217** [comment]
@Jhuster ffplay是什么？我一直想问。流本身是没有问题的。我以前用ijkplayer的播放器播放过。从没有出现过这种问题。

**Comment by Jhuster** [comment]
@z2045217 确定是用 ijkplayer 对流进行过对比测试 ？改 probesize 试过了是吧？ 是否有报错的 log

**Comment by z2045217** [comment]
试过了。我以前用的ijkplayer，没有出现过没有声音的情况。我用的giraffeplayer，这个就是简单封装ijkplayer播放器。改过了probesize ，还是试过了别的参数。也是还有会出现没有声音。这个潜在问题还是挺严重的。

**Comment by Jhuster** [comment]
@z2045217 到目前为止，说听不到声音的问题的，一般有 3 种情况：（1）音频编码格式不支持 （2） 修改 probesize 以后可以解决 （3）码流本身的原因

你把确定会出现问题的流地址发出来看看吧，我们这边 debug 下。

**Comment by z2045217** [comment]
@Jhuster rtmp://bf9.xiutv.com/xiyoulive/ROOM_15167_915c60c9740c6204a9b3b5db6008ef1f到八点半吧，你可以试试看。我试过了。格式没道理有的时候支持。有时候不支持。我修改了probesize ，几率低了。但是还有。这个主播以前在我经常看。没有过没有声音的时候。。

**Comment by Jhuster** [comment]
@z2045217 通过 ffplay debug 下来，发现这个流基本上要解析到 500000 以上字节才能解析出码流信息，所以建议你把 probesize 设置得再大点，mAVOptions.setInteger("probesize", 800000); 下面是其中一次 debug 的关键 log

```
[live_flv @ 0x7ff79303c200] After avformat_find_stream_info() pos: 511485 bytes read:511485 seeks:0 frames:107
```

**Comment by Jhuster** [comment]
@z2045217 推流是你们自己写的代码吗，FLV 封包模块应该有些可以优化的地方。

**Comment by z2045217** [comment]
这个地址是pc端obs推流的。具体的不知道。

**Comment by z2045217** [comment]
我刚刚试了下。刚改成80000，也差不多有。

**Comment by qssq** [comment]
http://117.144.248.49/HDhnws.m3u8?authCode=07110409322147352675&amp;stbId=006001FF0018120000060019F0D496A1&amp;Contentid=6837496099179515295&amp;mos=jbjhhzstsl&amp;livemode=1&amp;channel-id=wasusyt
 这个地址别的有声音。。

**Comment by Jhuster** [comment]
@qssq 你的地址发错了吧，用 ffplay 播放失败，上面说的方法测试过了吗，另外，音频编码格式是什么。
