### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x101000

### ISSUE THREAD

**Issue by coolspan** [pili-engineering/PLDroidPlayer#355]
11-15 11:52:48.362 277-277/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-15 11:52:48.362 277-277/? I/DEBUG: Build fingerprint: 'samsung/j3xproltezc/j3xproltechn:5.1.1/LMY47X/J3110ZCU1APE9:user/release-keys'
11-15 11:52:48.362 277-277/? I/DEBUG: Revision: '3'
11-15 11:52:48.362 277-277/? I/DEBUG: ABI: 'arm'
11-15 11:52:48.362 277-277/? I/DEBUG: pid: 22718, tid: 23630, name: ff_read  >>> comxx.musicplayer <<<
11-15 11:52:48.362 277-277/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x101000
11-15 11:52:48.382 277-277/? I/DEBUG:     r0 b08b3f1a  r1 000000b7  r2 00000000  r3 000f4240
11-15 11:52:48.392 277-277/? I/DEBUG:     r4 00000190  r5 b78af5f0  r6 b788ab90  r7 00000000
11-15 11:52:48.392 277-277/? I/DEBUG:     r8 00101000  r9 00009c40  sl b78af5f0  fp 9c226874
11-15 11:52:48.392 277-277/? I/DEBUG:     ip 0000003c  sp 9c226778  lr 9ad5e52d  pc 9ab9bf56  cpsr 40070030
11-15 11:52:48.392 277-277/? I/DEBUG: backtrace:
11-15 11:52:48.392 277-277/? I/DEBUG:     #00 pc 00042f56  /data/app/com.xx.musicplayer-2/lib/arm/libpldroidplayer.so
11-15 11:52:48.392 277-277/? I/DEBUG:     #01 pc 0005a43f  /data/app/com.xx.musicplayer-2/lib/arm/libpldroidplayer.so (ff_check_interrupt+10)

**Comment by tanhx2008** [comment]
Need more log！
