### ISSUE TITLE
视频没有图像

### ISSUE THREAD

**Issue by cdcdec** [pili-engineering/PLDroidPlayer#357]
如下所示的视频,播放时没有图像

![1](https://cloud.githubusercontent.com/assets/8176067/20335113/b572e784-abfa-11e6-8165-ceb3e761246f.png)

**Comment by Jhuster** [comment]
@cdcdec 暂时不支持 3GPP 的视频解码

**Comment by cdcdec** [comment]
哦 ，谢谢!
