### ISSUE TITLE
关于横竖屏切换，切到横屏时画面拉伸了，求帮忙分析下。谢谢

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#361]
想请教一个问题·，看直播的时候，我做横竖屏切换，到了横屏的时候，画面拉伸了，请问该如何解决呢。。谢谢

**Comment by Jhuster** [comment]
@15189611 需要详细说明下你是怎么做的

**Comment by 15189611** [comment]
mVideoView.setDisplayAspectRatio(PLVideoTextureView.ASPECT_RATIO_PAVED_PARENT);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        View decor = this.getWindow().getDecorView();
        decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);

**Comment by 15189611** [comment]
播放的时候是全屏&竖屏，然后切换到横屏，画面的内容跟竖屏比例不一样了，人的头像只显示一半

**Comment by Jhuster** [comment]
@15189611 刚刚我用 demo 验证了一次，没有什么问题，你下载 demo，然后在 PLVideoViewActivity 的 xml 里面加个 button，点击事件里面填入：
`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`
你看看切换到横屏是否正常，我这边验证是正常的，然后你再对比下你的代码吧

**Comment by 15189611** [comment]
切换到横屏的时候，宽度没有全屏是这样的、？

**Comment by 15189611** [comment]
我这边播放的是直播流，直播拍摄的时候采用的是竖屏&&全屏，然后切换到横屏的时候，宽度没有全屏，只有一点点。谢谢

**Comment by 15189611** [comment]
用你们demo本地视频播放，然后切换是正常的。请问播放直播流的时候，宽度就没有全屏。谢谢

**Comment by 15189611** [comment]
@Jhuster  请问改怎么解决这个问题呢·，谢谢

**Comment by Jhuster** [comment]
@15189611 `demo` 就是默认播放的直播流，横屏后设置为 ·ASPECT_RATIO_PAVED_PARENT· 就可以全屏了，我已经验证了。你多动手做做实验。

**Comment by 15189611** [comment]
@Jhuster 是的·，我也设置了也实验了，画面的比例 放大了很多，比如竖屏的时候人的上半身都显示全了。切换到横屏的时候，人的头部都显示不全。我想问的就是这个问题，画面比例如何做到像竖屏一样，谢谢

**Comment by Jhuster** [comment]
@15189611 我用 demo 里的直播流测试过了，横屏的时候，跟竖屏的时候一样，都可以全屏。

**Comment by 15189611** [comment]
@Jhuster rtmp://pili-live-rtmp.live.yupaopao.cn/ypp-live/5810c843101385530e27119e 您测试下这个谢谢

**Comment by Jhuster** [comment]
@15189611 可以的啊，PLVideoViewActivity 你固定设置为横屏，然后把 Player 配置为 ASPECT_RATIO_PAVED_PARENT

**Comment by 15189611** [comment]
@Jhuster  你用给你的直播流播放，然后切换到横屏。是可以的？人的头部显示全了？

**Comment by 15189611** [comment]
@Jhuster 我是直接在你demo中做实验的，只是替换个流的地址，然后代码是这样的
 mVideoView.setDisplayAspectRatio(PLVideoTextureView.ASPECT_RATIO_PAVED_PARENT);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        View decor = this.getWindow().getDecorView();
        decor.setSystemUiVisibility(View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);

**Comment by Jhuster** [comment]
@15189611 我懂你的意思了，你要理解图像缩放的基本原理，你是不可能把一个竖屏的图像，完全不剪裁的做到等比例扩大到全屏的。 所以，如果你希望横屏全屏播放而且还图像完整，那么录制的时候，就应该横屏录制

**Comment by 15189611** [comment]
@Jhuster 恩·是这样的，我们录制的时候是竖屏的，只有播放端才能切换横竖屏。所以我想请问该怎么样做到图像缩放，

**Comment by 15189611** [comment]
@Jhuster 按照您的意思，那我们有没有办法在切换到横屏的时候。进行裁剪呢，谢谢

**Comment by Jhuster** [comment]
@15189611 上面说过了，原理上讲，做不到不剪裁不拉伸把一个竖屏的图像横屏全屏，理论上就做不到。只能考虑横屏的时候两边留黑，或者录制的时候，用 4:3 的比例，或许横屏后，两边的黑不会太明显。

**Comment by 15189611** [comment]
@Jhuster  噢噢，我理解勒。那考虑两边留黑的话，会很明显？ 是不是正个画面的宽度只有一点点。谢谢
