### ISSUE TITLE
Error happened, what = -10000, extra = -2002

### ISSUE THREAD

**Issue by huxugang** [pili-engineering/PLDroidPlayer#365]
log如下：
read frame timeout
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2002)
 Error happened, what = -10000, extra = -2002
出现这种情况，视频就不动了，点击也没有反应，如何能让视频重新加载播放。是需要在PLMediaPlayer.OnErrorListener的回调中，重新设置链接请求吗？

**Comment by Jhuster** [comment]
@huxugang 嗯，重连，参考文档
