### ISSUE TITLE
播放本地raw下文件错误 -1330794744

### ISSUE THREAD

**Issue by yanghongzhi** [pili-engineering/PLDroidPlayer#369]
![default](https://cloud.githubusercontent.com/assets/5966620/20616324/56eb6d7a-b31c-11e6-9541-079d8bb14ad6.png)

**Comment by Jhuster** [comment]
@yanghongzhi 不支持

**Comment by lygttpod** [comment]
@Jhuster  这个功能还是用的挺多的  ，播放代码里的预先放好的视频在程序启动时候播放效果很好 （欢迎页播放本地视频无需加载等待），希望支持一下这个功能。
