### ISSUE TITLE
视频h264音频aac格式，但还是没有声音

### ISSUE THREAD

**Issue by wcenGitHub** [pili-engineering/PLDroidPlayer#370]
如题，我看了之前的一些帖子，说是支持aac音频的，请问应该从哪里着手调试呢？setVolume已经设成1了
谢谢

**Comment by Jhuster** [comment]
@wcenGitHub 流地址发一下，是否有 error log，用其他的播放器是否可以播放，如 vlc

**Comment by wcenGitHub** [comment]
其他vlc没问题，我们用flash也没问题，就是在手机上没声音。视频流我要开才有，因为是直播平台。能否约个时间？万分感谢

**Comment by wcenGitHub** [comment]
或者加一下我的qq，我给你账号？？谢谢了

**Comment by Jhuster** [comment]
@wcenGitHub 加一行配置试试：mAVOptions.setInteger("probesize", 500000);
