### ISSUE TITLE
直播源很大概率连接不上,之前的版本没有问题呀,然后发现报错信息.

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#371]
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init(Native Method)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initNativeOnce(IjkMediaPlayer.java:200)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:225)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:115)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.pili.pldroid.player.widget.a.c(PLBaseVideoView.java:487)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.pili.pldroid.player.widget.a$8.a(PLBaseVideoView.java:941)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.pili.pldroid.player.widget.PLVideoTextureView$a$1.onSurfaceTextureAvailable(PLVideoTextureView.java:247)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.TextureView.getHardwareLayer(TextureView.java:370)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14164)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14182)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:14979)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:3406)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3199)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.draw(View.java:15254)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.widget.FrameLayout.draw(FrameLayout.java:598)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2653)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.updateDisplayListIfDirty(View.java:14187)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.View.getDisplayList(View.java:14209)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2566)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2382)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2012)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1091)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5926)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:775)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:588)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:558)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:761)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.os.Looper.loop(Looper.java:135)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5273)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
11-26 10:57:25.575 10091-10091/com.xiusekecai.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by Vander-liu** [comment]
不知道 是不是我这边怎么造成这个问题的.

**Comment by Vander-liu** [comment]
@Jhuster 求助.

**Comment by Jhuster** [comment]
@Vander-liu 确定 so 更新了？

**Comment by Vander-liu** [comment]
是我的问题,我找到原因了.Sorry,很感谢.


原始邮件
发件人:卢俊notifications@github.com
收件人:pili-engineering/PLDroidPlayerPLDroidPlayer@noreply.github.com
抄送:Vander-liu540675759@qq.com; Mentionmention@noreply.github.com
发送时间:2016年11月26日(周六) 22:19
主题:Re: [pili-engineering/PLDroidPlayer] 直播源很大概率连接不上,之前的版本没有问题呀,然后发现报错信息. (#371)


@Vander-liu 确定 so 更新了？

**Comment by kevien92** [comment]
请问您是什么原因导致的

**Comment by Vander-liu** [comment]
So文件的问题.

**Comment by Vander-liu** [comment]
我也记得不太清了 ,时间过得很长,但是问题的来源是So文件的问题.
