### ISSUE TITLE
关于多次切换横竖屏，然后跳到其他Activity然后又回来，会操作JNI如下错误，不是必现，请帮忙分下原因，谢谢

### ISSUE THREAD

**Issue by 15189611** [pili-engineering/PLDroidPlayer#374]
![qq 20161128191503](https://cloud.githubusercontent.com/assets/13620658/20666419/11456fde-b59f-11e6-8434-86a35e27837f.png)

**Comment by Jhuster** [comment]
@15189611 什么版本 ？

**Comment by 15189611** [comment]
1.3.2的jar

**Comment by 15189611** [comment]
@Jhuster

**Comment by 15189611** [comment]
请问是不是1.3.2这个版本会有这个问题呢，还是其它原因导致的？谢谢
