### ISSUE TITLE
关于直播延迟。

### ISSUE THREAD

**Issue by hnlbxb2004** [pili-engineering/PLDroidPlayer#377]
咱们的sdk ，我用到了直播放音频 ，服务器是我自己从github 找的nginx-rtmp-modle  ，本地局域网，延迟大概3秒多，我以为是推流的原因，或者服务器的原因，因此我用腾讯云的播放器试验了下，延迟大概1秒内，那么至少说明不是推流或者服务器的问题。手机也试验了好多个。
我想问下，这种延迟有可能是因为什么引起的，我想知道点方向，去找原因，解决他。

**Comment by Jhuster** [comment]
@hnlbxb2004 开启一下累积延时优化功能：https://github.com/pili-engineering/PLDroidPlayer/wiki/5-功能使用#5.1

```
// 是否开启"延时优化"，只在在线直播流中有效
// 默认值是：0
options.setInteger(AVOptions.KEY_DELAY_OPTIMIZATION, 1);

// 默认的缓存大小，单位是 ms
// 默认值是：2000
options.setInteger(AVOptions.KEY_CACHE_BUFFER_DURATION, 2000);

// 最大的缓存大小，单位是 ms
// 默认值是：4000
options.setInteger(AVOptions.KEY_MAX_CACHE_BUFFER_DURATION, 4000);
```

**Comment by Huskera** [comment]
@Jhuster 我跟楼主的情况一样，也是局域网+nginx-rtmp-modle，延迟3s多，在Demo里面按上面说的加代码后还是不起作用，请问是什么原因啊？

使用的是PLMediaPlayerActivity：

...
//----以下是我加的---
        mAVOptions.setInteger(AVOptions.KEY_LIVE_STREAMING, 1);
        mAVOptions.setInteger(AVOptions.KEY_DELAY_OPTIMIZATION, 1);
        mAVOptions.setInteger(AVOptions.KEY_BUFFER_TIME, 100);
        mAVOptions.setInteger(AVOptions.KEY_CACHE_BUFFER_DURATION, 300);
        mAVOptions.setInteger(AVOptions.KEY_MAX_CACHE_BUFFER_DURATION, 300);
//---------------------

        AudioManager audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
        audioManager.requestAudioFocus(null, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN);
...

在new PLMediaPlayer的时候打断点可以看到参数也生效了。

**Comment by Huskera** [comment]
@Jhuster 我是对着摄像头做动作，然后看播放器多久有反应。
另外用flash做客户端在PC上测过，延迟很小，这说明应该不是服务器和源端的问题吧？

**Comment by Jhuster** [comment]
@Huskera 最新版本吗？你就用 demo 默认的配置，把地址换成你的播放地址再试试

**Comment by Huskera** [comment]
@Jhuster 是最新的1.4.1。用这个方法试过了，还是有3s。能不能帮忙分析一下可能是那些地方出问题？谢谢了！

**Comment by Jhuster** [comment]
要做到秒开，还需要服务器端做一些 GOP 缓存，如果用 demo 还是这个延时，那么播放器 SDK 已经没有什么可以配置和优化的了。

**Comment by Jhuster** [comment]
如果用 demo 还是这个延时，那么播放器 SDK 已经没有什么可以配置和优化的了，你debug下服务端是否有缓存
