### ISSUE TITLE
一些奇怪的问题求解答

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#380]
播放湖南卫视经常好好的就停止了,也不调用错误回调 这就搞不懂了，用的是1.4的，之前1.3是没有声音 现在是声音有了，经常停止播放  - -   mVideoView.start(); 或者 seVideoPAth又可以了。。

而其他直播源测试就是经常出现这种情况，突然就错误代码，但是只需要重新 setVideoPath又是可以了的，
能否优化下 体验呢？这突然错误也不应该死掉啊，有时候死掉更奇葩 图像不动了声音还有 但是重新设置videopath又可以了。。

**Comment by Jhuster** [comment]
@qssq 一般这种情况，网络不稳定、服务端的问题都有可能，你需要详细给出 错误回调 具体报了什么错误，底层 log 有什么输出，另外，码流地址也建议发出来一下，我这边也可以帮你 debug 看看 log
