### ISSUE TITLE
在线视频播放没有画面只有声音

### ISSUE THREAD

**Issue by GaoShin** [pili-engineering/PLDroidPlayer#381]
有一个视频播放的时候没有画面，只有声音？
视频的地址是http://imgcdn.zhoumopark.com/zmaudio/_pla_1480915650952.mp4
视频的信息如下所示：
![qq 20161205152420](https://cloud.githubusercontent.com/assets/24382545/20876770/3b7250dc-baff-11e6-98a1-c72d5ca839da.png)

**Comment by Jhuster** [comment]
当前版本不支持 mp4v 格式
