### ISSUE TITLE
求助.So文件相关

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#384]
我想采用动态注入的方式,将So文件根据手机不同的CPU架构来 分别下载不同的So文件,这块想了解下我们 播放器 的关于So文件方面的源码 可否借阅一下 .

**Comment by Vander-liu** [comment]
@Jhuster  求助.

**Comment by Jhuster** [comment]
@Vander-liu 我们没有做动态方式加载 so

**Comment by Vander-liu** [comment]
@Jhuster 我想自己实现这样一个操作,在打开App后引导下载,然后在点击进入直播间时在检查并加载So文件,

**Comment by Vander-liu** [comment]
SharedLibraryNameHelper.getInstance().renameSharedLibrary(soFilePath);
这一块,我感觉我可能会用到这个方法,然后我想查看下相关源码. 不知道可否 把部分的源码能让我参考下 .

**Comment by Vander-liu** [comment]
public void a() {
        if(this.a.contains("/")) {
            System.load(this.a);
        } else {
            System.loadLibrary(this.a);
        }

    }

    private static class a {
        public static final SharedLibraryNameHelper a = new SharedLibraryNameHelper();
    }

我只找到了这一块.然后我感觉还是得了解下, 真心求助,

**Comment by Jhuster** [comment]
@Vander-liu 这块跟你要做的功能，没有什么关系，只是用于更改 so 的名称。

```
private String mPlayerName = "pldroidplayer";
public void loadLibrary() {
        if (mPlayerName.contains("/")) {
            System.load(mPlayerName);
        } else {
            System.loadLibrary(mPlayerName);
        }
}
```

**Comment by Vander-liu** [comment]
那我做这个功能,会涉及到源码的内容么,如果没有那就Ok了.

**Comment by Vander-liu** [comment]
12-06 16:22:18.739 28455-28469/com.xiusekecai.debug E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
12-06 16:22:18.739 28455-28469/com.xiusekecai.debug E/System: Uncaught exception thrown by finalizer
12-06 16:22:18.739 28455-28469/com.xiusekecai.debug E/System: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1finalize__)
                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_finalize(Native Method)
                                                                  at tv.danmaku.ijk.media.player.IjkMediaPlayer.finalize(IjkMediaPlayer.java:960)
                                                                  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:191)
                                                                  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:174)
                                                                  at java.lang.Thread.run(Thread.java:818)
12-06 16:22:19.289 28455-28455/com.xiusekecai.debug E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)

不知道为什么我在1.4版本采用 后加载So文件在进入直播间调用我们播放器就会出现这个问题.而且我的直播间第一次打开的时候,So文件是存在的, 第二次打开的时候,就发生这种异常.

**Comment by Vander-liu** [comment]
@Jhuster

**Comment by Vander-liu** [comment]
之前  1.32  和 1.2xx 相关的版本 好像不存在这个问题 ....我好抓狂啦....

**Comment by Vander-liu** [comment]
@Jhuster   找到原因了,特别感谢 官方大大 . 是我们自己的问题..耽误您时间啦 .

**Comment by Jhuster** [comment]
@Vander-liu 不客气
