### ISSUE TITLE
这个http为什么pot可以 我们的七牛播放器就不行了呢？

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#385]
http://stream5.fjtv.net/dnpd/hd/live.m3u8?_upt=4314d10f1481047940

**Comment by Jhuster** [comment]
@qssq  你用 ffplay 播放看看，返回的是：Server returned 403 Forbidden (access denied)

**Comment by qssq** [comment]
额。失效了，我是从东南卫视抓的，之前是potplayer可以播放的。
