### ISSUE TITLE
'com.qiniu.pili:pili-android-qos:0.8.+' 问题

### ISSUE THREAD

**Issue by BryanYue** [pili-engineering/PLDroidPlayer#387]
E/AndroidRuntime(  843): FATAL EXCEPTION: QosReporter

E/AndroidRuntime(  843): Process: com.midea.mjmw365.smartrefrigerators, PID: 843

E/AndroidRuntime(  843): java.lang.NullPointerException: println needs a message

E/AndroidRuntime(  843): 	at android.util.Log.println_native(Native Method)

E/AndroidRuntime(  843): 	at android.util.Log.d(Log.java:139)

E/AndroidRuntime(  843): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:308)

E/AndroidRuntime(  843): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:171)

E/AndroidRuntime(  843): 	at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:218)

E/AndroidRuntime(  843): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:22)

E/AndroidRuntime(  843): 	at com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage(QosReporter.java:79)

E/AndroidRuntime(  843): 	at android.os.Handler.dispatchMessage(Handler.java:98)

E/AndroidRuntime(  843): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(  843): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Jhuster** [comment]
请更新到 `com.qiniu.pili:pili-android-qos:0.8.16`
