### ISSUE TITLE
播放1280*720的视频出现音频和画面不同步的现象

### ISSUE THREAD

**Issue by Damonzh** [pili-engineering/PLDroidPlayer#389]
画面要慢于音频很多

**Comment by Jhuster** [comment]
@Damonzh 720P 的流我们也验证过，没有这个问题。你是什么机型，参数是软编还是硬编，其他手机是否有试一下？另外，在电脑上用其他工具播放这个流呢？

**Comment by Damonzh** [comment]
@Jhuster  软硬编都尝试了，不行。我的设备不是手机，视频也没问题。同样的视频用你的demo跑在我的设备上也没有延迟，不知道是为什么了

**Comment by Jhuster** [comment]
@Damonzh `同样的视频用你的demo跑在我的设备上也没有延迟` ? 那就严格按照 demo 的 `AVOptions` 参数来配置你的 App

**Comment by Damonzh** [comment]
@Jhuster 我对比了下，没发现不同。但就是跑起来会有音视频不同步的问题
