### ISSUE TITLE
android端播放IOS录制的视频画面快进，没有声音

### ISSUE THREAD

**Issue by marlboro3420** [pili-engineering/PLDroidPlayer#390]
RT，但是播放安卓自己录的视频没有问题，正常播放。

**Comment by Jhuster** [comment]
iOS 录制的音视频分别是什么编码格式，ffplay 等其他播放器可以播放吗？

**Comment by marlboro3420** [comment]
IOS端说是MP4格式的，问题已经解决了，传值进来的时候加上
`i.putExtra("liveStreaming", 0);`
PLVideoTextureActivity 里面进来好像默认直播的，改为0就正常了。
真是奇怪，自己录得默认直播也是正常，IOS录得默认直播有问题。
