### ISSUE TITLE
'com.qiniu.pili:pili-android-qos:0.8.16'  出现java.lang.NullPointerException问题

### ISSUE THREAD

**Issue by BryanYue** [pili-engineering/PLDroidPlayer#392]
println needs a message

W/System.err( 1071): java.lang.NullPointerException: println needs a message

W/System.err( 1071): 	at android.util.Log.println_native(Native Method)

W/System.err( 1071): 	at android.util.Log.d(Log.java:139)

W/System.err( 1071): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:308)

W/System.err( 1071): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:171)

W/System.err( 1071): 	at com.qiniu.pili.droid.report.core.QosReporter.c(QosReporter.java:218)

W/System.err( 1071): 	at com.qiniu.pili.droid.report.core.QosReporter.a(QosReporter.java:22)

W/System.err( 1071): 	at com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage(QosReporter.java:79)

W/System.err( 1071): 	at android.os.Handler.dispatchMessage(Handler.java:98)

W/System.err( 1071): 	at android.os.Looper.loop(Looper.java:135)

W/System.err( 1071): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by BryanYue** [comment]
'com.qiniu.pili:pili-android-qos:0.8.+' 上也有这个问题，'com.qiniu.pili:pili-android-qos:0.8.16'未解决这个问题

**Comment by tanhx2008** [comment]
播放器 SDK 的版本是多少？

**Comment by BryanYue** [comment]
是1.4.0 最新版的

**Comment by tanhx2008** [comment]
播放器正常是会关闭 Debug 模式的，不会触发这个问题，如果还有问题，抓一下全部的 log，发出来看一下

**Comment by tanhx2008** [comment]
0.8.17 会完全修复这个问题

**Comment by BryanYue** [comment]
提供下邮箱号，我把全部log发您邮箱

**Comment by tanhx2008** [comment]
https://notepad.pw/as12mlxw
方便的话，粘到这里，谢谢

**Comment by BryanYue** [comment]
https://notepad.pw/share/oozk0vc9

**Comment by BryanYue** [comment]
地址打不开 我放百度云盘了  https://pan.baidu.com/s/1i5BK6PZ

**Comment by tanhx2008** [comment]
你这个版本应该不是线上发布的版本吧？是从哪里得到的版本？

**Comment by BryanYue** [comment]
直接拷的1.4 demo里的jar包
