### ISSUE TITLE
在线视频播放rmvb.avi播放不了

### ISSUE THREAD

**Issue by FrankLove** [pili-engineering/PLDroidPlayer#393]
为什么播放rtmp流可以，在线播放视频的时候只有flv可以，rmvb,avi就直接报错
12-15 17:16:19.285 12691-8049/com.pili.pldroid.playerdemo E/IJKMEDIA: http://192.168.2.28:8002/LGFTP/Teacher/Test/2.rmvb?domain=192.168.2.28: Invalid data found when processing input
12-15 17:16:19.285 12691-8049/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [8049]
12-15 17:16:19.285 12691-8047/com.pili.pldroid.playerdemo D/IJKMEDIA: FFP_MSG_ERROR: -1094995529
12-15 17:16:19.295 12691-12691/com.pili.pldroid.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1094995529)
12-15 17:16:19.295 12691-12691/com.pili.pldroid.playerdemo E/PLMediaPlayer: Error happened, what = -10000, extra = -1094995529
12-15 17:16:19.295 12691-12691/com.pili.pldroid.playerdemo E/PLMediaPlayerActivity: Error happened, errorCode = -1094995529

**Comment by Jhuster** [comment]
不支持这两种格式

**Comment by FrankLove** [comment]
@Jhuster ijkmediapler 本身就不支持吗

**Comment by Jhuster** [comment]
@FrankLove 我们为了减少 so 体积，对不常用的格式做了精简。

**Comment by FrankLove** [comment]
@Jhuster 但是我这边需要支持mp4,avi的话要怎么办呢
