### ISSUE TITLE
本地mp4视频播放只有声音没有画面, 详细信息如下

### ISSUE THREAD

**Issue by hike2008** [pili-engineering/PLDroidPlayer#394]
File
Name: 关爱贫困大学生，传递梦想与希望.mp4
Size: 5.53 MB (5526558 bytes)
Kind: MPEG-4 movie
UTI: public.mpeg-4
Location: /Users/Downloads
Created: 2016年12月15日 下午5:33:29
Modified: 2016年12月15日 下午5:33:30
Container
Format: MPEG-4
Format profile: Base Media
Codec ID: isom (isom/iso2/mp41)
Duration: 4mn 11s 546ms
Overall bit rate mode: Constant
Overall bit rate: 176 Kbps
Encoded date: UTC 1904-01-01 00:00:00
Tagged date: UTC 1904-01-01 00:00:00
Writing application: Lavf54.6.100
Video
ID: 1
Format: MPEG-4 Visual
Format profile: Simple@L3
Format settings, BVOP: No
Format settings, QPel: No
Format settings, GMC: No warppoints
Format settings, Matrix: Default (H.263)
Codec ID: 20
Duration: 4mn 11s 546ms
Bit rate mode: Constant
Bit rate: 142 Kbps
Width: 720 pixels
Height: 576 pixels
Pixel aspect ratio: 1.000
Display aspect ratio: 5:4
Frame rate mode: Constant
Frame rate: 11.000 fps
Frame count: 2767
Color space: YUV
Chroma subsampling: 4:2:0
Bit depth: 8 bits
Scan type: Progressive
Compression mode: Lossy
Bits/(Pixel*Frame): 0.031
Stream size: 4.45 MB (80.6%)
Writing library: XviD 64
Encoded date: UTC 1904-01-01 00:00:00
Tagged date: UTC 1904-01-01 00:00:00
Audio
ID: 2
Format: AAC
Format/Info: Advanced Audio Codec
Format profile: LC
Codec ID: 40
Duration: 4mn 11s 264ms
Duration_FirstFrame: 43ms
Bit rate mode: Constant
Bit rate: 32.0 Kbps
Channel(s): 1 channel
Channel positions: Front: C
Sampling rate: 24.0 KHz
Frame rate: 23.438 fps (1024 spf)
Frame count: 5890
Compression mode: Lossy
Stream size: 1.01 MB (18.2%)
Default: Yes
Alternate group: 1
Encoded date: UTC 1904-01-01 00:00:00
Tagged date: UTC 1904-01-01 00:00:00

**Comment by tanhx2008** [comment]
为了减小库的大小，当前版本不支持该视频的编码格式。

**Comment by hike2008** [comment]
如果想支持, 可否有办法解决, 谢谢

**Comment by tanhx2008** [comment]
try  1.4.1

**Comment by hike2008** [comment]
thanks, isom 编码的已经可以播放了;
