### ISSUE TITLE
obs推流，视屏横屏播放的时候，画面只有3分之二大小，顶部有3分之一黑屏，该怎么解决，视屏大小1920*1080

### ISSUE THREAD

**Issue by longchenpl** [pili-engineering/PLDroidPlayer#397]

**Comment by Jhuster** [comment]
@longchenpl Activity 已经设置为横屏了是吧，使用的哪一种显示模式，demo 测试的？ 你希望是什么样显示

**Comment by longchenpl** [comment]
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_FIT_PARENT);  不是demo  我希望可以全屏显示，我是在做视频的横竖屏切换    五种模式都试过了 效果不太理想

**Comment by Jhuster** [comment]
@longchenpl 首先有个被问过很多次的问题我先强调下，理论上，一个 4:3 的视频，不可能做到在 16:9 的手机上完全不剪裁不留黑边地进行全屏播放，如果理解了这一点后，你再描述下你希望的显示效果吧

**Comment by longchenpl** [comment]
不好意思 刚才点错了 
 想做成这种效果，刚开始做直播，有很多知识不太了解，请见谅，就是想实现类似于斗鱼直播的那种 
 窗口，全屏播放的效果

**Comment by Jhuster** [comment]
把 Activity 设置为横屏，然后播放的View 设置为：mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_FULL_PARENT);
播放 16:9 的流，就能无缝全屏，你的 OBS 推流是什么比例

**Comment by Jhuster** [comment]
把 Activity 设置为横屏，然后播放的View 设置为：mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_FULL_PARENT);
播放 16:9 的流，就能无缝全屏了。你用 demo 改改试试。

**Comment by longchenpl** [comment]
好的  谢谢大神  我下个demo试试  流是16:9的

**Comment by longchenpl** [comment]
mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_FULL_PARENT);  没有这个方法啊

**Comment by Jhuster** [comment]
记错了，ASPECT_RATIO_PAVED_PARENT

**Comment by longchenpl** [comment]
解决了  谢谢大神 我代码的问题
