### ISSUE TITLE
播放本地视频有声音有图像，但是播放rtmp直播流就只有图像没有声音啊，咋弄的？

### ISSUE THREAD

**Issue by kaiery** [pili-engineering/PLDroidPlayer#40]
播放本地视频有声音有图像，但是播放rtmp直播流就只有图像没有声音啊，咋弄的？
使用的1.14版本
直播流用的是red5，
用其他flash播放同一个 从red5出来直播流，是有声音的，但用PLDroidPlayer在手机里播放 就只有图像没有声音。
手机是note5，

**Comment by jjdxmashl** [comment]
同问，遇到相同的情况。

**Comment by jjdxmashl** [comment]
经过多次测试，1.1.2版本的有声音和图像，但是播放器横竖屏切换设置有点问题，1.1.4的播放器横竖屏切换设置比较理想，但是只有图像没有声音。
