### ISSUE TITLE
官方的demo居然播不了本地视频.. 

### ISSUE THREAD

**Issue by littleKun** [pili-engineering/PLDroidPlayer#401]
实测 下载最新的demo 但是无法播放本地的mp4  avi 等格式的视频, 是我哪里不对?????

**Comment by Jhuster** [comment]
@littleKun 视频是 h.264 吗？不支持 avi 这种格式

**Comment by littleKun** [comment]
@Jhuster  看了一下其他开发者提出的issues  回答是不支持 mp4 , mkv rmvb avi这些格式的视频...  这是格式的视频不是现在 本地文件保存的常用的视频格式吗?   还是此项目只能播放在线的流....这个我测试倒是可以的...

**Comment by Jhuster** [comment]
@littleKun 嗯，我们主要面向在线直播和点播领域，移动端通过手机下载 mkv, rmvb, avi 等视频文件来播放的场景并不多，暂时没有考虑这些格式，以减小包体积
