### ISSUE TITLE
播放4K视频太卡，不能播放网络mp4.rmvb等格式的视频

### ISSUE THREAD

**Issue by sanchibing** [pili-engineering/PLDroidPlayer#402]
播放4K视频太卡，不能播放网络mp4.rmvb等格式的视频。

**Comment by Jhuster** [comment]
@sanchibing 4K 卡一般是手机性能原因，用硬编试试，不支持 rmvb 格式

**Comment by sanchibing** [comment]
@Jhuster 自己编译的ijk so包播放4K就不会卡。

**Comment by Jhuster** [comment]
@sanchibing 明白了，因为我们为了降低播放延时，我们开启了追帧优化，你可以把 AVOption 配置为点播模式，或者简单关闭累计延时优化选项
