### ISSUE TITLE
请问PLVideoView播放视频，只有画面没有声音？

### ISSUE THREAD

**Issue by candebbs** [pili-engineering/PLDroidPlayer#405]
使用setVolume(1f, 1f)也是没有效果的？格式为：rtmp

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/370

**Comment by candebbs** [comment]
加了还是不行，是不是不支持一些音频解码格式

**Comment by Jhuster** [comment]
嗯，你的音频是什么格式

**Comment by candebbs** [comment]
AAC，单通道，双通道的。请问下so文件开源出来没有？

**Comment by Jhuster** [comment]
@candebbs 你的流地址发出来我们试试

**Comment by mogumodel** [comment]
测试发现有时有视频和声音能够正常播放，有时候只有视频无声音，测试媒体源：rtmp://v1.one-tv.com/live/mpegts.stream；不知道什么原因

**Comment by zhuxianchen** [comment]
我的地址也是 rtmp://live1.baihuwang.com:1935/live/bh  有的时候有声音 有的时候没有声音  用pc版的vlc测试就没有问题

**Comment by Jhuster** [comment]
加一行配置试试：mAVOptions.setInteger("probesize", 500000);
