### ISSUE TITLE
使用PLVideoTextureView布局时报错

### ISSUE THREAD

**Issue by dh1021** [pili-engineering/PLDroidPlayer#406]
The following classes could not be instantiated:
           - com.pili.pldroid.player.widget.PLVideoTextureView (Open Class, Show Exception, Clear Cache)
Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  
If this is an unexpected error you can also try to build the project, then manually refresh the layout.  

Exception Details 
java.lang.VerifyError: Expecting a stackmap frame at branch target 22 
Exception Details: 
Location: 
com/pili/pldroid/player/widget/a.start()V @5: if_icmpne 
Reason: Expected stackmap frame at this location.

**Comment by dh1021** [comment]
Log中提示：dalvikvm: Could not find method android.widget.FrameLayout.<init>, referenced from method com.pili.pldroid.player.widget.a.<init>

**Comment by Jhuster** [comment]
@dh1021 demo 可以跑起来吗？你的布局跟 demo 的布局有什么区别？

**Comment by dh1021** [comment]
demo可以跑，demo根布局用的FrameLayout，我用的LinearLayout，没多大关系吧

**Comment by Jhuster** [comment]
@dh1021 demo 可以跑，你可以把 demo 的 xml 配置和代码先搬到你的 app 中试试
