### ISSUE TITLE
实现播放小视频循环播放，并且在第一次播放完毕时提示

### ISSUE THREAD

**Issue by zjwjmmx** [pili-engineering/PLDroidPlayer#407]
想实现类似小视频播放功能，需要循环播放，用PLVideoTextureView设置了setLooping(true)，这时候PLMediaPlayer.OnCompletionListener接口不回调。如果不设置setLooping，在onCompletion想提示“轻触退出”，但是直接把PLVideoTextureView.start()又只会重播一遍。有什么办法吗？
PLDroidPlayer版本1.4.1

**Comment by tanhx2008** [comment]
每次收到 onCompletion 后，PLVideoTextureView.start()，这个能满足要求吗

**Comment by zjwjmmx** [comment]
我试过了，start后只会重新播放一遍，后面还是不播放了

**Comment by tanhx2008** [comment]
我的意思是：每次你都自己 start，自己实现循环播放，有什么问题没有？
如果按照你的需求修改，会影响大部分用户的处理逻辑

**Comment by tanhx2008** [comment]
我的意思是：每次你都自己 start，自己实现循环播放，有什么问题没有？
如果按照你的需求修改，会影响大部分用户的处理逻辑

**Comment by tanhx2008** [comment]
我的意思是：每次你都自己 start，自己实现循环播放，有什么问题没有？
如果按照你的需求修改，会影响大部分用户的处理逻辑

**Comment by Jhuster** [comment]
@zjwjmmx 每次收到 onCompletion 后，都调用一次 start()，已经可以满足要求了。

**Comment by zjwjmmx** [comment]
我前面说的start只会重新播放一遍就是放在onCompletion回调中。
我是这么做的，在onCompletion回调中，自己调用start()。第一次onCompletion回调，成功循环播放一遍。
但是在第二次onCompletion回调时start()却不会重新播放，（我确定第二次onCompletion回调已经执行了，start()也执行到了）不知道是不是我哪里没处理好？

**Comment by tanhx2008** [comment]
有小视频的播放源吗，我们验证下

**Comment by tanhx2008** [comment]
参考 Demo 的重连逻辑，我们用本地视频播放是没有问题的，可以实现自动播放

**Comment by tanhx2008** [comment]
<img width="686" alt="2017-01-04 09 26 52" src="https://cloud.githubusercontent.com/assets/6647525/21629164/7befaee8-d260-11e6-8806-a5f7e3eb773d.png">

**Comment by tanhx2008** [comment]
可以参考这段代码

**Comment by tanhx2008** [comment]
```
        private PLMediaPlayer.OnCompletionListener mOnCompletionListener = new PLMediaPlayer.OnCompletionListener() {
        @Override
        public void onCompletion(PLMediaPlayer plMediaPlayer) {
            Log.d(TAG, "Play Completed !");
            showToastTips("Play Completed !");
            boolean isNeedReconnect = false;
            if (isNeedReconnect) {
                sendReconnectMessage();
            } else {
                finish();
            }
        }
    };
```
