### ISSUE TITLE
在播放录屏推流的过程中，android播放器有一定概率，没有画面 后台一直出现onBufferingUpdate: 0，这是什么原因

### ISSUE THREAD

**Issue by cl1069573062** [pili-engineering/PLDroidPlayer#408]
同时首屏幕，需要7秒多，延迟大概有3秒

**Comment by Jhuster** [comment]
直播的话，onBufferingUpdate 的确是 0，首屏时间跟很多因素有关，播放器本身已经做到秒开了，目前需要看你的流是推到什么服务器了，服务器是否有做秒开的GOP缓存。偶尔没有画面的话，加大 AVOptions 的 probesize 参数试试

**Comment by cl1069573062** [comment]
我用PLVideoViewActivy时候把AVOptions 的 probesize的值调到 1024*1024 依然会出现没有画面，但是有声音的情况。 但是用PlMediaPlayerActivity用默认的probesize只是不停的在buffering 加载 ，但是不会出现没有画面只有声音的情况。

**Comment by Jhuster** [comment]
@cl1069573062 视频是什么编码，H.264? 只是同一台手机概率性出现看不到画面？用 ffplay 等其他播放器也是同样现象吗？

**Comment by cl1069573062** [comment]
我是用金山云录屏 编码是h.264  。  我用金山云自家的播放器也出现过。其他播放器没试过。只有用 PlMediaPlayerActivity不会出现， PlMediaPlayerActivity顶多就一直在加载，只要加载成功肯定有画面和声音。

**Comment by Jhuster** [comment]
@cl1069573062 初步判断，应该是推流端的问题，用其他播放器播放试试。

**Comment by cl1069573062** [comment]
恩恩 别的播放器也有。 当前的播放器出现的几率已经很小了。可能要从流媒体服务器上面做优化。 我用的流媒体服务器是nginx。 
请问，能监控到播放器当前的码流吗？我推流端是不推流声音的，如果回调函数OnInfoListener的case MEDIA_INFO_VIDEO_RENDERING_START 监控3秒内 码流都是0.就可以判断当前是黑屏，然后就重来一把就行了。
