### ISSUE TITLE
Firebase console Crash Reporting 

### ISSUE THREAD

**Issue by bogdanovkp** [pili-engineering/PLDroidPlayer#409]
`   android.util.Log.println_native (Log.java)
    android.util.Log.d (Log.java:139)
    com.qiniu.pili.droid.report.core.QosReporter.a (QosReporter.java:308)
    com.qiniu.pili.droid.report.core.QosReporter.a (QosReporter.java:171)
    com.qiniu.pili.droid.report.core.QosReporter.c (QosReporter.java:218)
    com.qiniu.pili.droid.report.core.QosReporter.a (QosReporter.java:22)
    com.qiniu.pili.droid.report.core.QosReporter$1.handleMessage (QosReporter.java:79)
    android.os.Handler.dispatchMessage (Handler.java:98)
    android.os.Looper.loop (Looper.java:148)
    android.os.HandlerThread.run (HandlerThread.java:61)
`

**Comment by tanhx2008** [comment]
0.8.17 版本已修复

**Comment by tanhx2008** [comment]
0.8.17 版本已修复

**Comment by tanhx2008** [comment]
多谢反馈，下一版本会修复
