### ISSUE TITLE
有的手机的mediaController不能顶到最上面

### ISSUE THREAD

**Issue by kangshifu** [pili-engineering/PLDroidPlayer#410]
有的android手机设置的meidaController不能顶到最顶端，与顶端有一定距离

**Comment by Jhuster** [comment]
@kangshifu `meidaController` 是支持完全自定义的，属于 SDK 外部的 UI 代码

**Comment by TimmyMa** [comment]
@kangshifu 用的是demo的代码吗，看一下popupwindow show的位置
