### ISSUE TITLE
pili-android-qos-0.8.16 集成问题

### ISSUE THREAD

**Issue by mogumodel** [pili-engineering/PLDroidPlayer#411]
这个库的打包方式是aar实际上只有包含代码没有资源文件，推荐使用jar的包来进行发布。其中有个values.xml文件包含app_name字符，基本上会和原有项目冲突。直接集成aar库会构建失败。

**Comment by Jhuster** [comment]
demo 测试过，不会冲突，跑下 demo 试试？

**Comment by Jhuster** [comment]
@mogumodel 你是说用 ·compile 'com.qiniu.pili:pili-android-qos:0.8.16'· 这个方式集成会失败吗？还是说下载下来后用 aar 集成会失败？aar 文件是可以解压为 jar 包的
