### ISSUE TITLE
添加jar包和项目中已引用的ijkplayer的冲突

### ISSUE THREAD

**Issue by WillXWell** [pili-engineering/PLDroidPlayer#416]
项目之前已经引用过ijkplayer，后来使用PLDroidPlayer自定义了一个播放器界面，现在不想回到ijkplayer重新写播放器界面了，请问有没有办法在不去掉原来引用的ijkplayer的前提下，同时使用PLDroidPlayer？

**Comment by Jhuster** [comment]
这个冲突没有办法，包名相同了，建议去掉 ijkplayer 的引用

**Comment by WillXWell** [comment]
好吧，谢谢了
