### ISSUE TITLE
自动播放下一首问题

### ISSUE THREAD

**Issue by wwllss** [pili-engineering/PLDroidPlayer#417]
使用的是PLVideoView控件，在PLMediaPlayer.OnCompletionListener回调中设置下一首的地址(PLVideoView.setVideoPath)，然后调用PLVideoView.start方法，视频不播放。

**Comment by tanhx2008** [comment]
播放的是本地视频还是网络视频，能提供下播放源吗？

**Comment by tanhx2008** [comment]
参考 Demo 的重新播放逻辑，我们用本地视频播放是没有问题的，可以实现自动播放

**Comment by tanhx2008** [comment]
<img width="686" alt="2017-01-04 09 26 52" src="https://cloud.githubusercontent.com/assets/6647525/21629128/3dd0b4fe-d260-11e6-9f83-0becd4f9e14c.png">

**Comment by tanhx2008** [comment]
可以参考这段代码

**Comment by tanhx2008** [comment]
```
        private PLMediaPlayer.OnCompletionListener mOnCompletionListener = new PLMediaPlayer.OnCompletionListener() {
        @Override
        public void onCompletion(PLMediaPlayer plMediaPlayer) {
            Log.d(TAG, "Play Completed !");
            showToastTips("Play Completed !");
            boolean isNeedReconnect = false;
            if (isNeedReconnect) {
                sendReconnectMessage();
            } else {
                finish();
            }
        }
    };
```

**Comment by wwllss** [comment]
播放源就是放在七牛云上的mp3文件，在OnCompletionListener的回调中设置下一首的地址，然后start不管用。只有重新设置VideoView，在设置AVOptions.KEY_START_ON_PREPARED是设置成1才算完成了连续播放的需求。。。

**Comment by tanhx2008** [comment]
参考上面的代码，或者参考 demo 中的重连逻辑的处理方法，可以实现连续播放的需求
