### ISSUE TITLE
Protocol not found,把http的播放地址换成https之后就播放不了，请问不支持https的地址播放么？

### ISSUE THREAD

**Issue by xinyitiandi** [pili-engineering/PLDroidPlayer#419]
https://oimgst244.qnssl.com/141%E7%AB%9E%E4%BA%89%E8%80%85.mp4

**Comment by Jhuster** [comment]
什么版本，最新的 demo 播放的吗？

**Comment by angularzues** [comment]
你把Jar包换成1.4.1版本就可以了，我之前也出现了这个问题。不止要把gradle配置依赖成最新的，jar包也要最新的。
