### ISSUE TITLE
使用1.1.4版本有可能会出现有声音没图像的情况！

### ISSUE THREAD

**Issue by DarklyCoder** [pili-engineering/PLDroidPlayer#42]
demo无法播放这个，我用暴风影音是可以打开的。这是链接 http://7xpa0v.media1.z0.glb.clouddn.com/0b0a4552f28eb98ba577f71f6e0724eb.mp4

**Comment by bbcallen** [comment]
```
    Stream #0:0(eng): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 480x480 [SAR 1:1 DAR 1:1], 282 kb/s, 30 fps, 30 tbr, 15360 tbn, 30 tbc (default)
```
mp4v is not include in default config.

**Comment by zhangqiyang** [comment]
为什么getCurrentPosition的返回值很大？

**Comment by jpxiong** [comment]
Video: mpeg4 (mp4v / 0x7634706D), none, 480x480, 282 kb/s

不支持的编码格式。如果要定制化，可以从[这里](https://github.com/jpxiong/ijkplayer)下载源码进行定制化。

**Comment by Kuki93** [comment]
视频不支持avi吗

**Comment by jpxiong** [comment]
如果要定制化，可以从[这里](https://github.com/pili-engineering/ijkplayer)下载源码进行定制化。
