### ISSUE TITLE
能不能支持下在线视频的多格式

### ISSUE THREAD

**Issue by FrankLove** [pili-engineering/PLDroidPlayer#421]
这个播放器播放rtmp流算是测试过的最流畅的了，感谢奉献。请问能不能多增加一些在线视频的格式支持，目前的版本支持的格式太少了，非常希望能够增加多一些的在线视频格式支持

**Comment by Jhuster** [comment]
目前的在线视频，rtmp-flv，HLV，HLS，mp4 这些最常见的协议或者格式都是支持的

**Comment by FrankLove** [comment]
上面的这些格式还是有点少，还有比如avi,rmvb,wmv.3gp,rm.mpeg这些格式也很常见了，能增加一下对这些格式的支持么，这个播放器的rtmp流真的优化的非常好，如果能增加对这些格式的支持就真的很棒了，真的非常希望能考虑下这个提议。

**Comment by Jhuster** [comment]
这个播放器 SDK 目前主打移动直播，支持太多其他格式的话，so 体积会变大，嗯，我们后期会考虑下单独提供支持更多格式的大 size 的 so

**Comment by FrankLove** [comment]
恩，好的。请问要在自己的项目中用这个播放器，是只要在app的bulid.grade文件中写这个就可以了吗？
    compile files('libs/pldroid-player-1.4.0.jar')
    compile 'com.qiniu:happy-dns:0.2.+'
    compile 'com.qiniu.pili:pili-android-qos:0.8.+'
我这样做，提示找不到so文件。是还要再把so文件拷贝的jnilibs目录里面吗

**Comment by Jhuster** [comment]
看下 wiki 文档吧，`https://github.com/pili-engineering/PLDroidPlayer/wiki/4-快速开始#4`
