### ISSUE TITLE
没有画面

### ISSUE THREAD

**Issue by xjguo75468722** [pili-engineering/PLDroidPlayer#422]
1、放在recyclerview里，暂停或者播放完成，然后将PLVideoTextureView或者PLVideoView滑出屏幕外，再滑回来，就会出现没有画面的情况。如果是播放状态就没事。
2、横竖屏切换，我的逻辑是再每个页面的最上面加一个撑满屏幕的布局，全屏时将PLVideoTextureView添加到全屏的布局里，竖屏时再添加回竖屏的布局，这个过程并没有新建PLVideoTextureView，用的都是一开始的PLVideoTextureView。 当在全屏时重新加载播放地址播放：
mVideoView.stopPlayback();
mVideoView.setVideoPath(videoUrl);
mVideoView.start();
再切回竖屏只有声音，没有画面。
横竖屏的activity已经设置 android:configChanges="orientation|keyboardHidden|screenSize"。
播放器的设置只有这一句mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);

gradle文件：
compile files('libs/pldroid-player-1.4.1.jar')
compile 'com.qiniu.pili:pili-android-qos:0.8.17'

jniLibs
arm64-v8a
armeabi
armeabi-v7a
x86
请问该怎么调试？谢谢

**Comment by Jhuster** [comment]
@xjguo75468722 

问题1： 播放完毕后，如果要手动重新播放，需要再设置一次 URL 然后调用 start

**Comment by Jhuster** [comment]
问题2: 不同 XML 里的 `PLVideoTextureView` 实例对象是不一样的，如果重新加载了 XML 布局，需要重新创建对象

**Comment by xjguo75468722** [comment]
@Jhuster 
问题1：手动暂停后，再滑动列表也是没画面了，没画面之后再次点击播放，又正常了
问题2：是一个XML，只不过全屏和竖屏是2个View，竖屏的时候全屏的View是隐藏的，全屏的时候把竖屏的播放器View的父布局remove，然后再 add到全屏的View里

**Comment by xjguo75468722** [comment]
@Jhuster 您那边是否能在demo里加一个横竖屏切换的功能
