### ISSUE TITLE
拉流直播很卡的问题

### ISSUE THREAD

**Issue by cat1024** [pili-engineering/PLDroidPlayer#426]
相同网络下，ios播放拉流比相对正常，而安卓端非常卡顿。应该是播放器的问题，请问一下有没有什么优化方案建议一下。
这是我的AVOptions 配置：

 AVOptions options = new AVOptions();
        options.setInteger(AVOptions.KEY_PREPARE_TIMEOUT, 30 * 1000);
        options.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 10 * 1000);
        options.setInteger(AVOptions.KEY_PROBESIZE, 128 * 1024);
        options.setInteger(AVOptions.KEY_LIVE_STREAMING, 1);
        options.setInteger(AVOptions.KEY_DELAY_OPTIMIZATION, 1);
        options.setInteger(AVOptions.KEY_MEDIACODEC, codecType);
        options.setInteger(AVOptions.KEY_START_ON_PREPARED, 1);
        mVideoView.setAVOptions(options);

**Comment by Jhuster** [comment]
@cat1024 什么 size 的流，高清吗？软解还是硬解，考虑把 `AVOptions.KEY_DELAY_OPTIMIZATION` 关闭试试看

**Comment by cat1024** [comment]
日志得到的onVideoSizeChanged: 720,1280，这个是流的size吗？    AVOptions.KEY_DELAY_OPTIMIZATION这个不是优化延时的的吗，拉流本身延时就有点严重了呀，设置的解码是自动AVOptions.MEDIA_CODEC_AUTO
