### ISSUE TITLE
切到后台切回来后花屏、黑屏问题

### ISSUE THREAD

**Issue by guodong89758** [pili-engineering/PLDroidPlayer#428]
播放状态切到后台，切回来后先花屏1-3s后才正常；
暂停状态切到后台，切回来后黑屏无法保留暂停时的画面；

**Comment by Jhuster** [comment]
@guodong89758 硬解从后台切换回前台花屏问题，下一个版本修复。第二个问题，由于 Android SurfaceView 切换到后台，View 会销毁，画面自然不会存在。

**Comment by wutongluxjtu** [comment]
@Jhuster 请教，在TextureView基础上，做哪些修改，可以解决硬解时，后台前换到前台 黑屏或者花屏的问题？

**Comment by tanhx2008** [comment]
1.5.0 版，PLVideoTextureView 已经修复该问题了
这个问题是由于 Android 的硬解机制引起的，所以，思路可以从硬解机制入手
