### ISSUE TITLE
SeekTo方法有问题？

### ISSUE THREAD

**Issue by linjian99666** [pili-engineering/PLDroidPlayer#429]
比如我的视频长度是60秒，我看到10秒的时候，拖动到开头的位置，也就是0秒的位置，播放时总是会从4~5秒的样子开始播放，始终不能从开始位置播放，或者是小于4秒的位置播放。一下子就跳到4秒左右播放。

**Comment by Jhuster** [comment]
@CrazyJamesLin 视频的第一帧是 I 帧吗，seek 是寻找最近的关键帧，换个视频试试

**Comment by CrazyJamesLin** [comment]
我用了三个视频都不行，都是不能seekto到第一帧，我感觉是seekbar的changlistener方法中mDurtion获取的的不对导致的，然后我直接设置seekto到0 或者1000或者2000依旧是不能到指定位置开始播放。

**Comment by jinyunfeng** [comment]
@CrazyJamesLin 你播放的hls吗，首先你需要确定你播放的前几秒钟是否有关键帧，如果有的话要确定关键帧在什么位置，一般开头的第一帧就是关键帧，如果播放器是hls的话，很有可能是seek的时候ffmpeg中pts计算出现了问题，解决这个问题，需要在ffmpeg中修改逻辑
