### ISSUE TITLE
播放本地mkv格式视频出错，mp4格式没有问题

### ISSUE THREAD

**Issue by wuyezhu** [pili-engineering/PLDroidPlayer#43]
以下是能找到的log：
Format aac detected only with low score of 1, misdetection possible!
Option http-detect-range-support not found.
More than one AAC RDB per ADTS frame
is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
Sample rate index in program config element does not match the sample rate index configured by the container.
Inconsistent channel configuration.
get_buffer() failed
Sample rate index in program config element does not match the sample rate index configured by the container.
decode_pce: Input buffer exhausted before END element found
channel element 3.5 is not allocated
channel element 3.5 is not allocated
channel element 3.6 is not allocated
Reserved bit set.

**Comment by wuyezhu** [comment]
新增日志：
01-12 13:58:29.762: E/IJKMEDIA(29515): invalid band type
01-12 13:58:29.762: E/IJKMEDIA(29515): Pulse data corrupt or invalid.
01-12 13:58:29.762: E/IJKMEDIA(29515): Dependent coupling is not supported together with LTP
01-12 13:58:29.912: W/IJKMEDIA(29515): file:///storage/extSdCard/视频/E16Venus.mkv: could not find codec parameters
该视频无法编解码？

**Comment by jpxiong** [comment]
could not find codec parameters

如果你需要加入对应的编码格式，可以下载[代码](https://github.com/jpxiong/ijkplayer)，然后自己定制化。
