### ISSUE TITLE
视频比例的问题,setDisplayAspectRatio

### ISSUE THREAD

**Issue by xjguo75468722** [pili-engineering/PLDroidPlayer#430]
ASPECT_RATIO_PAVED_PARENT 有一部分画面会显示不全
ASPECT_RATIO_16_9  画面又显示不全。

视频源没问题，IOS的就可以。我用vitamio也是可以的。
请问该怎么设置比较好呢？

**Comment by xjguo75468722** [comment]
这是布局
<RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@android:color/black">

            <com.pili.pldroid.player.widget.PLVideoTextureView
                android:id="@+id/videoView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_centerInParent="true"
                android:background="@android:color/black" />
</RelativeLayout>

**Comment by Jhuster** [comment]
@xjguo75468722 确定你测试的这台手机的屏幕尺寸比例跟流的长宽比例完全一致吗？

**Comment by xjguo75468722** [comment]
@Jhuster ASPECT_RATIO_16_9 是画面高度撑不满屏幕，宽度可以
横屏时手机的宽高为： w=1920, h=1080
视频宽高为：onVideoSizeChanged(PLMediaPlayer plMediaPlayer, int i, int i1)  
i=720, i1=576
手机型号为 华为mate8

**Comment by xjguo75468722** [comment]
竖屏时（16:9的高度小窗，）：
ASPECT_RATIO_PAVED_PARENT ：
画面会铺满，但是左边的画面显示不全
ASPECT_RATIO_16_9
画面正常显示，但是画面距离右边屏幕有个1像素的距离

横屏时：
ASPECT_RATIO_PAVED_PARENT ：
画面会铺满，但是左边的画面显示不全
ASPECT_RATIO_16_9
画面正常显示，左右也可以铺满屏幕，但是上下铺不满

**Comment by Jhuster** [comment]
@xjguo75468722 这个问题是个常识问题，一张 720x576 这个比例的图，是无法一点不剪裁和留黑就能做到铺满一个 1920 x 1080 的屏幕的

**Comment by xjguo75468722** [comment]
您看 IOS 的设备：
6	   :	750*1334（@2x）
6 Plus   :	1242*2208（@3x）
和1920 x 1080 的比例是一样的，但是IOS显示的就没问题呢。。。怪了

**Comment by xjguo75468722** [comment]
谢谢您，我加了这个属性就好了，非常感谢
android:layout_alignParentBottom="true"
android:layout_alignParentLeft="true"
android:layout_alignParentRight="true"
android:layout_alignParentTop="true"

**Comment by xjguo75468722** [comment]
@Jhuster  还有2个新问题：
1、我之前问的放在recyclerview里，暂停状态，滑出屏幕，再回来，是黑屏的状态
2、如果播放的视频读取buffer失败，或者其它错误，点击播放器时，控制栏（MediaController）显示不出来
3、MediaController里的onTouchEvent onTrackballEvent dispatchKeyEvent 不会触发

这三个问题您有好的建议吗？

**Comment by Jhuster** [comment]
新问题建议重开 issue，跟标题不符合

问题 1 ，是否设置的自动播放，应该需要重新 `setVideoPath`
问题 2,3 , 建议自己重新写一个 `MediaController` 吧，或者改下 `MediaController` 源码。
