### ISSUE TITLE
播放器断网没有重连

### ISSUE THREAD

**Issue by jiduqingqian** [pili-engineering/PLDroidPlayer#431]
播放器播放过程中，断开网络连接以后，播放完缓存视频，就直接回调PLMediaPlayer.OnCompletionListener(播放结束)。能不能做到断网重连呢？不是直播，是播放在线视频碰到的问题

**Comment by Jhuster** [comment]
@jiduqingqian `demo` 和 文档 都有演示和说明如何重连

**Comment by jiduqingqian** [comment]
在回调里面重连前需要释放下资源。
