### ISSUE TITLE
出于什么考虑会调用setMediaPlayer 和 setAnchorView 方法？

### ISSUE THREAD

**Issue by wogenhaosini** [pili-engineering/PLDroidPlayer#433]
我看demo 中 MediaController(Context context, boolean useFastForward, boolean disableProgressBar)   后两个参数  与 IMediaController.MediaPlayerControl接口中 有重合的方法，为什么 不放开 setMediaPlayer  而还是要自动赋值？

**Comment by wogenhaosini** [comment]
![29b7d7cc-7a99-4a5c-a23e-b811e3d34ec3](https://cloud.githubusercontent.com/assets/10138880/21885341/1e3d7c24-d8f2-11e6-89fa-9225fbb7ba76.png)
PLVideoTextureView 类 这里是出于什么考虑会调用`setMediaPlayer` 和 `setAnchorView` 方法？

**Comment by wogenhaosini** [comment]
@Jhuster  为何不回答我的问题？

**Comment by Jhuster** [comment]
为了简化外部调用，`PLVideoTextureView`没有必要暴露 `setMediaPlayer` ，目前的接口，是影响到使用了吗？

**Comment by wogenhaosini** [comment]
我觉得并没有简化外部调用，而是更加复杂，自定义controller还有很多ui上的回调，返回按钮，以及横竖屏之类的， `boolean useFastForward, boolean disableProgressBar` ，如果放开限制，这二个也可以直接在activity 中返回，而不用在传值。

**Comment by tanhx2008** [comment]
可以准确的描述下需求和目前的问题吗
