### ISSUE TITLE
播放视频错误errorCode = -1330794744

### ISSUE THREAD

**Issue by 1530120997** [pili-engineering/PLDroidPlayer#435]
E/IJKMEDIA: https://zuoyou365.com/upload/video/852326BA5F12D9CD0FC4B94A6784FC97.mp4: Protocol not found
01-13 14:02:25.074 20346-21395/com.banzuoyou.zuoyou I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [21395]
01-13 14:02:25.074 20346-21393/com.banzuoyou.zuoyou D/IJKMEDIA: FFP_MSG_ERROR: -1330794744
01-13 14:02:25.084 20346-20346/com.banzuoyou.zuoyou E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1330794744)
01-13 14:02:25.084 20346-20346/com.banzuoyou.zuoyou E/PLMediaPlayer: Error happened, what = -10000, errorCode = -1330794744
01-13 14:02:25.084 20346-20346/com.banzuoyou.zuoyou E/onError:: COED-1330794744

**Comment by Jhuster** [comment]
@1530120997 1.4.1 版本才支持 HTTPS
