### ISSUE TITLE
prepare timeout

### ISSUE THREAD

**Issue by 1530120997** [pili-engineering/PLDroidPlayer#436]
01-13 14:18:03.914 4026-5229/com.banzuoyou.zuoyou I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
01-13 14:18:03.914 4026-5229/com.banzuoyou.zuoyou E/IJKMEDIA: https://zuoyou365.com/upload/video/852326BA5F12D9CD0FC4B94A6784FC97.mp4: Immediate exit requested
01-13 14:18:03.914 4026-5226/com.banzuoyou.zuoyou D/IJKMEDIA: FFP_MSG_ERROR: -2001
01-13 14:18:03.914 4026-5227/com.banzuoyou.zuoyou I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5227]
01-13 14:18:03.914 4026-5229/com.banzuoyou.zuoyou I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [5229]
01-13 14:18:03.914 4026-4026/com.banzuoyou.zuoyou E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-2001)
01-13 14:18:03.914 4026-4026/com.banzuoyou.zuoyou E/PLMediaPlayer: Error happened, what = -10000, errorCode = -2001
01-13 14:18:03.914 4026-4026/com.banzuoyou.zuoyou E/onError:: COED-2001

**Comment by Jhuster** [comment]
@1530120997 你这个流的音频时间戳跟视频的时间戳相差比较大，你先看看
