### ISSUE TITLE
视频压缩播放问题

### ISSUE THREAD

**Issue by cat1024** [pili-engineering/PLDroidPlayer#437]
您好，我用本地相机拍摄的视频经过压缩处理后，在本地播放很流畅，但在上传服务器，从服务器拉下来的视频地址，用pldroidplayer 播放非常卡，经常要加载很长时间，播放也是一卡一卡的。这是视频地址：http://live.lalocal.cn/2017011418310410132385971081.mp4

**Comment by Jhuster** [comment]
@cat1024 你的视频有问题，音频时间戳跟视频时间戳相差特别大，导致音画同步错误，下面是我打印出来的时间戳信息：

```
audio frame readed, pts: 1024
audio frame readed, pts: 2048
video frame readed, pts: 94780
audio frame readed, pts: 3072
audio frame readed, pts: 4096
video frame readed, pts: 97775
audio frame readed, pts: 5120
video frame readed, pts: 100784
audio frame readed, pts: 6144
audio frame readed, pts: 7168
video frame readed, pts: 103771
audio frame readed, pts: 8192
video frame readed, pts: 106773
audio frame readed, pts: 9216
audio frame readed, pts: 10240
video frame readed, pts: 109768 
```

**Comment by cat1024** [comment]
可是这段视频在电脑上播放，手机本地播放，迅雷播放都是没有问题的呀。。。@Jhuster

**Comment by Jhuster** [comment]
@cat1024 你在电脑上用 ffplay 播放看看就知道了，也很卡，这个跟播放器的播控原理有关，我们的播放器是严格按照音视频帧的时间戳来做音画同步的，你应该不是直接用手机系统相机录的 mp4 文件吧？做个自己的处理？

**Comment by cat1024** [comment]
我是用相机录的，然后用代码对视频进行了压缩，难道压缩过程对声音和画面有影响。。。
