### ISSUE TITLE
使用播放器的导入so问题

### ISSUE THREAD

**Issue by tangxianqiang** [pili-engineering/PLDroidPlayer#438]
由于项目中使用了其他的so文件，需要放在libs文件夹下，然后通过sourceSet导入so文件，导入的cpu类型和官网的一样，一共4种，但是so文件不能成功调用。

**Comment by tanhx2008** [comment]
log 发出来看下

**Comment by tangxianqiang** [comment]
我现在把融云以模块形式加入了，现在可以用了。但是问题没有根本解决，日志很多，不知道该过滤哪些。。
