### ISSUE TITLE
播放缓冲的部分

### ISSUE THREAD

**Issue by kangshifu** [pili-engineering/PLDroidPlayer#440]
无网络的状况下,怎么设置参数还是要自己处理来已播放缓冲的部分

**Comment by Jhuster** [comment]
@kangshifu 如果是点播模式，会默认播放完缓冲部分，如果是直播，会直接回调错误

**Comment by WillXWell** [comment]
关于播放缓冲这里，我遇到一个问题：当视频缓冲了一部分时，模拟网络不稳定状况（断网，再恢复网络），视频不会继续缓冲；把缓冲播放完后，调用了completeListener，视频剩下的部分不会再缓冲和播放了。

**Comment by WillXWell** [comment]
@Jhuster 前面我说的这个问题，请问有解决办法吗？

**Comment by Jhuster** [comment]
@WillXWell 收到 onCompleted 消息后，判断 getCurrentPosition 是否 = getDuration， 如果不等于，则还没播放完毕，重连，seek 到当前播放的位置

**Comment by WillXWell** [comment]
@Jhuster 好的，谢谢！
