### ISSUE TITLE
concat多段视频拼接播放

### ISSUE THREAD

**Issue by wuyezhu** [pili-engineering/PLDroidPlayer#441]
多段视频拼接播放需求，参照ijk[ issues211](https://github.com/Bilibili/ijkplayer/issues/211)做法，创建了test.concat文件，内容类似：
`ffconcat version 1.0
file '/sdcard/1.mp4'
duration 3.0
file '/sdcard/2.mp4'
duration 3.0
file '/sdcard/3.mp4'
duration 3.0`
遇到以下错误：
Unsafe file name
Operation not permitted
根据研究应该是要设置以下参数
` IjkMediaPlayer ijkMediaPlayer = new IjkMediaPlayer();
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT,"safe",0);`
那，我们能否在PLMediaPlayer的setAVOptions中给出相关解决方案？或者有其他解决办法？
（单文件过大，无法用m3u8格式解决）

**Comment by wuyezhu** [comment]
已经用
` IjkMediaPlayer ijkMediaPlayer = new IjkMediaPlayer();
        ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "safe", 0);`
加SurfaceView解决这个问题，但是这样需要用两套播放逻辑，希望PLMediaPlayer能增加相关参数设置
thx

**Comment by tanhx2008** [comment]
感谢反馈，我们会考虑透传 setOption 接口的
