### ISSUE TITLE
从斗鱼html标签里截取的地址不能播放？

### ISSUE THREAD

**Issue by adugmcool** [pili-engineering/PLDroidPlayer#442]
http://hls3a.douyucdn.cn/live/619643ruutTA2VDW_550/playlist.m3u8?wsSecret=d1dbb4cfd5e04c3f3ec0cdb5690cfda2&amp;wsTime=1484629593  这种格式的地址？

**Comment by panden** [comment]
这个是接口地址吧？正常网页播放视频文件地址后面应该是一个文件名，例如：http://XXXXX/XXX.mp4

**Comment by Jhuster** [comment]
@adugmcool 这个流斗鱼服务器那边禁止拉流了，返回的是 `Server returned 403 Forbidden (access denied)`

**Comment by adugmcool** [comment]
wsSecret=d1dbb4cfd5e04c3f3ec0cdb5690cfda2&amp;wsTime=1484629593  这串地址 每隔5分钟会变   测试时需要先去获取最新的地址 才可以 我用的 https://github.com/umdk/UCDMediaPlayer_Android这个播放器 可以播放 但是非常不流畅  经常停顿 。
