### ISSUE TITLE
请问为什么这个地址安卓现在没法播放了？以前推流后安卓ios都可以播放。

### ISSUE THREAD

**Issue by qssq666123** [pili-engineering/PLDroidPlayer#443]
http://pili-media.huluboshi.com/recordings/z1.hulu.587f0fd168d03f12b0047ef7/587f0fd168d03f12b0047ef7.mp4 不

**Comment by qssq666123** [comment]
现在是有声音没图像，我这里全部换成ikplayer也很累。。。如果能解决就最好了，不得已还是先不换那个。

**Comment by Jhuster** [comment]
@qssq666123 这个流本身有问题，音视频时间戳不对，相差太大，ffplay 也播放不出图像

```
video frame readed, pts: 3418
audio frame readed, pts: 12283
video frame readed, pts: 3840
audio frame readed, pts: 13307
audio frame readed, pts: 14331
video frame readed, pts: 4275
audio frame readed, pts: 15355
video frame readed, pts: 4698
audio frame readed, pts: 16379
```

**Comment by qssq666123** [comment]
不好意思 貌似发错地址了

，现在安卓推得流ios安卓都没法看了，而昨天ios就可以，搞不懂规律了都。
下面这个地址是安卓不可以ios可以看
video=http://pili-media.huluboshi.com/recordings/z1.hulu.58802395818c6242ee096e20/58802395818c6242ee096e20.mp4




这个地址是安卓不可以ios也不可以。这是 ui那边做视频的弄的地址

video=http://v.huluboshi.com/201612/20161221173310.mp4




另外 但是昨天的那个我推流产生的回放地址ikpllayer可以播放 ios也可以播放，而七牛的播放器不行了，

头大。。。。 昨天那个也是我推的。

http://pili-media.huluboshi.com/recordings/z1.hulu.587f0fd168d03f12b0047ef7/587f0fd168d03f12b0047ef7.mp4",

**Comment by qssq666123** [comment]
另外 你说的那个视频音频差距这么大是怎么导致的呢 这都是使用你们的推流框架产生的额。

**Comment by Jhuster** [comment]
@qssq666123 你确定是用我们的推流产生的？你播放下 RTMP 流吧。 这几个视频都是同一个问题，音视频时间戳差异太大，请找你们服务端的人，可能是他们把 RTMP 流转为 mp4 出问题了。

**Comment by qssq666123** [comment]
只有http://v.huluboshi.com/201612/20161221173310.mp4 是格式转换出现的问题，但是这个地址时间戳吧。。其他播放都能播放。。

**Comment by qssq666123** [comment]
我不懂那个专业术语，是不是软件分析时间戳出错了呢？毕竟能播放的播放器还是有的。

**Comment by qssq666123** [comment]
http://v.huluboshi.com/201612/20161221173310.mp4  这个ikplayer也播放不了。ios可以。。但是http://pili-media.huluboshi.com/recordings/z1.hulu.587f0fd168d03f12b0047ef7/587f0fd168d03f12b0047ef7.mp4", ikplyaer可以。

**Comment by Jhuster** [comment]
@qssq666123 时间戳分析不会出错，验证过其他流。 不同播放器的原理不同，时间戳是做音画同步最重要的信息。原因已经指出，建议先不去找找视频源头的问题

**Comment by qssq666123** [comment]
关键是 2016这个视频是格式转换出呀，ios也正常呀，时间戳对得上呀。 那问题应该怎么搞，今天的地址和昨天的  hulu.****都是安卓产生的，现在的情况很严重啊只要是安卓推送的安卓百分之百看不了。。  ios也是用的你们的却可以，pldroid-camera-streaming-1.6.2.jar

**Comment by Jhuster** [comment]
@qssq666123 你试试最新的 2.x 版本

**Comment by qssq666123** [comment]
嗯，貌似是没关闭流成功的问题，不过 对于这种视频有待改进哦!毕竟ios和 ikplyaer是可以播放的。
