### ISSUE TITLE
竖屏视频播放自动变成横屏问题

### ISSUE THREAD

**Issue by likaiyuan559** [pili-engineering/PLDroidPlayer#444]
视频是360*640的，播放时自动旋转了-90°。
如果视频是640*360的话，则是正常的。
请问改用什么参数去设置？

**Comment by Jhuster** [comment]
`mVideoView.setDisplayOrientation(90); // 旋转90度`

**Comment by likaiyuan559** [comment]
我横屏的视频并不想让它旋转，需要自己监听OnVideoSizeChangedListener？

**Comment by Jhuster** [comment]
横屏录制的 `360 x 640` 视频不太常见，你可以自己监听 `OnVideoSizeChangedListener` 然后设置下播放角度吧

**Comment by likaiyuan559** [comment]
不，现在比较奇怪的是，这个视频本来就是360x640的，我在任何播放器播放都是竖屏的，代码中也没有设置参数，但是播放的时候，自动旋转了-90°，也就是自动变成横屏播放了。

**Comment by likaiyuan559** [comment]
mVideoView.setDisplayOrientation(90);没有作用，我是这样做的。

private PLMediaPlayer.OnVideoSizeChangedListener mOnVideoSizeChangedListener = new PLMediaPlayer.OnVideoSizeChangedListener() {
        @Override
        public void onVideoSizeChanged(PLMediaPlayer plMediaPlayer, int width, int height) {
            if(width < height && mVideoView != null){
                mVideoView.setDisplayOrientation(90);
            }
        }
    };

**Comment by likaiyuan559** [comment]
问题排查后，发现视频是640x360的，但是视频本身的orientation参数是90°，PLDroidPlayer好像并没有拿到这个参数去做自动的旋转，请问我该如何拿到视频本身的orientation参数？

**Comment by Jhuster** [comment]
```
private PLMediaPlayer.OnInfoListener mOnInfoListener = new PLMediaPlayer.OnInfoListener() {
        @Override
        public boolean onInfo(PLMediaPlayer plMediaPlayer, int what, int extra) {
            Log.d(TAG, "onInfo: " + what + ", " + extra);
            switch (what) {
                case PLMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED:
                    Log.d(TAG, "MEDIA_INFO_VIDEO_ROTATION_CHANGED: " + extra);

                    break;
            }
            return false;
        }
    };
```

**Comment by likaiyuan559** [comment]
为何这样设置无法旋转？

case PLMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED:
                    DebugTool.warn("MEDIA_INFO_VIDEO_ROTATION_CHANGED: " + extra);
                    mVideoView.setDisplayOrientation(extra);
                    break;

**Comment by Jhuster** [comment]
这个接口不是旋转的意思，而是以什么角度播放，你试试传入 0

**Comment by likaiyuan559** [comment]
为何Demo中setDisplayOrientation(int)有效，而我项目中无论如何调用却无效，我能保证代码已经走了，传入的值也一定是90的整除数，还需要注意哪些？

**Comment by likaiyuan559** [comment]
请问PLVideoTextureView的onFinishInflate()会在什么时候调用，这里调试发现PLVideoTextureView-->View a为null，导致onLayout的后续并没有执行，而setDisplayIOrientation(int)设置后无效。

**Comment by likaiyuan559** [comment]
这是Demo的调试情况：
![image](https://cloud.githubusercontent.com/assets/18045170/22140824/c7b1e8ca-df29-11e6-90f7-3b00aeab96c7.png)

这是我项目中调试的情况：
![image](https://cloud.githubusercontent.com/assets/18045170/22140845/eaa4fe76-df29-11e6-94ab-f37491972d71.png)

请问这是为何？

**Comment by likaiyuan559** [comment]
搞定了，因为我的PLVideoTextureView之前是new出来的，所以出现了这个问题。希望可以考虑一下兼容直接new PLVideoTextureView的情况。

**Comment by Jhuster** [comment]
嗯，好的，多谢反馈

**Comment by qssq666123** [comment]
plvideoview为什么没有setDisplayOrientation

**Comment by kexingmo** [comment]
同样遇到这个问题，特别坑，浪费了1天在解决这个问题：视频宽高比跟屏幕宽高比一样的时候，就莫名其妙旋转90

最后我的解决办法是：

// 这个是为了解决旋转角度的问题，视频宽高比例跟屏幕宽高比例一样的时候会旋转90度的问题
        mVideoView.setOnInfoListener(new PLMediaPlayer.OnInfoListener() {
            @Override
            public boolean onInfo(PLMediaPlayer plMediaPlayer, int what, int extras) {
                if(what == PLMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED){
                    if(extras != 0 ) {
                        mVideoView.setDisplayOrientation(Math.abs(360 - extras));
                    }
                }
                return false;
            }
        });

**Comment by kexingmo** [comment]
另外补充一点，明明垂直的视频，莫名其妙选择90度，使用getDisplayOrientation得到的值是0，不能理解
