### ISSUE TITLE
setCoverView问题，视频播放后图片不隐藏

### ISSUE THREAD

**Issue by longchenpl** [pili-engineering/PLDroidPlayer#445]

**Comment by longchenpl** [comment]
mVideoView.setBufferingIndicator(mVideoLoding);
        ImageView img = (ImageView) getActivity().findViewById(R.id.img_video_bg);
        mVideoView.setCoverView(img);

**Comment by tanhx2008** [comment]
能详细描述下吗？用我们 demo 测试是否正常

**Comment by longchenpl** [comment]
你们demo是正常的

**Comment by longchenpl** [comment]
log中有个Option ijkapplication not found.

**Comment by tanhx2008** [comment]
和这个没关系，参考 demo 中的代码，对比下看是否能解决呢？

**Comment by longchenpl** [comment]
我再研究下  好像跟我的代码位置有关系  我想知道它是怎么判断的

**Comment by tanhx2008** [comment]
播放器成功播放后，会把这个 view 隐藏掉
可以试下接到播放器开始播放的消息回调后，应用层主动隐藏是否 OK？

**Comment by longchenpl** [comment]
手动隐藏是可以的

**Comment by tanhx2008** [comment]
那就比较奇怪了，是最新版本吗？

**Comment by longchenpl** [comment]
谢谢大神  不好意思啊   我发现是我代码写的有问题

**Comment by tanhx2008** [comment]
找到问题就好

**Comment by longchenpl** [comment]
ImageView img = (ImageView) view.findViewById(R.id.img_video_bg);
        mVideoView.setCoverView(img);      我获取imagview的方式 有问题   但是不太理解为什么错了

**Comment by cuibg** [comment]
我的设置coverview没有任何反应，coverview模式是显示状态
