### ISSUE TITLE
setOnTouchListener

### ISSUE THREAD

**Issue by xjguo75468722** [pili-engineering/PLDroidPlayer#446]
如果没有开始播放，或者播放失败。播放器的View或者父View无法监听到setOnTouchListener或者onClick事件

**Comment by xjguo75468722** [comment]
就是还没缓冲好的时候

**Comment by tanhx2008** [comment]
是在 demo 中吗？用的哪个组件播放的？

**Comment by tanhx2008** [comment]
PLVideoTextureView 和 PLVideoView 是在播放状态下才会响应触摸事件，当然，您也可以自定义自己的播放响应视图，这样应用层可以完全控制 view 上的事件

**Comment by xjguo75468722** [comment]
@tanhx2008  谢谢。
1、我想事件的问题，不知道您那能否支持下？
因为大多数视频软件的播放界面都比较复杂（需要捕获事件操控播放器的View）。尤其当播放视频出问题的时候，这个播放器就像僵死了一样。
如果大家都使用PLMediaPlayer自定义视图，那PLVideoTextureView 和 PLVideoView 是不是用处小了好多。

2、请教下黑屏的问题:
当视频暂停时，按手机的home或者菜单键、再切回来，会黑屏（start继续播放的话画面就又出来了），有没有更好的办法？
我都注释了也不行
@Override
        public void surfaceDestroyed(SurfaceHolder holder) {
            // release();
            //releaseWithoutStop();
        }

**Comment by tanhx2008** [comment]
1、能完整的描述下你们的需求吗？我们评估下
2、PLVideoTextureView 在下一版本会修复该问题。

**Comment by xjguo75468722** [comment]
事件：
1、播放器横屏时有弹幕、相关视频、收拾滑动、码率切换、锁屏等几个功能布局，当用户点击的时候从屏幕滑出来，理想的操作是用户点击视频画面任意一个位置去隐藏滑动出来的View。如果监听不到事件（网络不好视频缓冲时间长，或者断网播放，或者播放的视频本身有问题），只能让用户去点击相对应的的布局按钮去隐藏（这样的体验非常不好）。

黑屏：
您可以用demo里的测试下，如果把视频暂停，按home键回到桌面，再次返回应用（onResume不要调用mVideoView.start();），或者放在recyclerview这种列表控件里，当视频View暂停状态，滑出屏幕，再次滑动回来，视频就会黑屏。 当点击再次播放start的时候，还是可以正常播放（黑屏的体验不好）。

**Comment by xjguo75468722** [comment]
我发现 MediaController 的 show() 和 hide() 也只有在正常播放的时候才会触发。再监听不好setOnTouchListener事件，开发者无法自已调用show() 和 hide() 。
这个体验也非常不好

**Comment by tanhx2008** [comment]
1、这些与播放器关系不大，应用层都可以实现自己的用户逻辑，播放器不回作更多的 UI 上的工作
2、黑屏：
软解不存在这个问题
硬解会在 PLVideoTextureView 上彻底修复，PLVideoView 由于系统硬解的机制，无法完全避免

**Comment by xjguo75468722** [comment]
@tanhx2008  好的，谢谢。
