### ISSUE TITLE
protocol not found

### ISSUE THREAD

**Issue by jrsadik7** [pili-engineering/PLDroidPlayer#45]
Protocol not found
/com.pili.android.playerdemo I/IJKMEDIA﹕ SDL_RunThread: [19156] ff_vout
/com.pili.android.playerdemo E/tv.danmaku.ijk.media.player.IjkMediaPlayer﹕ Error (-10000,-1330794744)

**Comment by longbai** [comment]
麻烦贴下 播放地址
