### ISSUE TITLE
PLVideoTextureView 可以播放rtsp只有画面没有声音

### ISSUE THREAD

**Issue by MrDavy** [pili-engineering/PLDroidPlayer#450]
请问PLVideoTextureView 可以播放rtsp，延时也很低 ，但是只有画面没有声音，是什么原因呢

**Comment by Jhuster** [comment]
@MrDavy 音频什么编码格式，流地址发出来看看

**Comment by MrDavy** [comment]
流是通过在Android手机安装screen stream mirroring软件产生的rtsp协议的流

**Comment by MrDavy** [comment]
查了下，视频格式：RTP h.264  音频格式：MP4A-LATM

**Comment by Jhuster** [comment]
@MrDavy 目前你是用什么版本测试的，1.4.1 应该已经支持 “MP4A-LATM”
