### ISSUE TITLE
m3u8播放问题

### ISSUE THREAD

**Issue by XiaMengjian** [pili-engineering/PLDroidPlayer#451]
请问 http://cache.m.iqiyi.com/dc/dt/e975e0fx2fe1890fx777a6171/20170206/7a/5c/744f39dfd8809aec8b03475232e32f96.m3u8?np_tag=nginx_part_tag&qd_sc=e4454c59560666dd975bd0a600a7a6b8&t_sign=-0-76f90cbd92f94a2e925d83e8ccd22cb7-612810200_04022000001000000000_17 

不能正常播放，是什么原因？谢谢

**Comment by Jhuster** [comment]
@XiaMengjian 地址有误，Safari 浏览器和 ffplay 都无法播放

**Comment by XiaMengjian** [comment]
@Jhuster 在ffplay上面我也试了下，不能播放，但是通过VLC 这个确实是可以播放的，请问这个是哪边的问题？

**Comment by Jhuster** [comment]
@XiaMengjian 流的数据不完整或者不正确，“ Invalid data found when processing input”

**Comment by XiaMengjian** [comment]
@Jhuster 好的，谢谢

**Comment by XiaMengjian** [comment]
你好，还有一个问题想请教一下，就是关于分段视频，该怎么处理，有没有具体的参考实例或者文档提及的？
