### ISSUE TITLE
播放MP4的时候出现一个Protocol not found错误

### ISSUE THREAD

**Issue by zc9** [pili-engineering/PLDroidPlayer#452]
tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1330794744)
 E/IJKMEDIA: http://hniptv.s.qupai.me/v/a82f3282-2abc-4e43-9447-8fda24e2cb9c.mp4?token=kFVQJFMzdVaZ1WeFlGSWJWZNh1SVd3KYFHaRBiZkRmZjdzMlBTZyYTNzkjYiJmM0YWY3ETOwIjN2QzNhBSM4Y2Y1IWZ2YzNjhTOwIDIyAiM3MTM0MDN5QTM: Protocol not found

**Comment by Jhuster** [comment]
@zc9 我用 demo 测试，可以播放

**Comment by zc9** [comment]
换成新版本可以了

**Comment by yjy951753** [comment]
好像的确不能播放。。。
