### ISSUE TITLE
腾讯视频这类链接无法正常播放

### ISSUE THREAD

**Issue by ghost** [pili-engineering/PLDroidPlayer#454]
我随便从腾讯网上找的一个视频，然后复制了flash地址和通用代码的链接，这两个链接用浏览器打开都是可以播放视频的，但是在您的Demo中替换DEFAULT_TEST_URL值为这两个链接，都无法正常播放，报错
`E/PLMediaPlayer: Error happened, what = -10000, errorCode = -1094995529`
能帮我解决一下这个问题吗？我的项目中都是这种链接...

flash地址：
https://imgcache.qq.com/tencentvideo_v1/playerv3/TPout.swf?max_age=86400&v=20161117&vid=h0374vgow2c&auto=0

通用地址：
https://v.qq.com/iframe/player.html?vid=h0374vgow2c&tiny=0&auto=0

**Comment by Jhuster** [comment]
@KevinsGitHub 你需要传入具体的播放地址，而不是一个网页地址，网页地址只有浏览器能打开，而不是播放器，首先你先用 ffplay 或者 vlc 播放一下你的地址吧，类似这样的 URL： rtmp://xxxx.com/xxxx.flv ，http://xxxx.com/xxxx.mp4
