### ISSUE TITLE
点播，播放过程中无网络的问题

### ISSUE THREAD

**Issue by huazidev** [pili-engineering/PLDroidPlayer#455]
有个问题，点播，在播放过程中如果网络，在播放完缓冲的视频后，过一会这个播放器好像就无效了，而且你们的IMediaController也不会再有其他的回调，此时如果有网络后，播放器会从头开始播放，如何才能从之前的位置播放？还有个问题就是拖动进度条的时候偶尔会回到开头播放，播放的视频是直播中生成的mp4文件，目前没有找到什么原因，试了试demo也偶尔会有这种情况。请问关于这两个问题有没有什么解决思路？

**Comment by Jhuster** [comment]
@huazidev 

1. 如何在重连后恢复上次的播放位置

实时记录当前播放的 position，重连后 seek 到该 position

2. 拖动进度条的时候偶尔会回到开头播放

mp4 文件在生成过程中可能有时间戳问题，需要进一步分析下文件，可以用 VLC 等第三方播放器 seek 到同一个位置试试，也可以把有问题的文件上传到网盘，把链接分享过了，告知seek到第几秒出现问题，我们抽空帮你分析下

**Comment by huazidev** [comment]
多谢，另外我们直播使用的你们的服务，mp4文件也是通过你们文档方法生成的，再碰到问题时会把视频链接给你们
