### ISSUE TITLE
怎么切换视频播放

### ISSUE THREAD

**Issue by hansionit** [pili-engineering/PLDroidPlayer#456]
比如我有一个视频的地址集合，现在在播放第一个，我在播放视频的时候切换至第二个，应该调用PLMediaPlayer的哪些方法

**Comment by Jhuster** [comment]
@hansionit 如果你是用的 PLXXXVideoView 的话，那么 setVideoPath 即可

**Comment by Jhuster** [comment]
@hansionit 其实，参考 demo 重连的写法即可

**Comment by hansionit** [comment]
@Jhuster 如果用PLMediaPlayer该怎么写呢？调用setVideoPath会报错

**Comment by Jhuster** [comment]
@hansionit 参考对应的 Activity 的重连流程
