### ISSUE TITLE
关于m3u8播放的问题

### ISSUE THREAD

**Issue by hcadoid** [pili-engineering/PLDroidPlayer#458]
1.对于们m3u8格式的，seekTo每次都会不准确，会快进，且seekTo(0)也是不会从第一帧播放，会跳个几秒钟，在播放完成后OnCompletionListener回调中getCurrentPosition与getDuration不相等。
2.在播放过程中，缓存了一部分后，断开连接了，又重新连接上，不重新走OnErrorListener？当播放到缓存结束的位置后，回调到了OnCompletionListener中，那怎么去重连呢？如上述OnCompletionListener中的getCurrentPosition与getDuration不相等，记录的位置重新seekTo也不太好判断。

**Comment by Jhuster** [comment]
@hcadoid `getCurrentPosition` 需要实时获取，不能在 `onError` 中获取，另外，点播模式下，`onCompletion` 的时候，如果跟 `getDuration()` 不相等的话，可能出现错误，而不是正常结束了

**Comment by hcadoid** [comment]
@Jhuster 
1.没有在onError 获取getCurrentPosition 的，onError中获取基本上获取到的是0，getCurrentPosition 是实时监控的，正常播放完成的视频走onCompletion的回调和getDuration也是不相等的。且seekTo的老是不准，连seekTo(0)都会跳帧几秒感觉。。。视频是在你们云平台上转码切片的ps:（https://o4jeap1oz.qnssl.com/5299011705449381888_360p_v1.m3u8?v=10003）
2.如上次说的，断开连接后重新连接后，播放完缓存后走onCompletion，感觉应该算是异常吧。。走onCompletion不太好去重连
