### ISSUE TITLE
请问这个播放器有没有什么方式获取实时网速

### ISSUE THREAD

**Issue by huazidev** [pili-engineering/PLDroidPlayer#459]
我们这边有个需求，就是现实下直播过程中，观众端接受的网速，七牛的播放器有没有什么方式可以获取实时的网速，看ijkplayer的issue中说是可以按照ios方式去改，https://github.com/Bilibili/ijkplayer/issues/1072

**Comment by Jhuster** [comment]
@huazidev 下一个版本提供实时播放的码率获取接口
