### ISSUE TITLE
视频源宽高比例发生变化时怎么重新计算？

### ISSUE THREAD

**Issue by yuanhejie** [pili-engineering/PLDroidPlayer#460]
目前用的ASPECT_RATIO_PAVED_PARENT ，在播放时，视频源的宽高发生变化了，如果从1:1变成4:3。还是会按1:1计算。怎么才能重新计算宽高比呢

**Comment by Jhuster** [comment]
@yuanhejie 在收到 `onVideoSizeChanged`消息后 ，调用 `mVideoView.requestLayout()` 或者重置播放试试

**Comment by nervending** [comment]
可惜视频如果是硬解的情况onVideoSizeChanged 根本不会回调
