### ISSUE TITLE
播放assets目录下的音频文件的问题

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#461]
使用PLMediaPlayer播放assets目录的音频文件时问题：
1.AVOptions不能设置这个构造参数,不然无法播放音频;
2.不能一直回调setOnBufferingUpdateListener里面的进度监听;
3.不能回调OnCompletionListener方法无法循环播放.
求解答.

**Comment by Jhuster** [comment]
我记得是不支持 assets 的播放的，你的问题再详细展开描述下？

**Comment by yanxiandroid** [comment]
@Jhuster 支持assets文件播放,我试过可以播放,只是不能监听,也不能设置播放参数.

**Comment by yanxiandroid** [comment]
@Jhuster 不过我用原生的MeiaPlayer解决播放解决了音频播放问题,可能是PLMediaPlayer针对assets目录的播放没有去做处理.这里只是issue一下你们

**Comment by Jhuster** [comment]
@yanxiandroid 嗯，多谢，回头我们看看
