### ISSUE TITLE
1.4.1版本，直播中播放状态切换到后台回来后会频繁触发 701 、702，而画面并无卡顿

### ISSUE THREAD

**Issue by timesfire** [pili-engineering/PLDroidPlayer#463]
用的是直播模式：
首次进入直播，播放正常，切换到后台再回来直播画面正常播放并无卡顿
但会频繁触发卡顿的消息回调701、702，此时设置的setBufferingIndicator view 会闪烁，
每次切换都会这样。版本是 1.4.1
求解~

**Comment by Jhuster** [comment]
@timesfire 嗯，多谢反馈，的确测到偶尔出现这个问题，建议先改用 1.4.0，我们近期在下一版本修复

**Comment by timesfire** [comment]
@Jhuster (版本1.4.1）现在是这样处理的，直播时，从暂停状态切换到播放状态，轮询(间隔1s)通过接口getPlayerState()获取播放器的状态，有些时候会长时间返回PAUSED状态，而画面早已经开始播放，这个获取播放器状态不是实时的吗？或者有没有方法可以监听到播放器成功开始播放？

**Comment by tanhx2008** [comment]
我们确认下

**Comment by timesfire** [comment]
@Jhuster 
频繁访问getPlayerState()这个接口会不会造成播放器卡顿？
测试时发现在没有轮询接口的情况下从暂停切换到播放比有轮询状态切换会快些(通过画面播放体现的）

**Comment by tanhx2008** [comment]
轮询的间隔是多少？

**Comment by timesfire** [comment]
@tanhx2008  轮询访问的时间是 1s

**Comment by tanhx2008** [comment]
没有必要轮询播放器状态，状态改变后，会有消息回调的，或者在需要判断状态时，在主动获取下

**Comment by timesfire** [comment]
@tanhx2008  
直播模式，首次播放onInfoListener会有相应的状态变更消息回调，当播放器从播放状态转为暂停，然后再切换到播放状态，这个过程在onInfoListener回调中只会有701、702卡顿消息输出。此时怎样判断播放器什么时间开始正常播放？

**Comment by everfire130** [comment]
我也想问一下如何监听 playerState的变化，onInfoListener对应不了播放状态
