### ISSUE TITLE
播放界面如何修改

### ISSUE THREAD

**Issue by Ly-cc** [pili-engineering/PLDroidPlayer#464]
播放界面不支持自定义吗？进度条什么的很丑

**Comment by Jhuster** [comment]
@Ly-cc 支持，进度条是 demo 源码开放的，随意改

**Comment by Ly-cc** [comment]
我用PLVideoTextureView，进度条的代码好像是PLVideoTextureView内部的，不支持。

**Comment by Jhuster** [comment]
@Ly-cc 你仔细看看代码，是外部的

**Comment by Ly-cc** [comment]
嗯，我错了
