### ISSUE TITLE
rtmp直播流，点播可以播放，但是直播播放不了

### ISSUE THREAD

**Issue by libill** [pili-engineering/PLDroidPlayer#469]
rtmp直播流，点播可以播放，但是直播播放不了
看log发现：
IJKMEDIA: Server error: NetStream.Play.StreamNotFound
Operation not permitted

**Comment by Jhuster** [comment]
@libill 流地址发出来看看

**Comment by libill** [comment]
rtmp://itvtest1java2.southeastasia.cloudapp.azure.com:5898/live/room1234

**Comment by libill** [comment]
@Jhuster 用这个推拉流地址，可以用直播播放吗？是什么问题引起的

**Comment by Jhuster** [comment]
@libill 流停止了，ffplay 也播放不了

**Comment by libill** [comment]
@Jhuster 这个链接是可以推流的，先推流，然后测试再直播播放
