### ISSUE TITLE
[rtmp]some video no sound only picture

### ISSUE THREAD

**Issue by otizis** [pili-engineering/PLDroidPlayer#47]
是RTMP点播视频MP4格式，大部正常播放，一部分视频只有画面没有声音。
如果把options.setInteger(AVOptions.KEY_LIVE_STREAMING, 1)设置上去，都可以有声音，但是视频前3秒都会丢失。
options.setInteger(AVOptions.KEY_MEDIACODEC, 0)也没有效果
最新版本1.1.4

**Comment by otizis** [comment]
有声音的视频，声音的handler是SoundHandler
没有声音的视频，handler是Sound Media Handler
其他都是一样的。

**Comment by jpxiong** [comment]
v1.2.0 已经解决该问题，预计下周更新

**Comment by otizis** [comment]
非常感谢，强烈期待V1.2.0版本！

**Comment by hellwu** [comment]
我也遇到这种情况，什么时候更新啊？？？

**Comment by wu-haiwei** [comment]
这个问题严重吗, 我们正在技术选型, 有没有进展,

**Comment by otizis** [comment]
@wu-haiwei 影响的范围20%的视频左右，重新处理视频内容工作量巨大
@jpxiong 是否有临时处理办法，等版本更新的话，心里没底

**Comment by hellwu** [comment]
@jpxiong 版本更新日期能确定下来吗？？？

**Comment by hellwu** [comment]
快点更新吧，急得上火啊

**Comment by longbai** [comment]
下周三合并更新，实在抱歉

**Comment by hongye612430** [comment]
@longbai  能不能先给个beta版，我在做选型测试，本周六加班给出报告，如果方便邮件给我382539376@qq.com  
@wu-haiwei ，你们技术选型都有哪些开源播放器？

**Comment by hellwu** [comment]
@longbai 说好的周三更新呢？？

**Comment by longbai** [comment]
@hellwu 快了，在做多机型 测试，这个要花些时间

**Comment by otizis** [comment]
问题解决了，多谢

**Comment by hellwu** [comment]
干得漂亮
