### ISSUE TITLE
onerror监听，监听不到

### ISSUE THREAD

**Issue by dazhiyu** [pili-engineering/PLDroidPlayer#472]
播放时，将网络断开，快进在缓存的进度里，加载不出页面，onerror监听也监听不到。
下面是打印的信息：
03-02 15:53:29.221 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.231 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.234 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.234 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.234 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.245 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.249 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.249 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.249 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.260 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.262 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.263 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.263 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.273 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.276 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.276 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.276 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.287 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.290 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.291 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.291 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.301 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.306 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.306 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.306 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.316 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.320 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.320 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.321 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.331 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.334 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.334 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.334 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.345 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.348 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.348 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.348 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.359 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.362 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.362 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4
03-02 15:53:29.363 5898-7911/com.bhtc.huajuan E/IJKMEDIA: stream 1, offset 0x10eed5: partial file
03-02 15:53:29.373 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 3
03-02 15:53:29.376 5898-7911/com.bhtc.huajuan E/IJKMEDIA: Failed to resolve hostname static.huajuanmall.com: No address associated with hostname
03-02 15:53:29.376 5898-7911/com.bhtc.huajuan I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 4

**Comment by Jhuster** [comment]
播放过程中断开 WiFi 吗，刚刚验证是有错误回调的，详细再描述下你的问题

**Comment by dazhiyu** [comment]
对就是在播放中断开wifi，然后就是缓冲到1：30，我快进到1:20，就出现这些，监听不到失败。

**Comment by tanhx2008** [comment]
给下播放地址？

**Comment by dazhiyu** [comment]
http://static.huajuanmall.com/images/videos/o_1akcg2505130l7pn1skmdjfl7fbq.mp4

**Comment by dazhiyu** [comment]
追加：如果下载到本地的视频有问题只能播放一半，也是这种异常，监听不到，有什么办法知道怎么监听这种状态吗？。。。。。。。。。

**Comment by dazhiyu** [comment]
好吧，在OnInfoListener监听到了，what返回702，缓存停止。
