### ISSUE TITLE
使用OnInfoListener接口回调来做试看x分钟的问题

### ISSUE THREAD

**Issue by WillXWell** [pili-engineering/PLDroidPlayer#473]
请问OnInfoListener接口的回调是在什么情况下发生？不是在视频播放的过程中一直回调吗？我调试发现视频播放过程中没有一直回调这个接口。我需要做视频试看的功能，要实时检测当前播放位置，哪里可以满足我的这个需求呢？

**Comment by Jhuster** [comment]
@WillXWell 参考下 demo 中进度条走动的源码，可以通过主动获取当前播放位置的方式，下一版本考虑每播放一帧就发一个消息，把 pts 传出来

**Comment by WillXWell** [comment]
@Jhuster 好的，我试下，谢谢了
