### ISSUE TITLE
能在eclipse上面跑吗？

### ISSUE THREAD

**Issue by ghost** [pili-engineering/PLDroidPlayer#475]
我把1.50 jar包和so文件都放到libs下，但是报空指针异常，怎么破?

**Comment by JiannaiJ** [comment]
VideoView报空指针，TextureView正常...

**Comment by tanhx2008** [comment]
贴下 log 看看

**Comment by JiannaiJ** [comment]
我最先用的是zip包里面releases下的jar文件和so文件。后来我改了用github git下来的demo里的jar文件就好了。  我想问一下，自己怎么换so文件？我需要硬解支持rmvb格式的。

**Comment by JiannaiJ** [comment]
@tanhx2008 能否提供支持rmvb格式的so文件？

**Comment by tanhx2008** [comment]
目前应该没有这个计划
