### ISSUE TITLE
视频播放读取-1482175992异常，该参数没有对应文档

### ISSUE THREAD

**Issue by onlike** [pili-engineering/PLDroidPlayer#477]
流地址：http://wscdn.alhls.xiaoka.tv/201738/e5c/a07/qS3XQcPkwRMD0hzm/index.m3u8

对应ijk部分log：
03-08 16:49:05.505 30814-1150/? I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
03-08 16:49:05.505 30814-1150/? E/IJKMEDIA: http://wscdn.alhls.xiaoka.tv/201738/e5c/a07/qS3XQcPkwRMD0hzm/index.m3u8: Server returned 5XX Server Error reply
03-08 16:49:05.505 30814-1150/? I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [1150]
03-08 16:49:05.505 30814-1148/? D/IJKMEDIA: FFP_MSG_ERROR: -1482175992
03-08 16:49:05.522 30814-30814/? E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1482175992)

**Comment by onlike** [comment]
经测试  IOS端（采用ijkplayer）可以正常播放该流  
另：采用与该问题流同样的推流转码技术的其他流地址，部分流  可以播放  但是卡顿非常严重
出现此类问题的都是  直播回顾流 地址

**Comment by tanhx2008** [comment]
我这边测试正常
