### ISSUE TITLE
rtsp 能播放 ，卡顿 

### ISSUE THREAD

**Issue by hnyer** [pili-engineering/PLDroidPlayer#480]
连接上摄像头后 ， rtsp://XXXX   能显示 ，但是转动摄像头时会有一些 卡顿 丢帧的现象 。 请问如何解决 。
测试手机是 魅蓝note2   .

版本是v1.5.0

**Comment by Jhuster** [comment]
@hnyer 你的流是什么分辨率，什么码率，什么帧率，其他高性能的手机呢，或者开硬解的效果呢

**Comment by robbenv** [comment]
我的也是连接摄像头的rtsp流，请问解决了吗

**Comment by Jhuster** [comment]
@robbenv 先确保你的 RTSP 流本身可以正常播放，另外，打印出 视频 和 音频 的每一帧时间戳看看，是否正常
