### ISSUE TITLE
如何获取 rtsp流的 YUV信息

### ISSUE THREAD

**Issue by hnyer** [pili-engineering/PLDroidPlayer#481]
需要获取 YUV420P的数据 。 请问是哪个API可以获得

**Comment by Jhuster** [comment]
需要每一帧的数据吗？

**Comment by hnyer** [comment]
是每一帧的 ，因为我需要获得这些数据  一个用途是用来实时显示 ， 另外一个用途是用来提供给其他接口 做算法的 （ 图像跟随）

**Comment by hnyer** [comment]
@Jhuster  是每一帧的 ，因为我需要获得这些数据 一个用途是用来实时显示 ， 另外一个用途是用来提供给其他接口 做算法的 （ 图像跟随）

**Comment by Jhuster** [comment]
嗯，了解了，目前不支持，我们会考虑在后面的版本提供

**Comment by hnyer** [comment]
@Jhuster  知道目前 有哪个开源的 支持这个功能吗？ （解码 rtsp协议的 H.264  显示并能获取yuv420数据）

**Comment by Jhuster** [comment]
@hnyer 如果比较急的话，你可以尝试直接编译 ijkplayer 然后自己做一下回调功能
