### ISSUE TITLE
unsupported amf type 17

### ISSUE THREAD

**Issue by zbldgit** [pili-engineering/PLDroidPlayer#483]
IJKMEDIA: Option ijkapplication not found.
IJKMEDIA: unsupported amf type 17

请问一下造成这个问题的原因

**Comment by tanhx2008** [comment]
流地址发一下呢？

**Comment by zbldgit** [comment]
rtmp://ws1.poll.offcn.com/live/6ad1bf221e15caf0a3bc282b04f872cf
我用vlc测试了一下，这个流能播放，但是替换了demo中的
DEFAULT_TEST_URL = "rtmp://ws1.poll.offcn.com/live/6ad1bf221e15caf0a3bc282b04f872cf";
DEFAULT_PLAYBACK_DOMAIN_ARRAY = {  "ws1.poll.offcn.com   };
点击播放出现上面那个问题

**Comment by zbldgit** [comment]
03-09 14:36:51.251 17000-17000/com.pili.pldroid.playerdemo I/Timeline: Timeline: Activity_launch_request time:203104410
03-09 14:36:51.342 17000-17000/com.pili.pldroid.playerdemo D/ActivityThreadInjector: clearCachedDrawables.
03-09 14:36:51.388 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_native_setup
03-09 14:36:51.388 17000-17000/com.pili.pldroid.playerdemo D/pldroid-player-native: pldroid_player native version = 1.4.1 
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ffpipeline_create_from_android()
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_inject_opaque(0x10085e)
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_inject_opaque()=void
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ffpipeline_set_mediacodec_select_callback
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_android_set_mediacodec_select_callback()=void
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.389 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOption
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.390 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setOptionLong
03-09 14:36:51.391 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setDataSourceAndHeaders
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo V/IJKMEDIA: setDataSource: path rtmp://59.47.226.165/live/6ad1bf221e15caf0a3bc282b04f872cf?domain=ws1.poll.offcn.com
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://59.47.226.165/live/6ad1bf221e15caf0a3bc282b04f872cf?domain=ws1.poll.offcn.com")
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_data_source(url="rtmp://59.47.226.165/live/6ad1bf221e15caf0a3bc282b04f872cf?domain=ws1.poll.offcn.com")=0
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7ffa4a9d68)
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ffpipeline_set_surface()
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_set_android_surface(surface=0x7ffa4a9d68)=void
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: IjkMediaPlayer_prepareAsync
03-09 14:36:51.392 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_prepare_async()
03-09 14:36:51.392 17000-30494/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_RunThread: [30494] ff_msg_loop
03-09 14:36:51.392 17000-30494/com.pili.pldroid.playerdemo D/IJKMEDIA: message_loop
03-09 14:36:51.393 17000-30494/com.pili.pldroid.playerdemo D/IJKMEDIA: FFP_MSG_FLUSH:
03-09 14:36:51.396 17000-17000/com.pili.pldroid.playerdemo D/IJKMEDIA: ijkmp_prepare_async()=0
03-09 14:36:51.396 17000-30496/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_RunThread: [30496] ff_read
03-09 14:36:51.397 17000-30495/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_RunThread: [30495] ff_vout
03-09 14:36:51.465 17000-17000/com.pili.pldroid.playerdemo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-09 14:36:51.483 17000-17040/com.pili.pldroid.playerdemo D/OpenGLRenderer: endAllActiveAnimators on 0x7f6644a800 (RippleDrawable) with handle 0x7f62ae11c0
03-09 14:36:52.627 17000-30496/com.pili.pldroid.playerdemo E/IJKMEDIA: Option ijkapplication not found.
03-09 14:36:52.627 17000-30496/com.pili.pldroid.playerdemo E/IJKMEDIA: unsupported amf type 17
03-09 14:36:53.796 17000-17038/com.pili.pldroid.playerdemo I/com.pili.pldroid.playerdemo: Foregroundcom.pili.pldroid.playerdemo
03-09 14:36:56.082 17000-30496/com.pili.pldroid.playerdemo A/IJKMEDIA: Failed to open file 'rtmp://59.47.226.165/live/6ad1bf221e15caf0a3bc282b04f872cf?domain=ws1.poll.offcn.com' or configure filtergraph
03-09 14:36:56.082 17000-30496/com.pili.pldroid.playerdemo I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [30496]

**Comment by zbldgit** [comment]
上面是完整的测试信息

**Comment by tanhx2008** [comment]
检查下流，ffplay 和 其他第三方播放器都是同样报错

**Comment by zbldgit** [comment]
vlc可以播放
