### ISSUE TITLE
播放视频偶尔出现加载过久的问题？

### ISSUE THREAD

**Issue by Vashon** [pili-engineering/PLDroidPlayer#486]
播放网上的视频时偶尔会出现加载很久情况，并报出下面的错误：
E/IJKMEDIA: Stream ends prematurely at 72797015, should be 73110950

请问这是什么原因？

**Comment by Jhuster** [comment]
@Vashon 以前见有人遇到过，你们是用到了阿里云的转码吗？

**Comment by Jhuster** [comment]
@Vashon 这可能是阿里云转码的 BUG，当然，也可能是 ffmpeg 对这种流兼容性不好，前段时间我 debug 的时候，发现用 ffplay 播放也会有这个问题，建议反馈问题给阿里云。
