### ISSUE TITLE
视频播放过程加载超时，卡死状态无法点击

### ISSUE THREAD

**Issue by ghost** [pili-engineering/PLDroidPlayer#487]
E/IJKMEDIA(2570): read frame timeout !
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(2570): onNativeInvoke 3
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(2570): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(2570): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(2570): onNativeInvoke 4
E/IJKMEDIA(2570): Failed to reconnect at 240312308.
I/IJKMEDIA(2570): SDL_JNI_DetachThreadEnv: [8753]
D/IJKMEDIA(2570): FFP_MSG_ERROR: -2002
I/IJKMEDIA(2570): SDL_JNI_DetachThreadEnv: [8752]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(2570): Error (-10000,-2002)
E/PLMediaPlayer(2570): Error happened, what = -10000, errorCode = -2002

视频地址肯定没问题，本地服务器视频。

**Comment by Jhuster** [comment]
@JiannaiJ 可以加大 `AVOption` 的 `AVOptions.KEY_GET_AV_FRAME_TIMEOUT` 试试，默认 10s 没有读到数据，建议 debug 下你的服务器程序

**Comment by JiannaiJ** [comment]
@Jhuster  数值是毫秒还是秒？
