### ISSUE TITLE
播放开报出的两个Error信息，如何解决？

### ISSUE THREAD

**Issue by ghost** [pili-engineering/PLDroidPlayer#488]
<----1----> 
E/IJKMEDIA(17196): csd-0[37]: 00000001
 E/IJKMEDIA(17196): csd-0[37]: 67640029
 E/IJKMEDIA(17196): csd-0[37]: acd98050
 E/IJKMEDIA(17196): csd-0[37]: 045b0110
 E/IJKMEDIA(17196): csd-0[37]: 0065b9b0
 E/IJKMEDIA(17196): csd-0[37]: 1312d008
 E/IJKMEDIA(17196): csd-0[37]: f18319a0
 E/IJKMEDIA(17196): csd-0[37]: 00000001
 E/IJKMEDIA(17196): csd-0[37]: 68e97b2c
 E/IJKMEDIA(17196): csd-0[37]: 8b000000

<----2---->
 E/IJKMEDIA(17196): configure acodec:0x1ee0056e format:0x1d700612: surface:0x1e0005d2
 E/ACodec(17196): [OMX.MS.AVC.Decoder] storeMetaDataInBuffers failed w/ err -2147483648

**Comment by Jhuster** [comment]
跑的 demo 吗？

**Comment by JiannaiJ** [comment]
@Jhuster  不是你们的demo，是我引用你们sdk进行播放产生的信息。

**Comment by Jhuster** [comment]
@JiannaiJ 还有什么信息，你有些初步的对比测试吗？比如：是不是所有手机都有这个报错，是播放特定的流才出现的吗，上下文完整的log

**Comment by JiannaiJ** [comment]
系统4.4.4，在arm-v7a平台上出现的错误，播放源是本地服务器上的文件（以smb共享协议读取的）
电影能正常播放，就是不知道后患如何。
<--------播放开始 第一出现错误-------->
E/IJKMEDIA(1712): Option http-detect-range-support not found. 

D/IJKMEDIA(1712): SDL_AMediaFormatJava_createVideoFormat
E/IJKMEDIA(1712): csd-0[38]: 00000001
E/IJKMEDIA(1712): csd-0[38]: 67640028
E/IJKMEDIA(1712): csd-0[38]: acc8501e
E/IJKMEDIA(1712): csd-0[38]: 01b68400
E/IJKMEDIA(1712): csd-0[38]: 00030004
E/IJKMEDIA(1712): csd-0[38]: 00000300
E/IJKMEDIA(1712): csd-0[38]: c83c60c6
E/IJKMEDIA(1712): csd-0[38]: 58000000
E/IJKMEDIA(1712): csd-0[38]: 0168ebec
E/IJKMEDIA(1712): csd-0[38]: f23c0000
I/IJKMEDIA(1712): amc: rotate notify: 0
D/IJKMEDIA(1712): FFP_MSG_VIDEO_ROTATION_CHANGED: 0
D/IJKMEDIA(1712): ffpipeline_select_mediacodec_l
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(1712): onSelectCodec: mime=video/avc, profile=100, level=40



D/IJKMEDIA(1712): SDL_AMediaCodecJava_createByCodecName
I/OMXClient(1712): Using client-side OMX mux.
D/IJKMEDIA(1712): SDL_AMediaCodecJava_init
D/IJKMEDIA(1712): SDL_AMediaCodec_increaseReference(): ref=1
D/IJKMEDIA(1712): SDL_AMediaCodecJava_configure_surface
E/IJKMEDIA(1712): configure acodec:0x1d20058e format:0x1d20057a: surface:0x1d200586
E/ACodec(1712): [OMX.MS.AVC.Decoder] storeMetaDataInBuffers failed w/ err -2147483648
D/IJKMEDIA(1712): SDL_AMediaCodecJava_start
I/IJKMEDIA(1712): reconfigure_codec_l:new acodec: 0x57b7d5c0
D/IJKMEDIA(1712): SDL_AMediaCodec_increaseReference(): ref=2

**Comment by JiannaiJ** [comment]
@Jhuster

**Comment by Jhuster** [comment]
@JiannaiJ 嗯，可以播放，问题不大，csd-0 也不是 error，下面那个 failed 我们再看看
