### ISSUE TITLE
Doesn't work on Android 6

### ISSUE THREAD

**Issue by mauriciogior** [pili-engineering/PLDroidPlayer#49]
`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.inevent.apps.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/us.inevent.apps.demo-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libpldroidplayer.so"`

**Comment by jpxiong** [comment]
What's the CPU Arch ?

**Comment by mauriciogior** [comment]
Doesn't matter, I tested on `arm` and `x86` (on simulator).

**Comment by jpxiong** [comment]
So it crashed on simulator. Got it. Thanks.

**Comment by mauriciogior** [comment]
@jpxiong actually that crash log is from Google Play.

Full log:

> 
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/us.inevent.apps.demo-2/base.apk"],nativeLibraryDirectories=[/data/app/us.inevent.apps.demo-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libpldroidplayer.so"
> 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
> 	at java.lang.System.loadLibrary(System.java:1076)
> 	at tv.danmaku.ijk.media.player.IjkMediaPlayer$1.loadLibrary(IjkMediaPlayer.java:108)
> 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.loadLibrariesOnce(IjkMediaPlayer.java:116)
> 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:163)
> 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:159)
> 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:150)
> 	at com.pili.pldroid.player.widget.VideoView.openVideo(VideoView.java:279)
> 	at com.pili.pldroid.player.widget.VideoView.access$2600(VideoView.java:41)
> 	at com.pili.pldroid.player.widget.VideoView$8.surfaceCreated(VideoView.java:592)
> 	at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
> 	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
> 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
> 	at android.view.Choreographer.doFrame(Choreographer.java:606)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
> 	at android.os.Handler.handleCallback(Handler.java:739)
> 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 	at android.os.Looper.loop(Looper.java:148)
> 	at android.app.ActivityThread.main(ActivityThread.java:5417)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Nexus 7 (flo) (Android 6)

**Comment by mauriciogior** [comment]
A workaround is to compile with SDK 22.

**Comment by bear45** [comment]
on nexus 5 (6.0) work sueecess!
compile with SDK 23.

**Comment by lijun952048910** [comment]
W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader

[DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.wangzhi.MaMaHelp-

1/base.apk"],nativeLibraryDirectories=[/data/app/com.wangzhi.MaMaHelp-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find 

"libpldroidplayer.so"
