### ISSUE TITLE
有没有截图某一帧图像的方法？

### ISSUE THREAD

**Issue by Dovar66** [pili-engineering/PLDroidPlayer#490]
播放器暂停状态下，activity.onpause()之后，再onResume()回到界面时，播放器上没有任何图像 ，所以我需要截取暂停时的那一帧图像在onResume()中设置到界面上
但是在播放器中没找到对应api，尝试过通过截屏获取但截屏时获取到的PLVideoTextureView依然没有视频图像

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/209

**Comment by Dovar66** [comment]
@Jhuster 多谢!
不过刚刚又遇到另外一个问题，关于PLVideoTextureView.getPlayerState()方法：app退入后台时我会让播放器暂停并且在暂停之前调用getPlayerState()打印播放器状态，然后发现首次打印时是正确的PLAYING状态，但返回界面继续播放后如果再次退入后台时打印的都是PAUSED状态，是这个api有误？
