### ISSUE TITLE
请问提示上报错误是什么问题？

### ISSUE THREAD

**Issue by gavinghliu** [pili-engineering/PLDroidPlayer#493]
# AsyncTask #2(46172)
java.lang.ClassCastException
android.telephony.CellInfoGsm cannot be cast to android.telephony.CellInfoWcdma
解析原始
1 com.pili.pldroid.player.report.common.a.i(Util.java:806)
2 com.pili.pldroid.player.report.core.f.i(QosStatusRecorder.java:89)
3 com.pili.pldroid.player.report.core.f.j(QosStatusRecorder.java:111)
4 com.pili.pldroid.player.report.core.f.d(QosStatusRecorder.java:67)
5 com.pili.pldroid.player.report.core.d$2$1.run(QosReceiver.java:52)
6 android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
7 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
8 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9 java.lang.Thread.run(Thread.java:818)

**Comment by tanhx2008** [comment]
请升级到 1.5.1，已修复该问题
