### ISSUE TITLE
播放视频有声音没画面

### ISSUE THREAD

**Issue by WillXWell** [pili-engineering/PLDroidPlayer#498]
我之前做了一个项目使用了PLDroidPlayer，一切正常，然后最近我把那个项目改了一个包名，印象中应该没有再修改其他东西，但是发现播放视频没有画面了（一脸蒙逼。。。）。

**Comment by WillXWell** [comment]
请问播放视频没有画面是什么原因呢？

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/370

**Comment by WillXWell** [comment]
不行啊，加这个也没有作用，还有硬解软解方式我也都试了，都不行。
我比对了代码，我的业务代码没有动过，会不会是so库相关的内容出问题导致的呢？

**Comment by Jhuster** [comment]
@WillXWell 你试试 demo ？

**Comment by WillXWell** [comment]
@Jhuster 我这个蛋碎一地的奇葩问题……我再自己找找原因吧，如果有问题再来请你帮忙好了，谢谢了
