### ISSUE TITLE
可否实现加载首个画面但是不马上播放？

### ISSUE THREAD

**Issue by qssq666123** [pili-engineering/PLDroidPlayer#499]
如标题所描述。只显示封面，点击播放才开始，

**Comment by Jhuster** [comment]
封面可以另行设置一张广告图片，不过也可以考虑 onInfo 消息收到首帧后，调用 pause 试试

**Comment by qssq666123** [comment]
- -广告图片 肯定不行的哈，老板让我们这样做，嗯 我看看我会不会了，onInfo.

**Comment by qssq666123** [comment]
@Override
    public boolean onInfo(PLMediaPlayer plMediaPlayer, int what, int extra) {
        Log.d(TAG, "onInfo what=" + what + ", extra=" + extra);

        if (what == PLMediaPlayer.MEDIA_INFO_BUFFERING_START) {
            Log.i(TAG, "onInfo: (MEDIA_INFO_BUFFERING_START)");
                onShowbufferingIndicatorNotify.onNotify(true);
        } else if (what == PLMediaPlayer.MEDIA_INFO_BUFFERING_END) {
            Log.i(TAG, "onInfo: (MEDIA_INFO_BUFFERING_END)");
                onShowbufferingIndicatorNotify.onNotify(false);
        } else if (what == PLMediaPlayer.MEDIA_INFO_AUDIO_RENDERING_START) {
//                Toast.makeText(this, "Audio Start", Toast.LENGTH_LONG).createAndShow();
            Log.i(TAG, "音频开始了,duration:");
        } else if (what == PLMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START) {
            Log.i(TAG, "视频开始了  duration:" );
        } else if (what == PLMediaPlayer.MEDIA_INFO_VIDEO_ROTATION_CHANGED) {
            //extra=90
            if (extra == 90) {

            }
        }
        return false;
    }
可以告诉我具体怎么弄嘛，懵比

**Comment by Jhuster** [comment]
`PLMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START` 这里调用 `pause`，用户点击屏幕后，调用 `resume`

**Comment by qssq666123** [comment]
这方法不行哦!屏幕还是黑的呢

**Comment by qssq666123** [comment]
好像概率太大，

**Comment by qssq666123** [comment]
看来只能适当调整延迟了
