### ISSUE TITLE
视频播放时好像放大了，只能显示部分

### ISSUE THREAD

**Issue by hooface** [pili-engineering/PLDroidPlayer#5]
您好，我成功编译了PLDroidPlayerDemo，但视频播放时好像放大了，只能显示部分，请问这是什么原因？

**Comment by jpxiong** [comment]
你好，为什么会觉得“视频播放好像放大了”，有做对比测试吗 ？播放的视频格式是什么？

**Comment by hooface** [comment]
谢谢您的这么快回复。
我是在美版 Nexus 5  测试的，视频是手机录制的 mp4 格式，使用 Nexus 5 自带的播放器显示正常，使用编译安装的PLDroidPlayerDemo播放时，屏幕也能全部显示，但整个画面上只能看到视频画面的一部分（视频画面明显有放大）。不知道我这样有没说清楚，或者说如何让视频画面适应手机屏幕大小？

**Comment by jpxiong** [comment]
是否方便提供你的视频？谢谢

**Comment by hooface** [comment]
谢谢。我使用 Android Studio 1.2.2 编译后，就可以正常显示了。

2015-06-26 10:25 GMT+08:00 jpxiong <notifications@github.com>:
