### ISSUE TITLE
看到了很多提rtmp播放时无声音的问题

### ISSUE THREAD

**Issue by hongye612430** [pili-engineering/PLDroidPlayer#50]
表示也遇到了rtmp播放时无声音
发现如果是h264编码M4V封包的就会有这个问题
看到有好几个人提类似，还没人解决，又没有源码……

**Comment by otizis** [comment]
开发人员说今天更新可以解决这个 问题的 #47

**Comment by mchao2016** [comment]
然而到现在还是没有画面

**Comment by Jhuster** [comment]
为了减少 so 的体积，我们删掉了很多不常用格式的支持，所以会出现一些不支持的封装格式或者不支持的编解码格式导致缺失画面或者声音的问题，后面的版本，我们考虑一下单独编译一份大size的so，提供给有需要的人。
