### ISSUE TITLE
PLVideoTextureView 能播放本地视频吗

### ISSUE THREAD

**Issue by huxugang** [pili-engineering/PLDroidPlayer#502]
我想用PLVideoTextureView播放本地视频，
  mVideoPath= Environment.getExternalStorageDirectory().getPath()+"/act_advancedspinaltwistl.mp4";
        mVideoView.setVideoPath(mVideoPath);
        mVideoView.start();
提示
E/IJKMEDIA: Option ijkapplication not found.
A/IJKMEDIA: Failed to open file '/storage/emulated/0/act_advancedspinaltwistl.mp4' or configure filtergraph
请问需要别的配置吗，还是这个只能播放流媒体，要播本地，需要换别的控件？谢谢

**Comment by Jhuster** [comment]
可以播放本地文件的，demo 界面可以选择本地文件做测试

**Comment by huxugang** [comment]
你好，我用1.40的demo，同样是上面的提示，不能播放

**Comment by Jhuster** [comment]
你再找个其他的 mp4 文件试试

**Comment by Jhuster** [comment]
`Failed to open file` 感觉不像是格式问题，可能是这个文件的问题，你对比下不同的文件的区别

**Comment by huxugang** [comment]
我现在也不是太清楚视频格式的问题，又换了个视频，有视频没声音

**Comment by Jhuster** [comment]
用 ffplay 或者 VLC 播放下你的 mp4 ，拿到编码信息
