### ISSUE TITLE
经常收不到第一帧渲染成功的回调

### ISSUE THREAD

**Issue by charmeleon2** [pili-engineering/PLDroidPlayer#503]
经常收不到第一帧渲染成功的回调，视频也无法播放，请问有什么办法知道是否已经渲染成功

**Comment by charmeleon2** [comment]
可以收到10001，但是没有3
同一个流在另一台设备上可以播放，概率出现此问题

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/353

**Comment by charmeleon2** [comment]
用官方demo也有概率出现这个问题，流的地址是 rtmp://play.archerycn.cn/office/003    
目前流不需要音频，只需要视频

**Comment by Jhuster** [comment]
@charmeleon2 你调整下 `probesizse` 试试

**Comment by charmeleon2** [comment]
@Jhuster  似乎没什么用，现在只能定时检测第一帧是否播放成功，如果没有就重新setpath

**Comment by Jhuster** [comment]
@charmeleon2 需要排查下你的流，用 ffplay 或者 VLC 也同步播放测试试试
