### ISSUE TITLE
播放进度条不能拖动到指定任意位置

### ISSUE THREAD

**Issue by lygttpod** [pili-engineering/PLDroidPlayer#508]
拖动进度条并不能快进到滑动位置，这个问题怎么处理，而且拖动时候会有明显响亮的杂音

**Comment by Jhuster** [comment]
@lygttpod 拖动的原理是寻找视频中附近的关键帧，不一定非常准确的到达那个松开的点，具体你的现象是？另外，杂音的话，试试先 `pause` 再 `seek`

**Comment by wengsongwei8** [comment]
下了一个最新的Demo，也会有这种情况：拖动进度条并不能快进到滑动位置，而是经常返回退原来的位置。（说明视频长度有127分钟）
