### ISSUE TITLE
您好，我想实现视频加密和解密的操作可以么？

### ISSUE THREAD

**Issue by xinyitiandi** [pili-engineering/PLDroidPlayer#513]
您好，我想对下载到本地的文件加密，然后解密再播放，这个可以实现么？怎样实现呢？求解

**Comment by Jhuster** [comment]
@xinyitiandi 本项目是在线视频播放 SDK，不支持下载视频到本地

**Comment by slyang520** [comment]
我想 播放本地文件   
com.pili.pldroid.playerdemo E/IJKMEDIA: Option ijkapplication not found.
com.pili.pldroid.playerdemo A/IJKMEDIA: Failed to open file '/storage/emulated/0/test/tem_image/1491805816632.mov' or configure filtergraph
这个我需要修改什么文件  你提供下思路么 @Jhuster
