### ISSUE TITLE
DNS解析和缓存管理问题

### ISSUE THREAD

**Issue by lygttpod** [pili-engineering/PLDroidPlayer#514]
现在遇到的问题是播放网络视频的时候普遍需要等十秒左右的时候才能加载出首屏，网络环境很好，看文档DNS这块描述的比较模糊，具体什么时候用    在调用播放之前启动还是什么时候 ，希望帮忙梳理一下思路

提供的demo中也没有这块的代码实例

文档里边有句话说  “提前传入待解析的域名列表会在第一次播放时得到更好的体验”  我在setvideoPath之前调用的   不知道这样写对不会，根本无法实现首屏秒开，缓存这块希望解答一下   谢谢！

`
      

        try {
            PLNetworkManager.getInstance().startDnsCacheService(mContext);
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        setOptions();
        playerView.setOnErrorListener(mOnErrorListener);
        playerView.setOnCompletionListener(mOnCompletionListener);
        playerView.setVideoPath(videoPath);
        playerView.start();
        
`

**Comment by Jhuster** [comment]
`lygttpod` 用我们的demo测测，另外，用 vlc 等播放器也测测，看看是不是流本身的问题。

**Comment by lygttpod** [comment]
@Jhuster 好的我看下，另外问下我启动DNS的用法对吗？是在start之前调用吗？

**Comment by Jhuster** [comment]
@lygttpod 建议在更早的时候启动，比如 MainActivity
