### ISSUE TITLE
请问竖屏视频到底应该怎么处理呢？ 屏幕全屏的时候使用竖立方式铺满全屏呢

### ISSUE THREAD

**Issue by qssq666123** [pili-engineering/PLDroidPlayer#516]
看了一下以前提交的issues,似乎在现在都用不上呀，没有那个setdisplay方法了。

**Comment by Jhuster** [comment]
要看你的视频长宽比是否跟屏幕长宽比是否一致了，比如都是 16:9，另外，SDK 提供了 `mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);`

**Comment by qssq** [comment]
那么如何知道呢？info回调吗

**Comment by qssq** [comment]
mPlvideoview.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT); 没有效果，还是竖屏。
