### ISSUE TITLE
开始播放视频，视频花掉

### ISSUE THREAD

**Issue by bear45** [pili-engineering/PLDroidPlayer#52]
开始播放视频前一两秒，视频会花掉，背景变黑，人物看不清。
播放一两秒后正常。
测试Url:http://imgtest.chengweiapp.com/febc5e4474384d568a9300d9ae32bfe7.mp4

**Comment by otizis** [comment]
把online关了试试

**Comment by bear45** [comment]
关掉直播后正常： // options.setInteger(AVOptions.KEY_LIVE_STREAMING, 1);
