### ISSUE TITLE
No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init()

### ISSUE THREAD

**Issue by zpscott** [pili-engineering/PLDroidPlayer#520]
04-08 21:50:45.889 28169-28169/ E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)
04-08 21:50:45.889 28169-28169/ W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)
04-08 21:50:45.889 28169-28169/ W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init(Native Method)
04-08 21:50:45.890 28169-28169/ W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initNativeOnce(IjkMediaPlayer.java:200)
04-08 21:50:45.890 28169-28169/ W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
04-08 21:50:45.890 28169-28169/ W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:225)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:137)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:130)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.pili.pldroid.player.widget.a.c(PLBaseVideoView.java:490)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.pili.pldroid.player.widget.a$8.a(PLBaseVideoView.java:969)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.pili.pldroid.player.widget.PLVideoView$a$1.surfaceCreated(PLVideoView.java:141)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:677)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:203)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2457)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1366)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6753)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:698)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:633)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:882)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.os.Looper.loop(Looper.java:207)
04-08 21:50:45.890 28169-28169/ W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5710)
04-08 21:50:45.890 28169-28169/ W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
04-08 21:50:45.890 28169-28169/ W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)

**Comment by zpscott** [comment]
找到原因了 jniLibs扔到java文件夹了。应该是和java文件夹平级才对。。晕死自己了。

**Comment by chnouman** [comment]
still facing the same issue.
