### ISSUE TITLE
如何能降低播放延迟

### ISSUE THREAD

**Issue by charmeleon2** [pili-engineering/PLDroidPlayer#521]
rtsp本地直播流，缓存大小已经改为500ms，已经添加dns解析，但经常出现比vlc慢上1 2s的情况

**Comment by Jhuster** [comment]
@charmeleon2 跟手机的 vlc 对比吗？都是软解/硬解来对比测试的吗

**Comment by charmeleon2** [comment]
都是用的软解，我用ijkplayer试了一下，延时大概是2-3秒，七牛这边还是要慢上2s左右，流是本地的，所以基本能排除网络方面的问题。vlc用的是pc端的

**Comment by Jhuster** [comment]
@charmeleon2 用的 demo 测试的吗？播放：rtmp://live.hkstv.hk.lxdns.com/live/hks  这个地址呢

**Comment by charmeleon2** [comment]
用你们的demo跑rtsp也是要比ijk慢2s左右，不过跑rtmp倒是和vlc上差不多
