### ISSUE TITLE
主播端和客户端都是用的软解，三星Note3手机观看直播时出现花屏问题

### ISSUE THREAD

**Issue by dwj1210** [pili-engineering/PLDroidPlayer#523]
![_20170412104906](https://cloud.githubusercontent.com/assets/24934234/24939829/806caad4-1f72-11e7-9d70-2f3820799b70.jpg)

**Comment by Jhuster** [comment]
其他手机观看呢？或者 VLC 等其他播放器播放呢？

**Comment by dwj1210** [comment]
使用vivox6观看没问题魅族也可以，这种情况和网络情况有关系吗？

**Comment by Jhuster** [comment]
用的哪一个 API，`PLVideoView` 还是 `PLVideoTextureView` ?

**Comment by wuqiong657** [comment]
我用PLVideoTextureView播放视频，也会出现

**Comment by dwj1210** [comment]
PLVideoView
