### ISSUE TITLE
播放视频时如何设置 ERROR_CODE_READ_FRAME_TIMEOUT的超时时间？

### ISSUE THREAD

**Issue by linuxsong** [pili-engineering/PLDroidPlayer#526]
播放视频时如果网络状况不佳时，会出现 ERROR_CODE_READ_FRAME_TIMEOUT错误，如何设置这个超时的时间呢？
目的时在出现网络状况不好时，能够多重试几次。设置KEY_PREPARE_TIMEOUT和KEY_GET_AV_FRAME_TIMEOUT并不能解决这个问题。

**Comment by Jhuster** [comment]
@linuxsong 如果 `KEY_GET_AV_FRAME_TIMEOUT` 都无法解决问题的话，可能跟流本身有关，播放 demo 默认的流是否也有类似问题

**Comment by linuxsong** [comment]
流本身是没有问题的，我是这样模拟的网络环境，连接上一个wifi,然后开始播放一小段时间，这时拔掉路由器的网线，形成“假网”（wifi处于连接状态），然后就会得到ERROR_CODE_READ_FRAME_TIMEOUT错误，这个错误出现的时间，并不依赖KEY_GET_AV_FRAME_TIMEOUT设置的时间，有没有办法可以控制这个错误的时间，比如在遇到网不稳定时可以设置这个时间，在网络恢复时可以继续。否则出现网络状况不好时没有办法多等一会，对用户的体验不是很好。

**Comment by Jhuster** [comment]
@linuxsong 确定配置正确了吗，`ERROR_CODE_READ_FRAME_TIMEOUT` 就是依赖的 `KEY_GET_AV_FRAME_TIMEOUT` 时间，可以把 SDK debug log 打开，然后看看 log 里面，player-opts 打印的参数是否生效。

超时错误后，可以重连，有错误出来提示比 UI 卡死要好
