### ISSUE TITLE
网速慢的时候声音在播视频卡住

### ISSUE THREAD

**Issue by kangshifu** [pili-engineering/PLDroidPlayer#527]
播放视频的时候有时候会出现声音在播放但是视频卡住不动的情况

**Comment by Jhuster** [comment]
@kangshifu 需要 log ，或者更多的信息

**Comment by kangshifu** [comment]
能不能知道当前视频流是否在播放，当视频流没有播放的时候把音频停下，另外问个问题，我怎么知道视频开始播放，比如当前网络不好，超时了，我开始重连，我希望重连后从上次播放的位置继续播，我现在不知道在哪里设置lastpostion

**Comment by Jhuster** [comment]
@kangshifu 多看看 Wiki 文档，`onInfoListener` 有相关回调，最后一个问题的答案：https://github.com/pili-engineering/PLDroidPlayer/issues/455
