### ISSUE TITLE
PLVideoView 怎么清掉上个视频帧

### ISSUE THREAD

**Issue by wjjiang917** [pili-engineering/PLDroidPlayer#528]
切换视频时，在下个视频还在加载过程中，会显示前一个视频最后一帧的图片。切换视频的代码：
mVideoView.stopPlayback();
mVideoView.setVideoPath(videoPath);
mVideoView.start();

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/97

**Comment by wjjiang917** [comment]
@Jhuster 谢谢，之前看了这个贴，试了一下，没写对。。。现在OK了
