### ISSUE TITLE
Vivo X9手机不能播放流，mp4文件

### ISSUE THREAD

**Issue by yjy951753** [pili-engineering/PLDroidPlayer#533]
04-19 18:31:55.966 23542-23542/com.maxleap.mobile.appmaker E/art: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init() (tried Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init and Java_tv_danmaku_ijk_media_player_IjkMediaPlayer_native_1init__)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.native_init(Native Method)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initNativeOnce(IjkMediaPlayer.java:200)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.initPlayer(IjkMediaPlayer.java:230)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(IjkMediaPlayer.java:225)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.a(PLMediaPlayer.java:137)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:130)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.widget.a.c(PLBaseVideoView.java:490)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.widget.a.setVideoURI(PLBaseVideoView.java:338)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.widget.PLVideoView.setVideoURI(PLVideoView.java:20)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.widget.a.setVideoPath(PLBaseVideoView.java:322)
04-19 18:31:55.976 23542-23542/com.maxleap.mobile.appmaker W/System.err:     at com.pili.pldroid.player.widget.PLVideoView.setVideoPath(PLVideoView.java:20)

**Comment by Jhuster** [comment]
@yjy951753 用 demo 试试
