### ISSUE TITLE
能否支持rtsp协议

### ISSUE THREAD

**Issue by FrankLove** [pili-engineering/PLDroidPlayer#537]
可以播放rtmp，但是rtsp却不行，可否考虑下支持rtsp呢

**Comment by Jhuster** [comment]
@FrankLove 用最新版本

**Comment by FrankLove** [comment]
@Jhuster 新版播放一个rtsp地址还是不行
 E/IJKMEDIA: rtsp://admin:lg123456@172.16.52.248:554/cam/realmonitor?channel=1&subtype=0: Protocol not found
这是我播放的一个rtsp然后出现这个提示

**Comment by Jhuster** [comment]
@FrankLove 你这个流，用 ffplay 或者 vlc 可以播？

**Comment by FrankLove** [comment]
@Jhuster 可以的，我用原生的ijkplayer播放都是没有问题的

**Comment by 1214658495** [comment]
大神，用最新版的可以播放rstp，但rstp本地流用点播模式，滑动进度条就会卡住。这个可以改程序参数解决吗？我的播放地址是“rtsp://192.168.42.1/tmp/SD0/TEST.MP4”。项目卡在这个点上，麻烦大神解答一下，万分感谢。

**Comment by 1214658495** [comment]
@Jhuster 大神，用最新版的可以播放rstp，但rstp本地流用点播模式，滑动进度条就会卡住。这个可以改程序参数解决吗？我的播放地址是“rtsp://192.168.42.1/tmp/SD0/TEST.MP4”。项目卡在这个点上，麻烦大神解答一下，万分感谢。

**Comment by FrankLove** [comment]
@1214658495  你这个播放的不是直播流吧

**Comment by 1214658495** [comment]
@FrankLove @Jhuster 是本地流媒体播放。就是把本地存储卡上的视频文件通过RSTP协议进行播放。可以和RSTP一样播放，但就是点播快进时就卡住不动了😢。
