### ISSUE TITLE
关于PLMediaPlayer重连的问题

### ISSUE THREAD

**Issue by hcyAndroid** [pili-engineering/PLDroidPlayer#544]
当播放在线视频的时候，遇到请求数据超时的时候，我让他重连，可是重连的时候，播放卡住。控制台上打印：  case PLMediaPlayer.MEDIA_INFO_BUFFERING_START。一直卡在这里，不往下执行。网络状态优秀，请问我该怎么处理重连最好。

**Comment by Jhuster** [comment]
@hcyAndroid 最新版本吗？用 demo 是否重现
