### ISSUE TITLE
PLVideoView无法开始播放视频

### ISSUE THREAD

**Issue by 646030315** [pili-engineering/PLDroidPlayer#545]
经过测试，我把PLVideoView直接放在界面最上层的时候，没有问题，如果表面有其他布局遮盖（一些加载布局），就会导致无法播放。请问这个问题怎么解决啊，在线等，很急。。

**Comment by Jhuster** [comment]
@646030315 首都首帧渲染的消息后，隐藏到其他遮盖的布局
