### ISSUE TITLE
播放完成监听没调用

### ISSUE THREAD

**Issue by buluojava** [pili-engineering/PLDroidPlayer#549]
控制条一直在走，播放完成监听也没有打印，播放的是rtsp转换成的mp4文件链接

**Comment by buluojava** [comment]
onError也没打印，播放完了重新回调一次缓冲就卡在那里，没有设置循环播放。

**Comment by buluojava** [comment]
大概是这个视频的问题？

**Comment by Jhuster** [comment]
@buluojava ffplay，VLC 等播放器播放这个文件是什么结果，有什么 log 输出。
