### ISSUE TITLE
为什么这报错？

### ISSUE THREAD

**Issue by xuekaiqi** [pili-engineering/PLDroidPlayer#550]
![qq 20170516102214](https://cloud.githubusercontent.com/assets/17778482/26087276/6b35fcf4-3a22-11e7-9030-c97cf7b4ad99.png)

    */
    private String genPublishURL() {
        String publishUrl = Util.syncRequest(isInputTypeJSON() ? GENERATE_STREAM_TEXT_V1 : GENERATE_STREAM_TEXT_V2);
        if (publishUrl == null) {
            Util.showToast(MainActivity.this, "Get publish GENERATE_STREAM_TEXT_V1 failed !!!");
            return null;
        }
        if (isInputTypeUnauthorized()) {
            // make an unauthorized GENERATE_STREAM_TEXT_V1 for effect
            try {
                URI u = new URI(publishUrl);
                publishUrl = String.format("rtmp://401.qbox.net%s?%s", u.getPath(), u.getRawQuery());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return publishUrl;
    }
}

? GENERATE_STREAM_TEXT_V1 : GENERATE_STREAM_TEXT_V2);这两个常量怎么找不到？

**Comment by Jhuster** [comment]
@xuekaiqi 这不是播放器的代码，而是推流的，你可以删除函数中的内容，填入一个推流地址即可。
