### ISSUE TITLE
如何设置PLVideoTextureView背景颜色

### ISSUE THREAD

**Issue by is1988** [pili-engineering/PLDroidPlayer#554]
我已经将PLVideoTextureView的background设置成黑色 加载的时候确实是全黑 但是加载完成 开始播放的时候 除了视频其他地方的颜色又变成了白色 请问如何设置

**Comment by droidxiao** [comment]
我也遇到这样的问题了，请问解决了么？

**Comment by is1988** [comment]
@droidxiao 除了PLVideoTextureView要设置 android:background="@color/colorBlack"
他坐在的layout也需要设置背景色为黑色  之前是我自己代码的问题
