### ISSUE TITLE
这播放器我越来越发现毛病越来越多了

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#555]
首先是布局问题，当嵌套到某些布局会导致不显示，或者闪一半，自己嵌套的问题也严重，修改为ｏｒｉｇｎ模式，视频都没有了，浪费了我不少时间，虽然我几个项目都在用，最近这些问题让我头疼

**Comment by Jhuster** [comment]
@qssq 布局和 UI 你可以完全自己写，PLMediaPlayer 提供了核心功能。另外，你的问题描述并不够准确和详细。

**Comment by qssq** [comment]
我头大，我基于ｐｖｉｄｅｏｖｉｅｗ，搞不懂这都是什么鬼问题，现在我写死高度正常了，不然适配区域会出现闪黑屏，我是搞不懂哪里问题，因为　这个容器里面其他布局都是正常的，　设置ｏｒｉｇｉｎ竟然视频都没有了我反复测试了半天才知道是设置视频缩放比为ｏｒｉｇｎ导致视频黑屏的问题，闪屏的问题还没有解决。　我现在放弃放在缩放比百分比布局或者　另外一种布局里面，
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, portrait&&full ? heightMeasureSpec : widthMeasureSpec * 9 / 16);　都有一些毛病，我另外一个界面稍微好一点没闪啊闪的，但是我都不知道到底怎么解决的。

**Comment by Jhuster** [comment]
@qssq 如果你对 UI 有特别地定制需求，可以用 `PLMediaPlayer`，然后自己写一个派生于 `SurfaceView` 的 View 类 ，传入 `Surface` 到播放器 SDK 即可

**Comment by qssq** [comment]
呜呜都太复杂了

**Comment by qssq** [comment]
我就是想弄个微信朋友圈的那样的动画加滑动关闭　，结果前面的视频　好像绘制出现了毛病，动画是成功了，可是视频总是闪

**Comment by zhanggao** [comment]
弄动画效果的需要用TextureView播放，不能用SurfaceView播放。这些东西跟播放器无关，你用别的也会出这些问题。
