### ISSUE TITLE
关于只播放网络视频

### ISSUE THREAD

**Issue by linzhengloser** [pili-engineering/PLDroidPlayer#556]
如果只播放网络视频,在设置参数方面和直播有什么区别？

**Comment by Jhuster** [comment]
如果不是直播流，可以按照点播的方式设置

**Comment by linzhengloser** [comment]
点播的方式是怎样设置的？能不能发下链接?谢谢~

**Comment by Jhuster** [comment]
@linzhengloser 参考 demo，选择 点播

**Comment by linzhengloser** [comment]
嗯好的~

**Comment by linzhengloser** [comment]
自定义MediaController
![image](https://cloud.githubusercontent.com/assets/12724989/26291827/cf03e9f6-3ee3-11e7-9fcd-71b67df0bb65.png)
![image](https://cloud.githubusercontent.com/assets/12724989/26291835/d8a3d2e6-3ee3-11e7-9bc3-d951daa5df4e.png)
![image](https://cloud.githubusercontent.com/assets/12724989/26291839/e060807e-3ee3-11e7-99cf-abd93df04b45.png)
点击暂停按钮,就报空指针,MediaPlayerController是空的,但是我刷新SeekBar的地方却没有报空指针.这是为什么？
