### ISSUE TITLE
这个播放器只能接入七牛云直播才能使用吗？

### ISSUE THREAD

**Issue by darkSuperman** [pili-engineering/PLDroidPlayer#557]
我看到帮助文档上面写到：文档为技术文档，需要阅读者：
具有基本的 Android 开发能力.
准备接入七牛云直播
也就是说不接七牛云直播的就不能使用吗？做了限制吗？

**Comment by Jhuster** [comment]
没有任何限制，都可以使用的

**Comment by darkSuperman** [comment]
好的，谢谢。

**Comment by darkSuperman** [comment]
请问一下，我用你的Demo测试下播放，输入了视频播放地址后，点击播放就显示 "unknow error"，无法播放，是直播的视频流，视屏源没问题，在网页能正常播放。请问这一般是什么原因呢?用点播也不能播放。

**Comment by Jhuster** [comment]
地址发出来看看，底层 log 输出也发下

**Comment by darkSuperman** [comment]
不好意思，是我地址搞错了，可以播放，谢谢。
