### ISSUE TITLE
把我自己的流地址放到项目中报Io异常，但是放到demo中可以正常直播？？？求解

### ISSUE THREAD

**Issue by JoxHero** [pili-engineering/PLDroidPlayer#566]
![image](https://cloud.githubusercontent.com/assets/16219982/26398073/f9083568-40aa-11e7-99a3-be483e0aecf8.png)

**Comment by Jhuster** [comment]
域名无法解析，同一个手机同一个网络下测试的？

**Comment by JoxHero** [comment]
推流的是pc端，是在一个网络下

**Comment by JoxHero** [comment]
demo和我自己的项目是在同一个手机测试的

**Comment by JoxHero** [comment]
解决了，要先启用dns缓存，因为项目流地址是外网的，我一直使用的是测试网络
