### ISSUE TITLE
1.4版本关播anr问题

### ISSUE THREAD

**Issue by TreasureTan** [pili-engineering/PLDroidPlayer#582]
弱网条件下退出直播间时候调用stop 和 销毁   但是还会产生anr问题  偶线

**Comment by hexi** [comment]
我也有这个问题

**Comment by hexi** [comment]
我用的是1.5.1版本

**Comment by Jhuster** [comment]
根据文档，打开 DNS 解析优化 https://github.com/pili-engineering/PLDroidPlayer/issues/351
