### ISSUE TITLE
有的视频不能播放，错误代码-858797304,但是手机自带播放器可以播放

### ISSUE THREAD

**Issue by hlmichael** [pili-engineering/PLDroidPlayer#586]
有的视频不能播放，错误代码-858797304,但是手机自带播放器可以播放

**Comment by tanhx2008** [comment]
看一下 log，可能是不支持的格式

**Comment by hlmichael** [comment]
http://cn-zjjh3-dx-v-06.acgvideo.com/vg2/9/00/18425263-1.mp4?expires=1497414000&platform=html5&ssig=M5bor2-wEubDruYAJ-Y07A&oi=3030925374&nfa=fkYkF/LEe5xFyJPq/bZ9eQ==&dynamic=1&hfa=2071168084  这个地址你可以试一下

**Comment by hlmichael** [comment]
http://cn-zjjh3-dx-v-06.acgvideo.com/vg2/9/00/18425263-1.mp4?expires=1497415200&platform=html5&ssig=v-FMCmmXO7ll9ZEW2lxAYg&oi=3030925374&nfa=fkYkF/LEe5xFyJPq/bZ9eQ==&dynamic=1&hfa=2071169109  可以试一下这个地址

**Comment by hlmichael** [comment]
不知道是不是跟cdn跳转有关，但好像也没有跳转

**Comment by hlmichael** [comment]
这个地址有失效时间，但是在有效的时间播放时会报Server returned 403 Forbidden (access denied)
