### ISSUE TITLE
请问能播放RTMP CDN吗?

### ISSUE THREAD

**Issue by BluewaytechPeter** [pili-engineering/PLDroidPlayer#59]
播放时出现 I/O error

**Comment by longbai** [comment]
可以的，麻烦提供下详细信息

**Comment by BluewaytechPeter** [comment]
AVOption setting:
AVOptions options = new AVOptions();
options.setInteger(AVOptions.KEY_MEDIACODEC, 1);
options.setInteger(AVOptions.KEY_BUFFER_TIME, 1000);
options.setInteger(AVOptions.KEY_GET_AV_FRAME_TIMEOUT, 8 * 1000);
options.setString(AVOptions.KEY_FFLAGS, AVOptions.VALUE_FFLAGS_NOBUFFER);
options.setInteger(AVOptions.KEY_LIVE_STREAMING, 0);

Error log:
E/IJKMEDIA: (private rtmp url with cdn): I/O error
E/ViewRootImpl: sendUserActionEvent() mView == null
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-5)

**Comment by longbai** [comment]
播放的路径给下

**Comment by BluewaytechPeter** [comment]
rtmp://fml.1AD01.omicroncdn.net/201AD01/aabbcc

**Comment by longbai** [comment]
ffplay rtmp://fml.1AD01.omicroncdn.net/201AD01/aabbcc is also failed.

**Comment by woyaosleeo** [comment]
rtmpdump -r "rtmp://fml.1AD01.omicroncdn.net/201AD01/aabbcc" -o abcd.flv
shows below error: "INFO: Connected...
ERROR: Closing connection: NetStream.Play.StreamNotFound"

**Comment by BluewaytechPeter** [comment]
因為是用CDN方式分發資源的，直接訪問會找不到。
請問PLDroid有類似FCSubscribe的请求或设定嗎?

**Comment by woyaosleeo** [comment]
做了如下实验，如果现在网页打开这个rtmp链接（用JWPLayer的插件）http://wpc.2dcc.edgecastcdn.net/002DCC/t//p/jvif.html?start=1&plugins=1&streamer=rtmp://fml.1AD01.omicroncdn.net/201AD01&file=aabbcc&fcsubscribe=true， 然后再用PLDroid 库，就可以看到视频流了。

**Comment by longbai** [comment]
这个是业务层的东西，PLdroid 不处理这个。

**Comment by woyaosleeo** [comment]
> 这个是业务层的东西，PLdroid 不处理这个

请问如果要添加这样的支持，我们自己需要做哪些工作，或者具体在哪几个文件中修改呢？指点一下吧。
