### ISSUE TITLE
重连错误回调的问题

### ISSUE THREAD

**Issue by liyuyitong** [pili-engineering/PLDroidPlayer#591]
播放连接失败，如果返回ERROR_CODE_READ_FRAME_TIMEOUT，我这边然后重连，后面重连失败，都不会再有OnErrorListener的回调

**Comment by liyuyitong** [comment]
1.播放连接失败，OnErrorListener回调，如果返回的是ERROR_CODE_READ_FRAME_TIMEOUT；
2.重新连接，还是连不上，也不会再有OnErrorListener的回调

**Comment by Jhuster** [comment]
@liyuyitong PREPARE 超时时间是多少？
