### ISSUE TITLE
今天打开工程提示com.qiniu:happy-dns:0.2.+不能用，官方的包也是

### ISSUE THREAD

**Issue by dazhiyu** [pili-engineering/PLDroidPlayer#592]
Error:(25, 13) Failed to resolve: com.qiniu:happy-dns:0.2.+
<a href="openFile:C:/Users/Administrator/Desktop/PLDroidPlayer-1.5.1/PLDroidPlayerDemo/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Jhuster** [comment]
我这边可以的，应该是你那边的环境问题
