### ISSUE TITLE
混淆编译时大量警告不知道是咋回事

### ISSUE THREAD

**Issue by jayleco** [pili-engineering/PLDroidPlayer#596]
混淆文件里加了
#PLDroidPlayer混淆
-keep class com.pili.pldroid.player.** { *; }
-keep class tv.danmaku.ijk.media.player.** {*;}

下面是报错截图：
![default](https://user-images.githubusercontent.com/9976349/27381892-225e5e5c-56b7-11e7-870e-c7b13aa4110f.png)

**Comment by Jhuster** [comment]
加上 `-keep class com.qiniu.** { ; }`
