### ISSUE TITLE
建议统一播放暂停入口 

### ISSUE THREAD

**Issue by qssq** [pili-engineering/PLDroidPlayer#597]
比如控制播放的，监听暂停 功能在哪里？ player也可以暂停，plvideoview也可以暂停，我现在是把所有都弄到了mediacontrol里面然后统一调用player进行暂停不然多个入口暂停问题可真大

**Comment by qssq** [comment]
我是在做弹幕的时候发现的不足。

**Comment by Jhuster** [comment]
@qssq SDK 对外的接口是 PLMediaPlayer 和 PLXXXVideoView，这个接口的暂停是对外的唯一接口，`mediacontrol` 是 app 层面的东西

**Comment by qssq** [comment]
没有回调吧？ 最终是调用了player 但是我没看到有做暂停的回调监听，搞的我只能到处控制 都是使用mediacontrol来维护包括 onResume
