### ISSUE TITLE
低版本PLVideoTextureView会报错

### ISSUE THREAD

**Issue by buluojava** [pili-engineering/PLDroidPlayer#598]
4.2.2退出播放界面的时候会报
E/SurfaceTexture: [unnamed-1217-0] detachFromContext: abandoned SurfaceTexture
E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
定位到是PLVideoTextureView的原因报的，我的minSdkVersion是14不明白为什么还会报这个错~~~~~

**Comment by Jhuster** [comment]
@buluojava 跑的 demo，毕现吗

**Comment by buluojava** [comment]
@Jhuster 邮件被当垃圾拦截了没看到，不是直接跑demo，是我集成后在项目里报，是必现。4.4以上不会报。
