### ISSUE TITLE
集成到项目里面报错了，帮忙看下

### ISSUE THREAD

**Issue by yuanyang5917** [pili-engineering/PLDroidPlayer#60]
Failed to register native method tv.danmaku.ijk.media.player.IjkMediaPlayer._setDataSource(Ltv/danmaku/ijk/media/player/misc/IMediaDataSource;)V in /data/app/com.xlingmao.maomeng-1/base.apk:classes2.dex
04-14 11:18:32.957 16092-16092/? A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception 'java.lang.NoSuchMethodError' thrown in java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String):-2
in call to FindClass from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)

**Comment by yuanyang5917** [comment]
重新倒入下就好了

**Comment by yuanyang5917** [comment]
是混淆出的错，能不能给个防混淆策略

**Comment by nbbzh** [comment]
请问你是怎么解决的？
