### ISSUE TITLE
android 广告机 双屏异显的时候，副屏上不能播放视频

### ISSUE THREAD

**Issue by liujun3512159** [pili-engineering/PLDroidPlayer#600]
我最近想把PLDroidPlayer整合到我的工程中，现在遇到一个小问题，我发现，这个PLDroidPlayer播放器，不能在双屏异显中的”副屏”上播放视频，但是，可以在主屏上播放视频，请问怎么办？
而且，我用另外一款播放器KSYMediaPlayer(金山云播放sdk)，也有这个问题，我和他们的技术交流了下，他们确认这是一个bug了，我猜测，PLDroidPlayer估计也是同样的问题

双屏异显，即一个android主板，对应2个屏幕，一个主屏，一个副屏。

**Comment by songhaonangit** [comment]
你用的是横屏显示还是竖屏呢？

**Comment by songhaonangit** [comment]
你用的是横屏显示还是竖屏呢？@liujun3512159
