### ISSUE TITLE
后台播放指的是退出Activity，还可以继续音频播放么。

### ISSUE THREAD

**Issue by Vander-liu** [pili-engineering/PLDroidPlayer#603]
为什么我在Demo中没有找到。。。

**Comment by Jhuster** [comment]
Activity.onPause 的时候，不调用 pause 即可

**Comment by Vander-liu** [comment]
懂了，如果我想实现Activity退出后实现声源播放，有好的方案推荐么，我的想法是开一个Service，然后通过AudioMedia实现。但是具体还在思考中，还没实践。

@Jhuster
