### ISSUE TITLE
如何在当前页面快速撤换播放源

### ISSUE THREAD

**Issue by guojiadui** [pili-engineering/PLDroidPlayer#608]
mVideoView.stopPlayback();
                mVideoView.setVideoURI(Uri.parse(url2));
                mVideoView.start();
我是这样做的，但是有几秒钟界面是没有任何反应，就卡在上一个播放源的界面不动，也没有加载动画和封面，体验很不好，怎么解

**Comment by Jhuster** [comment]
@guojiadui demo 有演示如何设置一个 loading 动画

**Comment by bifan-wei** [comment]
我也是这个问题，请问解决了么

**Comment by guojiadui** [comment]
我已经用其他播放器了
