### ISSUE TITLE
多段视频连续播放

### ISSUE THREAD

**Issue by charmeleon2** [pili-engineering/PLDroidPlayer#616]
服务器的视频是分成多段的，七牛是否有提供api能连续播放多段视频，放完一段后再去set第二段的地址会有一个加载的过程，体验不是很好

**Comment by stvenjobs** [comment]
我之前也发现七牛这块的体验不好了，后来改用金山的SDK，发现他们这块做的不错，你可以去体验下。

**Comment by Jhuster** [comment]
下一版本会优化这块体验

**Comment by Billllllllll** [comment]
我之前也发现七牛这块的体验不好了，后来改用金山的SDK，发现他们这块做的不错，你可以去体验下。而且他们版本更新比较活跃。

**Comment by linzhengloser** [comment]
请问一下 调用什么方法来设置多段视频？ 我调用了 setVideoPath 然后在调用 start 方法 好像能播了。

**Comment by Jhuster** [comment]
@linzhengloser 需要在 onCompletion 的时候，设置下一个视频

**Comment by linzhengloser** [comment]
我在  onCompletion 方法 中 调用 setVideoPath 然后在 调用 start 然后就没有然后了，并没有播放下一个视频。

**Comment by linzhengloser** [comment]
我是先播放的一个本地视频 然后在播放的一个网络视频 请问跟这个有关系吗？

**Comment by Jhuster** [comment]
@linzhengloser 确实收到 onCompletion 消息了吗？ 设置 setVideoPath 后，有什么错误输出？log 发出来看看

**Comment by linzhengloser** [comment]
![image](https://user-images.githubusercontent.com/12724989/28196774-50000060-6885-11e7-9d5e-d749df75fd2e.png)
不知道这个是不是报错的log.

**Comment by Jhuster** [comment]
@linzhengloser 不是，给一份完整的 log 吧

**Comment by linzhengloser** [comment]
07-14 13:48:38.334 6064-6064/com.risenb.honourfamily W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
07-14 13:48:38.334 6064-6064/com.risenb.honourfamily W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
07-14 13:48:38.480 6064-20859/com.risenb.honourfamily E/IJKMEDIA: Option http-detect-range-support not found.
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 00000001
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 6764001f
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: acd94090
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 1e684000
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 00030040
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 00000f03
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: c60c6580
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 00000001
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 68ebe3cb
07-14 13:48:38.635 6064-20859/com.risenb.honourfamily E/IJKMEDIA: csd-0[38]: 22c00000
07-14 13:48:38.678 6064-20859/com.risenb.honourfamily E/IJKMEDIA: configure acodec:0x1006ee format:0x716: surface:0x70a
07-14 13:48:38.700 6064-20875/com.risenb.honourfamily W/ACodec: Failed to set ANW_HWComposer to OMX, ignoring (-61)
07-14 13:48:38.701 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual 7
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 7 failed: -2147483648
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual 6
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 6 failed: -2147483648
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual 5
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 5 failed: -2147483648
07-14 13:48:38.702 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual 4
07-14 13:48:38.760 6064-20875/com.risenb.honourfamily W/ACodec: Failed to set ANW_HWComposer to OMX, ignoring (-61)
07-14 13:48:38.762 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual f
07-14 13:48:38.763 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 15 failed: -2147483648
07-14 13:48:38.763 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual e
07-14 13:48:38.763 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 14 failed: -2147483648
07-14 13:48:38.763 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual d
07-14 13:48:38.764 6064-20875/com.risenb.honourfamily W/ACodec: [OMX.MTK.VIDEO.DECODER.AVC] setting nBufferCountActual to 13 failed: -2147483648
07-14 13:48:38.764 6064-20875/com.risenb.honourfamily W/ACodec: nBufferCountActual c

**Comment by linzhengloser** [comment]
我不在 onCompletion 中调用  setVideoPath 就能够正常切换视频。

**Comment by linzhengloser** [comment]
我试了下 如果直接在 onCompletion 里面 setVideoPath 会无法播放 但是如果 发一个延时的消息去播放就可以。 不知道是不是我代码写的有问题。

**Comment by yuger** [comment]
同遇到这个坑，没有任何异常日志，延时几百毫秒start()就可以了

**Comment by zshbleaker** [comment]
这个问题已经修复，SDK 内部会处理异步队列，上层使用起来更方便。预计这两天会发布更新，感谢反馈。
