### ISSUE TITLE
libpldroidplayer.so: has text relocations

### ISSUE THREAD

**Issue by HC-lee** [pili-engineering/PLDroidPlayer#617]
项目的targetSdkVersion为22以上时，在android版本22以上的模拟器视频不能播放，报错信息为 libpldroidplayer.so: has text relocations；
将targetSdkVersion设置成22时可正常播放。
![wx20170717-154425 2x](https://user-images.githubusercontent.com/10934974/28259279-1192c5bc-6b08-11e7-8b23-8fcd8203948e.png)

**Comment by Jhuster** [comment]
https://github.com/pili-engineering/PLDroidPlayer/issues/311
