### ISSUE TITLE
建議在非 main thread 也能操作 PLVideoView

### ISSUE THREAD

**Issue by sc0ttie** [pili-engineering/PLDroidPlayer#625]
原本一直在使用 `PLMediaPlayer`
由於需要控制列就換成了 `PLVideoView`
但是在非 main thread 中呼叫 `.setVideoPath()`, `.start()`, `.stopPlayback()` 等方法就噴錯誤了
後來確認這些操作都是在 main thread 呼叫就正常了

Error Stack trace 如下：
![screen shot 2017-08-01 at 5 00 18 pm](https://user-images.githubusercontent.com/3683472/28817632-70f208e0-76db-11e7-9217-c37df5f7bb95.png)

**Comment by Jhuster** [comment]
@Malthael 能否不在非主线程调用该 API ？

**Comment by Malthael** [comment]
當然可以，但是就必須在每個呼叫這些 API 的地方多包一層 `.runOnUiThread()`，如果 API 內有做這件事的話就更好了，也可以減輕一些主執行緒的負擔。

**Comment by ReikyZ** [comment]
View 需要在主线程执行
