### ISSUE TITLE
播放视频PLVideoTextureView.getCurrentPosition居然超过了getDuration时间？？

### ISSUE THREAD

**Issue by 15281046619** [pili-engineering/PLDroidPlayer#626]
有什么解决方法吗？？

**Comment by Jhuster** [comment]
@15281046619 是不是跟视频有关，其他视频呢

**Comment by 15281046619** [comment]
对，与视频有关。还有就是部分视频能显示没声音。

**Comment by 15281046619** [comment]
对，与视频有关。还有就是部分视频能显示没声音。

**Comment by Jhuster** [comment]
@15281046619 发一个视频看看。 另外，没声音的问题，可以参考其他 issue ，增大 probesize

**Comment by 15281046619** [comment]
http://www.xingyi888.com/xingyi/upload/video/201706/af2a49de5a4f00679cc59ad9e331722e26a05e41.mp4
