### ISSUE TITLE
能否更新最新的ijkmediaplayer版本

### ISSUE THREAD

**Issue by hlmichael** [pili-engineering/PLDroidPlayer#628]
能否更新到最新的ijkmediaplayer版本，目前这个里面的ijkmediaplayer版本有一些功能不支持

**Comment by Jhuster** [comment]
@hlmichael 即将发布新版本，使用全新自研内核，你关注的是什么新功能

**Comment by hlmichael** [comment]
@Jhuster  我在使用plmediaplayer的时候发现一些请求被403拒绝掉了，但是直接使用最新ijkmediaplayer版本的时候就可以正常播放视频，非常希望能解决一下  谢谢
