### ISSUE TITLE
请问有支持截图，录屏和倍速播放的计划吗？

### ISSUE THREAD

**Issue by wzgl5533** [pili-engineering/PLDroidPlayer#629]
请问有支持截图，录屏和倍速播放的计划吗？

**Comment by Jhuster** [comment]
@wzgl5533 即将发布的新版，支持 mp4 倍数播放，支持音视频解码后的数据回调，录屏的话，推荐使用 https://github.com/pili-engineering/PLDroidShortVideo 的录屏 API 完成录屏功能

**Comment by wzgl5533** [comment]
目前没有针对RTMP等流媒体的操作吧？

**Comment by Jhuster** [comment]
@wzgl5533 实时直播流，是无法做到倍数播放的，有了播放解码后的音频、视频数据回调，截图和录屏是可以的，不过要看你是录制 App 屏幕，还是录制播放的音视频数据了

**Comment by wzgl5533** [comment]
新版本什么时候发布呢？

**Comment by Jhuster** [comment]
@wzgl5533 本周内会发布

**Comment by Jhuster** [comment]
@wzgl5533 已发布
