### ISSUE TITLE
不支持MKV吗？

### ISSUE THREAD

**Issue by General110** [pili-engineering/PLDroidPlayer#63]
E/IJKMEDIA: http://127.0.0.1:80/34406.mkv: Invalid data found when processing input
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [24396]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-1094995529)

**Comment by longbai** [comment]
目前还不支持，以后看情况考虑。
