### ISSUE TITLE
dns缓存相关

### ISSUE THREAD

**Issue by a1227308812** [pili-engineering/PLDroidPlayer#630]
我集成了compile 'com.qiniu:happy-dns:0.2.+'之后，没有设置自己的代理服务器，但是我播放我自己服务器上面的视频文件之后，它自己就缓存了该视频文件，现在我想我再次播放这个视频的时候能不能通过上面判断我已经缓存了这一个视频文件了就直接不在网络获取视频文件，从而直接使用已经缓存的视频文件呢？有没有这个接口啊？

**Comment by Jhuster** [comment]
@a1227308812 描述很绕，缓存是你做的，你可以判断是非有缓存，SDK 目前的版本没有本地缓存呢
