### ISSUE TITLE
PLVideoTextureView的setCoverView方法为什么会自动播放视频

### ISSUE THREAD

**Issue by as2227024221** [pili-engineering/PLDroidPlayer#633]

**Comment by Jhuster** [comment]
@as2227024221 不会的，应该是你有调用 start 或者 option 里面有配置自动播放

**Comment by as2227024221** [comment]
设置AVOptions.KEY_START_ON_PREPARED为0时setCoverView就获取不到封面了

**Comment by Jhuster** [comment]
@as2227024221 获取不到封面是什么意思，你的封面 ImageView 默认是 Visible 的吗 ？

**Comment by cuibg** [comment]
setcoverview 没有任何效果
