### ISSUE TITLE
可以进行码率切换吗？如何实现？？？

### ISSUE THREAD

**Issue by junmei520** [pili-engineering/PLDroidPlayer#636]

**Comment by Jhuster** [comment]
@junmei520 视频流的码率不是由播放端决定的，切换码率是由生产端负责的

**Comment by junmei520** [comment]
那生产端给我提供多种码率，我进行手动切换，是不是只要切换对应的流就可以了？

**Comment by Jhuster** [comment]
@junmei520 是的

**Comment by junmei520** [comment]
运行了下demo，不能实现上下滑动调节亮度声音吗？

**Comment by Jhuster** [comment]
@junmei520 app 自己去实现

**Comment by junmei520** [comment]
要满足我们自己的一些播放器要求，需要更改源码,您这个项目不是开源的是吧？

**Comment by Jhuster** [comment]
@junmei520 嗯，不开源，屏幕亮度可以在 app 层去做的，声音 SDK 提供了接口。

**Comment by junmei520** [comment]
使用mVideoView.setCoverView(coverView);来设置播放封面，只能设置本地图片，不能直接设置网络图片进行加载显示吗？由于异步联网加载，我这样写肯定不行吧：
        IageView coverView = (ImageView) findViewById(R.id.CoverView);
        String imgUrl="http://img.news.cctvplus.com/2017/0813/8058238_1502618830081_a.jpg";
        Glide.with(this).load(imgUrl).into(coverView);
        mVideoView.setCoverView(coverView);

**Comment by junmei520** [comment]
看到网上有说七牛的“直播推流端弱网优化策略”，也就是说你们推流端做了码率的自动切换处理，但是播放端没有做？？？

**Comment by Jhuster** [comment]
@junmei520 你可能没有真正理解动态码率的意思，动态码率是指，推流端发现网络不好的时候，主动降低码率，码流还是那个码流，并不会多产生一个新的码流，播放器端自然不需要做任何处理

**Comment by Jhuster** [comment]
@junmei520 封面图，你可以在外部 download & cache 下来，播放器不支持设置网络图片的封面

**Comment by junmei520** [comment]
切换清晰度可以再播放端实现吗

**Comment by Jhuster** [comment]
@junmei520 如果服务端做了各种分辨率的转码，一般不同的清晰度会有不同的 Video URL，你切换，就是 `setVideoPath` 设置不同的 URL 而已
