### ISSUE TITLE
横屏有白边

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#638]
我设置横屏播放后，左右两侧有白边，我通过代码怎么调都不能全屏播放，请问怎么解决？能直接QQ或者邮箱告知吗？非常感谢！QQ账号：837545155

**Comment by Jhuster** [comment]
@panyingdaoz mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);

**Comment by panyingdaoz** [comment]
非常感谢！我也刚看开发文档使用这个发放解决了
