### ISSUE TITLE
2.0.0问题

### ISSUE THREAD

**Issue by FireCatcher** [pili-engineering/PLDroidPlayer#639]
你好，今天试了下新版本的播放，遇到几个问题，麻烦给看看
1. 无法播放https的视频，而v1.6 是可以正常播放的
2. 在小米note2上用demo播放1080p的265视频，CPU占用高达 70%，这个还能优化不？

谢谢啦

**Comment by Jhuster** [comment]
@FireCatcher 我们有测试过 HTTPS 的播放，你测试的地址发出来我们验证下，多谢

**Comment by Jhuster** [comment]
@FireCatcher H.265 1080P 的解码的确会比较耗性能，我们在小米 5s 上测下来平均是 50% 左右，也要看视频源本身的情况，优化的话，回头我们再尝试看看有无优化空间

**Comment by FireCatcher** [comment]
视频内容有版权关系，地址不能给出来，抱歉
建议多测试下https的视频播放，我们多次测试确认在v2.0上是无法播放的，在v1.6上是ok的

**Comment by FireCatcher** [comment]
1080p的265解码确实会比较耗性能，测试视频内容是游戏场景
但是小米Note2是很新的机器了，70%的cpu占比确实有点夸张了...
APP基本没法做其它的操作了，会很卡..

**Comment by Jhuster** [comment]
@FireCatcher HTTS 那个问题，播放不了的话，底层会有 error 信息输出，麻烦发出来下，或者发我邮箱也行，多谢

**Comment by Jhuster** [comment]
@FireCatcher H.265 我们测下来没有这么高的 CPU 占用率，另外，这个占用率是指一个核还是所有核加起来这么多，你用什么工具测的，曲线图发出来看看

**Comment by FireCatcher** [comment]
就用的Android Studio的monitor，下面是cpu的曲线图

![image](https://user-images.githubusercontent.com/30924570/29399111-7ff3749c-835a-11e7-9bf7-803daf13f1e2.png)

**Comment by FireCatcher** [comment]
https视频播放失败的问题可能跟网络有关，换个网络就ok了，比较奇怪
