### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#64]
请问像那种网络抓取的视频怎样获取播放时间？总时间和当前播放的时间？因为我们的项目是分两种视频，一种是七牛的直播流，一种是网上抓取的视频。我看了里边的API好像没有获取时间的API啊？想请教您一下，谢谢！

**Comment by longbai** [comment]
直播没法获取总时间，可以用getposition 获取当前时间。 网上抓取的视频 是什么意思，能说下详细信息么？

**Comment by lzx1** [comment]
就是一场比赛 或者一集电视剧那种视频 像这样的 http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4

**Comment by longbai** [comment]
/**
     * Gets the duration of the file.
     *
     * @return the duration in milliseconds, if no duration is available
     *         (for example, if streaming live content), -1 is returned.
     */
    public long getDuration() {
        return mMediaPlayer.getDuration();
    }

这个 API 可以，如果能获取到meta信息 就可以 返回总长度。

**Comment by lzx1** [comment]
OK 我也看到了 在MediaController中 3q
