### ISSUE TITLE
网络处理

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#641]
我在做网络处理时，看了“http://blog.csdn.net/peaceful000/article/details/51996250”学习时，里面的“getStreamStatus”这个方法当中的“HttpEntity entity = response.getEntity();和HttpResponse”过时了怎么替换

**Comment by Jhuster** [comment]
@panyingdaoz 这个问题跟本 SDK 好像无关？

**Comment by panyingdaoz** [comment]
嗯，因为api6.0这些都没有了，所以我不知道怎么替换
