### ISSUE TITLE
2.0.0严重bug无法循环播放

### ISSUE THREAD

**Issue by seekting** [pili-engineering/PLDroidPlayer#643]
hi,pili-engineering
我发现一个重大bug,最新版2.0.0无法循环播放，通过:
setLooping(true)之后，视频第一次播放到结尾的时候会再播放一次，但是第二次播放完就再也不会循环了，另外，文档里说setLooping(true)之后，不会走onCompletion，但是仍然会走onCompletion

**Comment by AndMy** [comment]
onCompletion里面next

**Comment by seekting** [comment]
没有next的api哦

**Comment by seekting** [comment]
我怀疑c层的seek有问题，我尝试过用seekto实现，播放快结束的时候seekto 0但是第二次seekt to 的时候没有反应

**Comment by Jhuster** [comment]
@seekting 多谢反馈，已确认的确是个 bug，新版本升级改动比较大，近期会集中修复推出一个新的修复版本，抱歉

**Comment by panyingdaoz** [comment]
bug修复后麻烦告知，非常感谢！

**Comment by wjk2813** [comment]
2.0.6还没有修复吧，setLooping(true),然后重新播放的时候每次都出错 seek出错

**Comment by zshbleaker** [comment]
下个版本会重新实现 loop 的机制，彻底解决这个问题，并且大幅减少重复播放时的 buffering 时间
