### ISSUE TITLE
2.0.0在htc D820t 和  一加  ONE A2001 上native err 

### ISSUE THREAD

**Issue by lgthunder** [pili-engineering/PLDroidPlayer#646]
![image](https://user-images.githubusercontent.com/8942966/29258328-32d093b4-80eb-11e7-9ad0-a06f0f1d29e0.png)
![image](https://user-images.githubusercontent.com/8942966/29258338-4b5a8228-80eb-11e7-9cf0-422c3d6ce375.png)
错误log很多不知道哪个对你们有用，如果有帮助也能提供其他log

**Comment by Jhuster** [comment]
@lgthunder demo 可以跑起来吗 ？
