### ISSUE TITLE
Error happened, what = -10000, errorCode = -541478725

### ISSUE THREAD

**Issue by susussa** [pili-engineering/PLDroidPlayer#648]
E/IJKMEDIA: Failed to reconnect at 3668.
E/IJKMEDIA: error reading header
E/IJKMEDIA: http://rmrbtest-image.peopleapp.com/upload/video/201708/15026843859262141627fe99cc.mp4: End of file
D/IJKMEDIA: FFP_MSG_ERROR: -541478725
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [7665]
E/tv.danmaku.ijk.media.player.IjkMediaPlayer: Error (-10000,-541478725)
 E/PLMediaPlayer: Error happened, what = -10000, errorCode = -541478725

这是什么问题？

**Comment by Jhuster** [comment]
@susussa 流本身有问题，无法打开
