### ISSUE TITLE
MP4视频播放失败

### ISSUE THREAD

**Issue by dcskys** [pili-engineering/PLDroidPlayer#649]
2.0版本和1.6测试都失败 返回错误代码ERROR_CODE_OPEN_FAILED  -2 ，播放器打开失败 
播放地址 :http://183.129.248.50:11080/HighwayPlatform/upload/2017/08/14/1502690260043.mp4

**Comment by Jhuster** [comment]
@dcskys 这个文件可能是损坏的，其他的播放器，如 ffplay 也播放不了 ，报错：

`Stream ends prematurely at 4104, should be 597808`

**Comment by ghost1020** [comment]
https://download.91playmate.cn/1123ac9bbb3bef7608fa091f6f376315.mp4
这个视频在=1.6是可以播放的在2.0报-3，-2

**Comment by Jhuster** [comment]
@ghost1020 下一个版本修复
