### ISSUE TITLE
快速滑动黑屏

### ISSUE THREAD

**Issue by susussa** [pili-engineering/PLDroidPlayer#651]
D/IJKMEDIA: IjkMediaPlayer_start
 D/IJKMEDIA: ijkmp_start()
 D/IJKMEDIA: ijkmp_start()=-3
 W/tv.danmaku.ijk.media.player.IjkMediaPlayer: setScreenOnWhilePlaying(true) is ineffective for Surface
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
 D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbefcbca0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0xbefcbca0)=void
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27734]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27741]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27740]
 I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [27747]
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xaec318c0)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xaec31d00)
 E/IJKMEDIA: SDL_Overlay(ffmpeg): overlay_free_l(0xaee39680)
D/IJKMEDIA: ijkmp_shutdown_l()=void
 D/IJKMEDIA: ijkmp_dec_ref(): ref=0
 D/IJKMEDIA: ijkmp_shutdown_l()
 D/IJKMEDIA: ijkmp_shutdown_l()=void
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [8189] didn't call SDL_JNI_DetachThreadEnv() explicity
A/PowerManager: WakeLock finalized while still held: tv.danmaku.ijk.media.player.IjkMediaPlayer

**Comment by Jhuster** [comment]
@susussa 试试最新版本
