### ISSUE TITLE
2.0.0 首次播放機率性出現黑畫面

### ISSUE THREAD

**Issue by Malthael** [pili-engineering/PLDroidPlayer#652]
使用的元件是 `PLVideoView`，
執行的機器為紅米 3（Android 6.0.1），
播放 <del>RTMP</del> **HLS** 連結，
黑畫面的情況都是在第一次開 app 並第一次呼叫 `.start()` 時出現（無畫面無聲音），
`onInfo` 會持續噴出 `200`, `20001`, `20002`, `20003`, `20004`，
呼叫 `.isPlaying()` 回 `true`。

目前發現解決方法是讓 app 回到背景再回前景觸發 `onResume()`，
我在 `onResume()` 中有呼叫 `.start()`，
然後聲音跟畫面就出現了，
`onInfo` 出現 `200`, `10004`, `10005`。

但如果是自己連續呼叫兩次 `.start()` 或中間有間隔一些時間再呼叫都無效，
一定要到背景再回到前景的那次 `.start()` 才有用。

PS 更正，是播放 HLS 流

**Comment by Jhuster** [comment]
@Malthael 跑的我们的官方 demo 吗，其他手机有出现这个现象吗，RTMP 流地址可以发出来我们测测看吗

**Comment by Malthael** [comment]
@Jhuster 抱歉，我發現是播放 HLS 流...

1. 是自己的 app
2. 目前用另外一隻 HTC Desire 728 沒有發生過這種問題，但是紅米3幾乎是首開必發生
3. 待會將連結寄給你

下午會試著用你們的官方 demo 在我手邊的各測試機跑跑看相同連結，有結果出來會在這邊更新

**Comment by Malthael** [comment]
@Jhuster 請問有收到連結嗎？

官方的 demo 都可以播放我的 HLS 流，
剛剛把我的邏輯簡化到跟 demo 的一樣，
但結果變成紅米3無法播放了...

設定了 `.setDebugLoggingEnabled(true)`，
播放時 Logcat 一直重複噴出如下所示：
```
I/@@@QCLOG: Info T5A757450 C_HLS_Entity L972 live Playlist End!
I/@@@QCLOG: Info T5A757450 CBaseObject L112 In BA: cur buffer time:0, ullLastSegmentStartTime:0, ullLastSegmenetTransTime:84, ullLastBASegment:0
I/@@@QCLOG: Info T5A757450 C_M3U_Manager L1792 the PlayList Id:0, the sequenceId:1047
I/@@@QCLOG: Info T5A757450 C_M3U_Manager L1806 Can't get the sequence id:1047 in playlist:0
```

另外我想要設定 `onPreparedListener`，
但是看 `PLVideoView` 的建構子中有設定過了，
那我再設定一次把他原本的蓋過去會影響使用嗎？
