### ISSUE TITLE
无法暂停播放

### ISSUE THREAD

**Issue by pengdun** [pili-engineering/PLDroidPlayer#653]
调用pause()方法,后通过系统流量监控明显可以看到直播数据流量还在跑...使用版本2.0.0. 以前1.+版本好像也有这个问题

**Comment by Jhuster** [comment]
@pengdun 直播是实时流，不支持暂停，它不是点播文件，如果直播不想继续播放了，请关闭播放器

**Comment by pengdun** [comment]
@Jhuster 嗯 好的~
