### ISSUE TITLE
2.0不支持rtsp流媒体协议播放了？

### ISSUE THREAD

**Issue by 1214658495** [pili-engineering/PLDroidPlayer#654]
@Jhuster  大神您好，测试了2.0，发现不支持rtsp流媒体协议播放了？请问是更改了什么地方了？之前1.51是支持的

**Comment by Jhuster** [comment]
@1214658495 嗯，抱歉，由于 RTSP 的播放需求量不大，为了减小包体大小，新版我们去掉了对 RTSP 的支持
