### ISSUE TITLE
倍速播放怎么没有声音

### ISSUE THREAD

**Issue by anfengchuiyu** [pili-engineering/PLDroidPlayer#655]
倍速播放时没有声音，恢复1倍速后才有声音

**Comment by Jhuster** [comment]
@anfengchuiyu 的确是这样设计的，因为音频加速后，会变声，体验不好

**Comment by anfengchuiyu** [comment]
@Jhuster 请问有没有解决办法呢，我之前用过VLC，但是会遇到VLC不能播放某个MP4文件，但是其他播放器可以

**Comment by Jhuster** [comment]
@anfengchuiyu 这个不是问题，不存在解决办法，快放从理论上无法做到声音正常播放

**Comment by Jhuster** [comment]
@anfengchuiyu 新版已支持倍数后继续播放声音（注意，倍数后，声音会变声）

**Comment by zds-github** [comment]
新版倍速播放依然没有声音，设置倍速播放就没有声音了
