### ISSUE TITLE
设置预览模式为全屏铺满时，所播放视频在宽高不标准的视频控件内显示不全

### ISSUE THREAD

**Issue by AlexQcs** [pili-engineering/PLDroidPlayer#658]
当设置预览模式mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);时，如果视频的分辨率为1920*1080，而videoview的宽高为1000*800时，视频右边或者下边超出控件范围导致显示不全

**Comment by AlexQcs** [comment]
是否支持拉伸填满控件，而不是超出控件范围，或者是上下留白

**Comment by Jhuster** [comment]
@AlexQcs 嗯，各种 issue ，关于这个问题解释过很多遍了，视频分辨率与View长宽比比例不一致的时候，理论上没有办法做到 “不产生画面变形的情况下” 铺满控件，请仔细思考一下是不是这样的

**Comment by AlexQcs** [comment]
@Jhuster 不不不，你理解错我的意思了，我想要的效果是可以铺满控件，画面可以变形

**Comment by Jhuster** [comment]
@AlexQcs 这不是常规的设计，没有 “用户” 会喜欢变形的画面

**Comment by AlexQcs** [comment]
@Jhuster 主流视频网站如爱奇艺除了100%之外都会有铺满这个选项

**Comment by Jhuster** [comment]
@AlexQcs `mVideoView.setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT)` 这个就是铺满选项，如果视频流分辨率是 16:9，就能完美铺满，你看看主流视频网站播放的视频，是不是都是 16:9 的流

**Comment by misszero** [comment]
> @AlexQcs 这不是常规的设计，没有 “用户” 会喜欢变形的画面

没有用户喜欢变形的画面，但是的确有拉伸的需求，举个例子，某些户外LED屏高宽像素密度不一样，投屏的时候要求你画面宽度不变，而高度变为原来的一半，这样你的画面就必须拉伸。
