### ISSUE TITLE
关于视频压缩的问题

### ISSUE THREAD

**Issue by lzx1** [pili-engineering/PLDroidPlayer#66]
推流端推上去的视频比例是16:9，但是播放端的播放器是9:16的，怎样设置让视频不压缩，要不根本没法看啊？加急，望不吝赐教。

**Comment by lawder** [comment]
比例不一致就需要做 crop，如何 crop 参看demo 代码  onVideoSizeChanged()

**Comment by lzx1** [comment]
请再详细一点好吗 具体怎样crop呢？

**Comment by Tasla** [comment]
官方sdk 中提供的VideoView 并没有crop 操作，按照官方的demo 来设置，只能达到VideoView 全屏，播放内容拉伸。原因是因为它继承自SurfaceView，所以想要做到 center crop 的效果，就需要重写VideoView。VideoView中只是封装了一些MediaPlayer的操作和各种回调，所以只要实现一个继承自TextureView 的VideoView，并将官方的VideoView 中关于MediaPlayer和回调的封装迁移即可。TextureView 可以设置各种缩放／移动，算出屏幕和内容的宽高比值，在对TextureView进行transform 的设置。官方的做法可能是为了兼容低版？
