### ISSUE TITLE
问题很多，包括卡,没有图像,bilibili视频不能播放等

### ISSUE THREAD

**Issue by hlmichael** [pili-engineering/PLDroidPlayer#660]
1.视频间歇性打开黑屏，卡顿 有一些些声音
2.bilibili部分视频不能播放 ,errorcode:-3
3.带header的setdatasource方法不能使用，或者说调用但是不能播放

**Comment by Jhuster** [comment]
@hlmichael 麻烦给出更详细的信息：

1 和 2  有问题的视频链接给下
3. 给出一个示例的 headers 和流地址

**Comment by hlmichael** [comment]
@Jhuster  第一个问题我测试下来应该是seekTo()方法造成的，是否可以优化下

**Comment by hlmichael** [comment]
http://cn-sh-ix-v-05.acgvideo.com/vg0/5/3d/5153922-1.mp4?expires=1503045600&platform=html5&ssig=m7EemZB4Cw5xzFJLp-_mZg&oi=763133930&nfa=p7waPVGao5dKHZ4kemCeBg==&dynamic=1&hfa=2074455773&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM=     问题二是这个地址，但是过一段时间这个地址会失效，你懂的   1.6的也不能播

**Comment by hlmichael** [comment]
@Jhuster  http://cn-sh-ix-v-05.acgvideo.com/vg0/5/3d/5153922-1.mp4?expires=1503045600&platform=html5&ssig=m7EemZB4Cw5xzFJLp-_mZg&oi=763133930&nfa=p7waPVGao5dKHZ4kemCeBg==&dynamic=1&hfa=2074455773&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM= 问题二是这个地址，但是过一段时间这个地址会失效，你懂的 1.6的也不能播

**Comment by hlmichael** [comment]
@Jhuster   bilibili不能播的问题好像是可以了，但是seekTo()应该是还有问题的

**Comment by Jhuster** [comment]
@hlmichael seekTo 的确有点问题，下一个版本修复

**Comment by Jhuster** [comment]
@hlmichael headers 不支持的问题，下个版本修复，多谢反馈

**Comment by Jhuster** [comment]
@hlmichael 新版已发布

**Comment by hlmichael** [comment]
http://cn-sh-ix-v-06.acgvideo.com/vg3/2/8e/9797748-1.mp4?expires=1504594500&platform=html5&ssig=wAS3UvgDyO8KQVzbP7ATGw&oi=763133923&nfa=UQ+Gd1I1PHxc26ZyufPo/w==&dynamic=1&hfa=2073913958&hfb=M2Y2ZWYwZjM2YmRiYmY5MDljYTBiOWE2ZmEwYjJmYTM=  @Jhuster   这个片子的seekTo()还是有问题，大部分片子调用seekto是没问题的

**Comment by hlmichael** [comment]
似乎是在片子已经播放之后调用seekTo()没有问题，但是在第二次进入之后，由于记住了上次的播放位置，所以我在start()之后直接seekto()，不知道这样是不是有问题

**Comment by hlmichael** [comment]
似乎是在片子已经播放之后调用seekTo()没有问题，但是在第二次进入之后，由于记住了上次的播放位置，所以我在start()之后直接seekto()，不知道这样是不是有问题  @Jhuster
