### ISSUE TITLE
当前的时间点

### ISSUE THREAD

**Issue by 651614883** [pili-engineering/PLDroidPlayer#662]
我用Handler在IMediaController的实现类中更新SeekBar，发现即使播放完成了，mMediaPlayerControl.getCurrentPosition(); 还一直在增加，这是不是一个BUG？

**Comment by 651614883** [comment]
还有一个问题，当视频播放完成后MediaPlayerControl.isPlaying()=false，然后我拖动进度条MediaPlayerControl.seekTo(seekTo);视频从调整的进度开始播放，但是MediaPlayerControl.isPlaying()=false？

**Comment by Jhuster** [comment]
@651614883 麻烦升级到最新版看看？
