### ISSUE TITLE
播放器能不能嵌入到如ListView、GridView和RecyclerView中去？

### ISSUE THREAD

**Issue by wzgl5533** [pili-engineering/PLDroidPlayer#663]
跪求

**Comment by xieshangyi** [comment]
可以啊

**Comment by wzgl5533** [comment]
@xieshangyi 
https://user-images.githubusercontent.com/11958496/29440273-d8f8f490-83f5-11e7-8807-9ee4ece60b74.png

我测试的时候报这个错，是我嵌入不对吗？
