### ISSUE TITLE
JNI error

### ISSUE THREAD

**Issue by lidanqing** [pili-engineering/PLDroidPlayer#669]
我用PLDroidPlayer拉音频流好几天，都能正常运行，今天没有做任何操作，打开就报JNI的错误，上网查找资料说是jni中的编码问题，求教，谢谢！
art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xa6
string: '{"author":"","copyright":"","description":"","keywords":"","rating":"","title":"","presetname":"Custom","creationdate":"Tue Aug 29 14:02:28 2017
","videodevice":"Integrated Webcam","framerate":15,"width":320,"height":240,"videocodecid":"avc1","videodatarate":200,"avclevel":31,"avcprofile":66,"videokey
 in call to NewStringUTF

**Comment by lidanqing** [comment]
如果是jni层面的错误，那是不是需要作者更新修正.so文件，才可以正常使用，谢谢

**Comment by Jhuster** [comment]
@lidanqing 用 demo 可以复现吗

**Comment by lidanqing** [comment]
我用您提供的demo里面的.so文件就可以跑通了，用下载的sdk/release中的.so文件就会报错

**Comment by lidanqing** [comment]
刚又替换回sdk/release中的.so文件又能用了。。。。很奇怪，不知道什么原因啊，会不会什么时候用又崩了。。。

**Comment by lidanqing** [comment]
我的代码基本都是参照作者给的demo写的，为什么会有问题呢。。。现在还是出现了这个问题，替换.so也没有用，换了几台机器也一样，麻烦作者指点下，谢谢！ 

        mAVOptions = new AVOptions();
        // the unit of timeout is ms
        mAVOptions.setInteger(AVOptions.KEY_PREPARE_TIMEOUT, 10 * 1000);
        // 默认的缓存大小，单位是 ms
        mAVOptions.setInteger(AVOptions.KEY_CACHE_BUFFER_DURATION, 300);
        // 最大的缓存大小，单位是 ms
        mAVOptions.setInteger(AVOptions.KEY_MAX_CACHE_BUFFER_DURATION, 300);
        mAVOptions.setInteger(AVOptions.KEY_MEDIACODEC,AVOptions.MEDIA_CODEC_HW_DECODE);

        AudioManager audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
        audioManager.requestAudioFocus(null, AudioManager.STREAM_MUSIC, 
       AudioManager.AUDIOFOCUS_GAIN);

        prepare();

private void prepare() {
        if (mMediaPlayer == null) {
            mMediaPlayer = new PLMediaPlayer(getApplicationContext(), mAVOptions);
            mMediaPlayer.setDebugLoggingEnabled(true);
            mMediaPlayer.setWakeMode(getApplicationContext(), PowerManager.PARTIAL_WAKE_LOCK);
        }
        try {
            mAudioPath = "rtmp://xxxxxxxxxxxxx";
            mMediaPlayer.setDataSource(mAudioPath);
            mMediaPlayer.setOnPreparedListener(new PLMediaPlayer.OnPreparedListener() {
                @Override
                public void onPrepared(PLMediaPlayer plMediaPlayer, int i) {
                    mMediaPlayer.start();
                }
            });
            mMediaPlayer.prepareAsync();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

**Comment by Jhuster** [comment]
@lidanqing 可能跟你的码流有关，部分码流会导致问题出现，你那边这样测测看，把出问题的码流发出来我们分析下。

**Comment by lidanqing** [comment]
我用PLD作为音频播放器，PC的生产端码率更改了多次，也还是相同的问题

**Comment by lidanqing** [comment]
作者指的码流是什么意思呢，谢谢

**Comment by lidanqing** [comment]
PLD播放器setDataSource的地址之前是rtmp://118.178.122.224:1935/xxx/xxxxxx/vczz，换一个地址（如rtmp://118.178.122.224:1935/xxx/xxxxxx/sha）就不崩了，再换回vczz还是会崩溃。
难道传入的地址字符串会有影响吗

**Comment by Jhuster** [comment]
@lidanqing 这 2 个地址是同一个流吗？流的内容可能不同，我从外网能访问吗

**Comment by lidanqing** [comment]
对的，地址是rtmp://118.178.122.224:1935/live/livestream/vczz和rtmp://118.178.122.224:1935/live/livestream/sha

**Comment by lidanqing** [comment]
你好，rtmp://118.178.122.224:1935/live/livestream/shaa这个地址也出现了这样的问题，您是否发现流里面问题呢，谢谢

**Comment by lidanqing** [comment]
是否是srs server端的问题呢

**Comment by lidanqing** [comment]
总体现象是这样的：
1.使用一个PC推流地址一段时间后就会报jni的错误，更换一个地址就好了。
2.报错的代码烧到其他手机中，有的能正常工作，有的还是不行。
3.server地址是rtmp://118.178.122.224:1935/live/livestream/xxx。
麻烦作者指点下，谢谢

**Comment by Jhuster** [comment]
@lidanqing 地址打不开，是否在推流？

**Comment by lidanqing** [comment]
rtmp://118.178.122.224:1935/live/livestream/vczz
这个地址正在推流，谢谢

**Comment by Jhuster** [comment]
@lidanqing 麻烦先不要停，我们正在调试，晚点通知你

**Comment by lidanqing** [comment]
好的谢谢，四十分钟后可能会断掉，我到时候再重连可以吗

**Comment by Jhuster** [comment]
@lidanqing 嗯，可以的，多谢配合

**Comment by Jhuster** [comment]
```
INFO: Metadata:
INFO:   presetname            Custom
INFO:   creationdate          Tue Aug 29 21:43:15 2017
INFO:   videodevice           Integrated Webcam
INFO:   framerate             15.00
INFO:   width                 320.00
INFO:   height                240.00
INFO:   videocodecid          VP62
INFO:   videodatarate         500.00
INFO:   videokeyframe_frequency5.00
INFO:   audiodevice           ?K? (Realtek Audio)
INFO:   audiosamplerate       22050.00
INFO:   audiochannels         2.00
INFO:   audioinputvolume      57.00
INFO:   audiocodecid          .mp3
INFO:   audiodatarate         64.00
INFO:   server                SRS/2.0.243(ZhouGuowen)
INFO:   srs_primary           SRS/2.0release
INFO:   srs_authors           winlin,wenjie.zhao
INFO:   server_version        2.0.243
```

@lidanqing 这个视频编码格式 VP62 我们不支持，能否改为 H.264 ?

**Comment by lidanqing** [comment]
我这边只推送了音频，没有推送视频，

**Comment by lidanqing** [comment]
摄像头也打开了，格式是H.264

**Comment by Jhuster** [comment]
@lidanqing 流可以关闭了哈，我们这边 dump 下来分析了

**Comment by Jhuster** [comment]
@lidanqing 

```
08-31 15:01:13.581 10865 10946 I @@@QCLOG: Info T89C11920 CNDKPlayer L584 HandleEvent  metadata = {"author":"","copyright":"","description":"","keywords":"","rating":"","title":"","presetname":"Medium Bandwidth (300 Kbps) - H.264","creationdate":"Thu Aug 31 11:45:12 2017
08-31 15:01:13.581 10865 10946 I @@@QCLOG: ","videodevice":"HD WebCam","framerate":20,"width":320,"height":240,"videocodecid":"avc1","videodatarate":200,"avclevel":21,"avcprofile":77,"videokeyframe_frequency":5,"audiodevice":"?K? (Realtek High Definition Audio)","audiosamplerate":22050,"audiochannels":1,"audioinputvolume":75,"audiocodecid":".mp3","audiodatarate":48,"server":"SRS/2.0.243(ZhouGuowen)","srs_primary":"SRS/2.0release","srs_authors":"winlin,wenjie.zhao","server_version":"2.0.243"},   Size = 627
```

你的流，metadata 里面可能有特殊字符，导致这边解析失败，`"audiodevice":"?K?`

**Comment by lidanqing** [comment]
谢谢，那有什么好的解决办法吗，我这边PC不推流，安卓端刚打开也直接报错。我尝试过用其他接收流的开源代码，都可以正常运行。

**Comment by Jhuster** [comment]
@lidanqing 你那边 能改推流的 medata 代码吗

**Comment by lidanqing** [comment]
这个改不了，用的现成PC软件，换一个PC推流软件试试可以吗

**Comment by Jhuster** [comment]
@lidanqing 可以，换个 OBS 吧

**Comment by lidanqing** [comment]
换成OBS就可以了，用Adobe和大牛的都不行，应该是把 “麦克风（Realtek Audio）” 解析成了 “?K? (Realtek Audio)“

**Comment by Jhuster** [comment]
@lidanqing 新版版本 2.0.1 已发布，针对这个问题，做了一些兼容性保护，可以试试看

**Comment by lidanqing** [comment]
好的谢谢，我使用Adobe和大牛的推流，现在不会崩溃了，可是没有声音，也没有类似I/QPlayer: onInfo: 10005, 812的log信息。用OBS可以
