### ISSUE TITLE
关于x86

### ISSUE THREAD

**Issue by typ0520** [pili-engineering/PLDroidPlayer#67]
你好，我们的项目中不需要支持x86，如果不加x86的so包会导致crash，能帮忙做下处理下吗，没有x86的包别crash

**Comment by Jhuster** [comment]
有 crash log 吗？我这里测试了一下，没有 crash，你是在 demo 里面删除 x86 就会 crash 还是别的情况？

**Comment by jpxiong** [comment]
把 `jniLibs/x86` 目录删掉即可

**Comment by weizongwei5** [comment]
没有x86的so文件 碰到x86的手机 会自动 找到arm的so文件

**Comment by weizongwei5** [comment]
唯一的区别就是 因为没有使用x86的动态库文件 在x86的cpu上性能发挥的应该不是很好
