### ISSUE TITLE
plvideotextureview 进入后台再进入前台 画面不动

### ISSUE THREAD

**Issue by susussa** [pili-engineering/PLDroidPlayer#670]
plvideotextureview 进入后台再进入前台 继续播放 画面不动 有声音

**Comment by zshbleaker** [comment]
请问有修改过 demo 的代码吗？这边没能复现

**Comment by xieshangyi** [comment]
我也是遇到这个问题 估计是jni最新有点问题，旧的没问题

**Comment by xieshangyi** [comment]
我也是遇到这个问题 估计是jni最新有点问题，旧版本没有这个问题

**Comment by Jhuster** [comment]
是否用的 demo 做的测试，还是有别的逻辑修改
