### ISSUE TITLE
创建很多对象的时候会出现/libOpenSLES: Too many objects 异常.

### ISSUE THREAD

**Issue by TestSmirk** [pili-engineering/PLDroidPlayer#674]
2.0.1  Android6.0 LE Max2 x820   

如图. 手机上只显示视频第一帧. 无法继续播放.onPrepared 回调会继续走.start也成功,就是只显示第一帧. 
![BaiduShurufa_2017-9-1_19-13-22.png](https://i.loli.net/2017/09/01/59a940f93722c.png)

**Comment by jasonhe88** [comment]
同样碰到此问题，请问解决没有啊？
