### ISSUE TITLE
使用PLMediaPlayer，如何切换视频资源

### ISSUE THREAD

**Issue by hningoba** [pili-engineering/PLDroidPlayer#681]
我是利用PLMediaPlayer做单例的播放器，跨页面实现零缓冲续播。之前利用1.4版本，切换视频资源前先PLMediaPlayer.reset()，再设置新的Surface。
但是，我升级到2.1，还是用这种方法就不行了。请问下面两种场景我应该怎么处理呢？
1）跨页面（Surface不同），播放同一视频；
2）同一页面（Surface相同），播放不同视频；

**Comment by zshbleaker** [comment]
1): stop、setSurface、prepareAsync、收到 onReady 后 start
2): pause(可选)、setDataSource、prepareAsync、收到 onReady 后 start

**Comment by hningoba** [comment]
1）跨页面（Surface不同），播放同一视频：如果prepareAsync，会重头播放的，我们希望做到续播；
2）按照你的提示，我在七牛官方demo的PLMediaPlayerActivity，切换视频资源，有声音没画面。

**Comment by zshbleaker** [comment]
1): 业务端记录下停止前的时间戳，然后 seekTo 即可
2): 视频地址可以提供一下吗？我们调查一下

**Comment by hningoba** [comment]
两个页面切换做到无缝续播，就是希望上个页面pause，新的页面setSurface、start。如果是prepareAysnc + seekTo就做不到无缝续播了。跟具体视频无关，下面两个链接可以拿去测试下：
http://v.xiaohongshu.com/luo_n9CfYGAFCkHeGXZf_S3QIVkX?sign=1f8a050f5778039196f8f4626443ed38&t=59b252cf
http://v.xiaohongshu.com/lhnEDkz-HLI4qaobQHgfxj6nQCde?sign=32bf1d9e36d60d878f5a66d73804481d&t=59b252cf

**Comment by zshbleaker** [comment]
目前 pause、setSurface、start 这样会有什么问题吗？

**Comment by hningoba** [comment]
在postDelay中延迟触发setSurface、start才有效

**Comment by hningoba** [comment]
demo中setSurface、start是可以的，但是在我的项目中需要postDelay内setSurface、start才可以，不清楚原因
