### ISSUE TITLE
视频播放状态控制

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#684]
我尝试了下，没办法在没有控件的情况下，控制视频的暂停、播放以及停止播放；要实现的具体功能是，客户端接受到服务端的暂停指令后，客户端就要暂停播放。

**Comment by zshbleaker** [comment]
请问没有控件是指？

**Comment by panyingdaoz** [comment]
就是按钮控件。

**Comment by zshbleaker** [comment]
不一定需要按钮点击事件，在 UI 线程里直接执行播放器的 pause 方法就可以

**Comment by panyingdaoz** [comment]
因为指令的接收只能在一个新的类里面，所以就没办法在当前Activity里面直接Pause，我开启子线程但是不行，关于在一个非Activity类控制Activity类的UI怎么去实现呢？

**Comment by zshbleaker** [comment]
办法很多啊，比如写一个 MediaHelper 类，里面都是静态方法，把 PLMediaPlayer 的对象作为方法的参数传进去就好

**Comment by panyingdaoz** [comment]
新人，有没有相关文章推荐一下
