### ISSUE TITLE
2.0.1版本mp4格式在线点播视频，断网后播放完缓存的视频进度后直接回调onCompletion，并且进度条进度还一直走

### ISSUE THREAD

**Issue by guodong89758** [pili-engineering/PLDroidPlayer#685]
点播完全体现不出来网络重连的过程，希望断网后保持在网络异常的状态，重新联网后可以继续播放

**Comment by zshbleaker** [comment]
目前断网后 SDK 会不断回调 `ERROR_IO_ERROR`，内部不断触发重连机制，有网之后应该会重新连接。请问你遇到的情况是？

**Comment by zshbleaker** [comment]
请问能提供具体的播放地址吗？

**Comment by guodong89758** [comment]
http://video3.nextjoy.com/qrj/qrj03.mp4

**Comment by zshbleaker** [comment]
该问题已经修复，将会包含在下个 release 中，感谢反馈
