### ISSUE TITLE
setVideoPath导致ANR，以及当前界面切换播放源或直播源的问题

### ISSUE THREAD

**Issue by bifan-wei** [pili-engineering/PLDroidPlayer#689]
1.运行官方demo，PLVideoTextureActivity，选择直播，点击播放，每次退出都会ANR，在我的两个华为手机都出现了，可能这两个手机性能比较一般，一两年前的，在我的小米6没有出现。

2.请教一下，如何在一个界面上切换播放文件或者直播流源，我是VideoView.setVideoPath(vedioPath)，然后VideoView.start()，由于1问题，会导致ANR，如何才是正确的切换方式。

**Comment by zshbleaker** [comment]
第一个问题，请问可以提供一下完整的 log 吗，这个问题我们一直没有好的复现途径，这会对我们非常有帮助

第二个问题，我们会在下一个版本进行内部修复，目前可以认为 setVideoPath 然后 start 就好

**Comment by bifan-wei** [comment]
不好意思，写错了，是mVideoView.stopPlayback();会导致ANR，就是每次退出当前页面播放中或者加载中时，退出页面，onDestroy回调：
@Override
    protected void onDestroy() {
        super.onDestroy();
        mVideoView.stopPlayback();
    }

(我测试官网的demo时，进入播放页，正在缓存，因为的我是内网网络，所以一直缓冲，我点击返回键退出，就出现这个bug了，另外我播放视频文件，想切换视频源，通过以下代码切换：
mVideoView.stopPlayback();
 mVideoView.setVideoPath(vedioPath);
  mVideoView.start();

就发现就是mVideoView.setVideoPath(vedioPath);导致ANR，它应该不是异步的，所以堵塞了主线程。)

这个bug太严重，以前的版本不会出现的，请问现在应该怎么避免出现ANR比较好。

**Comment by zshbleaker** [comment]
是的，请问方便提供 stopPlayback 导致的 ANR 的 log 吗？

目前的版本，建议在 setVideoPath 之后收到 OnPreparedListener 回调后再去 start，否则可能会有问题。下个版本中我们会进行修复，让上层的使用方式更加自由

**Comment by bifan-wei** [comment]
surfaceChanged -- format=4 w=720 h=1280
09-13 20:26:01.639 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: surfaceRedrawNeeded
09-13 20:26:01.639 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: finishedDrawing
09-13 20:26:01.653 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: Changes: creating=false format=false size=false visible=false left=false top=false mUpdateWindowNeeded=true mReportDrawNeeded=true redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=true
09-13 20:26:01.653 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: Cur surface: Surface(name=null, identity=1515)
09-13 20:26:01.656 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: New surface: Surface(name=null, identity=1515), vis=true, frame=Rect(0, 0 - 720, 1280)
09-13 20:26:01.656 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: surfaceRedrawNeeded
09-13 20:26:01.656 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: finishedDrawing
09-13 20:26:01.693 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: onNetworkChanged !
09-13 20:26:01.699 18147-18147/com.pili.pldroid.playerdemo E/WifiManager: mWifiServiceMessenger == null
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L417 Network QOS Type is WIFI
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L429 Network QOS ISP Name is -
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L441 Network QOS Wifi Name is "305"
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L448 Network QOS Signal DB is -40
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L454 Network QOS Signal Level is 0
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: network info: WIFI, null, "305", -40, 0
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CAnalysisMng L886 [ANL]Recv network change event
09-13 20:26:01.701 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKPlayer L406 Network QOS Changed!
09-13 20:26:02.681 18147-18147/com.pili.pldroid.playerdemo I/SurfaceTextureClient: [STC::queueBuffer] (this:0x6082ff08) fps:37.95, dur:1001.20, max:390.68, min:4.16
09-13 20:26:03.196 18147-18147/com.pili.pldroid.playerdemo I/View: Key down dispatch to com.pili.pldroid.player.widget.PLVideoView{419de2c8 VFE..... .F...... 0,0-720,1280 #7f0d0067 app:id/VideoView}, event = KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=158, metaState=0, flags=0x48, repeatCount=0, eventTime=60013257, downTime=60013257, deviceId=2, source=0x101 }
09-13 20:26:03.432 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: Changes: creating=false format=false size=false visible=true left=false top=false mUpdateWindowNeeded=false mReportDrawNeeded=false redrawNeeded=false forceSizeChanged=false mVisible=true mRequestedVisible=false
09-13 20:26:03.433 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: Cur surface: Surface(name=null, identity=1515)
09-13 20:26:03.436 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: New surface: Surface(name=null, identity=-1), vis=false, frame=Rect(0, 0 - 720, 1280)
09-13 20:26:03.436 18147-18147/com.pili.pldroid.playerdemo I/SurfaceView: visibleChanged -- surfaceDestroyed
09-13 20:26:03.437 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: setDisplay +
09-13 20:26:03.437 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C CNDKVideoRnd L72 the surface is 0x0
09-13 20:26:03.437 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: setDisplay -
09-13 20:26:03.776 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: stop +
09-13 20:26:03.776 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: stop -
09-13 20:26:03.776 18147-18147/com.pili.pldroid.playerdemo I/QPlayer: release +
09-13 20:26:03.778 18147-18147/com.pili.pldroid.playerdemo W/@@@QCLOG: Warn T4002E18C COMBoxMng L256 CheckOpenStatus failed!
09-13 20:26:03.778 18147-18147/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T4002E18C COMBoxMng L204 Try to close failed for the status was error!
09-13 20:26:08.640 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]close[47864]
09-13 20:26:08.640 18147-18172/com.pili.pldroid.playerdemo W/System.err: java.net.SocketTimeoutException
09-13 20:26:08.641 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:604)
09-13 20:26:08.641 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:560)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:161)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at java.net.PlainDatagramSocketImpl.receive(PlainDatagramSocketImpl.java:169)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at java.net.DatagramSocket.receive(DatagramSocket.java:249)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.qiniu.android.dns.local.Resolver.udpCommunicate(Resolver.java:58)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.qiniu.android.dns.local.Resolver.resolve(Resolver.java:41)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.qiniu.android.dns.DnsManager.queryInternal(DnsManager.java:195)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.qiniu.android.dns.DnsManager.query(DnsManager.java:140)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.qiniu.android.dns.DnsManager.query(DnsManager.java:125)
09-13 20:26:08.642 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.pili.pldroid.player.network.a.c(DNSCacheManager.java:257)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.pili.pldroid.player.network.a.a(DNSCacheManager.java:245)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.pili.pldroid.player.network.a.c(DNSCacheManager.java:32)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at com.pili.pldroid.player.network.a$2.handleMessage(DNSCacheManager.java:164)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at android.os.Looper.loop(Looper.java:194)
09-13 20:26:08.643 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:60)
09-13 20:26:08.644 18147-18172/com.pili.pldroid.playerdemo W/System.err: Caused by: libcore.io.ErrnoException: recvfrom failed: EAGAIN (Try again)
09-13 20:26:08.645 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.Posix.recvfromBytes(Native Method)
09-13 20:26:08.645 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.Posix.recvfrom(Posix.java:136)
09-13 20:26:08.645 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
09-13 20:26:08.645 18147-18172/com.pili.pldroid.playerdemo W/System.err:     at libcore.io.IoBridge.recvfrom(IoBridge.java:557)
09-13 20:26:08.645 18147-18172/com.pili.pldroid.playerdemo W/System.err: 	... 15 more
09-13 20:26:08.646 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]connect[/114.114.114.114:53] tm:90
09-13 20:26:08.646 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]port[35581]
09-13 20:26:08.646 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]close[35581]
09-13 20:26:08.647 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]connect[/114.114.114.114:53] tm:90
09-13 20:26:08.647 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]port[51701]
09-13 20:26:08.647 18147-18172/com.pili.pldroid.playerdemo I/System.out: [CDS]close[51701]
09-13 20:26:13.864 18147-18159/com.pili.pldroid.playerdemo I/AndroidRuntime: timezone is Asia/Shanghai
09-13 20:26:13.865 18147-18159/com.pili.pldroid.playerdemo I/AndroidRuntime: persist.sys.timezone is Asia/Shanghai
09-13 20:26:13.865 18147-18159/com.pili.pldroid.playerdemo I/ViewRootImpl: ANR Key Analyze: No Key event currently.
09-13 20:26:13.868 18147-18159/com.pili.pldroid.playerdemo I/ViewRootImpl: ANR Key Analyze: Previeous Event null,finish at 1970-01-01 08:00:00.000
09-13 20:26:13.868 18147-18159/com.pili.pldroid.playerdemo I/ViewRootImpl: ANR Motion Analyze: No motion event currently.
09-13 20:26:13.869 18147-18159/com.pili.pldroid.playerdemo I/ViewRootImpl: ANR Motion Analyze: Previeous Event MotionEvent { action=ACTION_UP, id[0]=0, x[0]=492.0, y[0]=1211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=60011316, downTime=60011219, deviceId=2, source=0x1002 },finish at 2017-09-13 20:26:01.249
09-13 20:26:13.869 18147-18159/com.pili.pldroid.playerdemo I/ViewRootImpl: The current processed event of VRI is none

**Comment by zshbleaker** [comment]
请问还有更完整的 log 吗，这些信息有点少

**Comment by bifan-wei** [comment]
我大概猜到那个点击返回出现ANR的bug的问题所在，我连接内网，所以点击播放官网demo那个地址时一直在访问获取数据中，这时我点击返回退出，就会很容易出现ANR了，我试了用外网测试，不会出现，应该就是退出后还卡在那里访问数据，不过获取数据不是应该本身异步的么，还是说需要我调用时自己开线程？。

不过切换播放源出现ANR的问题，这个不是很懂：
 mVideoView.stopPlayback();    
 mVideoVieHolder.mVideoView.setVideoPath(vedioPath);
 mVideoView.start();  

我的视频源是可以访问的，播放挺流畅的，播放过程中调用上面的代码重新播放同一个视频源地址vedioPath，就出现阻塞了。我现在是开一个线程执行上面的代码，外部添加loading显示加载中。后面可以播放，只是得等待5到15秒左右才能进行播放，内网播放，网速应该是没问题的，

**Comment by zshbleaker** [comment]
目前内部打开视频流的实现的确是异步的，但是销毁播放器的过程是同步的，所以在网络特别差的时候会导致等待网络（主要是 DNS）导致阻塞，导致 ANR，这点下个版本会改进。目前我们建议提前使用 PLNetworkManager.setDnsCacheService 去提供 DNS 缓存，这个方法可以像 demo 那样放在 MainActivity 里，程序一启动就执行。

切换视频的问题，目前我们强烈建议不要在 setVideoPath 之后紧接着 start，而是在收到 onPrepared 回调后再 start；以及如果是在播放时设置新的地址，事实上无需调用 start，播放器会自动切换画面。

非常感谢提供的信息。

**Comment by 01Sr** [comment]
suspend all histogram:	Sum: 8.404ms 99% C.I. 4us-509.439us Avg: 35.610us Max: 1197us
DALVIK THREADS (53):
"Signal Catcher" daemon prio=5 tid=3 Runnable
  | group="system" sCount=0 dsCount=0 flags=0 obj=0x13200000 self=0xeb244200
  | sysTid=28734 nice=0 cgrp=default sched=0/0 handle=0xe4f0b970
  | state=R schedstat=( 493540849 9071355 196 ) utm=33 stm=16 core=7 HZ=100
  | stack=0xe4e10000-0xe4e12000 stackSize=1010KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 002d9bef  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+134)
  native: #01 pc 0036ee1b  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+210)
  native: #02 pc 0036b5d3  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
  native: #03 pc 003841f1  /system/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+624)
  native: #04 pc 0037e56f  /system/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+314)
  native: #05 pc 0037dc67  /system/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+758)
  native: #06 pc 0037d89f  /system/lib/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+614)
  native: #07 pc 00357b69  /system/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+120)
  native: #08 pc 00360b89  /system/lib/libart.so (art::SignalCatcher::HandleSigQuit()+1040)
  native: #09 pc 0035fd1b  /system/lib/libart.so (art::SignalCatcher::Run(void*)+246)
  native: #10 pc 00072161  /system/lib/libc.so (__pthread_start(void*)+22)
  native: #11 pc 0001e005  /system/lib/libc.so (__start_thread+24)
  (no managed stack frames)

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x74f77838 self=0xeb248000
  | sysTid=28727 nice=-10 cgrp=default sched=0/0 handle=0xef14a494
  | state=S schedstat=( 77943988610 8839588523 69751 ) utm=6906 stm=888 core=2 HZ=100
  | stack=0xff4e2000-0xff4e4000 stackSize=8MB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/28727/stack)
  native: #00 pc 00019eac  /system/lib/libc.so (syscall+28)
  native: #01 pc 0001d37b  /system/lib/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+90)
  native: #02 pc 00073499  /system/lib/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+436)
  native: #03 pc 000452e5  /data/app/edu.www.qsxt-uvsmHSnhk66CqV2MsZU_0Q==/lib/arm/libQPlayer.so (???)
  native: #04 pc 00080df5  /data/app/edu.www.qsxt-uvsmHSnhk66CqV2MsZU_0Q==/lib/arm/libQPlayer.so (???)
  at com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeStop(Native method)
  at com.qiniu.qplayer.mediaEngine.MediaPlayer.e(MediaPlayer.java:473)
  at com.pili.pldroid.player.PLMediaPlayer.stop(PLMediaPlayer.java:267)
  at com.pili.pldroid.player.widget.a.b(PLBaseVideoView.java:686)
  at com.pili.pldroid.player.widget.a.stopPlayback(PLBaseVideoView.java:273)
  at com.pili.pldroid.player.widget.PLVideoTextureView.stopPlayback(PLVideoTextureView.java:21)
  at elearning.qsxt.qiniu.VideoPlayerView.C(VideoPlayerView.java:251)
  at elearning.qsxt.qiniu.PlaybackView.j(PlaybackView.java:395)
  at elearning.qsxt.qiniu.view.VideoDisplayView.f(VideoDisplayView.java:428)
  at elearning.qsxt.discover.activity.PlayLiveActivity.G(PlayLiveActivity.java:422)
  at elearning.qsxt.discover.activity.PlayLiveActivity.F(PlayLiveActivity.java:418)
  at elearning.qsxt.discover.activity.PlayLiveActivity.a(PlayLiveActivity.java:342)
  at elearning.qsxt.qiniu.a.a.a(PlayerEventCollection.java:75)
  at elearning.qsxt.qiniu.view.PlayerTopView.onViewClick(PlayerTopView.java:198)
  at elearning.qsxt.qiniu.view.PlayerTopView_ViewBinding$1.doClick(PlayerTopView_ViewBinding.java:48)
  at butterknife.a.a.onClick(DebouncingOnClickListener.java:22)
  at android.view.View.performClick(View.java:6612)
  at android.view.View.performClickInternal(View.java:6581)
  at android.view.View.access$3100(View.java:785)
  at android.view.View$PerformClick.run(View.java:25904)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:280)
  at android.app.ActivityThread.main(ActivityThread.java:6710)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
