### ISSUE TITLE
播放直播流时crash奔溃

### ISSUE THREAD

**Issue by CastleFeng** [pili-engineering/PLDroidPlayer#690]
这是崩溃log
1 #00 pc 00000000000372b4 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
--
2 #01 pc 0000000000037614 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
3 #02 pc 00000000000369fc /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
4 #03 pc 0000000000036818 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
5 #04 pc 000000000003638c /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
6 #05 pc 0000000000034c68 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
7 #06 pc 000000000005244c /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
8 #07 pc 0000000000055964 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
9 #08 pc 0000000000059690 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
10 #09 pc 0000000000058928 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
11 #10 pc 000000000001c1b8 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
12 #11 pc 000000000001dff4 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
13 #12 pc 000000000001d9b8 /data/app/com.taobaichi.shenyexiaoguan.audience-2/lib/arm64/libQPlayer.so [arm64-v8a::896f05438d6c4632580248b5311e30a7]
14 #13 pc 00000000000688d4 /system/lib64/libc.so (_ZL15__pthread_startPv+196) [arm64-v8a::6c6c04b4223ca14a6942eeff93db1698]
15 #14 pc 000000000001db00 /system/lib64/libc.so (__start_thread+16) [arm64-v8a::6c6c04b4223ca14a6942eeff93db1698]

**Comment by zshbleaker** [comment]
请问 demo 可以复现吗？以及播放地址可以提供一下吗？

**Comment by CastleFeng** [comment]
可以复现的、视频流是用的http://live.9158.com/Fans/GetHotLive这个接口里的flv地址

**Comment by zshbleaker** [comment]
好的，我们这边调查一下，感谢反馈

**Comment by zshbleaker** [comment]
该问题已经修复，将会在下个 release 中包含， 感谢反馈
