### ISSUE TITLE
切换网络后调用PLVideoTextureView.pause方法无效，仍会继续播放

### ISSUE THREAD

**Issue by lh911002** [pili-engineering/PLDroidPlayer#692]
```java
public void pause() {
        if(this.e() && this.l.isPlaying()) {
            this.l.pause();
        }

        this.i = PlayerState.PAUSED;
    }
```
看了一下是`this.e() && this.l.isPlaying()`没有走进去
@zshbleaker

**Comment by zshbleaker** [comment]
请问一下在 pause 之前，调用 getPlayerState，返回的结果是？

**Comment by lh911002** [comment]
返回BUFFERING,用的是2.0.1版本SDK @zshbleaker

**Comment by zshbleaker** [comment]
请问返回 BUFFERING 的时候视频还在播放吗？

**Comment by lh911002** [comment]
视频中间会卡一下继续播放，不能确定调用pause时候是不是在卡着，只卡了一很短的一瞬间，然后继续播放，pause走不进去

**Comment by lh911002** [comment]
我这边可以稳定复现，场景就是监听WIFI切到4G,然后立刻调用pause方法

**Comment by zshbleaker** [comment]
嗯，目前的策略是 PlayerState 为 BUFFERING 的话，pause 实际上不会走到；如果是 PLAYING 的话才会暂停。毕竟一个正在缓冲的视频本身就是停着的。如果一定需要在缓冲结束之后暂停的话，可以在 OnInfoListener 里收到 MEDIA_INFO_BUFFERING_END 消息后暂停

**Comment by lh911002** [comment]
好的，那我知道了，谢谢 @zshbleaker
