### ISSUE TITLE
新的2.01版播放一些.m3u8格式的源，高频率自动重连！

### ISSUE THREAD

**Issue by anoleye** [pili-engineering/PLDroidPlayer#693]
新的2.01版播放一些.m3u8格式的源，有时网络不稳定，会不停的高频率的自动重连，我看log信息全是404错误，但是播放器会不停的自动重连，快的时候一秒钟能自动重连十多次以上，这频率也太高了，Toast错误提示的时候，就crash奔溃了。我记得1.60版以前的错误监听，有404回调接口的，现在新版的好几个接口没了。有时一碰到网络问题就是不停的高频率自动重连，当然这种情况不是经常发生，就是播放一些不稳定的源会这样，我觉得这个自动重连的频率可以控制一下，太高频率了，有时会crash奔溃。
[log.txt](https://github.com/pili-engineering/PLDroidPlayer/files/1309743/log.txt)

**Comment by zshbleaker** [comment]
感谢反馈，这个问题我们正在着手修复了
