### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by AIlll** [pili-engineering/PLDroidPlayer#696]
用的是PLVideoTextureView，播放本地视频：
1、setVideoPath之后就算开始准备视频了是吗？
2、OnPreparedListener在什么情况下会回调，我只在第一次进来的时候设置过setVideoPath，当我播放完再次调用PLVideoTextureView.start的时候，OnPreparedListener又回调了一次
3、没有提供截图的接口吗，播放视频的时候如何截图

**Comment by zshbleaker** [comment]
1、setVideoPath 内部会执行 prepare 
2、目前的机制是，onSurfaceCreated 与 setVideoPath 时都会 prepare，前者主要是为了 onResume 时可以直接调用 start
3、目前没有截图的接口，不过可以通过 OnVideoFrameListener 回调获取帧数据，自行生成图片

**Comment by AIlll** [comment]
也就是说，设置过setVideoPath ，只要没被销毁，onResume就会再次prepare是吗。
PLVideoTextureView没看到有释放播放器的接口，在不使用的时候是不需要release吗

**Comment by zshbleaker** [comment]
是的，onResume 时会再次 prepare，参考 demo；stopPlayback 就是 release.

**Comment by AIlll** [comment]
@zshbleaker  设置为全屏铺满模式，有些画面被挤到屏幕外去了，这个有办法改善吗，同一个视频，我用过别的播放器，全屏铺满是完整的画面。

**Comment by zshbleaker** [comment]
如果 view 的长宽比与视频的长宽比不一致，根据 PAVED 的定义，显示的内容应该是有裁剪的。如果不希望有裁剪，可以使用 APECT_RATIO_FIT_PARENT

**Comment by AIlll** [comment]
@zshbleaker 不支持哪些视频格式呢，我播放avi格式的好像有问题

**Comment by zshbleaker** [comment]
视频文件的话，目前支持 MP4(h264 + aac/mp3)

**Comment by AIlll** [comment]
@zshbleaker 请问下如何获取视频第一帧画面呢，设置为封面

**Comment by zshbleaker** [comment]
请问是要在播放前就获取第一帧画面还是？如果是在播放后获取，可以设置 OnVideoFrameListener

**Comment by AIlll** [comment]
@zshbleaker 播放前获取第一帧画面呢

**Comment by zshbleaker** [comment]
播放之前，播放器都没有视频的数据的，客户端肯定无法生成画面，建议在服务端生成视频的封面图，让客户端获取。七牛云有这个服务，可以看下😁 https://developer.qiniu.com/dora/manual/1313/video-frame-thumbnails-vframe

**Comment by AIlll** [comment]
@zshbleaker  OnVideoFrameListener只回调一次是吗，字节数组的数据是什么，如何获取当前帧数据。
有的视频播放OnVideoFrameListener不回调

**Comment by zshbleaker** [comment]
有新的视频帧时都会回调，目前有 YUV420P、JPEG 和 SEI 三种，format 参数里有说明。具体可以参考文档

**Comment by AIlll** [comment]
@zshbleaker  我是播放本地MP4文件，不回调OnVideoFrameListener，是不是就无法截图了

**Comment by zshbleaker** [comment]
本地文件也会有回调的，以及生成封面这种功能理论上来说不应该由播放器去做，应该会有专门的库处理这件事。

**Comment by AIlll** [comment]
@zshbleaker 不，不是为了封面，我只是需要截图。
播放本地文件好多个视频都没有回调OnVideoFrameListener

**Comment by zshbleaker** [comment]
本地文件也有的，检查下 AVOptions.KEY_VIDEO_DATA_CALLBACK 有没有设置

**Comment by AIlll** [comment]
@zshbleaker 确实是忘了设置这个，但是拿到的data，用BitmapFactory.decodeByteArray一直是为null，视频数据不是空的

**Comment by zshbleaker** [comment]
数据很有可能是 YUV420 的，BitmapFactory 要求 RGBA，可以搜索一下怎么从 YUV420 数据生成 bitmap
