### ISSUE TITLE
2.0.1版本，播放一些m3u8的流无法播放，只能获取第一帧的画面

### ISSUE THREAD

**Issue by AaronWolfX** [pili-engineering/PLDroidPlayer#699]

**Comment by AaronWolfX** [comment]
拖动进度条后，进度开始走，但是画面是隔几秒走一次

**Comment by AaronWolfX** [comment]
这是异常流的地址：http://live.banmabang.cn/cam_h3_tewz_a.m3u8
http://test.live.banmabang.cn/test_cam_365_h3_test_short_20170913.m3u8

**Comment by zshbleaker** [comment]
问题已确认，正在调查，感谢反馈

**Comment by AaronWolfX** [comment]
现在这个异常的流我们使用另一个播放器来播放，这就导致我们同时使用两个播放器，请问一下你们大概什么时候能解决这个问题？

**Comment by zshbleaker** [comment]
目前已经解决了，新版本预计会在这两天发布

**Comment by AaronWolfX** [comment]
好的，谢谢

**Comment by thearyong** [comment]
@zshbleaker 遇到同样的问题，弱弱请求下，可以提前发布不，
或者私发一个解决的版本，邮箱：thearyong@gmail.com
万分感谢~~~

ps:项目比较急，领导坐旁边催😭😭😭

**Comment by AaronWolfX** [comment]
2.0.2版本测试过了，有时候能播放，有时候不能播放

**Comment by zshbleaker** [comment]
呃，同样的流，有时可以，有时不可以？不可以播放时的 log 与播放地址可以提供一下吗

**Comment by AaronWolfX** [comment]
播放地址：http://live.banmabang.cn/cam_h3_cvme_test_2017091218.m3u8

**Comment by AaronWolfX** [comment]
`09-26 17:34:28.313 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.347 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 545460849459
09-26 17:34:28.430 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:28.473 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 311299
09-26 17:34:28.488 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:28.505 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:28.543 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:28.544 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.625 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:28.691 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:28.782 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 398991
09-26 17:34:28.814 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:28.829 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547338603712
09-26 17:34:28.877 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:28.877 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.966 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:29.000 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 333942
09-26 17:34:29.019 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:29.024 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:29.079 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 4611
09-26 17:34:29.123 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:29.123 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:29.190 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547336228416
09-26 17:34:29.220 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 408438
09-26 17:34:29.233 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:29.242 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:29.309 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520`

**Comment by AaronWolfX** [comment]
_09-26 17:34:28.313 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.347 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 545460849459
09-26 17:34:28.430 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:28.473 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 311299
09-26 17:34:28.488 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:28.505 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:28.543 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:28.544 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.625 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:28.691 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:28.782 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 398991
09-26 17:34:28.814 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:28.829 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547338603712
09-26 17:34:28.877 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:28.877 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:28.966 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:29.000 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 333942
09-26 17:34:29.019 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:29.024 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 0
09-26 17:34:29.079 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 4611
09-26 17:34:29.123 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 200, extra = 0
09-26 17:34:29.123 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: Connected !
09-26 17:34:29.190 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547336228416
09-26 17:34:29.220 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20001, extra = 408438
09-26 17:34:29.233 8004-8004/com.pili.pldroid.playerdemo I/PLVideoViewActivity: OnInfo, what = 20002, extra = 25
09-26 17:34:29.242 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520
09-26 17:34:29.309 8004-16459/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 5, 640 x 360, 2, 547169935520_

**Comment by AaronWolfX** [comment]
你要看什么的log，这是VideoViewActivity的log

**Comment by zshbleaker** [comment]
这个地址我这边试了很多次都是可以播放的，请问可以提供一下不能播时的 log 吗？grep 一下 QPlayer 关键字

**Comment by AaronWolfX** [comment]
09-28 11:15:56.729 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
09-28 11:15:56.740 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
09-28 11:15:56.745 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
09-28 11:15:56.756 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
09-28 11:15:56.772 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000021, 0, 0
09-28 11:15:56.772 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000022, 0, 0
09-28 11:15:56.777 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000001, 0, 0
09-28 11:15:56.778 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000004, 0, 0
09-28 11:15:56.778 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000005, 0, 0
09-28 11:15:56.783 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000003, 0, 0
09-28 11:15:56.783 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 200, 0
09-28 11:15:56.825 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11020001, 0, 0
09-28 11:15:56.825 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000010, 0, 0
09-28 11:15:56.825 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000011, 0, 0
09-28 11:15:56.825 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 0, 0
09-28 11:15:56.831 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 0, 0
09-28 11:15:56.846 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
09-28 11:15:56.852 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 18000006, 410318, 0
09-28 11:15:56.852 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 20001, 410318
09-28 11:15:56.852 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 18000004, 25, 0
09-28 11:15:56.853 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 20002, 25
09-28 11:15:56.858 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
09-28 11:15:56.866 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
09-28 11:15:56.871 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
09-28 11:15:56.877 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
09-28 11:15:56.882 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 18000006, 340318, 0
09-28 11:15:56.882 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 20001, 340318
09-28 11:15:56.882 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 18000004, 25, 0
09-28 11:15:56.883 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 20002, 25
09-28 11:15:56.898 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000021, 0, 0
09-28 11:15:56.898 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000022, 0, 0
09-28 11:15:57.161 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 15200004, 143, 0
09-28 11:15:57.161 19825-22291/com.pili.pldroid.playerdemo I/QPlayer: onInfo: 10004, 143

**Comment by AaronWolfX** [comment]
进去画面出现后马上退出来，然后再进去，我选择点播，自动
