### ISSUE TITLE
PLMediaPlayer在多次切换holder的时候不会成功，并且卡住，严重时还会崩溃

### ISSUE THREAD

**Issue by ifrac** [pili-engineering/PLDroidPlayer#700]
plMediaPlayers2.setDisplay(mSurfaceView7.getHolder());
           plMediaPlayers1.setDisplay(mSurfaceView1.getHolder());
执行一次是可以的但是当再次调用
           plMediaPlayers1.setDisplay(mSurfaceView7.getHolder());
           plMediaPlayers2.setDisplay(mSurfaceView1.getHolder());
就无法切换，两次执行时间很短，只有几秒钟时间，使用pause()方法和start()方法都不起作用，怎么操作才能实现多次快速切换播放器？

**Comment by zshbleaker** [comment]
给 SurfaceHolder 加一个 Callback，在 onSurfaceCreated 的回调里操作播放器，参考 https://github.com/pili-engineering/PLDroidPlayer/issues/694
