### ISSUE TITLE
2.0.2 作为recyclerview item

### ISSUE THREAD

**Issue by Vixb1122** [pili-engineering/PLDroidPlayer#706]
回收复用，画面无法正常渲染，只能听到声音

**Comment by FreeLeo** [comment]
我也是相同问题，出现：
09-29 05:29:17.992 21363-21664/com.zepra.android E/Surface: dequeueBuffer failed (No such device)
09-29 05:29:17.992 21363-21664/com.zepra.android E/Surface: Surface::unlockAndPost failed, no locked buffer
09-29 05:29:18.025 21363-21664/com.zepra.android E/BufferQueueProducer: [SurfaceTexture-0-21363-5] dequeueBuffer: BufferQueue has been abandoned
09-29 05:29:18.025 21363-21664/com.zepra.android E/Surface: dequeueBuffer failed (No such device)
09-29 05:29:18.025 21363-21664/com.zepra.android E/Surface: Surface::unlockAndPost failed, no locked buffer
09-29 05:29:18.058 21363-21664/com.zepra.android E/BufferQueueProducer: [SurfaceTexture-0-21363-5] dequeueBuffer: BufferQueue has been abandoned
09-29 05:29:18.058 21363-21664/com.zepra.android E/Surface: dequeueBuffer failed (No such device)
09-29 05:29:18.059 21363-21664/com.zepra.android E/Surface: Surface::unlockAndPost failed, no locked buffer
09-29 05:29:18.091 21363-21664/com.zepra.android E/BufferQueueProducer: [SurfaceTexture-0-21363-5] dequeueBuffer: BufferQueue has been abandoned

**Comment by zshbleaker** [comment]
请问在没刷新 view 时，也就是第一个视频，可以正常播放吗？

**Comment by FreeLeo** [comment]
@zshbleaker 可以播放，问题还没解决，如果方便，我们邮箱沟通下lizhen@brotsoft.com
