### ISSUE TITLE
m3u8视频进度拖动后demo卡死

### ISSUE THREAD

**Issue by AaronWolfX** [pili-engineering/PLDroidPlayer#711]
这个视频拖动后一直loading，demo直接卡住，http://live.banmabang.cn/recordings/z1.banmalive.cam_h3_xbnm/1505988000_1506009600.m3u8

**Comment by zshbleaker** [comment]
这个流的后半部分是无法播放的，播放器一直拿不到数据，ffmpeg 和 Safari 也无法播放。我们会修复这个情况下 demo 的可响应问题，感谢反馈
