### ISSUE TITLE
切换视频播放路径时发生崩溃

### ISSUE THREAD

**Issue by sys1211** [pili-engineering/PLDroidPlayer#712]
一个本地的视频列表与播放控件同屏，刚进去时没有问题正常播放，但是当点击别的视频切换视频路径时程序会崩溃
![image](https://user-images.githubusercontent.com/26588391/31335281-6ebabc14-ad24-11e7-8c41-a540f7d6cf8c.png)

**Comment by zshbleaker** [comment]
感谢反馈，下个版本会彻底修复切换播放地址的各种问题
