### ISSUE TITLE
2.0.2退出视频播放页时部分手机报错

### ISSUE THREAD

**Issue by guodong89758** [pili-engineering/PLDroidPlayer#713]
10-10 16:08:19.559 12169-12169/com.nextjoy.game A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12169 (om.nextjoy.game)
10-10 16:08:19.567 463-463/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-10 16:08:19.567 463-463/? A/DEBUG: Build fingerprint: 'htc/htccn_chs/htc_mectl:6.0.1/MMB29M/796600.3:user/release-keys'
10-10 16:08:19.567 463-463/? A/DEBUG: Revision: '0'
10-10 16:08:19.567 463-463/? A/DEBUG: ABI: 'arm'
10-10 16:08:19.568 463-463/? A/DEBUG: pid: 12169, tid: 12169, name: om.nextjoy.game  >>> com.nextjoy.game <<<
10-10 16:08:19.568 463-463/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
10-10 16:08:19.596 463-463/? A/DEBUG:     r0 b843a298  r1 befc4f68  r2 b843a298  r3 00000002
10-10 16:08:19.596 463-463/? A/DEBUG:     r4 00000000  r5 00000000  r6 12eef300  r7 131b9720
10-10 16:08:19.597 463-463/? A/DEBUG:     r8 131b9720  r9 b7e40588  sl 00000000  fp 12eef300
10-10 16:08:19.597 463-463/? A/DEBUG:     ip 96d554df  sp befc4f68  lr 96d554f7  pc 00000000  cpsr 600f0010
10-10 16:08:19.627 463-463/? A/DEBUG: backtrace:
10-10 16:08:19.628 463-463/? A/DEBUG:     #00 pc 00000000  <unknown>
10-10 16:08:19.628 463-463/? A/DEBUG:     #01 pc 000384f5  /data/app/com.nextjoy.game-1/lib/arm/libQPlayer.so
10-10 16:08:19.628 463-463/? A/DEBUG:     #02 pc 01a42fa9  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.qiniu.qplayer.mediaEngine.MediaPlayer.nativeGetPos(long)+92)
10-10 16:08:19.628 463-463/? A/DEBUG:     #03 pc 01a47c03  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.qiniu.qplayer.mediaEngine.MediaPlayer.getCurrentPosition()+78)
10-10 16:08:19.629 463-463/? A/DEBUG:     #04 pc 01a0b267  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.pili.pldroid.player.PLMediaPlayer.getCurrentPosition()+58)
10-10 16:08:19.629 463-463/? A/DEBUG:     #05 pc 01a15e4f  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.pili.pldroid.player.widget.a.getCurrentPosition()+114)
10-10 16:08:19.629 463-463/? A/DEBUG:     #06 pc 01a1aeb1  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.pili.pldroid.player.widget.PLVideoView.getCurrentPosition()+60)
10-10 16:08:19.629 463-463/? A/DEBUG:     #07 pc 018a95d1  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.nextjoy.game.ui.widget.PlayerController.setProgress()+188)
10-10 16:08:19.630 463-463/? A/DEBUG:     #08 pc 018a8549  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (long com.nextjoy.game.ui.widget.PlayerController.access$200(com.nextjoy.game.ui.widget.PlayerController)+60)
10-10 16:08:19.630 463-463/? A/DEBUG:     #09 pc 018a7a5f  /data/app/com.nextjoy.game-1/oat/arm/base.odex (offset 0xe99000) (void com.nextjoy.game.ui.widget.PlayerController$2.handleMessage(android.os.Message)+202)
10-10 16:08:19.630 463-463/? A/DEBUG:     #10 pc 02a42e45  /system/framework/arm/boot.oat (offset 0x228c000)

**Comment by smartown** [comment]
我这里也包这个错，我之前用的是2.0.1版本，换了jar包和so，退出播放界面就崩溃了！

**Comment by DaDaHuaHua** [comment]
我也遇到了，但是我尝试在他们的Demo测试没发现问题，是不是我们的使用姿势有问题？

**Comment by zshbleaker** [comment]
这个问题的确存在，将会在下次更新里彻底修复，感谢反馈

**Comment by Huskyyy** [comment]
版本：2.0.3版本，PLMediaPlayer，TextureView
手机：mx4
问题类似楼主的情况，log 如下：
11-13 12:07:10.798 3363-3363/com.xxx.debug A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x60 in tid 3363 (id_xxx.debug)
11-13 12:07:12.869 721-907/system_process E/NativeCrashListener: Exception dealing with report
                                                                 android.system.ErrnoException: read failed: EAGAIN (Try again)
                                                                     at libcore.io.Posix.readBytes(Native Method)
                                                                     at libcore.io.Posix.read(Posix.java:165)
                                                                     at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
                                                                     at android.system.Os.read(Os.java:350)
                                                                     at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                                     at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
11-13 12:07:21.088 3726-3726/? E/AEE/AED: timed out waiting for tid=3368 to stop
11-13 12:07:21.215 3726-3726/? E/AEE/AED: timed out waiting for tid=3369 to stop
11-13 12:07:21.373 3726-3726/? E/AEE/AED: timed out waiting for tid=3370 to stop
11-13 12:07:21.519 3726-3726/? E/AEE/AED: timed out waiting for tid=3372 to stop
11-13 12:07:21.672 3726-3726/? E/AEE/AED: timed out waiting for tid=3373 to stop
11-13 12:07:21.830 3726-3726/? E/AEE/AED: timed out waiting for tid=3375 to stop
11-13 12:07:21.981 3726-3726/? E/AEE/AED: timed out waiting for tid=3376 to stop
11-13 12:07:22.099 3726-3726/? E/AEE/AED: timed out waiting for tid=3377 to stop
11-13 12:07:22.229 3726-3726/? E/AEE/AED: timed out waiting for tid=3378 to stop
11-13 12:07:22.318 3726-3726/? E/AEE/AED: timed out waiting for tid=3379 to stop
11-13 12:07:22.421 3726-3726/? E/AEE/AED: timed out waiting for tid=3380 to stop
11-13 12:07:22.504 3726-3726/? E/AEE/AED: timed out waiting for tid=3381 to stop
11-13 12:07:22.597 3726-3726/? E/AEE/AED: timed out waiting for tid=3382 to stop
11-13 12:07:22.687 3726-3726/? E/AEE/AED: timed out waiting for tid=3383 to stop
11-13 12:07:22.779 3726-3726/? E/AEE/AED: timed out waiting for tid=3384 to stop
11-13 12:07:22.871 3726-3726/? E/AEE/AED: timed out waiting for tid=3385 to stop
11-13 12:07:22.889 3726-3726/? E/AEE/AED: timed out waiting for tid=3390 to stop
11-13 12:07:22.979 3726-3726/? E/AEE/AED: timed out waiting for tid=3398 to stop
11-13 12:07:23.078 3726-3726/? E/AEE/AED: timed out waiting for tid=3404 to stop
11-13 12:07:23.186 3726-3726/? E/AEE/AED: timed out waiting for tid=3406 to stop
11-13 12:07:23.316 3726-3726/? E/AEE/AED: timed out waiting for tid=3407 to stop
11-13 12:07:23.413 3726-3726/? E/AEE/AED: timed out waiting for tid=3408 to stop
11-13 12:07:23.527 3726-3726/? E/AEE/AED: timed out waiting for tid=3419 to stop
11-13 12:07:23.610 3726-3726/? E/AEE/AED: timed out waiting for tid=3420 to stop
11-13 12:07:23.696 3726-3726/? E/AEE/AED: timed out waiting for tid=3421 to stop
11-13 12:07:23.786 3726-3726/? E/AEE/AED: timed out waiting for tid=3422 to stop
11-13 12:07:23.877 3726-3726/? E/AEE/AED: timed out waiting for tid=3546 to stop

**Comment by Huskyyy** [comment]
抱歉，应该是我释放资源的方式不正确。
通过对比Demo中的代码，发现在将 PLMediaPlayer release 之后，将 PLMediaPlayer 的引用置空，上述报错现象不再出现。
