### ISSUE TITLE
AVOptions.KEY_LIVE_STREAMING 没有了，现在用什么设置？

### ISSUE THREAD

**Issue by EdenXY** [pili-engineering/PLDroidPlayer#714]
我之前用1.4的时候就发现我的视频流播放不了，必须 AVOptions.KEY_LIVE_STREAMING 设为0才能正常播放。现在最新版本发现这个参数没有了，我的视频流也没法正常播放，请问现在能通过什么参数设置吗？

**Comment by zshbleaker** [comment]
请问可以提供一下视频流的链接吗？我们调查一下。

新版本里这个参数设置与否已经没有实际区别了，故移除。
