### ISSUE TITLE
v2.0.2 重大bug:有些视频无法循环播放

### ISSUE THREAD

**Issue by seekting** [pili-engineering/PLDroidPlayer#715]
我发现有些视频源无法循环播放：
https://scontent-lax3-1.cdninstagram.com/t50.2886-16/22252289_1516226345137809_7936140350781915136_n.mp4

步骤：
开启循环，开启离线播放
播放https://scontent-lax3-1.cdninstagram.com/t50.2886-16/22252289_1516226345137809_7936140350781915136_n.mp4

发现第二次播放结束后，不再循环播放。。。

**Comment by zshbleaker** [comment]
问题已定位，正在修复，感谢反馈
