### ISSUE TITLE
 mVideoView.setVideoPath卡顿

### ISSUE THREAD

**Issue by bifan-wei** [pili-engineering/PLDroidPlayer#716]
新版本播放过程中使用 mVideoView.setVideoPath切换播放源还是会出现卡顿，请问一下怎么样才是正确的切换方式，demo中重连流程是在mOnErrorListener监听时sdk自动执行的

**Comment by zshbleaker** [comment]
下个版本将会彻底解决 setVideoPath 引发的问题
