### ISSUE TITLE
PLVideoTextureView videoView.setCoverView(View view)无效闪黑问题

### ISSUE THREAD

**Issue by Freedoms1988** [pili-engineering/PLDroidPlayer#717]
PLVideoTextureView videoView.setCoverView(View view)设置完成，SDK默认情况下，在视频加载完成播放前到正式开始播放，会闪黑一瞬间，从SDK和文档中无法查到关于CoverView的移除逻辑，故只好自己实现coverView的手动控制

**Comment by zshbleaker** [comment]
目前 SDK 没有提供移除 CoverView 的方法，请问 demo 上也会出现闪黑的现象吗？我们这边好像没能复现
