### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MurtadhaS** [pili-engineering/PLDroidPlayer#718]
I used version 2.0.2 and had a memory leak in the player.
I think you should check it out.

**Comment by zshbleaker** [comment]
This issue has been fixed in the development branch and will be contained in the next release. Thanks for your feedback.

**Comment by MurtadhaS** [comment]
where is the development branch ? I can't find any.

**Comment by zshbleaker** [comment]
It’s on my laptop and not released yet :P

**Comment by MurtadhaS** [comment]
Can you please push it here ?

**Comment by zshbleaker** [comment]
This would be included in the next release, maybe in next week.

**Comment by lostsakya** [comment]
Same problem on 2.0.4, it seems that bug is not fixed. @zshbleaker

**Comment by MurtadhaS** [comment]
Switched to ijkplayer. it is better.
but a little tricky to build.

**Comment by zshbleaker** [comment]
This has been fixed in 2.0.5.
