### ISSUE TITLE
播放在线mp4视频异常，ERROR_CODE_OPEN_FAILED，ERROR_CODE_IO_ERROR

### ISSUE THREAD

**Issue by tjt852** [pili-engineering/PLDroidPlayer#719]
10-22 19:39:52.323 19587-19587/com.xueqiu.video.mm I/QPlayer: init: 2.0.2, QPlayer-v1.1.0.46
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: init done: 547260092928
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions Hardware Decode: false
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_PREPARE_TIMEOUT: 10000
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_CACHE_BUFFER_DURATION: 500
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_MAX_CACHE_BUFFER_DURATION: 4000
10-22 19:39:52.327 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions prefer format: 2
10-22 19:39:52.329 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions [v_callback, a_callback, v_render, a_render]: false, false, false, false
10-22 19:39:52.331 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions Hardware Decode: false
10-22 19:39:52.331 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_PREPARE_TIMEOUT: 10000
10-22 19:39:52.331 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_CACHE_BUFFER_DURATION: 500
10-22 19:39:52.331 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions KEY_MAX_CACHE_BUFFER_DURATION: 4000
10-22 19:39:52.331 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions prefer format: 2
10-22 19:39:52.332 19587-19587/com.xueqiu.video.mm I/QPlayer: setAVOptions [v_callback, a_callback, v_render, a_render]: false, false, false, false
10-22 19:39:52.333 19587-19587/com.xueqiu.video.mm I/QPlayer: setLooping false
10-22 19:39:52.333 19587-19587/com.xueqiu.video.mm I/QPlayer: setDataSource: http://k.syasn.com/rs/rs61.mp4
10-22 19:39:52.333 19587-19587/com.xueqiu.video.mm I/QPlayer: setSurface +
10-22 19:39:52.339 19587-19587/com.xueqiu.video.mm I/QPlayer: setSurface -
10-22 19:39:52.339 19587-19587/com.xueqiu.video.mm I/QPlayer: prepareAsync
10-22 19:39:52.339 19587-19587/com.xueqiu.video.mm I/QPlayer: nativeOpen: 0
10-22 19:39:52.340 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 1600000a, 0, 0
10-22 19:39:52.341 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_PLAY_OPEN_START          00 : 00 : 00 : 000           0             0     
10-22 19:39:52.341 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000001, 0, 0
10-22 19:39:52.341 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_CONNECT_START       00 : 00 : 00 : 002           0             0    http://k.syasn.com/rs/rs61.mp4 
10-22 19:39:52.342 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000004, 0, 0
10-22 19:39:52.342 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_DNS_START           00 : 00 : 00 : 002           0             0    k.syasn.com 
10-22 19:39:52.357 19587-19587/com.xueqiu.video.mm D/BaseObserver: onComplete
10-22 19:39:52.358 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000006, 0, 0
10-22 19:39:52.358 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_DNS_GET_IPADDR      00 : 00 : 00 : 015           0             0    120.198.231.101 
10-22 19:39:52.392 19587-19587/com.xueqiu.video.mm I/QPlayer: onNetworkChanged !
10-22 19:39:52.396 19587-19587/com.xueqiu.video.mm I/QPlayer: network info: WIFI, null, "tjt852🔫-5G", -34, 0
10-22 19:39:52.406 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000003, 0, 0
10-22 19:39:52.407 19587-19979/com.xueqiu.video.mm I/QPlayer: onInfo: 200, 0
10-22 19:39:52.407 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_CONNECT_SUCESS      00 : 00 : 00 : 062           0             0     
10-22 19:39:52.424 19587-19587/com.xueqiu.video.mm I/System.out: onInfo:200___0
10-22 19:39:52.449 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11020001, 0, 0
10-22 19:39:52.449 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     Unknow ID 0X11020001            00 : 00 : 00 : 109           0             0     
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000010, 0, 0
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_GET_HEADDATA        00 : 00 : 00 : 109           0             0    302 
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000021, 0, 0
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_DISCONNECT_START    00 : 00 : 00 : 109           0             0     
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000022, 0, 0
10-22 19:39:52.450 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_DISCONNECT_DONE     00 : 00 : 00 : 109           0             0     
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000012, 0, 0
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG     QC_MSG_HTTP_REDIRECT            00 : 00 : 00 : 109           0             0    http://z9.syasn.com/rs/rs61.mp4?end=180 
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000001, 0, 0
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_CONNECT_START       00 : 00 : 00 : 109           0             0    http://z9.syasn.com/rs/rs61.mp4?end=180 
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000004, 0, 0
10-22 19:39:52.451 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_DNS_START           00 : 00 : 00 : 109           0             0    z9.syasn.com 
10-22 19:39:52.463 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000006, 0, 0
10-22 19:39:52.463 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_DNS_GET_IPADDR      00 : 00 : 00 : 118           0             0    221.229.204.74 
10-22 19:39:52.521 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000003, 0, 0
10-22 19:39:52.521 19587-19979/com.xueqiu.video.mm I/QPlayer: onInfo: 200, 0
10-22 19:39:52.522 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_CONNECT_SUCESS      00 : 00 : 00 : 177           0             0     
10-22 19:39:52.525 19587-19587/com.xueqiu.video.mm I/System.out: onInfo:200___0
10-22 19:39:53.027 19587-19978/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 16000002, 0, 0
10-22 19:39:53.027 19587-19978/com.xueqiu.video.mm E/QPlayer: onError: -2
10-22 19:39:53.028 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000021, 0, 0
10-22 19:39:53.028 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_DISCONNECT_START    00 : 00 : 00 : 686           0             0     
10-22 19:39:53.029 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000022, 0, 0
10-22 19:39:53.029 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_DISCONNECT_DONE     00 : 00 : 00 : 686           0             0     
10-22 19:39:53.029 19587-19979/com.xueqiu.video.mm I/QPlayer: postEventFromNative: 11000002, -2128609279, 0
10-22 19:39:53.029 19587-19979/com.xueqiu.video.mm E/QPlayer: onError: -3
10-22 19:39:53.029 19587-19979/com.xueqiu.video.mm I/@@@QCLOG: QCMSG    1QC_MSG_HTTP_CONNECT_FAILED      00 : 00 : 00 : 686  -2128609279            0     
10-22 19:39:53.060 19587-19587/com.xueqiu.video.mm D/CrashReport: >>> com.xueqiu.video.mm.view.activity.VideoActivity onPaused <<<
10-22 19:39:53.084 19587-19587/com.xueqiu.video.mm I/IgnoreTouchEvent: ignoreTouchEvent onWindowAttached
10-22 19:39:53.116 19587-19587/com.xueqiu.video.mm D/CrashReport: >>> com.xueqiu.video.mm.view.activity.MainActivity onResumed <<<
10-22 19:39:53.177 19587-19587/com.xueqiu.video.mm D/CrashReport: >>> com.xueqiu.video.mm.view.activity.VideoActivity onDestroyed <<<
10-22 19:39:53.180 19587-19587/com.xueqiu.video.mm I/QPlayer: stop +
10-22 19:39:53.180 19587-19587/com.xueqiu.video.mm I/QPlayer: stop -
10-22 19:39:53.180 19587-19587/com.xueqiu.video.mm I/QPlayer: release +
10-22 19:39:53.206 19587-19587/com.xueqiu.video.mm I/QPlayer: release -

**Comment by mioochoo** [comment]
播放在线MP4或者下载下来的MP4 都无法正常播放 有解决方法吗？

**Comment by zshbleaker** [comment]
是下载的  http://k.syasn.com/rs/rs61.mp4 <http://k.syasn.com/rs/rs61.mp4> 到手机，然后播放本地视频吗？这边试了下，似乎是可以的。

视频本身可以播放的话，提示 IO_ERROR 意味着到目标服务器的网络可能不是很通畅。最近风声紧，这种视频可能有点问题。。。

**Comment by mioochoo** [comment]
为什么我下载的不可以阿

**Comment by zshbleaker** [comment]
确定下载的没问题吗？我下载的 md5 是 778d5baf85a2cde5e9732b35b6d98a84

**Comment by mioochoo** [comment]
我加你QQ说可以吗？

**Comment by zshbleaker** [comment]
建议就在这里沟通，如果是一个通用的问题，也方便后来的人能搜索到解决方案。如果涉及到较为私密的信息，我们可以通过邮件讨论，我的工作邮件地址是 zhusihan@qiniu.com <mailto:zhusihan@qiniu.com>

**Comment by tjt852** [comment]
@zshbleaker 我不是下载下载播放，是在线播放，我用你们的1.3.1版本，而且现在播放还很正常，就能播放还有用火狐浏览器也行，，用2.0.2就不行了，也不知道具体原因，能解答下吗？？

**Comment by tjt852** [comment]
@mioochoo 这位朋友也播放不了吗？
