### ISSUE TITLE
2.0.2 播放问题

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#720]
为什么现在2.0.2无法切换播放路径，我停止后，无法再播放了，或者我直接切换路径也会直接崩溃，请问什么原因呢？

**Comment by panyingdaoz** [comment]
还有一个问题，就是我多次切换播放，切换的是相同的路径，但是会崩溃，log如下：

10-26 16:27:06.037 24291-27687/com.kingbrid.advertise.advertise E/@@@QCLOG: Err  TA192DF80 COMBoxMng L346 Open Source failed!
10-26 16:27:06.037 24291-27687/com.kingbrid.advertise.advertise E/QPlayer: onError: -2
10-26 16:27:06.047 24291-24291/com.kingbrid.advertise.advertise E/VideoViewActivity: [ (VideoViewActivity.java:503)#onError ] 发生错误, 错误代码 = -2
10-26 16:27:06.047 24291-27688/com.kingbrid.advertise.advertise E/QPlayer: onError: -3
10-26 16:27:06.097 24291-24291/com.kingbrid.advertise.advertise E/VideoViewActivity: [ (VideoViewActivity.java:503)#onError ] 发生错误, 错误代码 = -3

**Comment by zshbleaker** [comment]
这个问题将会在过几天发布的更新中彻底修复，感谢反馈

**Comment by panyingdaoz** [comment]
还有就是有时播放会卡住无法继续播放，怎么下个版本能解决吗？

**Comment by zshbleaker** [comment]
会解决的

**Comment by panyingdaoz** [comment]
好的
