### ISSUE TITLE
调用stopPlayback（）引起崩溃

### ISSUE THREAD

**Issue by dazhiyu** [pili-engineering/PLDroidPlayer#721]
我想是在页面结束视频播放，调用stopPlayback（）；
结果引起崩溃，2.0.2版本；
在官方demo中，把stopPlayback（）放到onPause（）方法中，退出也会引起崩溃；
还是说让视频停止释放内存有别的办法？急，急，急

**Comment by panyingdaoz** [comment]
你是调用后就崩溃了吗，我是调用没问题，但是我再次开始播放时就会崩溃。你的log是什么？

**Comment by dazhiyu** [comment]
com.bhtc.huajuan I/QPlayer: setDisplay +
com.bhtc.huajuan A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32415 (om.bhtc.huajuan)
就这两行

**Comment by zshbleaker** [comment]
近期将会更新一个版本，彻底修复这个问题，感谢反馈

**Comment by dazhiyu** [comment]
@zshbleaker 能先给我一下吗？头头催着上线呢正。。。。2964381294@qq.com

**Comment by zshbleaker** [comment]
@dazhiyu 我们不建议把灰度版本带到线上

**Comment by kexuejin** [comment]
我也遇到这个问题了，android 8.0 上的，调用stopPlayback会奔溃，同样的代码，其他手机就没问题
