### ISSUE TITLE
播放异常 ERROR_CODE_OPEN_FAILED

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#723]
当每次遇到“ERROR_CODE_OPEN_FAILED”异常的时候就会导致 APP崩溃，我不想他崩溃，我应该怎么做呢？

**Comment by zshbleaker** [comment]
Demo 里收到 OPEN FAILED 之后会执行 finish 操作，可以根据具体需求选择是否执行 finish
