### ISSUE TITLE
关于PLVideoView硬解失败之后,继续使用播放器进行硬解该怎么处理?

### ISSUE THREAD

**Issue by yanxiandroid** [pili-engineering/PLDroidPlayer#724]
本来硬解是可以播放视频的,但是由于有其他的程序使用视频解码芯片处理视频导致本播放器硬解失败,所以需要在OnError中进行初始化播放器继续硬解播放视频,但是播放失败了.求解决办法.

**Comment by zshbleaker** [comment]
硬解失败后应该会自动 fallback 到软解，请问这种情况下设置软解可以正常播放吗？
