### ISSUE TITLE
g711a 音频格式的视频无法播放也不报错

### ISSUE THREAD

**Issue by lanyan520** [pili-engineering/PLDroidPlayer#725]
播放视频，音频格式是g711a 然后播放不出来声音

**Comment by zshbleaker** [comment]
目前还不支持这个音频格式，只支持 aac 与 mp3。支持更多的格式将会显著增大 SDK 体积，所以短期内没有支持更多合适的计划

**Comment by lanyan520** [comment]
ijkplayer支持g711a么
