### ISSUE TITLE
播放rtmp流直播失败

### ISSUE THREAD

**Issue by lyy603** [pili-engineering/PLDroidPlayer#727]
使用播放器播放香港卫视的 RTMP 直播流：rtmp://live.hkstv.hk.lxdns.com/live/hks是没问题的，但是播放我们自己的RTMP 直播流链接却失败了。
提示：
11-02 16:09:49.277 15006-22572/cn.yaheen.online W/@@@QCLOG: Warn T75780440 CQCSource L123 Open source failed! err = 0X80000001
11-02 16:09:49.277 15006-22572/cn.yaheen.online E/@@@QCLOG: Err  T75780440 COMBoxMng L349 Open Source failed!
11-02 16:09:49.277 15006-22572/cn.yaheen.online E/QPlayer: onError: -2
11-02 16:09:49.337 15006-22572/cn.yaheen.online W/@@@QCLOG: Warn T75780440 CQCSource L123 Open source failed! err = 0X80000001
11-02 16:09:49.337 15006-22572/cn.yaheen.online E/@@@QCLOG: Err  T75780440 COMBoxMng L349 Open Source failed!
11-02 16:09:49.337 15006-22572/cn.yaheen.online E/QPlayer: onError: -2
请问该怎么解决？

**Comment by zshbleaker** [comment]
请问可以提供一下你们直播流的地址吗？我们这边排查一下

**Comment by lyy603** [comment]
我们用的是本地链接，这是我们推流端的设置：
C:\Program Files (x86)\loles\assets\ffmpeg-20170620-ae6f6d4-win32-shared\bin\ffmpeg.exe"" -f dshow -i video=screen-capture-recorder:audio=virtual-audio-capturer -vf scale=900:-1 -vcodec libx264 -r 15 -acodec aac -vbr 3 -ac 2 -ar 44100 -ab 1900 -pix_fmt yuv420p -tune zerolatency -preset ultrafast -f flv rtmp://172.16.100.33/red5Demo/screen_YY

**Comment by knightzc** [comment]
我也是这个问题，请问解决了吗，我以前用的1.3.2版本可以播放

**Comment by lyy603** [comment]
没有，换成阿里云服务器好像又可以了
