### ISSUE TITLE
播放视频seekto OnCompletionListener不调用问题

### ISSUE THREAD

**Issue by Freedoms1988** [pili-engineering/PLDroidPlayer#728]
在尝试使用SDK播放功能时，设置了OnCompletionListener接口回调，并在其中按业务需求放入逻辑，但有部分视频在调用过seekto，播放到视频最大长度后OnCompletionListener永远不调用（非必现，大几率出现），导致写在其中的业务代码无法执行，查阅文档，只有一个设置过looper=true才会不调用的说明，是否还有其他未知逻辑未在文档中说明？
另外同样代码在另一些视频seekto后、正常播放完成后都会准确调用OnCompletionListener。

**Comment by zshbleaker** [comment]
请问可以提供一下出问题的视频地址吗？我们排查一下

> 在 2017年11月2日，17:53，Freedoms <notifications@github.com> 写道：
> 
> 在尝试使用SDK播放功能时，设置了OnCompletionListener接口回调，并在其中按业务需求放入逻辑，但有部分视频在调用过seekto，播放到视频最大长度后OnCompletionListener永远不调用（非必现，大几率出现），导致写在其中的业务代码无法执行，查阅文档，只有一个设置过looper=true才会不调用的说明，是否还有其他未知逻辑未在文档中说明？

**Comment by Freedoms1988** [comment]
http://video.mb.moko.cc/2017-10-16/d4908bbd-97ab-443b-8742-f446498e2695.mp4/0306e508-9d4b-4578-9874-35b82f33fa14.m3u8  辛苦看一下是什么问题
