### ISSUE TITLE
看到你们基于ijkplayer, 是否该声明开源协议呢

### ISSUE THREAD

**Issue by smarxpan** [pili-engineering/PLDroidPlayer#73]
ijkplayer使用了LGPL开源协议

> LGPL是GPL的一个为主要为类库使用设计的开源协议。和GPL要求任何使用/修改/衍生之GPL类库的的软件必须采用GPL协议不同。LGPL允许商业软件通过类库引用(link)方式使用LGPL类库而不需要开源商业软件的代码。这使得采用LGPL协议的开源代码可以被商业软件作为类库引用并发布和销售。

> 但是如果修改LGPL协议的代码或者衍生，则所有修改的代码，涉及修改部分的额外代码和衍生的代码都必须采用LGPL协议。因此LGPL协议的开源代码很适合作为第三方类库被商业软件引用，但不适合希望以LGPL协议代码为基础，通过修改和衍生的方式做二次开发的商业软件采用。

> GPL/LGPL都保障原作者的知识产权，避免有人利用开源代码复制并开发类似的产品

LGPL协议具有传染性, 因此你们的项目涉及到ijkplayer的地方也必须使用LGPL协议. 

这个协议对商业并不友好, 作为三方库使用可以闭源. 当修改源码作为商业项目使用时, 修改的部分必须也使用LGPL协议进行开源.

PS: 我并非专业人士, 如果有错误欢迎指出. 希望注意到一点: Open source does not mean free.

**Comment by jpxiong** [comment]
你好，感谢提醒。我们之前在 PLDroidPlayer 特性里面提到基于 ijk ，但是没有明确说明基于 ijk 修改 repo 地址（https://github.com/jpxiong/ijkplayer），并且所有修改都是开源的。另外我们会完善声明。
