### ISSUE TITLE
2.0.3弱网时销毁播放器依然会阻塞主线程

### ISSUE THREAD

**Issue by Dovar66** [pili-engineering/PLDroidPlayer#736]
2.0.3弱网时销毁播放器依然会阻塞主线程。但如果把销毁的动作放到子线程的话，当快速销毁多个播放器时会崩溃

**Comment by zshbleaker** [comment]
请问销毁播放器的操作是在收到 onPrepared 消息之前还是之后？之前的话已经修复了，将会在下个版本内包含

**Comment by Dovar66** [comment]
只要是弱网，之前之后都会有问题，1.x的版本就存在了，开启DNS优化也没多大改善 @zshbleaker

**Comment by zshbleaker** [comment]
2.0.5 应该彻底修复了这个问题，可以更新试下
