### ISSUE TITLE
无法播放AVI格式,Toast提示未知错误

### ISSUE THREAD

**Issue by TengLeeIT** [pili-engineering/PLDroidPlayer#74]
这是错误Log

04-29 10:30:55.323 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Option ijkinject-opaque not found.
04-29 10:30:55.327 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 1.5 is not allocated
04-29 10:30:55.328 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.13 is not allocated
04-29 10:30:55.328 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.0 is not allocated
04-29 10:30:55.328 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.9 is not allocated
04-29 10:30:55.329 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.9 is not allocated
04-29 10:30:55.330 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.15 is not allocated
04-29 10:30:55.330 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.10 is not allocated
04-29 10:30:55.330 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.1 is not allocated
04-29 10:30:55.331 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.1 is not allocated
04-29 10:30:55.331 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 1.15 is not allocated
04-29 10:30:55.345 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Inconsistent channel configuration.
04-29 10:30:55.345 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: get_buffer() failed
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.5 is not allocated
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.1 is not allocated
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 1.9 is not allocated
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.9 is not allocated
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.15 is not allocated
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Number of scalefactor bands in group (47) exceeds limit (41).
04-29 10:30:55.346 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 3.0 is not allocated
04-29 10:30:55.351 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Inconsistent channel configuration.
04-29 10:30:55.351 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: get_buffer() failed
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: Dependent coupling is not supported together with LTP
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 1.4 is not allocated
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.15 is not allocated
04-29 10:30:55.352 2285-5207/com.pili.pldroid.playerdemo E/IJKMEDIA: channel element 2.15 is not allocated

**Comment by longbai** [comment]
因为使用者比较少，我们目前不支持 avi 格式的文件。
