### ISSUE TITLE
PLMediaPlayer，如何切换视频资源

### ISSUE THREAD

**Issue by jo-liu** [pili-engineering/PLDroidPlayer#742]
按照#681所说
我这边进行
         mMediaPlayer.pause();
         mMediaPlayer.setDataSource(mVideoPath);
         mMediaPlayer.prepareAsync();
之后直接调用surfaceDestroyed onDestroy 退出。请问如何进行视频流切换？

**Comment by zshbleaker** [comment]
setDataSource 然后 prepareAsync 即可，PLMediaPlayer 内部不会销毁 surface
