### ISSUE TITLE
MediaPlayer init problem

### ISSUE THREAD

**Issue by xglinux** [pili-engineering/PLDroidPlayer#743]
on android 4.1.2，Failure found，Log : com.pili.pldroid.playerdemo E/PLVideoViewActivity: Error happened, errorCode = -2。

If class com.qiniu.qplayer.mediaEngine.MediaPlayer,method init() change to 
{
......
String str = paramContext.getFilesDir().getParent() + "/lib";
str  = str +"/";  //add this line,the problem will be resolved.，So, please check your code.here...
.....
}

**Comment by zshbleaker** [comment]
This has been fixed and will be included in the next release. Thanks for reporting.

**Comment by xglinux** [comment]
make a mistake
