### ISSUE TITLE
PLDroidPlayer 2.0.3 has this problem on Android 4.1.0

### ISSUE THREAD

**Issue by xglinux** [pili-engineering/PLDroidPlayer#744]
PLDroidPlayer 2.0.3 could not play rtmp live stream on Android 4.1.0.
but modify:
class: com.qiniu.qplayer.mediaEngine.MediaPlayer,method: init()
...
String s = (new StringBuilder()).append(context.getFilesDir().getParent()).append("/lib").toString();
....

to 
String s = (new StringBuilder()).append(context.getFilesDir().getParent()).append("/lib").toString();
s += "/";

the problem will be resolved.
why?

Could you Modify the sdk to resolve it?

**Comment by zshbleaker** [comment]
This is a known issue and has been fixed in the development branch. The new version will be released within several days.
