### ISSUE TITLE
一个PLVideoTextureView频繁切换播放url几十次会导致libQPlayer.so 文件报错 以下是bugly上的出错信息

### ISSUE THREAD

**Issue by cx324** [pili-engineering/PLDroidPlayer#746]
#00 pc 00041b48 /system/lib/libc.so (tgkill+12) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
2 #01 pc 00040e99 /system/lib/libc.so (pthread_kill+32) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
3 #02 pc 0001c7fb /system/lib/libc.so (raise+10) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
4 #03 pc 000199ad /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
5 #04 pc 00017560 /system/lib/libc.so (abort+4) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
6 #05 pc 00042023 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
7 #06 pc 0004202d /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
8 #07 pc 00042085 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
9 #08 pc 000417f7 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
10 #09 pc 00041315 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
11 #10 pc 000413d9 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
12 #11 pc 00041d47 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so (_Znwj+78) [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
13 #12 pc 00041d8f /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so (_Znaj+2) [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
14 #13 pc 0001f82f /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
15 #14 pc 00020765 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
16 #15 pc 00020de7 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
17 #16 pc 00020ee9 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
18 #17 pc 000217b1 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
19 #18 pc 0001f12d /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
20 #19 pc 0001cd31 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
21 #20 pc 0002dd63 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
22 #21 pc 0002ff89 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
23 #22 pc 00031fd9 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
24 #23 pc 000330c9 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
25 #24 pc 0000dbfb /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
26 #25 pc 00031303 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
27 #26 pc 0000eea3 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
28 #27 pc 0000eb55 /data/app/com.vliao.vchat-2/lib/arm/libQPlayer.so [armeabi-v7a::16f4ad189c2f5202b03e43f925faf2ab]
29 #28 pc 0004079b /system/lib/libc.so (_ZL15__pthread_startPv+30) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]
30 #29 pc 0001a031 /system/lib/libc.so (__start_thread+6) [armeabi-v7a::bdde0af092610b6c08cded5bf956b757]

**Comment by zshbleaker** [comment]
请问是在 arm64 的手机上出现的吗？可以试下把 arm64 的 so 文件加入后还会不会复现

**Comment by cx324** [comment]
是的，是arm64-v8a架构的cpu，arm下的so文件我加入了，所有so文件我都加进去了，仍然会出现这个问题

**Comment by cx324** [comment]
@zshbleaker 是的，是arm64-v8a架构的cpu，arm下的so文件我加入了，所有so文件我都加进去了，仍然会出现这个问题

**Comment by cx324** [comment]
@zshbleaker 谢谢啦，解决。,

**Comment by zshbleaker** [comment]
请问是怎么解决的呢😂

我这边尝试复现时发现只要加入了 arm64 就不会 crash，具体原因尚在调查

**Comment by cx324** [comment]
@zshbleaker 就是arm64包没加进apk中。。 我在项目里面加了，但是没有在abiFilters中声明，导致运行的apk中仍然没有相应的包，所以崩溃了。我的锅 。。

**Comment by cx324** [comment]
@zshbleaker 请问你们的这个支持 mp4本地缓存  是指的那种链接指向的MP4文件吗？  我现在的链接就是这种，但是并不能缓存，我把链接放到你们的demo里面也不能缓存。

**Comment by zshbleaker** [comment]
@cx324 就是 http://abcd.com/xxx.mp4 这种，开启了离线缓存之后会在本地缓存文件

**Comment by zshbleaker** [comment]
2.0.5 修复了 arm64 so 缺失时的闪退问题，可以更新试试
