### ISSUE TITLE
使用PLMediaPlayerActivity 播放rtmp串流，有影像無聲音。

### ISSUE THREAD

**Issue by bb989** [pili-engineering/PLDroidPlayer#747]
使用範例中的PLMediaPlayerActivity.java 播放rtmp串流，影像正常但是沒有聲音，可以在那裡找到問題?(沒有錯誤信息傳回)

**Comment by zshbleaker** [comment]
请问播放地址可以提供吗？我们这边看下

**Comment by bb989** [comment]
rtmp://211.72.13.195:9305/livetv_e62670dc1eb50ef4786e4e86bfe62c79/live04

**Comment by bb989** [comment]
rtmp://211.72.13.195:9305/livetv_e62670dc1eb50ef4786e4e86bfe62c79/live04

**Comment by zshbleaker** [comment]
这边用开发版的 demo 试了下，是有画面的，不确定是不是最近的更新里修复了这个问题。下个版本将会在本周释出，到时候可以更新下。
