### ISSUE TITLE
播放器打开失败之后，更换url之后仍会播放器打开失败，url都是可以播放的，具体还不知道什么时候会出现这个问题

### ISSUE THREAD

**Issue by cx324** [pili-engineering/PLDroidPlayer#749]
![iw51sc2wx vgga5lb vq d](https://user-images.githubusercontent.com/8123469/33193388-3696b0a6-d103-11e7-895d-0043b9d79215.png)

**Comment by zshbleaker** [comment]
请问能提供一下具体的 URL 吗，我们这边调查与i 下

**Comment by cx324** [comment]
@zshbleaker 跟url无关吧，在网速很慢的情况下出现的，http://cdn.vliao1.xyz/prod/video/278619_1511770053730_u2sej8lu2nrpdb11576m，这个url指向的是一个mp4，但是好像不能缓存啊。 还有一个问题就是你们这个可以自定义缓冲进度条吗？

**Comment by cx324** [comment]
@zshbleaker 只要回调了播放器打开失败之后，之后会一致回调这个，再也播放不出视频了。退出页面重进也是，和网速以及url无关。

**Comment by zshbleaker** [comment]
请问是在什么场景下才会 open failed 呢？这边一直没能复现

**Comment by zshbleaker** [comment]
2.0.5 应该改善了这个问题，可以更新试试
