### ISSUE TITLE
1.5.1 升级 2.0.4 播放时返回 ERROR_CODE_OPEN_FAILED ERROR_CODE_IO_ERROR

### ISSUE THREAD

**Issue by lyz52789** [pili-engineering/PLDroidPlayer#755]
AVOptions options = new AVOptions();
options.setInteger(AVOptions.KEY_PREPARE_TIMEOUT, 10 * 1000);
options.setInteger(AVOptions.KEY_LIVE_STREAMING, mIsLiveStreaming ? 1 : 0);
options.setInteger(AVOptions.KEY_MEDIACODEC, AVOptions.MEDIA_CODEC_SW_DECODE);
options.setInteger(AVOptions.KEY_LOG_LEVEL,0);
mVideoView.setAVOptions(options);
mVideoView.setDebugLoggingEnabled(true);
mVideoView.setOnInfoListener(mOnInfoListener); mVideoView..setOnCompletionListener(mOnCompletionListener);
mVideoView..setOnErrorListener(mOnErrorListener);
mVideoView..setOnBufferingUpdateListener(mBufferingUpdateListener);
mVideoView..setOnVideoSizeChangedListener(mOnVideoSizeChangedListener);
mVideoView..setDisplayAspectRatio(PLVideoView.ASPECT_RATIO_PAVED_PARENT);
mVideoView..setLooping(false);
这是配置文档配置的。有疏漏么

**Comment by zshbleaker** [comment]
请问可以提供一下播放地址吗，我们这边调查一下

**Comment by lyz52789** [comment]
是直播地址 不能实时提供  我在demo 试过可用 不过因为 1.5.1 到 2.0.4 配置参数改变有点多 有新版的配置文档么？

**Comment by zshbleaker** [comment]
https://developer.qiniu.com/pili/sdk/1210/the-android-client-sdk 
参考 demo 配置一般不会出问题

**Comment by zshbleaker** [comment]
2.0.5 进一步改善了特定网络下 open failed 的问题，可以更新试下
