### ISSUE TITLE
频繁快速切换url会导致anr

### ISSUE THREAD

**Issue by cx324** [pili-engineering/PLDroidPlayer#756]
频繁快速切换播放的url，会有几率导致anr错误。我是在切换url之前调用了stopPlayback，然后在setVideoPath。

**Comment by zshbleaker** [comment]
切换 URL 之前不需要调用 stopPlayback，直接 setVideoPath 然后 start 即可

**Comment by cx324** [comment]
@zshbleaker 直接切换会导致在某一次中切换url没有成功，即它播放的url仍然是上一次的url对应的视频

**Comment by zshbleaker** [comment]
没有切换成功吗？这个比较奇怪，这种情况的 log 可以提供一下吗？我们调查一下

**Comment by cx324** [comment]
@zshbleaker 你说的log是你们的sdk打出来的log吗？ 那个有点多，需要提供哪些呢？

**Comment by zshbleaker** [comment]
把对应 package 所有 info level 的日志都打印出来，存成一个 txt 贴到这里就好

**Comment by cx324** [comment]
@zshbleaker 能给个邮箱吗？我通过邮箱发你吧。

**Comment by zshbleaker** [comment]
zshbleaker@icloud.com
