### ISSUE TITLE
setOnVideoFrameListener中怎么让onVideoFrameAvailable返回的数据为  YUV420P格式

### ISSUE THREAD

**Issue by SquareLeo** [pili-engineering/PLDroidPlayer#757]

**Comment by zshbleaker** [comment]
onVideoFrameAvailable 的第五个参数是 format，为 0 说明是 YUV420P，大多数情况下都是这个。详情参考 https://developer.qiniu.com/pili/sdk/1210/the-android-client-sdk

**Comment by SquareLeo** [comment]
你好，那个SEI流格式能转换为YUV420P的么

**Comment by zshbleaker** [comment]
SEI 是 h264 规范里一些帧的格式，用于告知解码器一些额外信息，本身不包含图像信息。一个 h264 流里应该只有一小部分帧是 SEI 的，没有 SEI 流这个说法。

**Comment by SquareLeo** [comment]
您好，打扰了！我想在以下方法（或者其他方法中）获取网络视频流的帧数据；每次获得的都是SEI数据；本地视频播放也是这个；
mVideoView.setOnVideoFrameListener(new PLMediaPlayer.OnVideoFrameListener() {
            @Override
            public void onVideoFrameAvailable(final byte[] bytes, int i, int i1, int i2, int i3, long l) {
                Log.e("Square",i + "--" + i1 + "---" + i2 + "------" + i3 + "------------"+l);
            }
        });

12-19 13:40:29.057 22061-22306/com.pili.pldroid.playerdemo E/Square: 7--480---288------2------------6911266816
12-19 13:40:29.057 22061-22306/com.pili.pldroid.playerdemo E/Square: 7--480---288------2------------7332102144
12-19 13:40:29.187 22061-22306/com.pili.pldroid.playerdemo E/Square: 7--480---288------2------------7332102144
12-19 13:40:29.190 22061-22306/com.pili.pldroid.playerdemo E/Square: 7--480---288------2------------7332102144
12-19 13:40:29.195 22061-22306/com.pili.pldroid.playerdemo E/Square: 7--480---288------2------------7332102144
那个打扰下我想问一下要怎么设置可以获取到YUV420P的数据，谢谢您！

**Comment by zshbleaker** [comment]
视频地址可以提供一下吗

**Comment by SquareLeo** [comment]
http://mvideo.spriteapp.cn/video/2017/1123/04bfdb0a-d006-11e7-9b78-1866daeb0df1cut_wpc.mp4

**Comment by SquareLeo** [comment]
rtmp://live.hkstv.hk.lxdns.com/live/hks  这个是你们的Demo里面的视频地址，然后我上面的数据是根据这个获取的，然后http://mvideo.spriteapp.cn/video/2017/1123/04bfdb0a-d006-11e7-9b78-1866daeb0df1cut_wpc.mp4这个视频的链接只能获取到一条数据；

**Comment by SquareLeo** [comment]
http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4    这个网络视频也是只有一次回调，之前我放到腾讯云测试的视频可以一直回调不过回调的数据都是SEI数据，那个我的腾讯云测试账号过期了。。。所以那个视频找不到了

**Comment by zshbleaker** [comment]
若要开启，AVOptions 设置 KEY_VIDEO_DATA_CALLBACK 的 value 应该为 1，目前 demo 里配置有误，设置为 1 之后就正常了，感谢反馈

**Comment by SquareLeo** [comment]
恩恩，我之前就是开启的，然后我又重新下了一遍Demo，开启之后返回的都是SEI数据（视频地址为Demo地址），这个返回的数据是由视频链接所设定的，还是我们自己可以设置的

**Comment by zshbleaker** [comment]
我这边使用 demo 开启了视频数据回调后播放那个 mp4 视频，除了第一帧是 SEI，其他都是 YUV420P 的帧数据

**Comment by SquareLeo** [comment]
Url设置：
videoPath="http://9890.vod.myqcloud.com/9890_4e292f9a3dd011e6b4078980237cc3d3.f20.mp4";

 options设置：
options.setInteger(AVOptions.KEY_VIDEO_DATA_CALLBACK, 1);

监听设置：
    private PLMediaPlayer.OnVideoFrameListener mOnVideoFrameListener = new PLMediaPlayer.OnVideoFrameListener() {
        @Override
        public void onVideoFrameAvailable(byte[] data, int size, int width, int height, int format, long ts) {
            Log.i(TAG, "onVideoFrameAvailable: " + size + ", " + width + " x " + height + ", " + format + ", " + ts);
        }
    };

播完上面地址整个视频的Logcat：
12-19 16:12:51.162 14079-15419/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 689, 640 x 360, 2, 0
12-19 16:13:35.949 14079-15419/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 689, 640 x 360, 2, 0
12-19 16:14:35.971 14079-15419/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 689, 640 x 360, 2, 0
12-19 16:15:35.987 14079-15419/com.pili.pldroid.playerdemo I/PLVideoViewActivity: onVideoFrameAvailable: 689, 640 x 360, 2, 29555302057967725

Demo下载时间：今天下午；Demo测试Activity：PLVideoViewActivity
就只有SEI帧的才会显示，其他的不会显示；可能是我load下来配置有问题，我再看看。。。
