### ISSUE TITLE
2.0.4  列表快速切换视频  SIGSEGV(SEGV_ACCERR) 

### ISSUE THREAD

**Issue by LangQiang** [pili-engineering/PLDroidPlayer#758]
#01 pc 00033286 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
--
3 #02 pc 0000e032 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
4 #03 pc 0000e092 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
5 #04 pc 0000dc04 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
6 #05 pc 0000edf4 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
7 #06 pc 0000eb54 /data/app/com.redwolfama.peonylespark-1/lib/arm/libQPlayer.so
8 #07 pc 00046dc2 /system/lib/libc.so
9 #08 pc 00019b2c /system/lib/libc.so

bugly抓到的
这个还没有解决吗

**Comment by zshbleaker** [comment]
需要提供更详细的信息

**Comment by LangQiang** [comment]
怎么提供呢..

**Comment by zshbleaker** [comment]
这个问题已经处理，将会在下次更新中修复，感谢反馈
