### ISSUE TITLE
播放不了rtsp，failed to open player

### ISSUE THREAD

**Issue by tpnet** [pili-engineering/PLDroidPlayer#763]
地址是这样子的：  rtsp://root:密码@地址/axis-media/media.amp ，，软解，硬解都不行，4个播放接口也试了，都不行

**Comment by baochengchen** [comment]
我这边是rtmp地址播放不了 很烦。。

**Comment by zshbleaker** [comment]
@tpnet 目前暂不支持 rtsp 协议
@baochengchen 请问可以提供一下无法播放的 rtmp 流地址吗？
