### ISSUE TITLE
播放.flv时好像没有声音，这是怎么回事呢

### ISSUE THREAD

**Issue by 2534290808** [pili-engineering/PLDroidPlayer#764]
播放.flv时好像没有声音，这是怎么回事呢

**Comment by zshbleaker** [comment]
请问可以提供播放地址吗？

**Comment by 2534290808** [comment]
http://exam.xhbycm.net/test.flv

**Comment by zshbleaker** [comment]
问题已经记录，正在修复中

**Comment by zshbleaker** [comment]
这个 flv 的音频流是 mp3，目前我们的 flv 解析器主要是为了 http-flv 的直播场景优化的，仅支持 aac 格式，后续考虑加入 mp3 支持

**Comment by 2534290808** [comment]
好像你们的ios端已经支持mp3音频的flv支持了

**Comment by zshbleaker** [comment]
Android 这边目前还不支持，之后考虑加入。目前建议使用更为通用的 aac 格式

**Comment by 2534290808** [comment]
那ios支持音频为aac的格式吗？

**Comment by zshbleaker** [comment]
也是不支持的

**Comment by zshbleaker** [comment]
aac 都是支持的
