### ISSUE TITLE
.m3u8地址切换到.flv地址时会出现app崩溃状况

### ISSUE THREAD

**Issue by 2534290808** [pili-engineering/PLDroidPlayer#766]
.m3u8地址切换到.flv地址时会出现app崩溃状况

**Comment by zshbleaker** [comment]
请问是必现的吗？两个播放地址可以提供一下吗？

**Comment by 2534290808** [comment]
http://play2.kandian.360.cn/vod_xinwen/vod-media/1160007_3029687_20160725140508.m3u8

http://exam.xhbycm.net/test.flv

**Comment by zshbleaker** [comment]
使用 demo 测试没有遇到 crash 现象，方法是 setVideoPath 然后再 start

**Comment by 2534290808** [comment]
需要先pause（）吗？

**Comment by zshbleaker** [comment]
不需要

**Comment by 2534290808** [comment]
我是用这段代码切换的，还是会闪退
if(plVideoTextureView!=null){
                    plVideoTextureView.setVideoPath(uri);
                    plVideoTextureView.start();
                }

**Comment by 2534290808** [comment]
你看一下有什么问题吗？

**Comment by 2534290808** [comment]
我是用的PLVideoTextureView,你们测试的时候用的是这个组件吗？

**Comment by 2534290808** [comment]
我升级到2.0.6之后发现不会crash了，非常感谢你们的团队，
