### ISSUE TITLE
播放器PLVideoTextureView在没有加载出来就退出，多试几次就会闪退

### ISSUE THREAD

**Issue by ZY9898** [pili-engineering/PLDroidPlayer#767]
我的cpu架构只用了arm和armv7，频繁进入播放页，然后不加载出来马上退出，就会闪退，最多2/3次就会出现，这是一个必现的问题，紧急，求解

**Comment by zshbleaker** [comment]
在加入了 arm64 的 so 之后还会出现这个问题吗？

**Comment by ZY9898** [comment]
已经反馈给你们的工程师了，缺少so库确实会出问题，在你们的demo也测试了，我的项目里没有arm64的so库喔
