### ISSUE TITLE
ViewPager+Fragment  PLVideoTextureView 快速滑动切换视频 崩溃

### ISSUE THREAD

**Issue by 1530120997** [pili-engineering/PLDroidPlayer#768]
? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8540008005b
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x0   00000079369a0800  x1   0000085400080003  x2   00000079369a0800  x3   0000000000000004
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x4   0000007fc537e300  x5   000000795a918944  x6   0000007fc537e310  x7   129e2b87679946a7
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x8   0000000000000000  x9   0000000000000000  x10  0000000000430000  x11  0000000000000005
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x12  0000007fc537e298  x13  0000007fc537e324  x14  000000795a4b1150  x15  0000000000000000
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x16  00000079383025a0  x17  0000000000000000  x18  000000795dde9918  x19  000000795aaa1a00
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x20  0000007938c9b930  x21  000000795aaa1a00  x22  0000007fc537e5fc  x23  000000793d6a1c57
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x24  000000000000000c  x25  129e2b87679946a7  x26  000000795aaa1a98  x27  129e2b87679946a7
12-07 18:49:42.186 29228-29228/? A/DEBUG:     x28  0000007fc537e320  x29  0000007fc537e320  x30  000000795a4ba794
12-07 18:49:42.186 29228-29228/? A/DEBUG:     sp   0000007fc537e2f0  pc   00000079383025b4  pstate 0000000080000000
12-07 18:49:42.191 29228-29228/? A/DEBUG: backtrace:
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #00 pc 00000000000665b4  /data/app/com.xxxxx-1/lib/arm64/libQPlayer.so
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #01 pc 00000000000db790  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #02 pc 00000000000d21b4  /system/lib64/libart.so (art_quick_invoke_stub+580)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #03 pc 00000000000dee80  /system/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+204)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #04 pc 000000000028cbf0  /system/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+312)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #05 pc 0000000000285bcc  /system/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+592)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #06 pc 00000000005539b4  /system/lib64/libart.so (MterpInvokeDirect+388)
12-07 18:49:42.191 29228-29228/? A/DEBUG:     #07 pc 00000000000c4c94  /system/lib64/libart.so (ExecuteMterpImpl+14484)

**Comment by 1530120997** [comment]
12-08 09:50:53.796 16103-16103/? A/DEBUG: Build fingerprint: 'HONOR/PRA-AL00X/HWPRA-H:7.0/HONORPRA-AL00X/C00B205:user/release-keys'
12-08 09:50:53.796 16103-16103/? A/DEBUG: Revision: '0'
12-08 09:50:53.796 16103-16103/? A/DEBUG: ABI: 'arm64'

**Comment by zshbleaker** [comment]
这个问题已经处理，将会在下次更新中修复，感谢反馈
