### ISSUE TITLE
播放m3u8 问题

### ISSUE THREAD

**Issue by TigerYao** [pili-engineering/PLDroidPlayer#770]
在最新版本上播放m3u8视频，seekto是，一直报错重连，一直转圈，没反应是啥问题
V/AS.WifiMaster: 13:12:03.874[4270] idle:IDLE, handleEvent(Intent { act=android.net.wifi.supplicant.STATE_CHANGE flg=0x24000010 (has extras) })
 E/@@@QCLOG: Err  TD5DFA930 CHTTPClient L609 connect error. nErr: -1, errorno: 101
 E/@@@QCLOG: Err  TD5DFA930 CAdaptiveStreamHLS L873 Can't open the url:http://cdn7.ushareit.cn/sz2/h_v/mOegV_240p/00078.ts

**Comment by zshbleaker** [comment]
可以提供一下 m3u8 链接吗？我们这边看下
