### ISSUE TITLE
PLVideoTextureView.setVideoPath ANR

### ISSUE THREAD

**Issue by LangQiang** [pili-engineering/PLDroidPlayer#772]
setVideoPath 会卡主线程,  还不能放到子线程里,setVideoPath里面貌似还有获取宽高重新设置TextureView宽高的代码,我该怎么办呢.

**Comment by Zziv** [comment]
我也碰到同样的问题。。。setVideoPath后卡住了，不会切换视频

**Comment by 1530120997** [comment]
我也碰到同样的问题。。。setVideoPath

**Comment by 1530120997** [comment]
先调用stopPlayback(); 试试

**Comment by Zziv** [comment]
@1530120997 你解决了吗？

**Comment by zshbleaker** [comment]
请问是如何使用的呢？应该是不会卡住主线程的

**Comment by LangQiang** [comment]
在recyclerview中, 每个item全屏显示,当可见的时候调用setVideoPath() ,不可见调pause
setVideoPath()这个会不同程度卡住ui线程, 测试过只setVideoPath 不调用start就会复现这个问题 很好复现的,可以提供代码

**Comment by LangQiang** [comment]
@zshbleaker

**Comment by 1530120997** [comment]
@Zziv 我做的效果类似于viewPager 左右滑切换视频 调用setVideoPath---> start  结果arn
最后我在调用setVideoPath---> start  前加上stopPlayback()---->  setVideoPath---> start 就好了 目前还没有发现anr

**Comment by cx324** [comment]
@1530120997 我做的和你的类似，我是垂直方向的Viewpager，我想问下你所有的页面用的是一个播放view，还是每个页面都有自己的一个播放view？

**Comment by zshbleaker** [comment]
@LangQiang @1530120997 @cx324 已确认播放器在 view 复用时的问题，正在修复

**Comment by 1530120997** [comment]
@Zziv 复用一个view 出新bug了

**Comment by 1530120997** [comment]
@Zziv 我也不知道该怎么说 怎么改都有bug 心累

**Comment by 1530120997** [comment]
@Zziv 你看一下是不是在销毁的时候持有了播放器的对象 导致播放器view 无法正确释放

**Comment by Zziv** [comment]
@1530120997 谢谢呀 其实我这边情况跟你差不多 需求跟你们也差不多 就是改来改去都有问题。。。哈哈哈哈，只能等新版本了

**Comment by 1530120997** [comment]
@Zziv 你注意一下持有对象的地方 我有一只跟新进度 销毁没有释放进度条里面的应用报错

**Comment by LangQiang** [comment]
@1530120997 我开始也是每次都调用stopPlayback() ,频繁快速切换,会有问题.

**Comment by 1530120997** [comment]
@LangQiang 最后你怎么解决的

**Comment by ZhuYichuan** [comment]
我这里也是同样 问题，快速滑动viewpager 主线程卡，有没有解决方案
