### ISSUE TITLE
视频数据源出错后onError方法多次执行

### ISSUE THREAD

**Issue by shangmingchao** [pili-engineering/PLDroidPlayer#773]
虽然可以通过`setOnErrorListener`方法监听error信息，但如何自定义出错后是否尝试重新请求，尝试频率/次数，以及自定义重试逻辑

**Comment by zshbleaker** [comment]
SDK 在收到 IO Error 后会无限自动重连，5s 一次，暂不支持自定义频率与次数。上层可以通过记录不同错误码的次数来实现自定义逻辑。

**Comment by zshbleaker** [comment]
SDK 在收到 IO Error 后会无限自动重连，5s 一次，暂不支持自定义频率与次数。上层可以通过记录不同错误码的次数来实现自定义逻辑。

**Comment by shangmingchao** [comment]
好的，谢谢，还有就是设置进度时音量异常的问题能修复么

**Comment by shangmingchao** [comment]
好的，谢谢，您可以close这个issue了
