### ISSUE TITLE
本地视频切换问题

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#774]
我在做本地视频循环播放时，在切换视频时会卡，且有时候切换后播放视频会卡，音频没问题？

**Comment by zshbleaker** [comment]
请问是如何切换的？

**Comment by panyingdaoz** [comment]
我是在OnCompletionListener 后进行切换的，每播放完一个视频后，我就切换另一个视频。

**Comment by zshbleaker** [comment]
是像
```
PLVideoView.setVideoURL(newUrl);
PLVideoView.start();
```

这样吗？

**Comment by panyingdaoz** [comment]
嗯，是的。

**Comment by zshbleaker** [comment]
@panyingdaoz 使用的的是 PLMediaPlayer 类？

**Comment by panyingdaoz** [comment]
没有啊，使用的是VideoView类，但是你们的监听是
private PLMediaPlayer.OnCompletionListener mOnCompletionListener = new PLMediaPlayer.OnCompletionListener() {
        @Override
        public void onCompletion(PLMediaPlayer plMediaPlayer) {
            KLog.e(TAG, "播放完成 !");
            showToast("播放完成 !");
            int sum = showSum().size();
            if (sum > 0) {
                playCondition();
                plMediaPlayer.start();
            }
        }
    };
这样，不允许我在这mVideoView.start()；只可以“plMediaPlayer.start();”这样。

**Comment by panyingdaoz** [comment]
你们有这样的问题吗？

**Comment by zshbleaker** [comment]
为什么不能直接在回调里调用 `mVideoView.start()` ？

**Comment by panyingdaoz** [comment]
我试过，直接调报错

**Comment by panyingdaoz** [comment]
@zshbleaker 我试过了，要是调用mVideoView.start()，启动播放是失败的，只有那样调用才能播放视频。

**Comment by panyingdaoz** [comment]
@zshbleaker 我还是过
private PLMediaPlayer.OnPreparedListener mOnPreparedListener = new PLMediaPlayer.OnPreparedListener() {
        @Override
        public void onPrepared(PLMediaPlayer plMediaPlayer, int i) {
            mVideoView.start();
        }
    };
这样调用的，是能正常循环播放，但是还是有卡顿，问题
