### ISSUE TITLE
从1.6.0升级到 2.0.4报错 Multiple dex files define Lcom/pili/pldroid/player/AVOptions

### ISSUE THREAD

**Issue by jacintoface** [pili-engineering/PLDroidPlayer#776]
这个怎么解决呢

**Comment by zshbleaker** [comment]
确认 jar 和 so 都更新后，clean 然后 rebuild project 试试

**Comment by jacintoface** [comment]
还是不行 我clean rebuild 清缓存都试过了 还是不行

**Comment by zshbleaker** [comment]
你的项目会用到 multidex 吗？如果不会的话，在 build.gradle 里加上
```
dexOptions {
    preDexLibraries = false
}
```
然后 clean 再 rebuild

**Comment by jacintoface** [comment]
还是先谢谢啦@zshbleaker ，可能是我比较菜有哪个地方操作不对，我只能先暂时退回1.6.0版本

**Comment by kexuejin** [comment]
明显更新版本后，没有clean项目，导致重复的包
