### ISSUE TITLE
关于webm格式视频播放问题

### ISSUE THREAD

**Issue by shangmingchao** [pili-engineering/PLDroidPlayer#778]
Hi, PLDroidPlayer播放webm格式视频出错，是不支持webm格式么？而且多次执行`stopPlayback()`方法后，为什么会无限回调`ERROR_CODE_PLAYER_DESTROYED = -2008`的error，即使退出应用也没有停止，除非杀进程。

**Comment by zshbleaker** [comment]
目前不支持 webm 格式。stopPlayback 后播放器已经销毁，需要再次 setVideoPath 来创建。应该不会无限回调，销毁后一次 stop 会回调一次 ERROR_CODE_PLAYER_DESTROYED
