### ISSUE TITLE
怎样在setVideoPath 之后不要自动播放视频

### ISSUE THREAD

**Issue by wuqi713** [pili-engineering/PLDroidPlayer#78]
看了代码好像没有能控制的地方

**Comment by longbai** [comment]
您是否可以改下代码，在start 的地方 调用setpath

**Comment by wuqi713** [comment]
看了一下代码 好像setVideoPath 之后设置了 OnPreparedListener 回调里面 直接start了

**Comment by Jhuster** [comment]
@wuqi713 这个需求马上会在 1.2.2 版本中提供和修复，稍等。

**Comment by wuqi713** [comment]
@Jhuster  好的

**Comment by wuqi713** [comment]
@Jhuster  大概什么时间能发不新版?

**Comment by Jhuster** [comment]
@wuqi713 v1.2.2 版本已发布，这个接口的使用说明：[AVOptions.KEY_START_ON_PREPARED](https://github.com/pili-engineering/PLDroidPlayer/wiki/6-高级功能#Play-avOptions)
