### ISSUE TITLE
视频切换卡顿，音视频不同步问题

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#781]
如果直接在onCompletion中调mVideoView.start(),不起作用，如果改为plMediaPlayer.start();这个就会卡顿，音视频不同步，后来使用
private PLMediaPlayer.OnPreparedListener mOnPreparedListener = new PLMediaPlayer.OnPreparedListener() {
        @Override
        public void onPrepared(PLMediaPlayer plMediaPlayer, int i) {
            mVideoView.start();
        }
    };
也会卡顿。

**Comment by zshbleaker** [comment]
在上一个视频播放完成的回调，或者在主线程的点击事件中设置新的 url 然后 start 就好
