### ISSUE TITLE
seek后在加载途中再次seek 就会闪退

### ISSUE THREAD

**Issue by MJLblabla** [pili-engineering/PLDroidPlayer#783]
seek后在加载途中再次seek 就会闪退

**Comment by zshbleaker** [comment]
在收到 onSeekComplete 前进行下一次 seek 操作会收到 ERROR_SEEK_FAILED 的错误码，demo 里收到任何错误都会直接 finish，可以根据实际业务调整

**Comment by MJLblabla** [comment]
我好像没有发现有刷新的功能。播放出错刷新一下重当前进度刷新

**Comment by zshbleaker** [comment]
没有这个功能，可以自己记录当前进度手动实现
