### ISSUE TITLE
视频格式是MPEG4的，什么时候才可以支持啊

### ISSUE THREAD

**Issue by dazhiyu** [pili-engineering/PLDroidPlayer#786]
上次2.0.3的时候问过，结果新版本还是不支持。。。

**Comment by zshbleaker** [comment]
我们在最近几个开发版本里陆续增加了 MPEG-4 各个 part 的支持，考虑到这个标准非常繁杂，可能有些部分支持的不完整。请问可以提供一个视频地址吗，我们这边看下

**Comment by dazhiyu** [comment]
抱歉，回答完了,这是地址
http://static.huajuanmall.com/video/thumb/o_1bu7gagbrd40132q6mo16jbe3oh.mp4

**Comment by zshbleaker** [comment]
这个地址在目前的开发版已经可以播放了，新版本发布后可以更新试下

**Comment by dazhiyu** [comment]
好的
