### ISSUE TITLE
PLVideoView视频缓冲时间过长

### ISSUE THREAD

**Issue by tienhere** [pili-engineering/PLDroidPlayer#787]
2.0.4      
测试发现点播视频时长越长，缓冲时间越长，1个小时的视频缓冲时间在10s以上，两个小时的时间缓冲时间在20s左右，并且可能一直缓冲，直至失败。。。
      怎么才能做到秒开，并且从打开到开始播放与视频本身的时长无关

**Comment by zshbleaker** [comment]
MP4 需要读取完 index table 信息才可以播放；视频越长，index table 越长，这点比较难避免。我们会在之后的版本继续想办法优化这个过程，感谢反馈
