### ISSUE TITLE
打开播放器失败有哪些原因导致

### ISSUE THREAD

**Issue by 547555857** [pili-engineering/PLDroidPlayer#788]
音频播放 会出现-2 
这个错误的大概原因是什么 
我该如何避免

**Comment by 547555857** [comment]
我是再播放本地音频
/storage/emulated/0/msc/1513826514421speech.wav
这个是我本地绝地路径 我需要对这个路径处理什么吗
还是播放器不支持这个格式？

**Comment by zshbleaker** [comment]
目前还不支持 wav 格式音频

**Comment by 547555857** [comment]
好 那为什么偶尔会出先播放器-2

**Comment by zshbleaker** [comment]
如果是播放本地不支持的格式，会出现 -2

**Comment by 547555857** [comment]
网络的音频也会出现

**Comment by zshbleaker** [comment]
目前弱网环境下可能会出现意外的 -2，这个问题将会在下个版本中修复。另外打开不支持格式的纯音频文件就会返回 OPEN FAILED

**Comment by 547555857** [comment]
ok 明白了
