### ISSUE TITLE
新改的版本 没有 release（）方法吗？

### ISSUE THREAD

**Issue by woshigaokun1314** [pili-engineering/PLDroidPlayer#789]
您好，更新了新版本的sdk 和 so 文件 。 没有 release（）方法吗？ 或者 我 页面销毁时要调用其它什么方法？

**Comment by zshbleaker** [comment]
PLMediaPlayer 是有 release 方法的，PLVideoView 与 PLVideoTextureView 调用了 stopPlayback 后会销毁内部的播放器

**Comment by woshigaokun1314** [comment]
哦哦。。谢了
