### ISSUE TITLE
能不能给个开源的 控制不太方便 

### ISSUE THREAD

**Issue by TedWithAHammer** [pili-engineering/PLDroidPlayer#79]
求邮件开源包 ，只需要外层控制层的 so的不需要 当然都给最好

**Comment by longbai** [comment]
麻烦说下您的详细需求

**Comment by winter120** [comment]
求so开源代码，没有x86_64位的.so文件，x86_64平台运行会找不到库文件异常退出

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/ijkplayer
