### ISSUE TITLE
请问下 这个怎么实现基于activity的旋转全屏呢，不是画面旋转

### ISSUE THREAD

**Issue by jacintoface** [pili-engineering/PLDroidPlayer#794]
我现在是在尝试setDisplayOrientation配合activity.setRequestedOrientation使用，但是没什么效果。

**Comment by zshbleaker** [comment]
activity 旋转后，重新计算 view 尺寸，然后 requestLayout

**Comment by jacintoface** [comment]
可以考虑在下个版本中 把这个直接加进去吗？现在直播中基本都会有这种旋转。。。

**Comment by zshbleaker** [comment]
Activity 的旋转信息是在 app 层才能接收到的，就是个旋转画面 + 重新测量 view 尺寸的过程，现有 API 完全可以实现
