### ISSUE TITLE
关于保持屏幕唤醒的建议

### ISSUE THREAD

**Issue by shangmingchao** [pili-engineering/PLDroidPlayer#797]
在播放视频的时候，肯定是要保持屏幕唤醒/常亮状态的。不管是原生的`MediaPlayer`还是Bilibili的`IjkMediaPlayer`都会处理是否保持屏幕唤醒的逻辑。
`com.pili.pldroid.player.PLMediaPlayer`是`com.qiniu.qplayer.mediaEngine.MediaPlayer`的一层封装，两者都没有处理屏幕唤醒逻辑，却实现了`setWakeMode()`方法。虽然我通过在`PLMediaPlayer`基础上再封装一层的方式实现了屏幕唤醒状态的控制，但我觉得这个逻辑应该由MediaPlayer自己实现，而不是交给使用者去处理这些逻辑。
另外，在上一次seek完成前再次seek会触发`ERROR_CODE_SEEK_FAILED(-4)`的error回调，这个error能否避免，或者这个error是否可以忽略(回调`onInfo()`而不是`onError()`?)，因为这对于MediaPlayer来说并不是一个error状态。

**Comment by zshbleaker** [comment]
屏幕唤醒的逻辑这个考虑加入，SEEK_FAILED 的这个建议很好，计划之后改成真正 fail 时再回调 error，频繁 seek 的场景返回一个 info。

感谢反馈

**Comment by shangmingchao** [comment]
好的，谢谢，期待`PLDroidPlayer`越来越完善，越来越好
