### ISSUE TITLE
控制播放时缓存时长问题

### ISSUE THREAD

**Issue by drawf** [pili-engineering/PLDroidPlayer#810]
我使用的版本：pldroid-player-1.5.1.jar

在我理解看来下面的参数分别是：播放器缓存多长开始播放、播放器最大缓存多久

可在实际应用中发现，播放一个4-5分钟的HLS的视频，mPlayer.getBufferPercentage() 会缓存视频长度的一半。

请问该如何完全控制 播放器的缓存能力？

// 默认的缓存大小，单位是 ms
// 默认值是：2000
options.setInteger(AVOptions.KEY_CACHE_BUFFER_DURATION, 2000);

// 最大的缓存大小，单位是 ms
// 默认值是：4000
options.setInteger(AVOptions.KEY_MAX_CACHE_BUFFER_DURATION, 4000);

**Comment by zshbleaker** [comment]
1.5.1 已经不再维护。那两个选项主要是用于用于微调延迟与追帧策略。

**Comment by drawf** [comment]
@zshbleaker 
谢谢回复。
请问最新的2.x版本是否支持控制播放时的缓冲大小呢？

**Comment by zshbleaker** [comment]
目前还不支持，后续考虑加入这一功能
