### ISSUE TITLE
关于源码的问题

### ISSUE THREAD

**Issue by Greathfs** [pili-engineering/PLDroidPlayer#813]
![image](https://user-images.githubusercontent.com/18097997/34924547-0273f09a-f9df-11e7-8955-268c1977e842.png)

我想自己通过PLMediaPlayer封装下,不想直接用PLVideoView,这个类应该不会涉及到什么核心的东西,能发一下这个类的源码吗?拜托了

**Comment by zshbleaker** [comment]
这个类只和 PLVideoView 与 PLVideoTextureView 有关，只用 PLMediaPlayer 的话不会用到

**Comment by Greathfs** [comment]
PLVideoView  应该是你们自己封装的PLMediaPlayer 吧 我其实是想参考下你们的封装  虽然我现在自己已经封装好了
