### ISSUE TITLE
这个m3u8的播放不了

### ISSUE THREAD

**Issue by AndMy** [pili-engineering/PLDroidPlayer#815]
1.6.0和2.0.6都不行
http://hls.zx.hualumedia.com/transcode/hls/2018/01/8327/320/8327.m3u8
这是log  log太多了截取部分

01-15 15:12:17.642 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 CHTTPIO2 L117 Open http://hls.zx.hualumedia.com/transcode/hls/2018/01/8327/320/8327-0022.ts. Length is       183676. Used Time 38.
01-15 15:12:17.643 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 CAdaptiveStreamHLS L899 segment size:183676
01-15 15:12:17.645 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11020001 start.
01-15 15:12:17.645 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11020001, 0, 0
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_IO_FIRST_BYTE_DONE       00 : 00 : 05 : 398           0             0     
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000010 start.
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000010, 0, 0
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.646 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_GET_HEADDATA        00 : 00 : 05 : 398           0             0    200 
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000011 start.
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000011, 0, 0
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_CONTENT_LEN         00 : 00 : 05 : 399           0        183676     
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 0, 0
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.647 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 399           0             0    http://hls.zx.hualumedia.com/transcode/hls/2018/01/8327/320/8327-0022.ts 
01-15 15:12:17.668 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.668 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
01-15 15:12:17.668 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.668 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 424      262144         45296     
01-15 15:12:17.689 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.689 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
01-15 15:12:17.689 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.689 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 445      262144         78416     
01-15 15:12:17.699 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.700 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 262144, 0
01-15 15:12:17.700 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.700 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   35QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 453      262144        114416     
01-15 15:12:17.720 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.720 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
01-15 15:12:17.721 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.721 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 476     1048576        147536     
01-15 15:12:17.731 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000030 start.
01-15 15:12:17.731 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000030, 1048576, 0
01-15 15:12:17.732 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.732 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_HTTP_DOWNLOAD_SPEED      00 : 00 : 05 : 485     1048576        183676     
01-15 15:12:17.743 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 CAdaptiveStreamBA L113 In BA: cur buffer time:0, ullLastSegmentStartTime:0, ullLastSegmenetTransTime:138, ullLastBASegment:0
01-15 15:12:17.743 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 C_M3U_Manager L1792 the PlayList Id:0, the sequenceId:23
01-15 15:12:17.743 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 C_M3U_Manager L1806 Can't get the sequence id:23 in playlist:0
01-15 15:12:17.743 29242-9467/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T7722AD90 C_HLS_Entity L967 VOD End!
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000021 start.
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000021, 0, 0
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_HTTP_DISCONNECT_START    00 : 00 : 05 : 499           0             0     
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000022 start.
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000022, 0, 0
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_HTTP_DISCONNECT_DONE     00 : 00 : 05 : 499           0             0     
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 11000060 start.
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 11000060, 0, 0
01-15 15:12:17.747 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: onBufferingUpdate: 100
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_HTTP_DOWNLOAD_FINISH     00 : 00 : 05 : 499           0             0     
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 15200002 start.
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 16000007, 0, 0
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 COMBoxMng L1492 Play complete!
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 0
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_SNKV_EOS                 00 : 00 : 05 : 499           0             0     
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 15100002 start.
01-15 15:12:17.748 29242-29242/com.pili.pldroid.playerdemo D/PLAudioPlayerActivity: onBufferingUpdate: 100%
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 16000007, 0, 0
01-15 15:12:17.748 29242-29242/com.pili.pldroid.playerdemo D/PLAudioPlayerActivity: Play Completed !
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 COMBoxMng L1492 Play complete!
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:17.748 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_SNK_AUDIO_EOS            00 : 00 : 05 : 499           0             0     
01-15 15:12:17.750 29242-29242/com.pili.pldroid.playerdemo D/PLAudioPlayerActivity: Play Completed !
01-15 15:12:18.194 29242-29242/com.pili.pldroid.playerdemo I/QPlayer: stop + State: COMPLETED
01-15 15:12:18.194 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ----Stop Value is 00000000 start.
01-15 15:12:18.204 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 CBoxVideoRnd L191 Video Render num:        0 -        0
01-15 15:12:18.209 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L274 ----Stop leave! rc =        0. Used Time: 15
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/QPlayer: stop -
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/QPlayer: release + State: COMPLETED
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L256 ----ReceiveMsg Value is 1600000E start.
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/QPlayer: postEventFromNative: 1600000e, 0, 0
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 QCFuncLog L274 ----ReceiveMsg leave! rc =        0. Used Time: 1
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 CAnalysisMng L390 [ANL][KPI]+Recv stop event, 1163755, pos 1
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T78962CE0 CAnalysisMng L400 [ANL][KPI]-Recv stop event, 1163755, use time 0
01-15 15:12:18.210 29242-9455/com.pili.pldroid.playerdemo I/@@@QCLOG: QCMSG   36QC_MSG_PLAY_STOP                00 : 00 : 05 : 952           0             1     
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ----Close Value is 00000000 start.
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------Stop Value is 00000000 start.
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L274 --------Stop leave! rc =        0. Used Time: 0
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------~CBoxVideoRnd Value is 00000000 start.
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 --------~CBoxVideoRnd leave! no return. Ussed Time: 0
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------~CBoxVideoDec Value is 00000000 start.
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 --------~CBoxVideoDec leave! no return. Ussed Time: 0
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------~CBoxAudioRnd Value is 00000000 start.
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 --------~CBoxAudioRnd leave! no return. Ussed Time: 0
01-15 15:12:18.210 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------~CBoxAudioDec Value is 00000000 start.
01-15 15:12:18.211 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 ULIBFunc L116 Free lib =  0x771d7128
01-15 15:12:18.211 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 --------~CBoxAudioDec leave! no return. Ussed Time: 1
01-15 15:12:18.211 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 --------~CBoxSource Value is 00000000 start.
01-15 15:12:18.211 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ------------Close Value is 00000000 start.
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 ------------Close leave! no return. Ussed Time: 1
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ------------Close Value is 00000000 start.
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 ------------Close leave! no return. Ussed Time: 0
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 --------~CBoxSource leave! no return. Ussed Time: 1
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L274 ----Close leave! rc =        0. Used Time: 2
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ----Close Value is 00000000 start.
01-15 15:12:18.213 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L274 ----Close leave! rc =        0. Used Time: 0
01-15 15:12:18.218 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L256 ----~CAnalysisMng Value is 00000000 start.
01-15 15:12:18.218 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 CAnalysisMng L104 [ANL]+Exit ANL, position 1
01-15 15:12:18.223 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 CAnalysisMng L126 [ANL][KPI]-Exit ANL, use time 5
01-15 15:12:18.223 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 QCFuncLog L278 ----~CAnalysisMng leave! no return. Ussed Time: 5
01-15 15:12:18.233 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 COpenSLESRnd L94 Uninit
01-15 15:12:18.233 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 CBaseClock L37 Destroy CBaseClock
01-15 15:12:18.233 29242-29242/com.pili.pldroid.playerdemo I/@@@QCLOG: Info T400E7154 jniPlayer L59 It was Safe to exit ndk player!
01-15 15:12:18.233 29242-29242/com.pili.pldroid.playerdemo I/QPlayer: release -

**Comment by Greathfs** [comment]
纯音频?

**Comment by AndMy** [comment]
对 ， 是纯音频

**Comment by zshbleaker** [comment]
这个地址 ffplay 和 QuickTime 都不能播放啊

**Comment by AndMy** [comment]
ios可以播放，浏览器也可以播放，就冒昧的来请教了；其实音频转码过程有问题
恩恩 ，今天查看转码记录，里面包含了png流和音频流

**Comment by zshbleaker** [comment]
这边看到的是，前几个 ts 都有问题，播放器就打开失败了。我们这边针对这种场景做下处理，感谢反馈

**Comment by AndMy** [comment]
恩恩，没事的，反馈靠大家，让七牛更稳定，更强大
