### ISSUE TITLE
请教个问题:视频播放完毕后，拖动SeekBar  继续播放拖动的当前的进度

### ISSUE THREAD

**Issue by JakePrim** [pili-engineering/PLDroidPlayer#817]
但是我调了 videoView.seekTo(newPosition);  不管用 ？

**Comment by Flhawker** [comment]
我有类似的问题，我这边是播放完毕后，重新调用start，并不会从头开始播放，然后调用seekto也没有用，这是什么原因？

**Comment by Flhawker** [comment]
还有就是，播放的时候，有一定卡顿的情况，用系统自带的就不会。

**Comment by Flhawker** [comment]
没人回复我的问题吗？还是说我的描述不正确？

**Comment by zshbleaker** [comment]
是指收到 onCompletion 之后调用 seekTo 吗？这边好像没能复现

**Comment by Flhawker** [comment]
是的，在onCompletion之后，我们会修改图标为，播放按钮，当用户点击播放后，我们执行：
        mPlayer.start();
        if (mSeeker.getMax() == mSeeker.getProgress()) {
            mTrackPosition = 0;
            seekTo(0);
        }

        mHandler.post(mUpdateCounters);
        mBtnPlayPause.setImageDrawable(mPauseDrawable);
        ViewUtil.hide(mCoverFrame);

        if (mCallback != null) mCallback.onStarted(this);


但貌似，seek并没有起作用。

**Comment by Flhawker** [comment]
handle 用于更新剩余时间；pause用于暂停与继续；hide用于隐藏seekbar。

**Comment by Flhawker** [comment]
@zshbleaker 重现了吗？是不是有问题？在线等。

**Comment by zshbleaker** [comment]
确定 mSeeker.getMax() == mSeeker.getProgress() 有走到吗？去掉判断，直接在 onCompletion 里 seekTo 试试

**Comment by Flhawker** [comment]
试过不可以，确定走了，会出现seek失败，然后就直接调用complete结束了。获取位置的时候，还是结尾，当调用currentposition时，调用start和seek后。

**Comment by Flhawker** [comment]
seek(41)； 一帧数据，就能够seek成功，修复bug吧！start 由于 complete，无法start，无法start，就无法缓冲一帧数据，无法缓冲一帧数据，就不能seek，死循环了。

**Comment by zshbleaker** [comment]
seekTo(0) 之后调用一下 start 就好

**Comment by Flhawker** [comment]
seekTo(0) 直接失败，无法seek成功，只有到达第一帧才可以，我们的视频是 25帧每秒。

**Comment by zshbleaker** [comment]
返回 seek failed 的 error 吗？这个有点奇怪，请问可以提供一个播放地址吗，我们研究一下

**Comment by Flhawker** [comment]
就是普通本地视频，播放完成后，收到complete通知后，如果用户点击start，这时候先调用seek，再到用start，是seek不过去的。

**Comment by Flhawker** [comment]
这个你们自己测试一下就知道，很容易重现的。

**Comment by zshbleaker** [comment]
这个是我们一直都有测试的功能，事实上目前线上版本的 loop 功能也就是收到 complete 消息后 seekTo 0，都是正常工作的
