### ISSUE TITLE
想从某个进度开始播放

### ISSUE THREAD

**Issue by yazhi1992** [pili-engineering/PLDroidPlayer#818]
因为在列表中使用PLVideoView会出现复用错误的问题（比如recyclerview 的 item 0 播放到某个进度，下滑列表后，下面的item会复用item 0，导致显示错误。在列表中使用有什么需要注意的吗？可否在demo补全recyclerview中的使用示例？），所以想要换种实现，点击播放后从某个进度开始播放，但是在start之前调用seek没用。经过测试在第一帧视频已成功渲染后调用seek才生效。但是这样就会出现第一帧了。请问这个问题怎么解决？版本是最新版。

**Comment by zshbleaker** [comment]
下个版本的 demo 会增加 RecyclerView 的用例，感谢反馈。

可以在 onPrepared 后 seek，收到 onSeekComplete 之后 start，应该是没有问题的

**Comment by yazhi1992** [comment]
@zshbleaker 你好，我使用七牛的demo测试了一下，你提供的解决方案在播放本地视频有效，可以从指定进度开始播放，但是播放网络视频该方法无效。视频地址：http://download.jiayouxueba.com/test1000.m3u8。
请问如何解决？

**Comment by yazhi1992** [comment]
@zshbleaker 另外请教，比如当前播放在 10s，seekTo 20s是正常的。但是如果seekTo 4s（只调用了 seekTo 方法），就会从0s开始播放，这是什么问题？

**Comment by zshbleaker** [comment]
目前的 seek 机制是跳到指定时间戳最近的关键帧处，因此可能会有数秒的偏差。下个版本将会增加一个选项，用于指定是 seek 到关键帧还是时间戳。感谢反馈

**Comment by yazhi1992** [comment]
@zshbleaker 你好，请问下个版本（recyclerview demo）有计划什么时候上吗？

**Comment by zshbleaker** [comment]
应该是下周

**Comment by hongyang51** [comment]
@zshbleaker  精准seekto是否已经解决?  尤其在播放hls链接视频时 我看更新日志没有涉及这块的 求解答
