### ISSUE TITLE
怎样同时支持 nellymoser 和 speex 解码

### ISSUE THREAD

**Issue by autismbug92** [pili-engineering/PLDroidPlayer#819]
比较喜欢 PLDroidPlayer 的封装，但是貌似不支持 nellymoser 的解码。
自己去编译 ijkplayer 的 so ，又不清楚 libspeex 的库的编译集成方式，网上去找了好久资料都没找到说明白的。
请教下，编译支持 speex解码的方法。谢谢！

**Comment by zshbleaker** [comment]
PLDroidPlayer 目前还没有支持 speex 的计划
