### ISSUE TITLE
使用硬解码播放优酷视频地址 画面出现抖动情况

### ISSUE THREAD

**Issue by Greathfs** [pili-engineering/PLDroidPlayer#820]
我们在使用ijkplayer的时候也出现过这个问题 不知道这边大佬能不能解决下这个问题

**Comment by Greathfs** [comment]
优酷视频地址
```
http://pl-ali.youku.com/playlist/m3u8?vid=XOTU5OTUwMDI4&type=hd2&ups_client_netip=70e1e642&ups_ts=1516237705&utid=iOHmEtaUEEoCAXDh5kJp90QT&ccode=0502&psid=e9fd8bcaa114796561fb279e2cf1e3a8&duration=5403&expire=18000&ups_key=4d07e4ea53febd1e418a77dff1270475
```

**Comment by zshbleaker** [comment]
请问画面抖动是指？我这边试了下是正常的

**Comment by Greathfs** [comment]
就是播放画面会闪  我们这个apk不是安在手机上的  是安在类似AndroidTv上的

**Comment by zshbleaker** [comment]
那可能是设备兼容性的问题，SoC 的型号可以提供下吗？

**Comment by Greathfs** [comment]
瑞芯微3188  这个就是我们目前设备上使用的

**Comment by Greathfs** [comment]
瑞芯微3188 这个就是目前我们设备使用的

**Comment by Flhawker** [comment]
哈哈，都是RK芯片，感觉他这个播放器播放的时候就会卡，用系统自带的就不会卡。

**Comment by Greathfs** [comment]
@Flhawker 你们也是用的这个芯片吗?你们出现过视频播放画面抖动的问题吗?

**Comment by wututu** [comment]
我是同样的媒资同样的问题......同样的抖动,系统播放器直接黑屏

**Comment by wututu** [comment]
同样的androitTV(好几台,应该是通方案创维50G7和一部分康佳) CPU是rtd299o

**Comment by Greathfs** [comment]
@wututu 使用Exoplayer试试吧 这个播放器底层应该是使用ijk ijk在TV上不是很好 我之前是用的exoplayer  感觉还可以

**Comment by wututu** [comment]
诶,之前一直是用的ijk,换起来怕引入别的bug啊
