### ISSUE TITLE
无法播放爱奇艺视频

### ISSUE THREAD

**Issue by Greathfs** [pili-engineering/PLDroidPlayer#823]
```
http://cache.m.iqiyi.com/mus/680139900/2d8306f8646713aa4d4b56a653480d86/afbe8fd3d73448c9//20170515/f3/8b/f63043c2ad886bf4057334392ac893ab.m3u8?qd_originate=tmts_py&tvid=680139900&bossStatus=0&qd_vip=0&px=&qd_src=03020031010000000000&prv=&previewType=&previewTime=&from=&qd_time=1516267463646&qd_p=70e1e642&qd_asc=d41a4a7c5182ee8cd44a9a05405ab4fc&qypid=841976700_03030021010000000000_2&qd_k=2340c4bd023d2e23e81c5d4e7beff518&isdol=0&code=2&dfp=e0c16aa063ea5e4a7d910bb3a1c2aef1eb966db350c6f1134223fcf5200e0b862c&vf=d52792539687cc3e77bcdbd0186995eb&np_tag=nginx_part_tag
```

直接崩溃

**Comment by Greathfs** [comment]
经测试:

ijkplayer播放 OK
exoplayer播放 OK
原生播放器播放 OK
金山播放器播放 OK
七牛播放器播放 崩溃了....

**Comment by zshbleaker** [comment]
地址确定没发错吗？我这边 ffplay 和 QuickTime 都没法播放啊

**Comment by Greathfs** [comment]
爱奇艺的地址失效很快,你可能需要去抓下

**Comment by Greathfs** [comment]
抓下他们的m3u8地址就行

**Comment by zshbleaker** [comment]
请问 crash log 可以提供一下吗

**Comment by Greathfs** [comment]
直接进程崩溃了 整个log都没了

**Comment by zshbleaker** [comment]
是用 Studio 的那个 logcat 界面看的吗？过滤选项从 Show only selected application 改成 No filters 就好

**Comment by Greathfs** [comment]
mMediaPlayer.prepareAsync();这个方法执行完就崩了

**Comment by Greathfs** [comment]
我再抓下log 试试

**Comment by Greathfs** [comment]
![image](https://user-images.githubusercontent.com/18097997/35091517-d054c288-fc77-11e7-88f1-95b3d404f3de.png)

**Comment by zshbleaker** [comment]
可以提供更完整的 log 吗？从打开 app 到 crash 时间内所有的 log

**Comment by Greathfs** [comment]
![qq 20180119085833](https://user-images.githubusercontent.com/18097997/35129620-61b4da04-fcf7-11e7-9e7d-b4eba6a1ddab.png)

你们自己抓下看看 我这里log就这些啊

**Comment by Greathfs** [comment]
大佬们 这个问题解决了吗?我发现VLC也播放不了爱奇艺的m3u8地址....
