### ISSUE TITLE
在视频点击播放，loading时，关闭视频页面，偶现的崩溃

### ISSUE THREAD

**Issue by dazhiyu** [pili-engineering/PLDroidPlayer#830]
只有一句异常提示：
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3766 

版本为2.0.4

**Comment by zshbleaker** [comment]
2.0.6 修复了这个问题，建议升级版本

**Comment by dazhiyu** [comment]
嗯嗯
