### ISSUE TITLE
播放冲突

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#831]
我添加了一个字幕滚动功能，就导致了他们同事运行时，画面有卡顿、字幕滚动速度变慢问题，还有我觉得视频的解码速度有点慢，视频中的画面要是切换的快的话视频就会有点花、不清晰。我应该怎么处理才能避免我的第一个问题呢？

**Comment by panyingdaoz** [comment]
还有为什么很多mp4无法播放呢？

**Comment by zshbleaker** [comment]
字母卡顿的问题，请问使用的是播放器的哪个类呢？

MP4 无法播放的问题，请问可以提供无法播放的地址吗？我们这边调查一下

**Comment by panyingdaoz** [comment]
@zshbleaker 是VideoViewActivity这个类，mp4是本地文件

**Comment by panyingdaoz** [comment]
@zshbleaker 问题查出来了，是我的字幕的实现方法跟视频的实现方法是一样的，当他们同事运行时对CPU的暂用太大，在运行内存比较小的机子运行时就会卡顿。
