### ISSUE TITLE
官方demo：videoPath的地址不对，app就crash了

### ISSUE THREAD

**Issue by Redoteam** [pili-engineering/PLDroidPlayer#834]
我用的videoPath = "rtsp://192.168.1.11:554/type=1507:test:end".
log抓了几次都没抓到，在demo里面用全局异常类，也没抓到。
下面的不知道是不是这个日志，（不知道怎么上截图）
`pldroid.playerdemo W/@@@QCCODEC: Open source rtsp://192.168.1.11:554/type=1507:test:end failed! err = 0XB0ADAF08
01-29 13:18:57.687 9507-9571/com.pili.pldroid.playerdemo W/@@@QCLOG: Warn TF3858100 CQCFFSource L129 Open source failed! err = 0X80000001
01-29 13:18:57.687 9507-9571/com.pili.pldroid.playerdemo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9571 (roid.playerdemo)`

**Comment by Redoteam** [comment]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11248 (roid.playerdemo)

**Comment by Redoteam** [comment]
刚刚测试了一下，关闭网络，用我上面的videoPath，也会crash

**Comment by zshbleaker** [comment]
目前还没有正式支持 RTSP 协议，后续会加上保护，避免 crash

**Comment by Redoteam** [comment]
哇，这么快！给你32个赞👍

**Comment by Redoteam** [comment]
@zshbleaker 请问大佬，m3u8支持吗？

**Comment by Redoteam** [comment]
刚刚找了一个地址测试了，可以播，而且地址错误，也不会crash

**Comment by zshbleaker** [comment]
支持的
