### ISSUE TITLE
PLVideoView叠在另外一个PLVideoView上面，发现上面这个PLVideoView透明了，完全看不到它在播放什么，怎么回事呢？

### ISSUE THREAD

**Issue by MrHeping** [pili-engineering/PLDroidPlayer#837]
布局文件：
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="@dimen/activity_padding">

    <com.pili.pldroid.player.widget.PLVideoView
        android:id="@+id/dp_video_large"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#000000"/>

    <com.pili.pldroid.player.widget.PLVideoView
        android:id="@+id/dp_video_small"
        android:layout_width="@dimen/video_width"
        android:layout_height="@dimen/video_height"
        android:background="#000000"/>

    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_centerInParent="true">

        <Button
            android:id="@+id/dp_btn_up"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="向上移动"/>

        <Button
            android:id="@+id/dp_btn_down"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@id/dp_btn_up"
            android:layout_marginTop="5dp"
            android:text="向下移动"/>
    </RelativeLayout>
</RelativeLayout>

这个问题困惑我很久了，麻烦大神能解答一下，不胜感激。

**Comment by zshbleaker** [comment]
PLVideoView 会把数据渲染到 SurfaceView 上，SurfaceView 的机制使得重叠会透明：https://developer.android.com/reference/android/view/SurfaceView.html

目前 SDK 还没有暴露 setZOrderOnTop 方法，之后会考虑加入，感谢反馈

**Comment by MrHeping** [comment]
明白了，谢谢
