### ISSUE TITLE
setDataSource 带 hearder  不好使

### ISSUE THREAD

**Issue by xjguo75468722** [pili-engineering/PLDroidPlayer#844]
播放时设置 setDataSource 带hearder， 用抓包工具抓不到。 但是原生的VideoView是可以抓到的，有解决办法吗？

用的是1.6.0的包

**Comment by zshbleaker** [comment]
设置 header 不生效吗？

**Comment by xjguo75468722** [comment]
确实。我用Wireshark抓包， 原生的VideoView是成功的， 七牛的不可以。

**Comment by zshbleaker** [comment]
不可以是指，抓到了这个 HTTP 请求，但是 header 里没有设置的内容？

**Comment by xjguo75468722** [comment]
对的，抓到了，播放MP4地址的请求。 但是请求的HEADER不是我设置的，是默认的

**Comment by zshbleaker** [comment]
好的，我们这边调查一下

**Comment by xjguo75468722** [comment]
我刚下的最新DEMO，2.0.6 是有效的。我弄成最新版本吧，谢谢
