### ISSUE TITLE
循环播放崩溃

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#845]
我在做循环播放时会报一下错误然后就崩溃，
02-03 09:18:47.227 651-1763/? A/libc: Fatal signal 11 (SIGSEGV) at 0x5f119000 (code=1), thread 1763 (roid.playerdemo)
02-03 09:18:48.727 2343-2459/system_process E/InputDispatcher: channel '4207db18 com.pili.pldroid.playerdemo/com.pili.pldroid.playerdemo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-03 09:18:48.797 2343-2459/system_process E/InputDispatcher: channel '41e51380 com.pili.pldroid.playerdemo/com.pili.pldroid.playerdemo.PLVideoTextureActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-03 09:18:49.847 13829-13829/com.pili.pldroid.playerdemo E/Trace: error opening trace file: No such file or directory (2)
02-03 09:18:50.367 13829-13829/com.pili.pldroid.playerdemo E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering
02-03 09:18:50.617 13829-13829/com.pili.pldroid.playerdemo E/dalvikvm: Could not find class 'android.widget.ThemedSpinnerAdapter', referenced from method android.support.v7.widget.AppCompatSpinner$DropDownAdapter.<init>
这是用demo测试的结果，帮忙看看。

**Comment by zshbleaker** [comment]
下个版本会重写循环播放的机制，感谢反馈

**Comment by shangmingchao** [comment]
是的，我在RecyclerView视频轮播中`seekTo(0)`后`start()`有时候会很卡，内存占用也挺高的，希望能更好地处理这种情景
