### ISSUE TITLE
Demo 远程连接播放不了，请求，急！

### ISSUE THREAD

**Issue by skyzd** [pili-engineering/PLDroidPlayer#850]
http://p2zmea1zp.bkt.clouddn.com/Fjr-nCPMT5ALM0AswX7Ha1jpz8s2
这个地址使用demo进行播放，播放不了，界面toast提示“failed to open player”
荣耀V8手机
不知道是视频格式问题，还是什么问题？

**Comment by zshbleaker** [comment]
刚发布的新版本里 OK 了，可以试试

**Comment by skyzd** [comment]
@zshbleaker 已经解决了，谢谢

**Comment by fangkyi03** [comment]
我还是这个问题 依旧不行 不仅demo中的rmtp不行 自己上传的视频文件也不行 打开本地直接崩溃
