### ISSUE TITLE
为什么有些视频需要把probesize调高才能收到声音

### ISSUE THREAD

**Issue by dasamanren** [pili-engineering/PLDroidPlayer#854]
为什么有些视频需要把probesize调高才能收到声音,有些默认就能听到声音,是哪里有区别呢

**Comment by zshbleaker** [comment]
probe 是 ffmpeg 的概念，通过检测 probe size 里的内容，去判断流的内容。如果流的开头一段都没有音频数据，ffmpeg 就会认为这个流都没有音频；把 probe size 增大到包含音频数据的区间的话，就正常了

2.0+ 的版本不再基于 ffmpeg，也不会有这个问题，欢迎更新尝试
