### ISSUE TITLE
libQPlayer.so 崩溃

### ISSUE THREAD

**Issue by peterchen** [pili-engineering/PLDroidPlayer#855]
版本：2.1.0
视频地址：
http://yuemao-app-video.oss-cn-beijing.aliyuncs.com/NWE3Y2ExMmQyNWIzNSMxNTE4MTE3MTY1LjE1NDQjdmlkZW8%3D.mp4
AVOptions设置离线缓存，第一次播放能播放，再次播放的时候就崩溃了。我armv7、arm64下面的so文件都添加了还是不行。

02-23 19:44:38.369 508-730/com.anyue.yuemao A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadcab1 in tid 730 (om.anyue.yuemao)
                                                    
                                                    [ 02-23 19:44:38.375   489:  489 W/         ]
                                                    debuggerd: handling request: pid=508 uid=10734 gid=10734 tid=730
02-23 19:44:38.453 740-740/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-23 19:44:38.454 740-740/? A/DEBUG: Build fingerprint: 'motorola/griffin_retcn/griffin:7.0/NCC25.106-11/11:user/release-keys'
02-23 19:44:38.454 740-740/? A/DEBUG: Revision: 'p3b0'
02-23 19:44:38.455 740-740/? A/DEBUG: ABI: 'arm64'
02-23 19:44:38.455 740-740/? A/DEBUG: pid: 508, tid: 730, name: om.anyue.yuemao  >>> com.anyue.yuemao <<<
02-23 19:44:38.455 740-740/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdeadcab1
02-23 19:44:38.455 740-740/? A/DEBUG:     x0   000000787bb83a24  x1   0000007891692000  x2   0000000000000000  x3   0000000000000010
02-23 19:44:38.455 740-740/? A/DEBUG:     x4   0000000000000000  x5   0000000000000040  x6   000000000000003f  x7   0000000000000000
02-23 19:44:38.456 740-740/? A/DEBUG:     x8   00000000deadcab1  x9   0000000000000000  x10  0000000000000001  x11  0000000000000160
02-23 19:44:38.456 740-740/? A/DEBUG:     x12  0000000000000000  x13  0000000000000000  x14  ffffffffffffffff  x15  000000787bb8576c
02-23 19:44:38.456 740-740/? A/DEBUG:     x16  000000787bbc83c0  x17  000000789bbfbc58  x18  0000000040000000  x19  0000007891433500
02-23 19:44:38.456 740-740/? A/DEBUG:     x20  0000007891692000  x21  000000787b833628  x22  000000787a7e3880  x23  0000000000000200
02-23 19:44:38.456 740-740/? A/DEBUG:     x24  0000000000000000  x25  0000000000000001  x26  000000787b83362c  x27  000000007461646d
02-23 19:44:38.456 740-740/? A/DEBUG:     x28  0000000000000001  x29  000000787b833510  x30  000000787bb83a58
02-23 19:44:38.456 740-740/? A/DEBUG:     sp   000000787b833510  pc   000000787bb83a34  pstate 0000000020000000
02-23 19:44:38.468 740-740/? A/DEBUG: backtrace:
02-23 19:44:38.468 740-740/? A/DEBUG:     #00 pc 00000000000a6a34  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.468 740-740/? A/DEBUG:     #01 pc 00000000000a6a54  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.468 740-740/? A/DEBUG:     #02 pc 00000000000a6a20  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.468 740-740/? A/DEBUG:     #03 pc 00000000000a5fd8  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.468 740-740/? A/DEBUG:     #04 pc 00000000000a5a9c  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.468 740-740/? A/DEBUG:     #05 pc 00000000000a5a4c  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #06 pc 00000000000a6644  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so (_Znwm+112)
02-23 19:44:38.469 740-740/? A/DEBUG:     #07 pc 00000000000a6698  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so (_Znam+8)
02-23 19:44:38.469 740-740/? A/DEBUG:     #08 pc 00000000000485d4  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #09 pc 000000000004ab74  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #10 pc 000000000004a980  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #11 pc 00000000000498ec  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #12 pc 0000000000048d0c  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #13 pc 0000000000047484  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #14 pc 000000000005e898  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #15 pc 0000000000062d20  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #16 pc 000000000006658c  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #17 pc 00000000000682b4  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #18 pc 0000000000029540  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #19 pc 000000000002909c  /data/app/com.anyue.yuemao-1/lib/arm64/libQPlayer.so
02-23 19:44:38.469 740-740/? A/DEBUG:     #20 pc 0000000000068554  /system/lib64/libc.so (_ZL15__pthread_startPv+196)
02-23 19:44:38.469 740-740/? A/DEBUG:     #21 pc 000000000001dd28  /system/lib64/libc.so (__start_thread+16)

**Comment by zshbleaker** [comment]
这个问题正在修复，感谢反馈

**Comment by peterchen** [comment]
@zshbleaker 大概什么时候会修复好，有一个大概日期吗？

**Comment by zshbleaker** [comment]
正在集中调查，预计本周或下周将会提供一个 bugfix 的版本

**Comment by peterchen** [comment]
2.1.1版本已解决
