### ISSUE TITLE
部分在线Mp4播放不出来。

### ISSUE THREAD

**Issue by peterchen** [pili-engineering/PLDroidPlayer#856]
mp4地址如下：
http://yuemao-app-video.oss-cn-beijing.aliyuncs.com/NWEyOGJhNzRiYTJhZCMxNTEyNjE4NjEyLjc2MjUjdmlkZW8%3D.mp4

**Comment by zshbleaker** [comment]
这个问题正在修复中，感谢反馈

**Comment by peterchen** [comment]
@zshbleaker 大概什么时候会修复好，有一个大概日期吗？

**Comment by oleky** [comment]
我这边也是类似状况，flv格式的，以前版本都可以，更新2.1.0之后就不能了。这个视频是经过处理的视频，添加了5秒的广告

**Comment by zshbleaker** [comment]
已经修复完成，尽量本周内发一个 hotfix

**Comment by peterchen** [comment]
@zshbleaker 你好，咨询下这个问题和#855问题是否在2.1.1版本解决了。

**Comment by zshbleaker** [comment]
2.1.1 应该解决了，如果还播不了的话，可以提供一下流地址

**Comment by peterchen** [comment]
在2.1.1 解决了，谢谢支持。
