### ISSUE TITLE
PLVideoTextureView如何切换视频横竖屏和view比例？

### ISSUE THREAD

**Issue by jackuhan** [pili-engineering/PLDroidPlayer#86]
能解释下吗？

**Comment by Jhuster** [comment]
@jackuhan Activity 的横竖屏是由 Android 开发者自己来配置的，当然，PLVideoTextureView 也为你提供了一个旋转播放角度的 API：setDisplayOrientation

设置 view 的比例的 API：setDisplayAspectRatio

具体用法，请参考 wiki：https://github.com/pili-engineering/PLDroidPlayer/wiki/5-快速开始#using-PLXXXView
