### ISSUE TITLE
有几个问题想请教

### ISSUE THREAD

**Issue by Zhangxd77** [pili-engineering/PLDroidPlayer#867]
播放音频，想获取音频的总时长，当前播放到位置，让音频播放某个指定位置。这个部分在哪里？
mMediaPlayer.getDuration();获取总时长是这么获取吗？我获取的一直是0
谢谢

**Comment by zshbleaker** [comment]
从制定位置播放可以用 `seekTo` 方法。
是这么获取的，一直获取的是 0 是有问题的，请问可以提供一下流地址吗，我们这边看下

**Comment by Zhangxd77** [comment]
应该是我之前写的位置不对，PLOnAudioFrameListener写在这里面就能获取到了。地址就是一个普通的歌曲。

**Comment by zshbleaker** [comment]
理论上来说 getDuration 也应该是能获取信息的，我们这边找了几个 mp3 都是可以的，所以想看看你那个文件是不是构造比较特殊，我们做下针对性处理
