### ISSUE TITLE
怎么解决视频seekTo()之后缓存消失的问题

### ISSUE THREAD

**Issue by steamstab** [pili-engineering/PLDroidPlayer#87]
请问，Player在seekTo()之后之前缓冲会消失，重新开始加载，怎么解决能保留缓存？

**Comment by Jhuster** [comment]
@steamstab 目前是这样设计的，没有办法保留。如果 `seekTo` 后，缓存都保留下来的话，会导致内存占用过大。

**Comment by wuqi713** [comment]
@Jhuster 我看到ijkplayer有个pull request 关于 add seek support cache 能否考虑一下支持。 这样能增加不少用户体验
