### ISSUE TITLE
有关视频播放问题

### ISSUE THREAD

**Issue by zhiwo** [pili-engineering/PLDroidPlayer#88]
不支持Http 啊，这个好坑啊，有童鞋有解决方案吗

**Comment by Jhuster** [comment]
@zhiwo 支持啊，你要播放的 URL 地址发出来看看

**Comment by zhiwo** [comment]
http://dl.fyfile.com:81/vod/%E4%BF%A1%E4%BB%B0%E4%B8%8E%E7%A7%91%E5%AD%A6-%E5%86%AF%E7%A7%89%E8%AF%9A/%E4%B8%8A%E5%B8%9D%E4%B8%8E%E7%A7%91%E5%AD%A62.mp4?_=1
或http://www.hdchurch.org/video/sunday/20160501/20160501-03yangxuewu.mp4 都不行

**Comment by Jhuster** [comment]
@zhiwo 我刚刚用这个 demo 都测试过一遍，两个视频地址都可以播放的。

**Comment by zhiwo** [comment]
。。。。,是2.1版本吗，我的都返回-104，是因为手机吗我的是魅蓝2     5.0系统

**Comment by Jhuster** [comment]
@zhiwo 播放配置是：软解还是硬解？ 你是说 onError 的 errorCode 等于 －104 吗 ？

**Comment by zhiwo** [comment]
软硬都试了不行，对PLMediaPlayer.OnErrorListener() 这个方法里面的值返回是-104

**Comment by Jhuster** [comment]
@zhiwo 请问是什么网络环境？电信、移动、联通还是其他，Wi-Fi 还是2G/3G/4G ？试试换一个网络环境看看是不是也不行？谢谢

**Comment by zhiwo** [comment]
我了个去，还真是换了自己的网没问题，多谢我再测测去
