### ISSUE TITLE
有个问题想请教一下：将app退到后台以后，音频还在播放，但是卡顿，出现问题应该是在哪里？

### ISSUE THREAD

**Issue by Zhangxd77** [pili-engineering/PLDroidPlayer#883]
你好，我将app退到后台，声音还在播放（正确的），但是卡顿，就是音乐像缓冲很慢的效果，您知道出现这个问题应该是哪里吗，谢谢

**Comment by Zhangxd77** [comment]
![image](https://user-images.githubusercontent.com/20806535/37890283-94c92cf8-3102-11e8-98f6-9ab6dae9fa19.png)

这个是退到后台后的log信息，看起来和在app中播放没什么区别啊。
然后把APP回来以后，就正常了，不卡顿了。

**Comment by zshbleaker** [comment]
请问使用的版本是？2.1.0 之后我们修改了音频的渲染机制，应该解决了这个问题

**Comment by Zhangxd77** [comment]
用的是2.1.1，这个应该不是你们的问题。是我哪里写错了，我这属于简单封装了一下，因为不想在MainActivity中写太多代码，我demo是好使的，但是我现在找不到是哪里问题，希望能指点我一下大概哪里问题

**Comment by zshbleaker** [comment]
看起来是 SDK 内部调用的 AudioTrack.write 出现了延迟，这个有点奇怪。是在主线程里创建的播放器吗？

**Comment by Zhangxd77** [comment]
我能加一下您什么，或者邮件形式说吗？方便吗

**Comment by Zhangxd77** [comment]
是在主线程创建的，

**Comment by zshbleaker** [comment]
这个… 我们也不太好定位，或者你写一个最小能复现这个问题的代码发一下，我们这边跑跑看

**Comment by Zhangxd77** [comment]
我刚才试了一下，换了个URL后台播就没问题了。但是iOS是正常的。。但是我只换了个URL地址啊。。

**Comment by zshbleaker** [comment]
可以提供一下出问题的 URL 吗，我们这边分析一下

**Comment by Zhangxd77** [comment]
我这个url有时效性，而且进行加密了，能加一下你qq不？

**Comment by Zhangxd77** [comment]
你好，我昨天又试了别的播放器，他们是后台可以播放。但是会播放一会就突然停了。我怀疑是由于这个超链接有时效性，然后咱们这个七牛的缓存边播边听做的比较好，所以在时效性之前就加载完。但是我现在还是后台播放就卡，我能给您一下apk看看吗

**Comment by LeaoWinchester** [comment]
您好，请问后台播放卡顿的问题解决了吗？ 我这边也遇到同样的问题，用的是西瓜播放器。

**Comment by LeaoWinchester** [comment]
有好的方法，如果可以的话烦请联系我：mr_cqunhui@sina.com

**Comment by Zhangxd77** [comment]
不好意思，时间有点久我忘了当时怎么弄的了

**Comment by LeaoWinchester** [comment]
好的，我继续看看吧，搞了两天了 没找到原因！

**Comment by LeaoWinchester** [comment]
您上面讨论的版本是指什么版本？
