### ISSUE TITLE
出现视频无法播放问题

### ISSUE THREAD

**Issue by DingZheng2017** [pili-engineering/PLDroidPlayer#884]
171.82.226.129 , 2018-03-05T11:15:23+08:00 , 0.053 , 200 , POST /V5_3/UserBehavior/TrackCrashLog HTTP/1.1 , - , - , - , [{\x22content\x22:\x22java.lang.IllegalStateException: Unable to retrieve AudioTrack pointer for write()\x5Cn\x5Ctat android.media.AudioTrack.native_write_byte(Native Method)\x5Cn\x5Ctat android.media.AudioTrack.write(AudioTrack.java:1255)\x5Cn\x5Ctat com.qiniu.qplayer.mediaEngine.MediaPlayer$a.a(MediaPlayer.java:1385)\x5Cn\x5Ctat com.qiniu.qplayer.mediaEngine.MediaPlayer.audioDataFromNative(MediaPlayer.java:923)\x5Cn\x22,\x22schoolId\x22:\x222173\x22,\x22userId\x22:\x222476027\x22,\x22createdDate\x22:1520169421054,\x22clientType\x22:\x221\x22,\x22appVersion\x22:\x2218.2.0\x22,\x22appSdkVersion\x22:\x225.1.1\x22,\x22modelName\x22:\x22vivo X7Plus\x22}]

录制的时间在2小时左右

**Comment by zshbleaker** [comment]
可以提供一下流地址吗

**Comment by DingZheng2017** [comment]
应该是存储区域问题，没事了
