### ISSUE TITLE
请问音量控制接口是？

### ISSUE THREAD

**Issue by panyingdaoz** [pili-engineering/PLDroidPlayer#887]
还有就是我想播放完视频后显示下图片（图片是全屏显示，显示时间是5-15秒），可以支持实现吗？

**Comment by zshbleaker** [comment]
setVolume

可以的，播放完成后 PLOnCompletionListener 会有回调消息，业务层可以根据回调消息控制 View 的显示

**Comment by panyingdaoz** [comment]
@zshbleaker setVolume最大支持多大的数值呢？

**Comment by zshbleaker** [comment]
1.0 就是原始的音频强度，超过 1 会增大，不建议超过 3，可能会出现爆音

**Comment by panyingdaoz** [comment]
哦，好的，还有就是我刚刚说用的图片显示用View不要用ImageView吗，我ImageView时无法显示
