### ISSUE TITLE
libVLC开源协议问题

### ISSUE THREAD

**Issue by erehmi** [pili-engineering/PLDroidPlayer#90]
libVLC是指[videolan/vlc](https://github.com/videolan/vlc)吗? 
如果是的话, 那就应该注意下vlc采用的是GPLv2协议, GPLv2协议对商业应用会有限制吧, 比如开源

**Comment by jpxiong** [comment]
There are both LGPL and GPL source files in libVLC.

[ijkplayer](https://github.com/pili-engineering/ijkplayer) only depends on libVLC's LGPL source code, you can find them by "git grep -i videolan", "git grep -i vlc"

**Comment by jpxiong** [comment]
You can also find the discussion [here](https://github.com/Bilibili/ijkplayer/issues/1275).
