### ISSUE TITLE
有关横竖屏切换

### ISSUE THREAD

**Issue by zhiwo** [pili-engineering/PLDroidPlayer#91]
我自定义MediaController控件，然后修改布局后，把横屏时直接 mVideoView.setDisplayOrientation(270);切换横屏后，MediaController控件显示正确，视频界面显示头部朝下，并不是画面头部在右，请教下这个是为什么啊谢谢

**Comment by zhiwo** [comment]
哈哈，设置成360都可以了，但是这个最大不是270吗

**Comment by Jhuster** [comment]
@zhiwo 设置 360 会返回 false，其实等于默认值 0 度

**Comment by zhiwo** [comment]
不是啊，按理说360应该就是0，但是在我手机上效果是，竖屏设置0时，画面都是竖的，横屏时360才是正确的，难道是分手机？

**Comment by zhiwo** [comment]
我明白了，我试试了竖屏270也是就是头朝左，应该是onConfigurationChanged这个事件的原因

**Comment by zhiwo** [comment]
亲，横屏的时选择ASPECT_RATIO_PAVED_PARENT时，画面显示不完，这个是平铺的吗，不是按照比例缩放吗

**Comment by Jhuster** [comment]
`ASPECT_RATIO_PAVED_PARENT ` 是按照比例缩放直到能占满全屏幕，如果屏幕分辨率与视频分辨率不一致的话，自然会有部分画面显示不全。

**Comment by zhiwo** [comment]
那就是不能即沾满全屏有能显示完整，而且图像不变形，画质差点也行啊

**Comment by Jhuster** [comment]
@zhiwo 跟画质没有关系，请仔细思考一下，屏幕分辨率与视频分辨率不一致的话，你说的这个需求从逻辑上就是无法做到的。
