### ISSUE TITLE
播放控制 暂停 总是在屏幕最下边

### ISSUE THREAD

**Issue by fvaryu** [pili-engineering/PLDroidPlayer#915]
播放控制 暂停 进度条 总是在屏幕最下边。我现在只是在屏幕中间有一个快播放区域，但是进度显示会到屏幕最下方

**Comment by fvaryu** [comment]
知道原因了，popwindow showAtLoaction 有问题，需要自定义一个

**Comment by Zhangxd77** [comment]
你好。请问你解决了么

**Comment by fvaryu** [comment]
@Zhangxd77  我自己重写了一下  不过我现在没有使用指责个库了
