### ISSUE TITLE
使用音频，重新给播放数据源之后，也使用了seekto方法，但是还是会从第一秒播，请问哪里错了，谢谢谢谢，很急

### ISSUE THREAD

**Issue by Zhangxd77** [pili-engineering/PLDroidPlayer#919]
我通过保存在本地了数据库，进行了判断。如果之前未播放过，就
`   mMediaPlayer.setDataSource(mUrl);
    mMediaPlayer.prepareAsync();`
如果播放过
`
 mMediaPlayer.setDataSource(mUrl);
 mMediaPlayer.seekTo(historyPosition);
mMediaPlayer.prepareAsync();
`

播放过这么写，也使用了seekTo，但是还是会从第一秒开始播，一下午了无法解决，很急，麻烦看到给点思路，谢谢谢谢！！

**Comment by cunmin** [comment]
@Override
                public void onPrepared(player) {
                    player.seekTo(historyPosition);
                    player.start();
                }
你是这样写的么

**Comment by Zhangxd77** [comment]
后来发现是自己写错了，谢谢
