### ISSUE TITLE
请问在获取网络上视频的时候可以缓存到本地吗？

### ISSUE THREAD

**Issue by hanilala** [pili-engineering/PLDroidPlayer#92]

**Comment by Jhuster** [comment]
@hanilala 目前没有提供相关功能

**Comment by hanilala** [comment]
@Jhuster 要添加缓存功能的话，应该从何处入手，谢谢。

**Comment by Jhuster** [comment]
@hanilala 目前在 java 层没有办法做这个功能，如果要定制化，可以从[这里](https://github.com/pili-engineering/ijkplayer)下载源码进行定制化。

**Comment by Jhuster** [comment]
@hanilala 目前我们没有提供缓存到本地的功能，你可以从[这里](https://github.com/pili-engineering/ijkplayer)下载源码进行定制化。

**Comment by Jhuster** [comment]
@hanilala 我们不支持这个功能，暂无支持计划。
