### ISSUE TITLE
怎么后台播放

### ISSUE THREAD

**Issue by suikatomoki** [pili-engineering/PLDroidPlayer#95]
Audioplayer用于纯音频播放，支持后台运行（文档原话）。但是我用了发现并不支持后台播放，按home键后，直接报 av_read_frame error: abb6a7bb( , , , ): AVERROR_EXIT

**Comment by Jhuster** [comment]
@suikatomoki 请问使用的哪一个版本，1.2.0 以后，推荐使用 `PLMediaPlayer` 来实现音频的播放，具体示例可以参考 demo 代码

**Comment by suikatomoki** [comment]
@Jhuster 知道的，我都试过了。后台播放音频是默认的吗，不需要配置任何参数？

**Comment by Jhuster** [comment]
@suikatomoki 嗯，不需要，只是进入后台的时候不要调用 `pause` 或者 `stop` 即可。

**Comment by suikatomoki** [comment]
@Jhuster 我这边后台之后，过了两到三秒的样子，就会停止播放，并有如下log
![-49a2238e2b9ef5d5](https://cloud.githubusercontent.com/assets/10336224/15104407/877b2c60-157d-11e6-8714-785eb9556ec3.png)

**Comment by Jhuster** [comment]
@suikatomoki 建议把播放音乐的代码放到｀Service｀中。

**Comment by suikatomoki** [comment]
@Jhuster 放到service里了，还用的是前台service，加了通知。

**Comment by suikatomoki** [comment]
@Jhuster

https://github.com/Bilibili/ijkplayer/issues/1286

**Comment by Jhuster** [comment]
@suikatomoki 十分感谢
