### ISSUE TITLE
是否可以提供X86_64、MIPS、MIPS64平台的.so文件

### ISSUE THREAD

**Issue by winter120** [pili-engineering/PLDroidPlayer#96]
个人项目中添加了JNI代码，并且全平台编译，结果x86_64位平台上，只有自己的JNI动态库，没有PLDroidPlayer的库，直接找不到库文件异常退出。但x86平台就可以运行。

**Comment by jpxiong** [comment]
https://github.com/pili-engineering/ijkplayer

**Comment by winter120** [comment]
收到，谢谢

**Comment by winter120** [comment]
ijikplayer编译完之后，libpldroidplayer.so又要如何去得到呢...

**Comment by gyckey** [comment]
我也有类似的问题．是否可以考虑支持下？
