### ISSUE TITLE
怎么清除videoview上面的图像 

### ISSUE THREAD

**Issue by weizongwei5** [pili-engineering/PLDroidPlayer#97]
怎么清除videoview上面的图像 设置为黑屏

**Comment by Jhuster** [comment]
@weizongwei5 请问你想在什么时候清除？如果是 **播放完毕后** 再清除的话，暂时可以用如下方法，后面我们再完善：

`
mVideoView.stopPlayback(); 
Canvas canvas = mVideoView.getSurfaceView().getHolder().lockCanvas();
canvas.drawColor(Color.BLACK);
mVideoView.getSurfaceView().getHolder().unlockCanvasAndPost(canvas);
`

**Comment by weizongwei5** [comment]
谢谢

**Comment by Jhuster** [comment]
@weizongwei5 还有一种更加简单的方法，播放完毕后调用：

mVideoView.getSurfaceView().setBackgroundColor(Color.BLACK);

**Comment by weizongwei5** [comment]
非常非常!感谢 !

**Comment by weizongwei5** [comment]
设置背景色的方案 以前在ijk上面  好像设置了背景  视频播放都出不来了 就直接黑了

**Comment by Jhuster** [comment]
@weizongwei5 嗯，注意，我说的是播放完毕后可以暂时这样处理，播放前这样设置的话，需要再加一条语句就不会黑屏了：

```
mVideoView.getSurfaceView().setZOrderOnTop(true);
```

**Comment by yilylong** [comment]
如果是PLVideoTextureView 怎么设置清屏。遇到个问题 就是 在listview 里面添加PLVideoTextureView 播放 ，在点击不同item 播放的时候 因为listview的view重用机制所以PLVideoTextureView 是在重用的，出现了点击一个新item 的播放 会先闪现一下之前item 播放过的画面。
